### ISSUE TITLE
hertz使用hertz.Static时，如果注册了相对路径，请求时会出现相对路径重复两遍而导致文件找不到的情况

### ISSUE THREAD

**Issue by UserLooper** [cloudwego/hertz#1000]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hertz version:**

Please provide the version of Hertz you are using.

**Environment:**

The output of `go env`.

**Additional context**

**Comment by UserLooper** [comment]
hertz.Static("/static", "./static")

[Error] HERTZ: Cannot open file="./static/static/index.html", error=open ./static/static/index.html: no such file or directory

请求是/static/index.html

**Comment by li-jin-gou** [comment]
@UserLooper  https://github.com/cloudwego/hertz/issues/400 看下是不是这个问题

**Comment by UserLooper** [comment]
> @UserLooper #400看下不是这个问题

看起来是的，我理解为relativePath是http请求的路径，看起来不是，只是文件的子路径
