### ISSUE TITLE
no api gateway provided?

### ISSUE THREAD

**Issue by huibunny** [cloudwego/hertz#101]
Api gateway is the most important part if you use microservices. No one can be found good in golang world.

**Comment by welkeyever** [comment]
Yes, good point. However, API Gateway is beyond the scope of hertz. Bytedance indeed has some API Gateways built atop hertz. 

We'll explore a good way to expand on this topic

**Comment by Duslia** [comment]
If you have any other questions or requirements, you can join Lark group and give us a feedback
