### ISSUE TITLE
V0.7.0 递归结构体无法退出遍历

### ISSUE THREAD

**Issue by dorlolo** [cloudwego/hertz#1015]
**Describe the bug**
递归结构体作为请求参数时，在v0.7.0版本中没做优化，他会导致无法停止遍历

**To Reproduce**
举个例子
```go
type AppMenu struct {
    Parent     *AppMenu
    Children   []AppMenu
}
func (m *menuApi) CreateMenus(ctx context.Context, c *app.RequestContext) {
	var info AppMenu
	if err := c.Bind(&info); err != nil {
		server.ReplyWithFailed(e.ArgumentParseFailed, err, c)
		return
	}
	fmt.Println(info )
}
```
它会一直遍历Parent字段

![微信图片_20231205185227](https://github.com/cloudwego/hertz/assets/35569481/5d80153b-3a78-49a2-ba44-12715af3a49a)

**Hertz version:**

v0.7.0

**Comment by FGYFFFF** [comment]
我来修复下

**Comment by dorlolo** [comment]
@FGYFFFF 好的！
