### ISSUE TITLE
小概率事件解析不到路由，不确定是否是bug

### ISSUE THREAD

**Issue by dorlolo** [cloudwego/hertz#1017]
**Describe the Question**

开发过程中，会概率性出现http请求异常的问题，所有接口都会这个情况。出现问题时会触发noRoute，控制台会输出`cannot access directory without index page. xxx`

**Screenshots**
这次又遇到了特地截个图。其次说明一下，这个并不是构造的请求有问题，因为在chrome中选择“重复XHR”后是可以请求成功的。
<img width="618" alt="234e7351749300a7c56b8f7eef6a943" src="https://github.com/cloudwego/hertz/assets/35569481/f6c7c820-e2b3-49f8-a1b7-c3ea66c42bc1">

这是当时控制台输出的内容,可以看到路由解析成了一个`/`
<img width="696" alt="382aa343dbbe5b29fee912434be830a" src="https://github.com/cloudwego/hertz/assets/35569481/d32c1100-09b7-4fb3-9a12-b04c67130639">
这里为了避免出现`cannot access directory without index page. xxx`这个报错，已经把GenerateIndexPages设置成了true。

**Hertz version:**
当前版本
github.com/cloudwego/hertz v0.6..8
github.com/cloudwego/netpoll v0.5.0 
hertz v0.6.6 , v0.6..8, v0.7.0,v0.7.2

**Environment:**
windows 11：go1.21.3
ubuntu:  go1.20.9

**Additional context:**
这个问题是在11月底左右出现的，此之前没有这样的问题（印象中），所以我不确定是不是bug。思来想去也就升级过golang版本，但是换系统换版本号都试过，问题依然存在。 请问题有没有人出现过这个问题的，或者提供一下问题排查的思路。

我这里贴上我启动服务时相关的代码
```go
func InitServer(c context.Context) {
	h = hz.Default(
		hz.WithTransport(standard.NewTransporter),
		hz.WithHostPorts(fmt.Sprintf("%s:%d", global.CONFIG.Profile.BackendHost, global.CONFIG.Profile.BackendPort)),
		hz.WithMaxRequestBodySize(utils.MB*5), 
	)
	binding.SetLooseZeroMode(true)
	if global.CONFIG.Profile.UseI18n {
		h.Use(hertzI18n.Localize(
			hertzI18n.WithBundle(&hertzI18n.BundleCfg{
				RootPath:         filepath.Join(global.CONFIG.Profile.DataDir, "system/localize"),
				AcceptLanguage:   []language.Tag{language.Chinese, language.English},
				DefaultLanguage:  language.Chinese,
				FormatBundleFile: "yaml",
				UnmarshalFunc:    yaml.Unmarshal,
			}),
			hertzI18n.WithGetLangHandle(middleware.GetI18nLang),
		))
	}
	h.NoRoute(func(c context.Context, ctx *app.RequestContext) {
		ctx.AbortWithStatusJSON(errs.NotFound.D().Http, map[string]interface{}{
			"code":   errs.NotFound.D().Code,
			"notice": "不支持的请求",
		})
	})
	h.StaticFS("/", &app.FS{Root: global.CONFIG.Profile.DataDir, GenerateIndexPages: false})

	h.Use(middleware.AllowAllOrigins(), middleware.SetUserInfo(), middleware.DebugPrintRequest())
	for _, r := range routerPreloadList {
		r.Register(h)
	}

	serverStarted := false
	defer func() {
		if !serverStarted {
			_ = ShutdownHertz(context.Background())
		}
	}()
	serverStarted = true
	h.Spin()
}
```

**Comment by li-jin-gou** [comment]
这种情况的404 是因为在 handler 中异步使用了 app.RequestContext 导致的
![image](https://github.com/cloudwego/hertz/assets/97824201/e9a5408d-9350-4a36-ab91-aa5fa44b391a)
可以检查一下 go func 中有没有使用 app.RequestContext 的场景，如果有的话可以换成 .Copy 提供安全的副本 或者在 goroutine 外把数据获取好，传递进去。主要目的是为了避免异步使用  app.RequestContext。

**Comment by li-jin-gou** [comment]
> @li-jin-gou 并没有在HandlerFunc中使用携程，就像这次出现的问题，只是获取数据后，在数据库中添加数据。然而出现问题时，断点后都打不到HandlerFunc中。此外我也检查了中间件，也没有使用携程处理任务。

应该是这个问题，可以仔细检查一下，另外是不是已经在生产环境使用 hertz 了？

**Comment by li-jin-gou** [comment]
> > @li-jin-gou 并没有在HandlerFunc中使用携程，就像这次出现的问题，只是获取数据后，在数据库中添加数据。然而出现问题时，断点后都打不到HandlerFunc中。此外我也检查了中间件，也没有使用携程处理任务。
> 
> 应该是这个问题，可以仔细检查一下，另外是不是已经在生产环境使用 hertz 了？

```
package main

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

func main() {
	h := server.Default()
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		go func() { ctx.Path() }()
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})

	h.Spin()
}
```
可以试试

**Comment by dorlolo** [comment]
好的，我试试。等确认问题我再留言。

> > > @li-jin-gou 并没有在HandlerFunc中使用携程，就像这次出现的问题，只是获取数据后，在数据库中添加数据。然而出现问题时，断点后都打不到HandlerFunc中。此外我也检查了中间件，也没有使用携程处理任务。
> > 
> > 
> > 应该是这个问题，可以仔细检查一下，另外是不是已经在生产环境使用 hertz 了？
> 
> ```
> package main
> 
> import (
> 	"context"
> 	"github.com/cloudwego/hertz/pkg/app"
> 	"github.com/cloudwego/hertz/pkg/app/server"
> 	"github.com/cloudwego/hertz/pkg/common/utils"
> 	"github.com/cloudwego/hertz/pkg/protocol/consts"
> )
> 
> func main() {
> 	h := server.Default()
> 	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
> 		go func() { ctx.Path() }()
> 		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
> 	})
> 
> 	h.Spin()
> }
> ```
> 
> 可以试试复现代码

好的，我试试。等定位到问题再留个言

**Comment by dorlolo** [comment]
> > > @li-jin-gou 并没有在HandlerFunc中使用携程，就像这次出现的问题，只是获取数据后，在数据库中添加数据。然而出现问题时，断点后都打不到HandlerFunc中。此外我也检查了中间件，也没有使用携程处理任务。
> > 
> > 
> > 应该是这个问题，可以仔细检查一下，另外是不是已经在生产环境使用 hertz 了？
> 
> ```
> package main
> 
> import (
> 	"context"
> 	"github.com/cloudwego/hertz/pkg/app"
> 	"github.com/cloudwego/hertz/pkg/app/server"
> 	"github.com/cloudwego/hertz/pkg/common/utils"
> 	"github.com/cloudwego/hertz/pkg/protocol/consts"
> )
> 
> func main() {
> 	h := server.Default()
> 	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
> 		go func() { ctx.Path() }()
> 		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
> 	})
> 
> 	h.Spin()
> }
> ```
> 
> 可以试试复现代码

问题确实复现了！感谢！我定位下具体问题。

**Comment by li-jin-gou** [comment]
好的

**Comment by dorlolo** [comment]
> 好的，这个 case 比较经典，我们也需要补充一下文档

抱歉，我忽略了一个问题。这个代码虽然能复现路由变成了`/`这种情况，但是前端能正常接收到返回值。
```go
h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		go func() {
			thisPath := ctx.Path()
			fmt.Println("ctx.Path():" + string(thisPath))
		}()
		ctx.JSON(consts.StatusOK, map[string]interface{}{
			"ping": "pong",
		})
	})
```
而我的问题是它会跑到noRoute方法中，也就是说，在进入控制层之前就出错了。

**Comment by li-jin-gou** [comment]
> > 好的，这个 case 比较经典，我们也需要补充一下文档
> 
> 抱歉，我忽略了一个问题。这个代码虽然能复现路由变成了`/`这种情况，但是前端能正常接收到返回值。
> 
> ```go
> h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
> 		go func() {
> 			thisPath := ctx.Path()
> 			fmt.Println("ctx.Path():" + string(thisPath))
> 		}()
> 		ctx.JSON(consts.StatusOK, map[string]interface{}{
> 			"ping": "pong",
> 		})
> 	})
> ```
> 
> 而我的问题是它会跑到noRoute方法中，也就是说，在进入控制层之前就出错了。

我上面的那个case 变成 / 是因为我没定义 noroute ，否则它会跑到noRoute方法中，因为都没有注册 / 路由。

**Comment by dorlolo** [comment]
> > > 好的，这个 case 比较经典，我们也需要补充一下文档
> > 
> > 
> > 抱歉，我忽略了一个问题。这个代码虽然能复现路由变成了`/`这种情况，但是前端能正常接收到返回值。
> > ```go
> > h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
> > 		go func() {
> > 			thisPath := ctx.Path()
> > 			fmt.Println("ctx.Path():" + string(thisPath))
> > 		}()
> > 		ctx.JSON(consts.StatusOK, map[string]interface{}{
> > 			"ping": "pong",
> > 		})
> > 	})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 而我的问题是它会跑到noRoute方法中，也就是说，在进入控制层之前就出错了。
> 
> 我上面的那个case 变成 / 是因为我没定义 noroute ，否则它会跑到noRoute方法中，因为都没有注册 / 路由。

请看一下我的测试用例和测试结果。
测试用例,定义了NoRoute
```go
package test

import (
	"context"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app"
	hz "github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/app/server/binding"
	"github.com/cloudwego/hertz/pkg/network/standard"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/dorlolo/ketgo-admin/internal/errs"
	"github.com/dorlolo/ketgo-admin/utils"
	"testing"
)

func TestNoRoute(t *testing.T) {
	var h = hz.Default(
		hz.WithTransport(standard.NewTransporter),
		hz.WithHostPorts("localhost:8088"),
		hz.WithMaxRequestBodySize(utils.MB*5),
	)
	binding.SetLooseZeroMode(true)
	h.NoRoute(func(c context.Context, ctx *app.RequestContext) {
		//ctx.AbortWithMsg("Unsupported path", errs.NotFound.D().Http)
		ctx.AbortWithStatusJSON(errs.NotFound.D().Http, map[string]interface{}{
			"code":   errs.NotFound.D().Code,
			"notice": "不支持的请求",
		})
	})

	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		go func() {
			thisPath := ctx.Path()
			fmt.Println("ctx.Path():" + string(thisPath))
		}()
		ctx.JSON(consts.StatusOK, map[string]interface{}{
			"ping": "pong",
		})
	})
	h.Spin()
}
```cmd
C:\Users\lenovo>curl -X GET localhost:8088/ping
{"ping":"pong"}
C:\Users\lenovo>curl -X GET localhost:8088/ping
{"ping":"pong"}
C:\Users\lenovo>curl -X GET localhost:8088/ping
{"ping":"pong"}
C:\Users\lenovo>curl -X GET localhost:8088/ping
{"ping":"pong"}
C:\Users\lenovo>curl -X GET localhost:8088/ping
{"ping":"pong"}
C:\Users\lenovo>curl -X GET localhost:8088/ping
{"ping":"pong"}
C:\Users\lenovo>curl -X GET localhost:8088/ping
{"ping":"pong"}
C:\Users\lenovo>curl -X GET localhost:8088/ping
{"ping":"pong"}
C:\Users\lenovo>curl -X GET localhost:8088/ping
{"ping":"pong"}
C:\Users\lenovo>curl -X GET localhost:8088/ping
{"ping":"pong"}
C:\Users\lenovo>curl -X GET localhost:8088/ping
{"ping":"pong"}
C:\Users\lenovo>curl -X GET localhost:8088/ping
{"ping":"pong"}
C:\Users\lenovo>curl -X GET localhost:8088/ping
{"ping":"pong"}
```
这是控制台的输出。 请看一下最后一次请求的结果，对应上面最后一个curl命令
```txt
=== RUN   TestNoRoute
2023/12/08 16:12:44.165981 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/ping                     --> handlerName=github.com/dorlolo/ketgo-admin/test.TestNoRoute.func2 (num=2 handlers)
2023/12/08 16:12:44.177013 engine.go:389: [Info] HERTZ: Using network library=standard
2023/12/08 16:12:44.184587 transport.go:65: [Info] HERTZ: HTTP server listening on address=127.0.0.1:8088
ctx.Path():/ping
ctx.Path():/ping
ctx.Path():/ping
ctx.Path():/ping
ctx.Path():/ping
ctx.Path():/ping
ctx.Path():/ping
ctx.Path():/ping
ctx.Path():/ping
ctx.Path():/ping
ctx.Path():/ping
ctx.Path():/ping
ctx.Path():/
```

**Comment by dorlolo** [comment]
> ```batchfile
> {"ping":"pong"}
> ```


啊？那为什么会正常返回了`{"ping":"pong"}`  而不是NoRoute中的报错？

**Comment by dorlolo** [comment]
> 最后一个是 ‘/’ 没有注册到路由上，就会走到 NoRoute

啊？那为什么会正常返回了{"ping":"pong"} 而不是NoRoute中的报错？

**Comment by li-jin-gou** [comment]
你并发高一些就会了

**Comment by li-jin-gou** [comment]
i18n 导致
