### ISSUE TITLE
BindAndValidate绑定校验能正常通过null的问题

### ISSUE THREAD

**Issue by Joker-DW** [cloudwego/hertz#1021]
接口入参struct定义了required的tag；
例如：
type Req struct {
	TestInt int `json:"test_int,required" vd:"$>=0"`
}

但是前端传test_int为null到接口的时候，居然能正常解析，越过了参数校验没有报错

**Comment by Joker-DW** [comment]
这个问题倒是还好，我们在前端先容错这个问题；但是这个问题降低了服务端的可靠性，还是希望能够早日修复

**Comment by li-jin-gou** [comment]
如果在企业内部使用 hertz 的话，可以飞书联系一下，可以详细聊聊 @Joker-DW

**Comment by FGYFFFF** [comment]
Required 使用 json.Get() 函数来判断对应的 key 是否传递，在你的这个 case 里，你传递了对应的 key
