### ISSUE TITLE
自定义模板中的Service 级别中的Models为切片

### ISSUE THREAD

**Issue by mxbf99** [cloudwego/hertz#1023]
**Describe the Question**

自定义模板的Service 级别的渲染数据中的Models是否可以和Method中的Models样做成一个map进行循环渲染

**Reproducible Code**

-path: "biz/service/{{.GenPackage}}/{{ToSnakeCase .ServiceName}}.go"
    loop_service: true
    update_behavior:
      type: "skip"
    body: |-
      package {{.FilePackage}}
      import (
       "context"

       "github.com/cloudwego/hertz/pkg/app"
      {{- range $k, $v := .Models}}
        "{{$v.Package}}"   //models切片 不是map  $k为空
      {{- end}}
      )“

**Expected behavior**

Service 级别的渲染数据中的Models为切片,定义service的时候model导入的的别名空 

**Screenshots**

![屏幕截图 2023-12-12 140504](https://github.com/cloudwego/hertz/assets/103180867/c7c57d64-5b45-402b-923b-a46537eef615)

**Hertz version:**

0.7.3

**Environment:**

The output of `go env`.

**Additional context**

Add any other context about the question here.

**Comment by li-jin-gou** [comment]
cc @FGYFFFF

**Comment by FGYFFFF** [comment]
可以的，可以单独加个 map 把 []model 转换一下。你有时间提个 pr 吗？

**Comment by mxbf99** [comment]
研究了一下使用method渲染services感觉也还可以
