### ISSUE TITLE
Is there have anyway to load config file or read environment variables

### ISSUE THREAD

**Issue by duyucongc** [cloudwego/hertz#1025]
I want to use hertz, but i find there is no example of how to load config file, i have to use viper load config by manually.
Will there be plans to support modules that load configuration files or environment variables in the future?

**Comment by rogerogers** [comment]
refer to https://github.com/cloudwego/cwgo

**Comment by li-jin-gou** [comment]
> refer to https://github.com/cloudwego/cwgo

thanks
