### ISSUE TITLE
cwgo-2023白皮书下载不了

### ISSUE THREAD

**Issue by Tobehalo** [cloudwego/hertz#1027]
已填写问卷
![1702552775110](https://github.com/cloudwego/hertz/assets/7876198/29e2dcde-5e79-44ad-ac06-bf8ae06d27ff)
打开链接提示无法访问
![1702552860399](https://github.com/cloudwego/hertz/assets/7876198/d56cb743-2056-4a1c-b973-bf3a124d5267)

**Comment by li-jin-gou** [comment]
cc @GuangmingLuo

**Comment by li-jin-gou** [comment]
cc @Tobehalo https://github.com/cloudwego/community/blob/main/CloudWeGo-2023-technical-white-paper.pdf

**Comment by GuangmingLuo** [comment]
应该是网络访问问题

**Comment by Tobehalo** [comment]
谢谢解答，可以下载了
