### ISSUE TITLE
There are some functions lack arguments with Context  in Model dictionary generated by `hz update...` command

### ISSUE THREAD

**Issue by fireapproval** [cloudwego/hertz#1033]
**Describe the bug**

using `hz update` command to generates standard dictionarys，but lacking more arguments in mode dictionary

**To Reproduce**

1. Go to 'biz/model'
2. Click on 'anyone dictionary'
3. See errors like this

![image](https://github.com/cloudwego/hertz/assets/125383416/68fd8ac8-298a-4729-bee6-e4fa9014732c)

**Hertz version:**

hz version is v0.7.1

**Environment:**

Go version is go1.21.5

**Comment by li-jin-gou** [comment]
参考 https://github.com/cloudwego/hertz/issues/873 ，这块什么时候能主动加 replace 🥺 cc @FGYFFFF
