### ISSUE TITLE
Proposal: add some error log for 400(missing host)

### ISSUE THREAD

**Issue by welkeyever** [cloudwego/hertz#1034]
**Is your feature request related to a problem? Please describe.**
#1003  add a extra check for missing host request, will directly return a 400 response before accesslog recording(kind of confusing).

**Describe the solution you'd like**
May let middleware(accesslog) to record the 400, also with other 400 scenario.

**Describe alternatives you've considered**
Feel free to discuss it here~

**Comment by kingcanfish** [comment]
```go
// align with https://datatracker.ietf.org/doc/html/rfc2616#section-5.2
if len(ctx.Request.Host()) == 0 && ctx.Request.Header.IsHTTP11() && bytesconv.B2s(ctx.Request.Method()) != consts.MethodConnect {
	ctx.SetHandlers(engine.Handlers)
	serveError(c, ctx, consts.StatusBadRequest, requiredHostBody)
	return
}
```
It might be enough to call this function `ctx.SetHandlers(engine.Handlers)` before `serveError` ?
