### ISSUE TITLE
protobuf 里面使用 gotag 注解报错，生成代码不起作用

### ISSUE THREAD

**Issue by jjeejj** [cloudwego/hertz#1040]
查看 官方文档 https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/annotation/ 是这样书写 gotag 的
![img_v3_026o_6189bc01-0258-4a9e-b9bd-20bcd6f88d4g](https://github.com/cloudwego/hertz/assets/15176971/158bc926-f898-45d5-a24e-fd668a2e7197)

我先是这样用的
![img_v3_026o_0b5e8e93-5ec6-4d26-90d4-daad11a76b0g](https://github.com/cloudwego/hertz/assets/15176971/d65f930e-308c-404d-8c24-814556fb1f75)

生成代码的时候报错了
![img_v3_026o_403d41bd-3c24-42f8-bb27-8e1af682b8bg](https://github.com/cloudwego/hertz/assets/15176971/11dc1af9-c65e-4ae7-bf72-ab0021d4907d)

然后 我又 尝试 加斜扛砖码
 int32 total = 1[(api.go_tag) = "json: \"total\""];

生成代码的时候 提示语法错误
enerate file aa.proto failed: invalid go.tag value: , err: invalid syntax

**Comment by li-jin-gou** [comment]
cc @FGYFFFF  +文档修复

**Comment by li-jin-gou** [comment]
@jjeejj 按照 https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/annotation/#field-%E6%B3%A8%E8%A7%A3 这个再试试哈

**Comment by jjeejj** [comment]
> @jjeejj 按照 [cloudwego.io/zh/docs/hertz/tutorials/toolkit/annotation/#field-%E6%B3%A8%E8%A7%A3](https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/annotation/#field-%E6%B3%A8%E8%A7%A3) 这个再试试哈

这个不是文档问题，我已经添加 加斜扛砖码 ，生成代码的时候提示语法错误
<img width="537" alt="image" src="https://github.com/cloudwego/hertz/assets/15176971/3c8ad0dc-cd5d-4035-9504-804146ab1699">

<img width="437" alt="image" src="https://github.com/cloudwego/hertz/assets/15176971/6b65ee93-ffc0-4098-a8a2-9e8e9498eb5e">

@FGYFFFF @li-jin-gou

**Comment by FGYFFFF** [comment]
> > @jjeejj 按照 [cloudwego.io/zh/docs/hertz/tutorials/toolkit/annotation/#field-%E6%B3%A8%E8%A7%A3](https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/annotation/#field-%E6%B3%A8%E8%A7%A3) 这个再试试哈
> 
> 这个不是文档问题，我已经添加 加斜扛砖码 ，生成代码的时候提示语法错误 <img alt="image" width="537" src="https://private-user-images.githubusercontent.com/15176971/295417758-3c8ad0dc-cd5d-4035-9504-804146ab1699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTUxNTIsIm5iZiI6MTcwNDg1NDg1MiwicGF0aCI6Ii8xNTE3Njk3MS8yOTU0MTc3NTgtM2M4YWQwZGMtY2Q1ZC00MDM1LTk1MDQtODA0MTQ2YWIxNjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAyNDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMjZjYjlkZmFjMjkyZmZlZGUzNGI2NWExN2UyOWQzOWJhNTBjMjFhM2IzNjQ1ZWM1MGIyOGUxZTE0MzQ1YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MX3_HVZb2VKxrXxzFp0PgWQu8uwQbU3z687l30YN1QA">
> 
> <img alt="image" width="437" src="https://private-user-images.githubusercontent.com/15176971/295417808-6b65ee93-ffc0-4098-a8a2-9e8e9498eb5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTUxNTIsIm5iZiI6MTcwNDg1NDg1MiwicGF0aCI6Ii8xNTE3Njk3MS8yOTU0MTc4MDgtNmI2NWVlOTMtZmZjMC00MDk4LWE4YTItOWU4ZTk0OThlYjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAyNDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YWE5NGUyODEwMDc1ZmQ0MzE4YTQxZjEzNGZlZTg1YjRkMzE3OTVlMWQ0OWJlMDU5ZDMyOTZjYjQ3NTU0YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dEFYBLbiL4ebmaDKnDwaPJTWTaqsVfMZ8Z7tmwMAflM">
> @FGYFFFF @li-jin-gou
json: 后面多个空格。 你先改下，我看看工具能不能优化下
