### ISSUE TITLE
[fatal error: fault] when c.JSON(consts.StatusOK, utils.H{"rows": Rows})

### ISSUE THREAD

**Issue by anyfig** [cloudwego/hertz#1042]
**Describe the Question**
i change my framework from fiber to hertz in my project, and meet some problems. 

**Reproducible Code**
as following Screenshots, 
Rows type is []domain.Notice, 
when c.JSON(consts.StatusOK, utils.H{"rows": Rows}), 
it crashed fatal error: fault

**Screenshots**

![2024-01-09 103242](https://github.com/cloudwego/hertz/assets/56902794/2901bacd-3fe1-453c-8e23-a5b89e9c4e44)

**Comment by li-jin-gou** [comment]
I suspect it's because hertz has sonic built in by default.

**Comment by li-jin-gou** [comment]
refer to https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/json/ and modify json to std-json

**Comment by li-jin-gou** [comment]
Not sure exactly what's causing this error, but we can try changing the json configuration.

**Comment by anyfig** [comment]
> I suspect it's because hertz has sonic built in by default.

you are right, i use "encoding/json" now,  it is exactly sonic causing this error

**Comment by li-jin-gou** [comment]
cc @AsterDY
