### ISSUE TITLE
希望websocket能兼容gws

### ISSUE THREAD

**Issue by Hanson** [cloudwego/hertz#1052]
目前websocket用的是改造自 gorilla 的框架，在高并发的场景下体现了性能不足的问题，也跟自身的链接池管理，锁有关。

希望能兼容 gws https://github.com/lxzan/gws

**Comment by li-jin-gou** [comment]
列为 todo。

**Comment by li-jin-gou** [comment]
PTAL @Skyenought

**Comment by shenfc6** [comment]
hi @li-jin-gou ，我关注这个issue有一段时间了，并且最近看了RFC6455以及gws的源码，请问这个issue还需要帮忙吗？以及能否大致告诉我所谓的兼容gws需要做到什么程度

**Comment by xiaost** [comment]
@Hanson @shenfc6 

Websocket功能并非Hertz自身的功能，相关的代码也不在这个库里。
并不存在 hertz 兼容 xx ，而是 xx 兼容 hertz。

建议如果 gws 想支持hertz的话，可以在 gws 或单独的库实现。
如果希望 hertz 提供什么接口以扩展协议，可以提交新的 issue
