### ISSUE TITLE
hz如何只生成query tag？

### ISSUE THREAD

**Issue by ljkk** [cloudwego/hertz#1069]
**Describe the Question**

使用hz生成model代码，字段注解只写了api.query="num,required"，我期望只生成query tag，但是却生成了json和query两个tag，而且json tag中没有required，这样导致请求的query参数中没有num，也不报错。

**Hertz version:**

hz version v0.8.1

**Comment by skytt** [comment]
遇到同样的问题了，请问如何解决的呢，谢谢
