### ISSUE TITLE
how many multi million of websocket connections can be supported by hertz websocket?

### ISSUE THREAD

**Issue by ouvaa** [cloudwego/hertz#1073]
saw this:
https://www.druva.com/blog/websockets--scale-at-fractional-footprint-in-go

any comparison etc with memory usage?

**Comment by li-jin-gou** [comment]
First of all can support millions of connections, if it is demo (ping/pong) , find a better machine, usually can carry it. If it is a complex business scenario to support millions of connections, the number of machines must also go up.
