### ISSUE TITLE
How can HZ support *. Thrift?

### ISSUE THREAD

**Issue by RogueCultivators** [cloudwego/hertz#1076]
I hope to specify all files with the same suffix in a certain folder during generation

**Comment by li-jin-gou** [comment]
Not support.



---Original---
From: ***@***.***&gt;
Date: Sat, Mar 9, 2024 15:07 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [cloudwego/hertz] How can HZ support *. Thrift? (Issue #1076)




 
I hope to specify all files with the same suffix in a certain folder during generation
