### ISSUE TITLE
为什么链路追踪总是并且关系没有层次

### ISSUE THREAD

**Issue by flairamos** [cloudwego/hertz#1078]
是使用hertz和kitex做链路追踪时，span总是并列关系，在官方示例下没人回复，转向框架仓库希望有人能答疑解惑：

[https://github.com/cloudwego/hertz-examples/issues/136#issue-2199773563](https://github.com/cloudwego/hertz-examples/issues/136#issue-2199773563)

首先，我使用cwgo工具生成了api server服务与rpc server和rpc client服务，然后docker 运行了jaeger-all-in-one环境。
其次，参考本仓库的openTelemetry扩展配置链路追踪。

具体配置如下：

api server :
![image](https://github.com/cloudwego/hertz-examples/assets/125383416/98e756fd-cc56-40c1-9e57-15e78de32933)

rpc server:
![image](https://github.com/cloudwego/hertz-examples/assets/125383416/e8a5ea26-2046-4e30-a2ae-7530e1db6ba2)

rpc client：
![image](https://github.com/cloudwego/hertz-examples/assets/125383416/fe6d488c-812c-493c-918b-6b5437ea671d)

完成上述配置后向接口发送一次请求，jaeger UI的query如下：

![image](https://github.com/cloudwego/hertz-examples/assets/125383416/c9830b4e-ea9a-40ff-bef8-29b8e1eed77d)

我是在http的service层调用的rpc client获取数据，按照这个逻辑，应该是分层次的，类似于这样：

```shell
user-http-server
|——user-rpc-server
```

请问是那个地方配置错了，还是我理解错了，需要怎样配置或者使用才能达到此仓库的图片显示的那样有参差的记录。希望能得到解答，谢谢！

**Comment by li-jin-gou** [comment]
cc @rogerogers

**Comment by li-jin-gou** [comment]
辛苦帮看下 @rogerogers  @CoderPoet

**Comment by rogerogers** [comment]
user-http-client 的写法有问题，导致 user-rpc-server 找不到 parent span
![image](https://github.com/cloudwego/hertz/assets/40619032/18e46307-c082-4b83-9eff-27807b4cf908)
这个 shutdown 直接关闭了上报，shutdown 实际应该放在 hook 里

**Comment by rogerogers** [comment]
另外，一个服务初始化一个 provider 就可以, client 这里不用再初始化一次

**Comment by flairamos** [comment]
> 另外，一个服务初始化一个 provider 就可以, client 这里不用再初始化一次

谢谢，已解决
![image](https://github.com/cloudwego/hertz/assets/125383416/ee2484fa-14ac-4998-9884-679b98c88302)
