### ISSUE TITLE
Long running high hit rate hertz's bottlenecked by MarshalLogArray

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/hertz#1079]
is this normal? my tls is consuming 3x lower processing time than this:

Please look into these. thx

tls:

![Screenshot from 2024-03-23 00-09-59](https://github.com/cloudwego/hertz/assets/104323920/67a3f812-d6c5-4d24-87ad-d74276871e05)

marshallogarray?

![Screenshot from 2024-03-23 00-06-49](https://github.com/cloudwego/hertz/assets/104323920/b7510560-022c-4a5d-a47e-e6e87491ccf8)

**Comment by ouvaa** [comment]
sorry i just realised this is from a hertz-contrib library.

**Comment by kolinfluence** [comment]
sry i just realised it's from a hertz-contrib library
