### ISSUE TITLE
hertz 与 kitex 同一端口，请求接口会出现 short connection 错误日志

### ISSUE THREAD

**Issue by cateams** [cloudwego/hertz#1095]
如标题所示，完整错误提示为：
[Error] KITEX: processing error, remoteAddr=127.0.0.1:61090, error=HERTZ: short connection

接口是正常返回数据的，这个错误提示是什么意思，怎么样可以关闭呢，避免污染日志信息

**Comment by li-jin-gou** [comment]
hex 不支持 windows 我怀疑是这个原因
