### ISSUE TITLE
hz 集成 protoc-gen-openapi 插件报错

### ISSUE THREAD

**Issue by darrenxyue** [cloudwego/hertz#1096]
Describe the Question

![img_v3_02a3_64145d6d-a9ff-4b76-8777-8d9b4680a9cg](https://github.com/cloudwego/hertz/assets/28799116/794bffe4-8f1e-4b09-9eb9-27cb15e4ad32)
按照这个示例生成文档时报错，
plugin protoc_gen_hertz returns error: exit status 1, cause:
openapiv3/annotations.proto: File not found.
google/api/annotations.proto: File not found.

Expected behavior

怎么才能导入 openapiv3/annotations.proto 和 google/api/annotations.proto

Hertz version:

v0.8.1

Environment:

go1.22.2

**Comment by li-jin-gou** [comment]
same to https://github.com/cloudwego/hertz-examples/issues/143
