### ISSUE TITLE
路由问题

### ISSUE THREAD

**Issue by namecost** [cloudwego/hertz#1097]
当没有定义相关路由时，返回下面的错误：
Cannot open requested path

{"level":"error","message":"HERTZ: Cannot open file=\"./static/ghfghfgh/ind8ex.html\", error=open ./static/ghfghfgh/ind8ex.html: no such file or directory"}

**Comment by li-jin-gou** [comment]
没看懂要问啥🤨

**Comment by namecost** [comment]
> 没看懂要问啥🤨

没有定义相关路由的时候，系统会自动寻找相关静态文件。

**Comment by li-jin-gou** [comment]
代码咋写的发下

**Comment by namecost** [comment]
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	r.NoRoute(func(c context.Context, ctx *app.RequestContext) {
		//ctx.NotFound()
		ctx.Redirect(consts.StatusFound, []byte("/404")) // 未匹配的跳转到404
		return
		// Status Code: 404
	})
	// set NoMethod handler
	r.NoMethod(func(c context.Context, ctx *app.RequestContext) {
		ctx.NotFound()
		return
		// Status Code: 404
	})
	r.StaticFile("/favicon.ico", "./static/favicon.ico")
	root := r.Group("/", rootMw()...)
	{
		root.GET("/404", append(f404Mw(), f404.AddInfo)...)
		root.GET("/", append(rootMw(), home.AddInfo)...)
		root.GET("/page/:id/", append(rootMw(), home.AddInfo)...)

		_page := root.Group("/service", _pageMw()...)
		_page.GET("/register.:id", append(_pageMw(), page.AddInfo)...)
		_page.GET("/search.:id", append(_pageMw(), page.AddInfo)...)
		_page.GET("/about.:id", append(_pageMw(), page.AddInfo)...)
		_page.GET("/privacy.:id", append(_pageMw(), page.AddInfo)...)
		_page.GET("/contact.:id", append(_pageMw(), page.AddInfo)...)
		_page.GET("/dmca.:id", append(_pageMw(), page.AddInfo)...)
		_page.GET("/advertise.:id", append(_pageMw(), page.AddInfo)...)
		_page.GET("/buy.:id", append(_pageMw(), page.AddInfo)...)
		_page.GET("/buy-success.:id", append(_pageMw(), page.ResultInfo)...)
		_page.GET("/buy-error.:id", append(_pageMw(), page.ResultInfo)...)
		_page.GET("/submit-error.:id", append(_pageMw(), page.ResultInfo)...)

		_page.POST("/register.:id", append(_pageMw(), page.RegisterPost)...)
		_page.POST("/search.:id", append(_searchMw(), page.SearchPost)...)
		_page.POST("/contact.:id", append(_pageMw(), page.ContactPost)...)
		_page.POST("/dmca.:id", append(_pageMw(), page.DMCAPost)...)
		_page.POST("/submit.:id", append(_pageMw(), page.SubmitPost)...)
		_page.POST("/form.:id", append(_pageMw(), page.FormPost)...)

		root.GET("/:name.html", append(_postMw(), post.AddInfo)...)

		_sitemap := root.Group("/sitemap.:id", _sitemapMw()...)
		_sitemap.GET("/", append(_sitemapMw(), sitemap.AddInfo)...)
		_sitemap.GET("/:id/", append(_sitemapMw(), sitemap.AddInfo)...)

		_tag := root.Group("/:name", _tagMw()...)
		_tag.GET("/", append(_tagMw(), tag.AddInfo)...)
		_tag.GET("/:id/", append(_tagMw(), tag.AddInfo)...)

	}

}

**Comment by namecost** [comment]
访问这个页面  /ghfghfgh/ind8ex.html 就会出现 Cannot open requested path

{"level":"error","message":"HERTZ: Cannot open file=\"./static/ghfghfgh/ind8ex\", error=open ./static/ghfghfgh/ind8ex: no such file or directory"}
{"level":"info","t":1713709033,"m":"GET","s":404,"ip":"19.2.49.22","h":"test2.twzo.com","p":"/ghfghfgh/ind8ex","ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","r":""}

**Comment by namecost** [comment]
render里面加了这个，注释掉就好了。
	//h.Static("/", "./static")

**Comment by namecost** [comment]
有没有其他解决方案，直接当找不到文件的时候直接返回404，而不是给出这个“Cannot open requested path”
