### ISSUE TITLE
服务端如何感知客户端时候中断连接

### ISSUE THREAD

**Issue by liqiaoyang-pm** [cloudwego/hertz#1112]
最近在做一个LLM需求,需要客户端中断请求后服务端可以感知到请求中断，用gin中的ctx.request().context().done(),函数可以感知到，请问在hertz中应该如何实现？

**Comment by li-jin-gou** [comment]
issue 的问题同 https://github.com/cloudwego/hertz/issues/855 ，目前不支持，待 pr 合入
