### ISSUE TITLE
how do i use unix domain socket?

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#113]
how do i use unix domain socket? is this possible? any examples? thx

**Comment by Duslia** [comment]
You can customize Dial function by WithDialFunc

**Comment by welkeyever** [comment]
https://www.cloudwego.io/zh/docs/hertz/reference/config/ 
* set `WithHostPorts ` to your uds path
* set `WithNetwork ` to "unix"

**Comment by hiqsociety** [comment]
really need example. sorry i am quite dense...

**Comment by powerxu519** [comment]
**server**

> h := server.Default(server.WithHostPorts("xxx"), server.WithNetwork("unix"))

**Comment by hiqsociety** [comment]
ok thx got it.
i was trying to customize Dial function by WithDialFunc and also using the withhostport etc. i get it. thx.
