### ISSUE TITLE
Export errMissingFile error type

### ISSUE THREAD

**Issue by kamikazechaser** [cloudwego/hertz#1138]
**Is your feature request related to a problem? Please describe.**

Feature request.

**Describe the solution you'd like**

Standard library exposes `http.ErrMissingFile` the same should be exposed by `protocol`. I can send a PR if this is within scope.

**Describe alternatives you've considered**

N/A

**Additional context**

This allows easy building of error handlers without performing string comparison/using errors.Is e.t.c.

**Comment by li-jin-gou** [comment]
Can you submit a PR? @kamikazechaser ❤️
