### ISSUE TITLE
有没有现成的连一些中间件的方法

### ISSUE THREAD

**Issue by cxb999** [cloudwego/hertz#1151]
就是比如redis和mysql或者kafka，有没有现成的方法，可以支持链接池或者失败重试什么的，还是都需要我们自己封装咧？

**Comment by cxb999** [comment]
？为啥是无效问题

**Comment by GuangmingLuo** [comment]
按照这个模板提 issue 
<img width="1190" alt="image" src="https://github.com/cloudwego/hertz/assets/16001996/988fba02-0794-4aeb-9c13-067e8e3b478d">
