### ISSUE TITLE
有没有现成的连一些中间件的方法

### ISSUE THREAD

**Issue by cxb999** [cloudwego/hertz#1152]
**Describe the Question**

就是比如redis和mysql或者kafka，有没有现成的方法，可以支持链接池或者失败重试什么的，还是都需要我们自己封装咧？

**Hertz version:**

v0.9.1

**Environment:**

go version go1.21.6 darwin/amd64

**Comment by GuangmingLuo** [comment]
查看下这个项目的 README，有 gorm/gen 的例子：https://github.com/cloudwego/hertz-examples

**Comment by li-jin-gou** [comment]
> 就是比如redis和mysql或者kafka，有没有现成的方法，可以支持链接池或者失败重试什么的，还是都需要我们自己封装咧？

使用工具生成吧 https://www.cloudwego.io/zh/docs/cwgo/tutorials/layout/
