### ISSUE TITLE
 OnShutdown: There is no guarantee of order or execution

### ISSUE THREAD

**Issue by powerxu519** [cloudwego/hertz#117]
**Describe the bug**

 Engine.OnShutdown is no guarantee of order or execution
 **Is this its own design idea? If not, I think it is a bug**

**To Reproduce**

1.  go run hertz-examples/graceful_shutdown/main.go

**Expected behavior**

Because of asynchronous execution, there is no guarantee of order or success

**Screenshots**

![image](https://user-images.githubusercontent.com/58555404/177368243-7900d8d0-7fb6-47b9-a240-22b96196a635.png)
![image](https://user-images.githubusercontent.com/58555404/177368343-1f63a0c6-80cb-43a3-95a8-a37d822fe716.png)

**Environment:**

GO111MODULE="on"
GOARCH="amd64"
GOOS="linux"

**Comment by welkeyever** [comment]
Yes, It is by design. 
Because synchronization here means waiting, however, normally there hasn't much time for the closing hook. Synchronization may result in subsequent hooks not even having a chance to execute. 

If there is a strong order of exit behavior, you may assemble it and register it as one hook.

**Comment by powerxu519** [comment]
However, there is no guarantee of success, and if you use hooks to shut down some services, you may leak

**Comment by welkeyever** [comment]
Yes, but in a real environment it is difficult to guarantee, as deployment platform normally has a DDL for a closing process(like k8s, platform in Bytedance also). Process may be directly killed when time's up. 

Very little can be done by just having synchronization in hooks to reduce the chance of leak.

**Comment by powerxu519** [comment]
I see. Thank you very much
