### ISSUE TITLE
在 go1.23.0版本下编译报错invalid reference to encoding/json.safeSet

### ISSUE THREAD

**Issue by Royal-go** [cloudwego/hertz#1174]
**Describe the bug**

项目用到hertz v0.9.2，将go版本升级到1.23.0,编译报错
link: github.com/bytedance/sonic/ast: invalid reference to encoding/json.safeSet

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hertz version:**

Please provide the version of Hertz you are using.

**Environment:**

The output of `go env`.

**Additional context**

**Comment by GuangmingLuo** [comment]
升级 sonic 至最新版

**Comment by Royal-go** [comment]
> 升级 sonic 至最新版

谢谢，
通过这个命令解决了
go get -u github.com/bytedance/sonic/ast
