### ISSUE TITLE
How can I bind mapped or arrayed query parameters in a GET request?

### ISSUE THREAD

**Issue by Benjababe** [cloudwego/hertz#1176]
**Describe the Question**

I'm currently using protobuf to generate the endpoints and parameters to be bound. But I'm not sure how to bind query parameters that are mapped or slices. (Eg: `?filter[colour]=red&filter[size]=xl`). 

**Reproducible Code**

I'm not totally sure how it would be created with protobuf but this is my guess.

```
message TestQuery {
  string              key_word = 1;
  map<string, string> filter   = 2;
}

message Empty {}

service BookingService {
  rpc Test(TestQuery) returns (Empty) {
    option (api.get) = "/api/test";
  }
}
```

And when `GET /api/test?filter[color]=red&filter[size]=xl` is called, the `Filter` attribute is nil. 

Using `/api/test?filter={ "color": "red", "size": "xl" }` works but I think including JSON strings in the query path isn't standard practice. 

I was able to adapt gin's [QueryMap function](https://github.com/gin-gonic/gin/blob/master/context.go#L476-L505) for the `RequestContext` struct but writing external code for an existing library is unoptimal.

```go
func GetQueryMap(c *app.RequestContext, key string) (map[string]string, bool) {
	var values url.Values

	u, err := url.Parse(c.Request.URI().String())
	if err != nil {
		values = url.Values{}
	} else {
		values = u.Query()
	}

	dicts := make(map[string]string)
	exist := false
	for k, v := range values {
		if i := strings.IndexByte(k, '['); i >= 1 && k[0:i] == key {
			if j := strings.IndexByte(k[i+1:], ']'); j >= 1 {
				exist = true
				dicts[k[i+1:][:j]] = v[0]
			}
		}
	}

	return dicts, exist
}

func GetQueryMapSlice(c *app.RequestContext, key string) (map[string][]string, bool) {
	var values url.Values

	u, err := url.Parse(c.Request.URI().String())
	if err != nil {
		values = url.Values{}
	} else {
		values = u.Query()
	}

	dicts := make(map[string][]string)
	exist := false
	for k, v := range values {
		if i := strings.IndexByte(k, '['); i >= 1 && k[0:i] == key {
			if j := strings.IndexByte(k[i+1:], ']'); j >= 1 {
				exist = true
				dicts[k[i+1:][:j]] = v
			}
		}
	}

	return dicts, exist
}
```

**Expected behavior**

I need to be able to pass in mapped parameters like `?filter[color]=red&filter[size]=xl` and Hertz will bind it to the relevant request struct in the `c.BindAndValidate(&req)` call.

**Hertz version:**

v0.9.2

**Environment:**

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\<user>\AppData\Local\go-build
set GOENV=C:\Users\<user>\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\<user>\go\pkg\mod
set GONOPROXY=github.com/dysonsphere-watt
set GONOSUMDB=github.com/dysonsphere-watt
set GOOS=windows
set GOPATH=C:\Users\<user>\go
set GOPRIVATE=github.com/dysonsphere-watt
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\<user>\Desktop\<dirs...>\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\<user>\AppData\Local\Temp\go-build606887767=/tmp/go-build -gno-record-gcc-switches

**Comment by FGYFFFF** [comment]
你需要将 json 进行序列化，然后使用 url.PathEscape() 进行转换，之后将得到的字符串赋值到 query 里就可以了
