### ISSUE TITLE
how do i set the content type?

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#118]
not sure how to set content-type.

all examples provide text/plain

how to set response header easily?

i know ctx.HTML() sets content type html but how do i override c.String() coz i want output as text/html

**Comment by welkeyever** [comment]
check here: https://github.com/cloudwego/hertz/blob/9ced80f0fdfca80d478af48635921ff52fb30bd2/pkg/app/server/render/render.go#L62

**Comment by hiqsociety** [comment]
in the end i used c.Data() <- is this advisable? just to set text/html

**Comment by welkeyever** [comment]
yes, the principle is the same, the core is the one mentioned above.
