### ISSUE TITLE
client error:connection is closed by peer while being in the connection pool

### ISSUE THREAD

**Issue by zhangairku** [cloudwego/hertz#1183]
**使用hertz客户端报错**

对一个http接口访问时，偶发性的报错：connection is closed by peer while being in the connection pool

**Reproducible Code**
clientCfg := &tls.Config{
			InsecureSkipVerify: true,
		}
client.NewClient(
			client.WithTLSConfig(clientCfg),
			client.WithDialer(standard.NewDialer()),
			//client.WithDialTimeout(1 * time.Second),//连接建立超时时间，默认 1s
			client.WithWriteTimeout(5000*time.Millisecond),       //写入数据超时时间，默认值：无限
			client.WithClientReadTimeout(20*time.Second),         //设置读取 response 的最长时间，默认无限长
			client.WithMaxConnWaitTimeout(1000*time.Millisecond), //设置等待空闲连接的最大时间，默认不等待
			client.WithMaxIdleConnDuration(30*time.Second),       //空闲连接超时时间,当超时后会关闭该连接，默认10s
			client.WithMaxConnDuration(30*time.Second),           //设置连接存活的最大时长，超过这个时间的连接在完成当前请求后会被关闭，默认无限长
			client.WithMaxConnsPerHost(1000000),
}
**Hertz version:**

0.9.2

**Comment by mystery-pai** [comment]
Encountered the same error, not sure how to resolve it...
