### ISSUE TITLE
link: github.com/bytedance/sonic/ast: invalid reference to encoding/json.safeSet

### ISSUE THREAD

**Issue by meacial** [cloudwego/hertz#1184]
go version: 1.23

os: linux 

when build, get error:

**link: github.com/bytedance/sonic/ast: invalid reference to encoding/json.safeSet**

**Comment by GuangmingLuo** [comment]
升级 sonic 至最新版本

**Comment by GuangmingLuo** [comment]
https://github.com/cloudwego/hertz/issues/1180
