### ISSUE TITLE
hz thriftgo 生成的文件头是否可以关闭或定制

### ISSUE THREAD

**Issue by lhpqaq** [cloudwego/hertz#1185]
**Describe the Question**

团队使用的hz版本不一样，每次update都会更改model文件的文件头与.hz中的版本，见图片。
我没有找到可以控制文件头的hz或者thriftgo的参数，请问是否有这样的参数或者是否可以支持这样的参数？

**Reproducible Code**

```sh
	hz update --mod=xxx --idl=idl/xxx.thrift --customize_package=template/package.yaml
```

**Expected behavior**

可以通过参数设置是否修改.hz和文件头

**Screenshots**

<img width="1263" alt="image" src="https://github.com/user-attachments/assets/5c7405f1-25ff-4907-b641-db029d783587">
<img width="1266" alt="image" src="https://github.com/user-attachments/assets/e1be0e9d-680d-441b-9766-9ec9c49b8dd5">

**Hertz version:**

Please provide the version of Hertz you are using.

**Environment:**

The output of `go env`.

**Additional context**

Add any other context about the question here.

**Comment by lhpqaq** [comment]
比如生成代码的时候同时添加证书

**Comment by li-jin-gou** [comment]
感觉不太好搞 cc @FGYFFFF

**Comment by li-jin-gou** [comment]
这块的确很烦人

**Comment by lhpqaq** [comment]
可以分配给我试试不 @li-jin-gou

**Comment by FGYFFFF** [comment]
@lhpqaq 这块需要去 thriftgo[https://github.com/cloudwego/thriftgo] 仓库解决~ 主要是 没有版本号之后会不容易查问题

**Comment by lhpqaq** [comment]
@FGYFFFF  版本号统一放在一个.thriftgo 文件里怎么样，每个model对应一个版本号，仿照.hz

**Comment by FGYFFFF** [comment]
> @FGYFFFF 版本号统一放在一个.thriftgo 文件里怎么样，每个model对应一个版本号，仿照.hz

理论上可以；不过最好去 thriftgo 提 issue 讨论吧，先看看能不能去掉文件头的版本号
