### ISSUE TITLE
项目中使用io/ioutil包问题

### ISSUE THREAD

**Issue by miajio** [cloudwego/hertz#1202]
基于项目中使用到的io/ioutil是否考虑直接更换为使用os
从golang官方文档定义的使用, io/ioutil在1.6版本后虽然保留,但是内部方法是直接调用了os的对应方法。
考虑到后续golang的版本更新情况, 不太建议持续使用io/ioutil包

**Comment by GuangmingLuo** [comment]
@miajio Kitex 项目中已经替换过了，你有兴趣的话可以给 Hertz 项目提个 PR 修改下
