### ISSUE TITLE
杀死进程后重启应用提示端口被占用

### ISSUE THREAD

**Issue by jinkaz** [cloudwego/hertz#1211]
版本：0.9.3
问题：在单机测试环境，测试通过kill -2 kill -9 后会有一段时间提示端口号被占用
日志：panic: create netpoll listener fail: listen tcp 0.0.0.0:8523: bind: address already in use

-2 也看到了优雅停机的日志：
2024/10/14 17:45:08.359425 hertz.go:113: [Info] HERTZ: Received signal: interrupt
2024/10/14 17:45:08.359502 hertz.go:77: [Info] HERTZ: Begin graceful shutdown, wait at most num=5 seconds...
2024/10/14 17:45:08.361387 registry.go:121: [Info] HERTZ: deregister instance success
2024/10/14 17:45:08.361504 engine.go:314: [Info] HERTZ: Execute OnShutdownHooks finish
但重启应用，就会提示被占用。
启动命令：nohup ./xxxx &

**Comment by GuangmingLuo** [comment]
@jinkaz 按照模版创建 issue  
<img width="1210" alt="image" src="https://github.com/user-attachments/assets/ae6b7d96-225d-439a-a4b7-32f58a5ad7c7">
