### ISSUE TITLE
申请将自己的项目加入到Bizdemo代码示例

### ISSUE THREAD

**Issue by qingyggg** [cloudwego/hertz#1219]
1.我用hertz写了一个简易的论坛服务器，后面计划将该项目拆分成微服务，并且逐步完善它作为论坛服务器应该有的功能

2.我想将该项目贡献到biz demo里作为代码示例，以供学习hertz，热爱hertz的开发者们一个优秀的项目实例，希望该项目能让他们更加收益匪浅

3.该项目的代码仓库 地址  ：https://github.com/qingyggg/blog_server.git

**Comment by GuangmingLuo** [comment]
duplicated with https://github.com/cloudwego/hertz-examples/issues/156
