### ISSUE TITLE
hz工具生成代码时能支持自动寻找mod 吗？

### ISSUE THREAD

**Issue by pigfu** [cloudwego/hertz#1220]
**Describe the bug**

我在/home/app目录下执行了go mod init app
然后在 /home/app/order目录下执行  hz new -module app -idl proto/order.proto
它会在/home/app/order目录下继续生成个go.mod文件，而不能像kitex一样寻找/home/app目录下的go.mod

**Comment by FGYFFFF** [comment]
你不指定 mod 他就自己搜索了
