### ISSUE TITLE
access log middleware: latency value is too long

### ISSUE THREAD

**Issue by teresadq** [cloudwego/hertz#1231]
**Describe the bug**

When using access log middleware and setup `${latency}`, the output value contains too many white space!!!

**To Reproduce**
use the code below:
```
	h.Use(
		accesslog.New(
			accesslog.WithFormat(`[${time}] status=${status} latency="${latency}" method=${method} path=${path} queryParams=${queryParams}`),
		),
	)
```

**Expected behavior**

we expect the output is `latency="459ns"`. But we got `latency="        459ns"`.

**Screenshots**

![image](https://github.com/user-attachments/assets/276f10b4-0e11-4de9-83a6-e8bb9bb0c267)

**Hertz version:**

hertz: v0.9.3

**Environment:**

go version go1.23.1 linux/amd64

**Comment by xiaost** [comment]
@teresadq `accesslog` is NOT a part of this hertz repo.
kindly report on corresponding issue page of `accesslog`.
