### ISSUE TITLE
go install hz

### ISSUE THREAD

**Issue by xieyj-apple** [cloudwego/hertz#1235]
go install github.com/cloudwego/hertz/cmd/hz@latest
go: downloading github.com/cloudwego/hertz v0.9.3
go: github.com/cloudwego/hertz/cmd/hz@v0.0.4: module github.com/cloudwego/hertz@v0.9.3 found, but does not contain package github.com/cloudwego/hertz/cmd/hz

**Comment by GuangmingLuo** [comment]
@xieyj-apple 按照 issue 模板进行提问，否则会被标记为 Invalid issue
