### ISSUE TITLE
hz update命令不更新已有handler方法的注释

### ISSUE THREAD

**Issue by debuggy** [cloudwego/hertz#1238]
**Describe the Question**

我修改了idl里面某个方法的路径，在执行 hz update 命令时发现handler里该方法的注释没有同步修改，想问下这是by design的设计吗
```
hz update -idl idl/xxx.thrift
```

**Expected behavior**

希望可以同步修改handler注释，因为我会使用swagger中间件来同步修改接口文档

**Hertz version:**

v0.9.1

**Environment:**

GOVERSION='go1.21.0'

**Comment by xiaost** [comment]
这是预期内的，如果已经存在了，不会覆盖。
