### ISSUE TITLE
期望启用https时提供http的重定向能力

### ISSUE THREAD

**Issue by Jeremyly** [cloudwego/hertz#1240]
**Is your feature request related to a problem? Please describe.**

用户有时候访问时，可能输入的是http，但监听的是https。目前提供的WithTLS()不具备该参数。且http请求直接被拒绝，没有开放自定义处理的接口。

**Describe the solution you'd like**

期望的是，提供一个配置方法，支持自定义处理http请求，比如重定向到https。

**Additional context**

hertz version: v0.9.3

**Comment by xiaost** [comment]
重定向，只需要几行代码，没必要放到hertz本身实现。如果有需要，请自行重定向。

**Comment by Jeremyly** [comment]
> 重定向，只需要几行代码，没必要放到hertz本身实现。如果有需要，请自行重定向。

关键在于https并不是使用默认端口443。而是使用了特定的端口，一个端口只能起一个监听。无法再起一个同端口的http监听的呀。
比如正确的访问路径是：`https://127.0.0.1:8443/ping`。但是由于用户未输入s:`http://127.0.0.1:8443/ping`。此时框架报错：
```hash
[Error] HERTZ: Error=tls: first record does not look like a TLS handshake, remoteAddr=127.0.0.1:54825
```
我期望的就是这种场景，可以提供一个自定义接口，可以由用户自定义处理这种错误。
