### ISSUE TITLE
Hertz做http反向代理时，遇到协议升级没能正确处理

### ISSUE THREAD

**Issue by shawdongGithub** [cloudwego/hertz#1249]
**Describe the bug**
使用hertz做7层http反向代理，没有正确处理协议升级。
**To Reproduce**
1. 反向代理的相关代码
```
# packge hadler
func Proxy(ctx context.Context, c *app.RequestContext) {
	target := "http://xx.xx.xx.xx:port"
	p, _ := reverseproxy.NewSingleHostReverseProxy(target)
	p.ServeHTTP(ctx, c)
}
```
2. hertz 服务启动的相关代码
```
func main() {
	h := server.Default()
	h.NoRoute(handler.Proxy)
	h.Spin()
}
```
3. 当我代理的目标站点存在某个websocket连接资源时，会报错无法建立websocket连接。

**Expected behavior**
hertz作为http7层反向代理时能够正确处理协议升级维持长连接

**Hertz version: v0.9.3**

**Comment by xiaost** [comment]
暂不支持。

**Comment by rogerogers** [comment]
`reverseproxy` 有个 `NewWSReverseProxy` 方法能满足需求吗

**Comment by shawdongGithub** [comment]
> `reverseproxy` 有个 `NewWSReverseProxy` 方法能满足需求吗

针对特定的url直接配置成NewWSReverseProxy确实能满足，但比较麻烦不太灵活。
