### ISSUE TITLE
feat: add hertz sentinel adapter

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/hertz#138]
**Is your feature request related to a problem? Please describe.**

- add hertz sentinel adapter so hertz can use sentinel to achieve circuit breaker and limiter,and so on.

**Describe the solution you'd like**
- doesn't need a lot of extensions
- use `hertz middleware` and `sentinel-go` to achieve client and server 's adapter
- the pseudo-code as follows
```go
func SentinelServerMiddleware(opts ...Option) hertz.HandlerFunc {
	options := evaluateOptions(opts)
	return func(ctx context.Context, c *hertz.RequestContext) {
		resourceName := c.Request.Method + ":" + c.FullPath()

		if options.resourceExtract != nil {
			resourceName = options.resourceExtract(c)
		}

		entry, err := sentinel.Entry(
			resourceName,
			sentinel.WithResourceType(base.ResTypeWeb),
			sentinel.WithTrafficType(base.Inbound),
		)

		if err != nil {
			if options.blockFallback != nil {
				options.blockFallback(c)
			} else {
				c.AbortWithStatus(http.StatusTooManyRequests)
			}
			return
		}

		defer entry.Exit()
		c.Next(ctx)
	}
}

```
**Describe alternatives you've considered**

**Additional context**
- https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/middleware/
- https://sentinelguard.io/zh-cn/docs/golang/basic-api-usage.html

**Comment by Skyenought** [comment]
i want to try

**Comment by Skyenought** [comment]
I want to try this
