### ISSUE TITLE
Hertz panic on my mac with apple 64-bit processor

### ISSUE THREAD

**Issue by stayhungry001** [cloudwego/hertz#140]
**Describe the bug**
I try to run a sample example on my mac with m1 CPU. The following panic shows up. The go runs ok with other project.

panic: Unsupported CPU, maybe it's too old to run Sonic.

goroutine 1 [running]:
github.com/bytedance/sonic/internal/native.init.0()
        /Users/hellworld/go/pkg/mod/github.com/bytedance/sonic@v1.3.0/internal/native/dispatch_amd64.go:144 +0x1fb
exit status 2

**To Reproduce**
Run the following code:

package main

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/basic_auth"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

func main() {
	h := server.Default(server.WithHostPorts("127.0.0.1:8080"))
	h.Use(basic_auth.BasicAuth(map[string]string{
		"test1": "value1",
		"test2": "value2",
	}))

	h.GET("/basicAuth", func(ctx context.Context, c *app.RequestContext) {
		c.String(consts.StatusOK, "hello hertz")
	})

	h.Spin()
}

**Expected behavior**

The code is running normal.

**Screenshots**

**Hertz version:**

v0.1.0

**Environment:**

The 2020 mac with m1
go version go1.18.3 darwin/amd64

**Additional context**

**Comment by li-jin-gou** [comment]
https://www.cloudwego.io/zh/docs/hertz/reference/json/#mac-m1-%E4%B8%8A%E7%BC%96%E8%AF%91%E6%8A%A5%E9%94%99 @stayhungry001

**Comment by FlameMida** [comment]
you should install go darwin/arm64 version not darwin/amd64 version @stayhungry001
