### ISSUE TITLE
http 服务端不支持web session操作吗?

### ISSUE THREAD

**Issue by supercxx** [cloudwego/hertz#141]

**Comment by li-jin-gou** [comment]
对于 Session 的扩展能力详见 https://github.com/cloudwego/hertz/issues/65 @supercxx

**Comment by Duslia** [comment]
We will support it soon and please pay attention to #65 . Hertz also provide adapter to net/http in https://github.com/cloudwego/hertz/blob/develop/pkg/common/adaptor/request.go. You can adapt session middleware easily. This issue will be closed.
