### ISSUE TITLE
Does the routing function not support fuzzy matching?

### ISSUE THREAD

**Issue by zjclyz** [cloudwego/hertz#157]
**Describe the bug**

I was hoping to match all paths with "/*", and the startup reported an error directly.

**To Reproduce**

```go
func main() {
	h := server.New(server.WithTransport(standard.NewTransporter), server.WithHostPorts("127.0.0.1:8081"))
	h.Any("/*", func(ctx context.Context, rc *app.RequestContext) {
		rc.String(consts.StatusOK, "ok")
	})
	h.Spin()
}
```

**Expected behavior**

The above code reported an error directly on startup with the following error message.
```
2022/07/30 17:06:21.941828 engine.go:524: [Debug] HERTZ: Method=GET    absolutePath=/*                        --> handlerName=main.main.func1 (num=1 handlers)
panic: wildcards must be named with a non-empty name in path '/*'

goroutine 1 [running]:
github.com/cloudwego/hertz/pkg/route.checkPathValid(0xc00040923c, 0x2, 0xc0002dd320)
        /Users/xxx/develop/go_work/pkg/mod/github.com/cloudwego/hertz@v0.2.0/pkg/route/tree.go:137 +0x277
github.com/cloudwego/hertz/pkg/route.(*router).addRoute(0xc0003dc380, 0xc00040923c, 0x2, 0xc0000ba338, 0x1, 0x1)
        /Users/xxx/develop/go_work/pkg/mod/github.com/cloudwego/hertz@v0.2.0/pkg/route/tree.go:154 +0x4d
github.com/cloudwego/hertz/pkg/route.(*Engine).addRoute(0xc00000c1e0, 0x173ee80, 0x3, 0xc00040923c, 0x2, 0xc0000ba338, 0x1, 0x1)
        /Users/xxx/develop/go_work/pkg/mod/github.com/cloudwego/hertz@v0.2.0/pkg/route/engine.go:541 +0x132
github.com/cloudwego/hertz/pkg/route.(*RouterGroup).handle(0xc00000c208, 0x173ee80, 0x3, 0x173e727, 0x2, 0xc0000ba330, 0x1, 0x1, 0xc000128101, 0xc0000ba330)
        /Users/xxx/develop/go_work/pkg/mod/github.com/cloudwego/hertz@v0.2.0/pkg/route/routergroup.go:113 +0x1a7
github.com/cloudwego/hertz/pkg/route.(*RouterGroup).Any(0xc00000c208, 0x173e727, 0x2, 0xc0000ba330, 0x1, 0x1, 0xc000096058, 0x10014c0)
        /Users/xxx/develop/go_work/pkg/mod/github.com/cloudwego/hertz@v0.2.0/pkg/route/routergroup.go:174 +0x7c
main.main()
        /Users/xxx/develop/go_work/go-gateway/cmd/demo/hertzsvr/hertzsvr.go:26 +0xfc
exit status 2
```

I want to match all requests with something like "/*", I don't care about the specific request path, is this not supported?

**Hertz version:**

hertz@v0.2.0

**Environment:**

> GO111MODULE="auto"
GOARCH="amd64"
GOBIN="/Users/xxx/develop/go_work//bin"
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xxx/develop/go_work/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxx/develop/go_work/"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go@1.16/1.16.15/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go@1.16/1.16.15/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.15"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xxxx/develop/go_work/go-gateway/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s3/81mgg3_919b18cg6x54nfpj00000gn/T/go-build294814848=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by li-jin-gou** [comment]
参考一下这个demo https://github.com/cloudwego/hertz-examples/tree/main/route @zjclyz

**Comment by zjclyz** [comment]
> 
看了的，没有我预期的，我希望把所有请求匹配到一个handler中去处理，应该如何设置呢？

**Comment by zjclyz** [comment]
> > 
> 
> 看了的，没有我预期的，我希望把所有请求匹配到一个handler中去处理，应该如何设置呢？

**Comment by zjclyz** [comment]
> 参考一下这个demo https://github.com/cloudwego/hertz-examples/tree/main/route @zjclyz


看了的，没有我预期的，我希望把所有请求匹配到一个handler中去处理，应该如何设置呢？

**Comment by li-jin-gou** [comment]
> > 参考一下这个demo https://github.com/cloudwego/hertz-examples/tree/main/route @zjclyz
> 
> 看了的，没有我预期的，我希望把所有请求匹配到一个handler中去处理，应该如何设置呢？

示例demo
```
	h := server.Default()
	h.Any("/*params", func(c context.Context, ctx *app.RequestContext) {
		hlog.Info(ctx.Param("params"))
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})
	h.Spin()
```
路由是有优先级的
```
静态路由 > 参数路由 > 通配路由
```
要想实现你这个功能你要规避这一点，按照例子改改就行了，不复杂。
另外都放在一个 handler里面就觉得怪怪的....

**Comment by zjclyz** [comment]
> > > 参考一下这个demo https://github.com/cloudwego/hertz-examples/tree/main/route @zjclyz
> > 
> > 
> > 看了的，没有我预期的，我希望把所有请求匹配到一个handler中去处理，应该如何设置呢？
> 
> 示例demo
> 
> ```
> 	h := server.Default()
> 	h.Any("/*params", func(c context.Context, ctx *app.RequestContext) {
> 		hlog.Info(ctx.Param("params"))
> 		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
> 	})
> 	h.Spin()
> ```
> 
> 路由是有优先级的
> 
> ```
> 静态路由 > 参数路由 > 通配路由
> ```
> 
> 要想实现你这个功能你要规避这一点，按照例子改改就行了，不复杂。 另外都放在一个 handler里面就觉得怪怪的....

比如做一个网关的场景，是希望匹配所有请求统一处理的，并不像一个业务系统一样，某类path就应该到对应的handler去处理。

其实我也好奇，hertz为啥把路由功能的代码也整合进来呢？是否考虑用第三库的形式提供路由功能？这样解耦后，如果觉得官方的不满足要求可以有新的实现？

**Comment by zjclyz** [comment]
@li-jin-gou 这个提问给怎么关闭了？🤣
