### ISSUE TITLE
how do i get multiple select values from a form?

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#158]
my form has \<select name="g" multiple>\<option name="70010000"\>70010000\</option\> ... etc.

i got only the first value using the below form using

```

                g := c.PostForm("g")
                fmt.Printf("g = %s\n",g)
                //g = 70010000

```  

but how do i get all the values below?

```
    g:[70010000 70010700 70010300]

````

````

` {{} [] } %!s(bool=false) %!s(bool=false)    } {{} [] } <nil> {%!s(*protocol.Request=<nil>)} %!s(*bytebufferpool.ByteBuffer=<nil>)  %!s(int=4194304) %!s(*multipart.Form=&{map[city:[] country:[] d:[] f[]:[                       ] g:[70010000 70010700 70010300] h:[] n:[] state:[] v:[  ]] map[]}) ----WebKitFormBoundarypcGsJBqbVr5PnXRl %!s(bool=true) %!s(bool=true) %!s(bool=false) [] [] %!s(*config.RequestOptions=<nil>)} {{} {{} %!s(bool=false) %!s(bool=false) %!s(bool=false) %!s(bool=false) %!s(bool=false) %!s(int=0) %!s(int=0)   hertz [] { HTTP/1.1 200 OK

`````

**Comment by rogerogers** [comment]
Seems not support yet, you can use json instead.

**Comment by hiqsociety** [comment]
> Seems not support yet, you may use json request instead.

the values are inside BUT not gettable. means 

fmt.Printf("%s",g) only gets the first value 70010000 from

    g:[70010000 70010700 70010300]
    
    surely there's a way to get all the values?
    
       g := c.PostForm("g")

**Comment by hiqsociety** [comment]
> Seems not support yet, you may use json request instead.

how?

**Comment by rogerogers** [comment]
> > Seems not support yet, you may use json request instead.
> 
> the values are inside BUT not gettable. means
> 
> fmt.Printf("%s",g) only gets the first value 70010000 from
> 
> ```
> g:[70010000 70010700 70010300]
> 
> surely there's a way to get all the values?
> 
>    g := c.PostForm("g")
> ```

I take a try, c.PostForm("g") only return first value, you may get  all args by using c.PostArgs(), then parse it yourself.

```go
func getG(args string) []string {
	var g []string
	values := strings.Split(args, "&")
	for _, v := range values {
		if !strings.Contains(v, "=") {
			continue
		}
		a := strings.SplitN(v, "=", 2)
		g = append(g, a[1])
	}
	return g
}

args, err := url.QueryUnescape(fmt.Sprintf("%s", c.PostArgs()))
fmt.Printf("%#v", getG(args))
```

**Comment by rogerogers** [comment]
> > Seems not support yet, you may use json request instead.
> 
> how?

Covert all formdata to json format.

**Comment by hiqsociety** [comment]
1. i have no idea why but i'm always getting nothing from c.PostArgs(). PostForm("g") has things but c.PostArgs() always return nothing.
2. i cant believe this simple c.PostForm not available. i check how to fix it

**Comment by hiqsociety** [comment]
updated : i've checked. it's not supported. possible NOT to use JSON? when will this be supported?
GetPostForm doesnt work too.

please help

**Comment by rogerogers** [comment]
PostForm peek value from PostArgs, seems impossible PostArgs return nothing when PostForm has value . Could you provide more detail? data and headers.

**Comment by hiqsociety** [comment]
> PostForm peek value from PostArgs, seems impossible PostArgs return nothing when PostForm has value . Could you provide more detail? data and headers.

i will do so. need some time to replicate.
since i can get PostForm and not PostArgs, i will wait more for the multiple value "select" to be ready then. since i'm only lacking this and i can accept postargs not working on my side.

**Comment by hiqsociety** [comment]
i updated issue here,

with enctype="multipart/form-data", PostArgs shows nothing.

https://github.com/cloudwego/hertz/issues/180
