### ISSUE TITLE
http2 support

### ISSUE THREAD

**Issue by juhuahaoteng** [cloudwego/hertz#165]
http2 support, as soon as you can.

**Comment by li-jin-gou** [comment]
Hello @juhuahaoteng  feel free to contact us and join the lark group, describing a specific requirement scenario❤️

**Comment by Duslia** [comment]
https://github.com/hertz-contrib/http2/pull/1

**Comment by ultperf** [comment]
@Duslia i was trying to test this but can you provide an example for letsencrypt in your repo?
i'll be testing out in real production traffic.

my letsencrypt previous config is
```
import (
	"golang.org/x/crypto/acme"
	"golang.org/x/crypto/acme/autocert"
)
	


		letsencryptCfg := &tls.Config{
			GetCertificate: certManager.GetCertificate,
			NextProtos: []string{
				"http/1.1", acme.ALPNProto,
			},
		}

			tlsCfg := &tls.Config{
				GetCertificate: func(hello *tls.ClientHelloInfo) (*tls.Certificate, error) {
					return letsencryptCfg.GetCertificate(hello)
				},
			}

```

with reference here, not sure how to do letsencrypt with http2 coz i saw the http/1.1 and not sure how to make it http2 etc. can u pls provide example and expand on the above? thx.
https://github.com/Duslia/hertz/blob/feat/h2/examples/h2/main.go

**Comment by li-jin-gou** [comment]
@juhuahaoteng  already support https://github.com/hertz-contrib/http2
