### ISSUE TITLE
Qustion about api func (ctx *RequestContext) AbortWithMsg(msg string, statusCode int)

### ISSUE THREAD

**Issue by jxskiss** [cloudwego/hertz#166]
While reading the code, I find that the api 
func (ctx *RequestContext) AbortWithMsg(msg string, statusCode int) takes statusCode as second arg, but all other AbortXXX apis take statusCode as first arg. It looks strange and no good reason, does it make sense to have consistent arg position for statusCode?

**Comment by li-jin-gou** [comment]
@jxskiss  the position of the parameter is meaningless
