### ISSUE TITLE
how do i get the image size uploaded in pixels?

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#171]
`
        h.POST("/p", func(ctx context.Context, c *app.RequestContext) {

                form, _ := c.MultipartForm()
                files := form.File["f[]"]

                for _, file := range files {

                        fileExt := filepath.Ext(file.Filename)

                 if fileExt == ".gif" {

                }else if fileExt == ".png" {

                }else if fileExt == ".jpg" {

                }
               src, _ := file.Open()
               
               //stuck here, how do i make get the image size in pixels?
               
`

**Comment by li-jin-gou** [comment]
use some image processing package :anguished: and hertz will not support... @hiqsociety
