### ISSUE TITLE
run go test fail,path:hertz/pkg/route 

### ISSUE THREAD

**Issue by safeoy** [cloudwego/hertz#173]
**Describe the bug**

run go test fail， path : hertz/pkg/route 

**To Reproduce**

1. cd hertz/pkg/route
2. run `go test`
3. check test log

**Expected behavior**

unit test pass

**Screenshots**

![image](https://user-images.githubusercontent.com/5627477/182805172-9fa47318-4136-48f8-bdc7-65811803f84f.png)

**Hertz version:**

v0.2.1

**Environment:**

GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/work/.cache/go-build"
GOENV="/home/work/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/work/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/work/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/work/go/src/github.com/safeoy/hertz/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2130077788=/tmp/go-build -gno-record-gcc-switches"

**Comment by LhdDream** [comment]
Hi, first of all thank you for your PR , when Go version <= 1.16, mime.TypeByExtension will return Content-Type='text/plain; charset=utf-8', otherwise it will return Content-Type='text/x-go; charset=utf-8'

**Comment by LhdDream** [comment]
You can refer to this link to refine your unit tests
https://github.com/gin-gonic/gin/blob/ad66d9d11a7d79d08be897bc617cda1e20f71855/context_test.go#L1017

**Comment by safeoy** [comment]
@LhdDream Thanks for the reminder, I'll try to refine it

**Comment by safeoy** [comment]
> Hi, first of all thank you for your PR , when Go version <= 1.16, mime.TypeByExtension will return Content-Type='text/plain; charset=utf-8', otherwise it will return Content-Type='text/x-go; charset=utf-8'

@LhdDream I've re-edited the code, do you mind if I use this quote of yours in the comments? It is shown below

![image](https://user-images.githubusercontent.com/5627477/182868940-abe431b2-c2ae-44fc-80e7-ce8509d7bf48.png)

**Comment by LhdDream** [comment]
@safeoy Of course, I'll feel very honored
