### ISSUE TITLE
Read data timeout in hijack mode

### ISSUE THREAD

**Issue by zjclyz** [cloudwego/hertz#178]
**Describe the bug**

When starting the service, if the transport is set to "standard.NewTransporter", a timeout error will be reported immediately when reading the connection data in hijacking mode, and if it is "netpoll. NewTransporter" is normal.

**To Reproduce**

The following code can reproduce the problem：
```go
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/network"
	// "github.com/cloudwego/hertz/pkg/network/netpoll"
	"github.com/cloudwego/hertz/pkg/network/standard"
)

func main() {
	// server.WithTransport(standard.NewTransporter) 
	h := server.Default(server.WithTransport(standard.NewTransporter),
		 server.WithHostPorts("127.0.0.1:8080"), server.WithStreamBody(true))

	// server.WithTransport(netpoll.NewTransporter)
	// h := server.Default(server.WithTransport(netpoll.NewTransporter),
	// 	 server.WithHostPorts("127.0.0.1:8080"), server.WithStreamBody(true))

	h.Any("/hello", handler)
	h.Spin()
}

func handler(ctx context.Context, c *app.RequestContext) {
	c.Hijack(func(c network.Conn) { // 劫持连接
		fmt.Println("start...")
		start := time.Now()
		_, err := c.Peek(1) // Tries to read the data, but immediately reports a timeout error
		d := time.Since(start)/time.Millisecond
		fmt.Println("peek err:", err, "Duration: ", d) // print: peek err: read tcp 127.0.0.1:8080->127.0.0.1:64833: i/o timeout Duration:  0s
		fmt.Println("over...")
	})
	c.WriteString("hello")
}
```

**Expected behavior**

When you start the service with the above code, the access request will immediately print a timeout log, which should reasonably stop at the line "_, err := c.Peek(1)".

**Hertz version:**

v0.2.1

**Additional context**

I looked at the Hertz source code and it clears the connection timeout setting when entering hijack mode, but call a wrong method：
File Location：hertz/pkg/protocol/http1/server.go
```
			// Hijacked conn process the timeout by itself
			err = ctx.GetConn().SetReadTimeout(0)
			if err != nil {
				return
			}
```
SetReadTimeout(0) should be replaced with SetReadDeadline(time.Time{}).

**Comment by li-jin-gou** [comment]
十分感谢，使用标准库设置超时的逻辑:
```
func (c *Conn) SetReadTimeout(t time.Duration) error {
	return c.c.SetReadDeadline(time.Now().Add(t))
}
```

这里改为就没有问题了
```
func (c *Conn) SetReadTimeout(t time.Duration) error {
	if t > 0 {
		return c.c.SetReadDeadline(time.Now().Add(t))
	}
	return nil
}
```

**Comment by zjclyz** [comment]
> 十分感谢，使用标准库设置超时的逻辑:
> 
> ```
> func (c *Conn) SetReadTimeout(t time.Duration) error {
> 	return c.c.SetReadDeadline(time.Now().Add(t))
> }
> ```
> 
> 这里改为应该就没有问题了
> 
> ```go
> func (c *Conn) SetReadTimeout(t time.Duration) error {
> 	if t <= 0 {
> 		return c.c.SetReadDeadline(time.Time{})
> 	}
> 	return c.c.SetReadDeadline(time.Now().Add(t))
> }
> ```

👍🏻
