### ISSUE TITLE
PostArgs() enctype="multipart/form-data" issue

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#180]
**Describe the bug**

related to https://github.com/cloudwego/hertz/issues/158 also

the issue with         \<form method=post enctype="multipart/form-data"\>
and        \<form method=post\>

if with multipart/form-data, 

       h.POST("/ttt", func(ctx context.Context, c *app.RequestContext) {
                fmt.Printf("EMPTY!!! = %s", c.PostArgs()) // <- PostArgs() will get no results with multipart/form-data!!!
        })

**Comment by rogerogers** [comment]
For multipart form
You could get value like this.
```go
form, err := c.MultipartForm()
//form.Value returns a map.
fmt.Println(form.Value["yourKey"])
```

**Comment by hiqsociety** [comment]
thx!
