### ISSUE TITLE
how do i access "g"? i can only get the first value from g

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#181]
```

                form, err := c.MultipartForm()
                if err != nil {

                        fmt.Printf("HELLO = %s\n",err)
                        return

                }
```

fmt.Printf("form  = %s\n",form)

```
      form  = &{map[c:[] city:[] country:[] d:[] f[]:[               ] g:[70010100 70011200 70011000] h:[] p:[] q:[] state:[] v:[]] map[]}

```
how do i access "g"? i can only get the first value from g
  g := c.PostForm("g")
  
  which is 70010100 and not the rest.
  
  anyone knows how to get the other values of g from "form"?

**Comment by rogerogers** [comment]
fmt.Println(form.Value["g"])

**Comment by hiqsociety** [comment]
> fmt.Println(form.Value["g"])

thank you! u r the best!
