### ISSUE TITLE
Request help: Support more extensions of service Registration and Discovery

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/hertz#197]
> We hope more developers join CloudWeGo. This is a task issue that needs your help.

###  Issue Description
Support more extensions of service Registration and Discovery. You can choose [ZooKeeper](https://zookeeper.apache.org/), [Consul](https://www.consul.io/), [etcd](https://etcd.io/)...

### Code Repository
Please create a new sub-module  in https://github.com/hertz-contrib/registry, the sub-module  name is suggested xxx, eg zookeeper.

### Extension API
- https://www.cloudwego.io/zh/docs/hertz/tutorials/service-governance/service_discovery/
- https://www.cloudwego.io/zh/docs/hertz/tutorials/framework-exten/service_discovery/

### picked

- [x] zookeeper: Done By @zstone12 
- [x] consul: Doing By @LemonFish873310466
- [x] nacos: Doing By @Skyenought
- [x] etcd Doing By @qiuyuyin
- [x] polaris Doing By @rogerogers
- [x] eureka Doing By @haswf
- [x] servicecomb by @a631807682

**Comment by zstone12** [comment]
Please assign ZooKeeper to me.

**Comment by LemonFish873310466** [comment]
Please assign Consul to me. thx❤️

**Comment by Skyenought** [comment]
Maybe I can try nacos if you have the patience?

**Comment by li-jin-gou** [comment]
> Please assign ZooKeeper to me.

thanks :heartbeat:

**Comment by li-jin-gou** [comment]
> Please assign Consul to me. thx❤️

thanks :heartbeat:

**Comment by li-jin-gou** [comment]
> Maybe I can try nacos if you have the patience?

thanks :heartbeat:

**Comment by rogerogers** [comment]
polaris

**Comment by li-jin-gou** [comment]
> polaris

thanks 💓

**Comment by qiuyuyin** [comment]
etcd

**Comment by li-jin-gou** [comment]
> etcd

Thanks💓, you may join our Feishu Chat Group to discuss more details about this task and welcome to contact me @qiuyuyin

**Comment by Haswf** [comment]
I would like to work on bringing eureka integration to Hertz

**Comment by li-jin-gou** [comment]
> I would like to work on bringing eureka integration to Hertz

thanks 💓@Haswf

**Comment by a631807682** [comment]
servicecomb

**Comment by li-jin-gou** [comment]
> servicecomb

thanks 💓 @a631807682
