### ISSUE TITLE
[docs]: translate hertz tutorials/tutorials/framework-exten/service_discovery/

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/hertz#200]
monitoring:
zh web page：https://www.cloudwego.io/zh/docs/hertz/tutorials/framework-exten/service_discovery/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/framework-exten/service_discovery.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials

Notes:

Do not change the original layout, code style or content sequence.
Software Translator is a tool, not god, do not use the result as the final result.
Translation principle: faithfulness, expressiveness and elegance.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by rogerogers** [comment]
Assign me.

**Comment by li-jin-gou** [comment]
> Assign me.

thanks @rogerogers
