### ISSUE TITLE
http3 integration. http2 is outdated. just go with http3

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#206]
https://github.com/cloudwego/hertz/issues/165

maybe integrate with this
https://pkg.go.dev/github.com/lucas-clemente/quic-go/http3

**Comment by li-jin-gou** [comment]
Hello @hiqsociety feel free to contact us and join the lark group, describing a specific requirement scenario:heart:

**Comment by rafimuhammad01** [comment]
hi @li-jin-gou I am interested to working on this issue, can you help me where to start?

**Comment by li-jin-gou** [comment]
@rafimuhammad01  Hello, this feature is already in preparation, welcome to code review together when the time comes

**Comment by Duslia** [comment]
@hiqsociety The HTTP2 PR has been created and http3 is on the way. Welcome to review and try out HTTP2. 
PR: https://github.com/cloudwego/hertz/pull/283 
Usage: https://github.com/Duslia/hertz/tree/feat/h2/examples

**Comment by hiqsociety** [comment]
ok. will do so! thx! keep it up.

**Comment by ultperf** [comment]
@Duslia pls provide the instructions for both http2 server and reverse proxy http2 client. thx

**Comment by li-jin-gou** [comment]
same to https://github.com/cloudwego/hertz/issues/458
