### ISSUE TITLE
Proposal: Go 1.19 support

### ISSUE THREAD

**Issue by rogerogers** [cloudwego/hertz#212]
**Is your feature request related to a problem? Please describe.**

The current version of Sonic (1.3.0) does not support golang 1.19, causes panic when running project with go version 1.19.

**Describe the solution you'd like**

Support for the 1.19 version has been released, upgrade sonic to version 1.4.0.

**Describe alternatives you've considered**

**Additional context**

**Comment by li-jin-gou** [comment]
refer to https://github.com/cloudwego/hertz/pull/191
