### ISSUE TITLE
@latest found (v0.2.1), but does not contain package github.com/cloudwego/hertz/pkg/consts

### ISSUE THREAD

**Issue by yangboz** [cloudwego/hertz#213]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hertz version:**

Please provide the version of Hertz you are using.

**Environment:**

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/apple/Library/Caches/go-build"
GOENV="/Users/apple/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/apple/go/pkg/mod"
GONOPROXY=".gitlab.com,.gitee.com"
GONOSUMDB=".gitlab.com,.gitee.com"
GOOS="darwin"
GOPATH="/Users/apple/go"
GOPRIVATE=".gitlab.com,.gitee.com"
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/Cellar/go/1.15.7_1/libexec"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.7_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/apple/go/src/github.com/cloudwego/hertz_demo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/62/hrfn26914bxd9sq0k79xkjjh0000gn/T/go-build665278446=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Additional context**
hertz_demo chapter  of 
[https://www.cloudwego.io/docs/hertz/getting-started/]
(https://www.cloudwego.io/docs/hertz/getting-started/)

**Comment by li-jin-gou** [comment]
可以提供一下具体代码的示例嘛,下面这个是文档中的demo,其中常量是在 `github.com/cloudwego/hertz/pkg/protocol/consts`中了，而不是 `github.com/cloudwego/hertz/pkg/consts`
```go
package main

import (
    "context"

    "github.com/cloudwego/hertz/pkg/app"
    "github.com/cloudwego/hertz/pkg/app/server"
    "github.com/cloudwego/hertz/pkg/common/utils"
    "github.com/cloudwego/hertz/pkg/protocol/consts"
)

func main() {
    h := server.Default()

    h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
            ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
    })

    h.Spin()
}
```

**Comment by yangboz** [comment]
> @yangboz 可以提供一下具体代码的示例嘛,下面这个是文档中的demo,其中常量是在 `github.com/cloudwego/hertz/pkg/protocol/consts`中了，而不是 `github.com/cloudwego/hertz/pkg/consts`
> 
> ```go
> package main
> 
> import (
>     "context"
> 
>     "github.com/cloudwego/hertz/pkg/app"
>     "github.com/cloudwego/hertz/pkg/app/server"
>     "github.com/cloudwego/hertz/pkg/common/utils"
>     "github.com/cloudwego/hertz/pkg/protocol/consts"
> )
> 
> func main() {
>     h := server.Default()
> 
>     h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
>             ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
>     })
> 
>     h.Spin()
> }
> ```

就是当前文档所用的参考代码

**Comment by li-jin-gou** [comment]
详细报错信息粘贴一下 @yangboz 我本地是OK的

**Comment by yangboz** [comment]
确认文档已修正 https://www.cloudwego.io/docs/hertz/getting-started/
