### ISSUE TITLE
Can hertz support all of the logs about one context can be print in one line

### ISSUE THREAD

**Issue by codeoos** [cloudwego/hertz#221]
**Is your feature request related to a problem? Please describe.**

I find that all of the functions about CtxXXXf(for example: CtxNoticef)have a param "ctx",but the param "ctx" aren't be used...So i can't print all logs about one ctx in one line.

**Describe the solution you'd like**

We can add an LogCtx in ctx,In LogCtx,It have some log fields,when this ctx's life is end,all of the fields will be printed.

**Comment by li-jin-gou** [comment]
可以支持自定义logger https://www.cloudwego.io/zh/docs/hertz/tutorials/framework-exten/log/
一个比较好的自定义实现可以参考，https://github.com/hertz-contrib/obs-opentelemetry/tree/main/logging/logrus

**Comment by codeoos** [comment]
OK,我的英语很中式吗，一眼国人？🤣

**Comment by codeoos** [comment]
英文发了issue，被中文回复，比较惊讶&好奇hhh

**Comment by PureWhiteWu** [comment]
@codeoos 
![image](https://user-images.githubusercontent.com/3314335/187422363-00ff9cd9-2310-4aad-8c4e-04e19e7f6799.png)

**Comment by codeoos** [comment]
🤣
