### ISSUE TITLE
:zap: optimize: may HeaderScanner and HeaderValueScanner be pooled?

### ISSUE THREAD

**Issue by byene0923** [cloudwego/hertz#227]
**Is your feature request related to a problem? Please describe.**

is it possible to make  [HeaderScanner](https://github.com/cloudwego/hertz/blob/develop/pkg/protocol/http1/ext/headerscanner.go#L53)  and [HeaderValueScanner](https://github.com/cloudwego/hertz/blob/develop/pkg/protocol/http1/ext/headerscanner.go#L75) pooled ?

**Comment by Haswf** [comment]
I would like to work on this.

**Comment by byene0923** [comment]
I thought this may be done like [bodyStreamPool](https://github.com/cloudwego/hertz/blob/97bb37e14eec8fd29e7d23e0ce25fe4e01d76954/pkg/protocol/http1/ext/stream.go#L58)? 

by the way
you could also think how to  reset `HeaderScanner` and `HeaderValueScanner` , such as how to handle  `sync.Pool` and `[]byte`?

**Comment by li-jin-gou** [comment]
There is no gain, choose to close it.
