### ISSUE TITLE
[docs]: translate hertz tutorials/basic-feature/route/

### ISSUE THREAD

**Issue by Skyenought** [cloudwego/hertz#233]
### route:
- **zh web page**: https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/route/
- **zh docs**: https://github.com/cloudwego/cloudwego.github.io/edit/main/content/zh/docs/hertz/tutorials/basic-feature/route.md
- **en folder**: https://github.com/cloudwego/cloudwego.github.io/edit/main/content/en/docs/hertz/tutorials/basic-feature/

### Notes:

Do not change the original layout, code style or content sequence.
Software Translator is a tool, not god, do not use the result as the final result.
Translation principle: faithfulness, expressiveness and elegance.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by BinaryLorain** [comment]
Please assign it to me.

**Comment by Skyenought** [comment]
> Please assign it to me.

thx
