### ISSUE TITLE
:memo: [docs]: translate hertz tutorials/service-governance/open-telemetry/

### ISSUE THREAD

**Issue by Skyenought** [cloudwego/hertz#234]
### OpenTelemetry
- **zh web page**: https://www.cloudwego.io/zh/docs/hertz/tutorials/service-governance/open-telemetry/
- **zh docs**: https://github.com/cloudwego/cloudwego.github.io/edit/main/content/zh/docs/hertz/tutorials/service-governance/open-telemetry.md
- **en folder**: https://github.com/cloudwego/cloudwego.github.io/edit/main/content/zh/docs/hertz/tutorials/service-governance/

### Notes:
Do not change the original layout, code style or content sequence.
Software Translator is a tool, not god, do not use the result as the final result.
Translation principle: faithfulness, expressiveness and elegance.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by iyear** [comment]
I am willing to work for this :)

**Comment by li-jin-gou** [comment]
> I am willing to work for this :)

thanks
