### ISSUE TITLE
any reverse proxy example?

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#24]
any reverse proxy example? thx

**Comment by Duslia** [comment]
Thanks for feedback. This feature is on the way.

**Comment by hiqsociety** [comment]
it's a godsent! thx! u guys are the best!

**Comment by hiqsociety** [comment]
sry for asking but without reverse proxy actually is very incomplete. when will reverse proxy be done? this is very crucial as a golang http framework.

i saw forward proxy is complete already so just wondering if it's simple to convert?

**Comment by Duslia** [comment]
We would probably prefer the community developers to support this feature. I wonder if you'd be interested in supporting it. If you are interest in it, you can contact me in CloudWeGo Lark or WeChat group easily.

**Comment by Duslia** [comment]
This issue has been assigned to powerxu519

**Comment by powerxu519** [comment]
I hope to give it a try

**Comment by li-jin-gou** [comment]
@hiqsociety  refer to https://github.com/hertz-contrib/reverseproxy
