### ISSUE TITLE
:sparkles: support pprof extension

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/hertz#240]
**Is your feature request related to a problem? Please describe.**

- Elegantly support pprof

**Additional context**

refer to:
- https://github.com/gofiber/fiber/tree/master/middleware/pprof
- https://github.com/gin-contrib/pprof

**Comment by Haswf** [comment]
Please assign this to me. I would like to work on this.

**Comment by li-jin-gou** [comment]
> Please assign this to me. I would like to work on this.

thanks

**Comment by li-jin-gou** [comment]
@Haswf  There are unfinished issues, this issue will unassigned.

**Comment by wangbei98** [comment]
i want to try it

**Comment by li-jin-gou** [comment]
@wangbei98  thanks
