### ISSUE TITLE
:memo: [docs]: translate hertz tutorials/basic-feature/protocol/websocket/

### ISSUE THREAD

**Issue by baiyutang** [cloudwego/hertz#244]
## Websocket
**zh web page**：https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/protocol/websocket/
**zh doc**：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/basic-feature/protocol/websocket.md
**en folder**：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials/basic-feature/protocol

tips：
1. you can create new dir named `protocol`
2. [protocol.md](https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/protocol/): move `protocol.md`  into `protocol` and rename as `_index.md`; modify the section about websocket's description
3. websocket.md: add new page in `protocol`, translate [this page](https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/protocol/websocket/)

**Notes**:
Do not change the original layout, code style or content sequence.
Software Translator is a tool, not god, do not use the result as the final result.
Translation principle: faithfulness, expressiveness and elegance.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by L2ncE** [comment]
I want to try this
