### ISSUE TITLE
:sparkles: support sentry extension 

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/hertz#246]
**Is your feature request related to a problem? Please describe.**

- Elegantly support sentry

**Additional context**

Refer to :
- https://github.com/getsentry/sentry-go
- https://github.com/gofiber/contrib/tree/main/fibersentry

**Comment by gityh2021** [comment]
I want to finish this task.

**Comment by li-jin-gou** [comment]
@gityh2021  thanks
