### ISSUE TITLE
✨ Proposal: convert handler of `net/http` to  handler of `hertz`

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/hertz#252]
**Is your feature request related to a problem? Please describe.**

 add adaptor to convert handler of `net/http` to  function of `hertz`

-  Support for fast migration of `net/http` services to hertz

**Describe the solution you'd like**

- add handler adapter to convert handler function of `net/http` to  handler function of `hertz`

**Notice**

-  A lot of useful functionality provided by `hertz` is missing
- `net/http` -> `hertz` handler conversion has some overhead

**Comment by Skyenought** [comment]
https://github.com/cloudwego/hertz/pull/253

**Comment by Skyenought** [comment]
https://github.com/cloudwego/hertz/pull/253
