### ISSUE TITLE
optimize: add a option to controls whether debugPrintRoute executes

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/hertz#268]
**Is your feature request related to a problem? Please describe.**

-  When the server is running, it  will print a lot of logs of the routes and i wish I could control its printing

**Describe the solution you'd like**

- add a option

**Comment by L2ncE** [comment]
It seems that adding a new parameter to `addRoute` would require a lot of changes. Is it feasible to use syntactic sugar to transform into optional parameters.

**Comment by li-jin-gou** [comment]
> It seems that adding a new parameter to `addRoute` would require a lot of changes. Is it feasible to use syntactic sugar to transform into optional parameters.

add `With**` 's option

**Comment by L2ncE** [comment]
I want to do it

**Comment by li-jin-gou** [comment]
@L2ncE  Thanks, but there are unfinished doc  issues, so issue will unassigned.
