### ISSUE TITLE
Question: why `name` property  in `pkg/route/engine.Engine` is public ?

### ISSUE THREAD

**Issue by Skyenought** [cloudwego/hertz#270]
**Describe the solution you'd like**

zh: 在 [pkg/route/engine](https://github.com/cloudwego/hertz/blob/develop/pkg/route/engine.go#L115) 中，name 属性为公用。

从 [GetServiceName](https://github.com/cloudwego/hertz/blob/develop/pkg/route/engine.go#L453) 方法知, 在没有设置属性的时候，会返回 "hertz" 作为默认信息。

但实际上，我可以直接通过直接取值取到意料之外的值
```go
engine := New()
assert.Assert(t, string(engine.GetServerName()) != engine.Name)
```
所以我想问，这是因为有相关背景才将属性公有的吗？

**Comment by ackerr** [comment]
我理解这里name是public的，是为了方便你设置自定义ServerName吧，如果你没设置过就是默认的`hertz`

这是对应的测试用例
```
func Test_getServerName(t *testing.T) {
	engine := New()
	assert.DeepEqual(t, []byte("hertz"), engine.GetServerName())
	ss := New()
	ss.Name = "test_name"
	assert.DeepEqual(t, []byte("test_name"), ss.GetServerName())
}
```

**Comment by Skyenought** [comment]
> 我理解这里name是public的，是为了方便你设置自定义ServerName吧，如果你没设置过就是默认的`hertz`
> 
> 这是对应的测试用例
> 
> ```
> func Test_getServerName(t *testing.T) {
> 	engine := New()
> 	assert.DeepEqual(t, []byte("hertz"), engine.GetServerName())
> 	ss := New()
> 	ss.Name = "test_name"
> 	assert.DeepEqual(t, []byte("test_name"), ss.GetServerName())
> }
> ```

thx
