### ISSUE TITLE
hertz默认Json Marshall库sonic在不支持AVX的amd64服务器上初始化失败

### ISSUE THREAD

**Issue by adcs120lan** [cloudwego/hertz#277]
https://www.cloudwego.io/zh/docs/hertz/reference/json/
已使用自定义 JSON Marshall 库，但在不支持AVX的amd64服务器上，应用启动时会报以下错误：

panic: Unsupported CPU, maybe it's too old to run Sonic.

goroutine 1 [running]:
github.com/bytedance/sonic/internal/native.init.0()
/go/pkg/mod/github.com/bytedance/sonic@v1.3.1/internal/native/dispatch_amd64.go:144 +0x1fb

请问是否可以通过某项设置，来阻止sonic初始化报错，或者让sonic降级到标准库也行。

**Comment by li-jin-gou** [comment]
cc @AsterDY

**Comment by AsterDY** [comment]
upgrade sonic >= v1.4.0

**Comment by adcs120lan** [comment]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/9584373/192457355-128f0962-04a4-4031-b224-32a7fc092563.png">
<img width="963" alt="image" src="https://user-images.githubusercontent.com/9584373/192458814-8d5ce2a8-3489-4712-8062-b70cc8aca056.png">
经测试hertz自动引入的v1.4.0版sonic和升级的v1.5.0版sonic在启动后还是报错。

**Comment by adcs120lan** [comment]
hertz在使用自定义JSON Marshal库后，是否能不初始化sonic？

**Comment by AsterDY** [comment]
> hertz在使用自定义JSON Marshal库后，是否能不初始化sonic？

this only can be resolved from hertz @li-jin-gou

**Comment by AsterDY** [comment]
> <img alt="image" width="809" src="https://user-images.githubusercontent.com/9584373/192457355-128f0962-04a4-4031-b224-32a7fc092563.png">
> 
> <img alt="image" width="963" src="https://user-images.githubusercontent.com/9584373/192458814-8d5ce2a8-3489-4712-8062-b70cc8aca056.png">
> 
> 经测试hertz自动引入的v1.4.0版sonic和升级的v1.5.0版sonic在启动后还是报错。

给个full stack吧，看不出来你是咋引入的

**Comment by adcs120lan** [comment]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/9584373/192474232-878fd3fa-be22-4a65-a20b-4caa6a18c5b9.png">
<img width="780" alt="image" src="https://user-images.githubusercontent.com/9584373/192474374-750f16ed-4df9-4ace-acf5-62d935366187.png">
<img width="417" alt="image" src="https://user-images.githubusercontent.com/9584373/192474446-aedf37aa-0377-4ff6-9d1b-1a461d50d3ec.png">
sonic是hertz间接引入的，该项目已经使用自定义JSON Marshal库，但至少在render设置自定义Json时会初始化sonic。
项目启动的日志只有这么多，sonic报错后项目终止启动
@AsterDY

**Comment by welkeyever** [comment]
应该可以加个编译选项过滤掉这个问题 & 提供用户一个选择的空间；我试试

**Comment by AsterDY** [comment]
> <img alt="image" width="682" src="https://user-images.githubusercontent.com/9584373/192474232-878fd3fa-be22-4a65-a20b-4caa6a18c5b9.png">
> 
> <img alt="image" width="780" src="https://user-images.githubusercontent.com/9584373/192474374-750f16ed-4df9-4ace-acf5-62d935366187.png">
> 
> <img alt="image" width="417" src="https://user-images.githubusercontent.com/9584373/192474446-aedf37aa-0377-4ff6-9d1b-1a461d50d3ec.png">
> 
> sonic是hertz间接引入的，该项目已经使用自定义JSON Marshal库，但至少在render设置自定义Json时会初始化sonic。 项目启动的日志只有这么多，sonic报错后项目终止启动 @AsterDY

难道是你的cpu连SSE4都没有？main最新提交(https://github.com/bytedance/sonic/commit/56e81a633e4c41efba9b475296a63369a5a0437d)应该已经支持 SSE，麻烦再试试呢

**Comment by adcs120lan** [comment]
谢谢，服务已经能启动了，部分服务器的CPU支持的指令集较为古老

**Comment by armyhcz** [comment]
系统cpu版本: ubtuntu  4  Intel(R) Pentium(R) Gold G5400 CPU @ 3.70GHz
引入版本: github.com/cloudwego/hertz v0.3.2
还是有这个问题
