### ISSUE TITLE
Hope Hertz supports swagger middleware

### ISSUE THREAD

**Issue by bodhisatan** [cloudwego/hertz#28]
**Is your feature request related to a problem? Please describe.**

Recently I work on the [mall preject](https://github.com/cloudwego/kitex-examples/pull/28), I want to reconstruct the api layer to Hertz, but I need a swagger tool to generate api doc

**Describe the solution you'd like**

support Hertz swagger middleware

**Describe alternatives you've considered**

**Additional context**

**Comment by bodhisatan** [comment]
I finished one: https://github.com/bodhisatan/hertz-swagger, can it be merged into `hertz-contrib` after PR? @welkeyever

**Comment by Duslia** [comment]
It has been merged. Please refer to https://github.com/hertz-contrib/swagger
