### ISSUE TITLE
Supplementary documentation for json tag

### ISSUE THREAD

**Issue by welkeyever** [cloudwego/hertz#281]
Update user docs for this update: #278 at https://www.cloudwego.io/docs/hertz/reference/json/
- https://github.com/cloudwego/cloudwego.github.io/blob/main/content/en/docs/hertz/reference/json.md
- https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/reference/json.md

**Comment by Haswf** [comment]
I would like to work on this. However, I haven't had the chance to play with go build tag and constraint. It may take a while for me to learn it first.

**Comment by welkeyever** [comment]
Good job! Already assigned to you

> I would like to work on this. However, I haven't had the chance to play with go build tag and constraint. It may take a while for me to learn it first.

Looking forward to it~

**Comment by GuangmingLuo** [comment]
hi, any progress of this? @Haswf

**Comment by li-jin-gou** [comment]
> I want to take over this task

thanks

**Comment by li-jin-gou** [comment]
No response for too long and reset it.
