### ISSUE TITLE
hlog lacks examples and unit tests

### ISSUE THREAD

**Issue by L2ncE** [cloudwego/hertz#293]
**Is your feature request related to a problem? Please describe.**

I see a lack of samples and unit tests for the use of hlog

**Describe the solution you'd like**

add examples and unit tests

**Comment by li-jin-gou** [comment]
Thanks for reporting! Are you interested in submitting a pr to solve it?
It's OK if it is not so, I'll put it into TODOs.

**Comment by L2ncE** [comment]
> Thanks for reporting! Are you interested in submitting a pr to solve it? It's OK if it is not so, I'll put it into TODOs.

I'd like to try

**Comment by li-jin-gou** [comment]
@L2ncE  We should also improve the logging documentation to let users know that we support zap log.
- https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/log/

**Comment by L2ncE** [comment]
> @L2ncE We should also improve the logging documentation to let users know that we support zap log.
> 
> * https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/log/

got it
