### ISSUE TITLE
Proposal: add csrf middleware

### ISSUE THREAD

**Issue by L2ncE** [cloudwego/hertz#300]
**Is your feature request related to a problem? Please describe.**

Currently Hertz does not support csrf yet

**Describe the solution you'd like**

Add csrf middleware

**Comment by li-jin-gou** [comment]
Thanks for reporting! Are you interested in submitting a pr to fix it?
It's OK if it is not so, I'll put it into TODOs.

**Comment by L2ncE** [comment]
> 

I'd like to try it.
