### ISSUE TITLE
Proposal: add favicon middleware

### ISSUE THREAD

**Issue by justlorain** [cloudwego/hertz#301]
**Is your feature request related to a problem? Please describe.**

Add a favicon middleware to provide more options for users.

**Describe the solution you'd like**

Add favicon middleware.

**Comment by li-jin-gou** [comment]
Helolo @justlorain, I realize that this is not necessary because it is not complicated and the configuration of `FS` is easy to solve this problem.

**Comment by justlorain** [comment]
I got it, thx.
