### ISSUE TITLE
code unsafety under   pkg\protocol

### ISSUE THREAD

**Issue by bolt163** [cloudwego/hertz#302]
**Describe the bug**

there may be a unsafety rise  with  os.Open(path)    opertaion  in  AddFile  function at   line 176  of   multipart.go file  under  pkg/protocol  directory,

if  '../'   or '../../../', '../../../../../'    etc is in the path, which may trigger a  unauthorized access to the path, the proper operation need to defer the   unauthorized access

**Expected behavior**

 the proper operation need to defer the unauthorized access  with path contain '../'  releated path

**Screenshots**

**Hertz version:**

Please provide the version of Hertz you are using.

**Environment:**

The output of `go env`.

**Additional context**

**Comment by li-jin-gou** [comment]
Hello,can you provide more detailed information?

**Comment by welkeyever** [comment]
A demo is helpful if you may offer one🙏

**Comment by li-jin-gou** [comment]
close due to no response
