### ISSUE TITLE
Cannot switch the network library to netpoll

### ISSUE THREAD

**Issue by zj-kenzhou** [cloudwego/hertz#314]
**Describe the bug**
default network library is standard,
Cannot switch the network library to netpoll

**Screenshots**

**Hertz version:**

0.3.2

**Environment:**

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\zhouken\AppData\Local\go-build
set GOENV=C:\Users\zhouken\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\zhouken\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\zhouken\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\zhouken\go\src\hertz_demo\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\zhouken\AppData\Local\Temp\go-build3669130104=/tmp/go-build -gno-record-gcc-switches

**Comment by zj-kenzhou** [comment]
update comment

**Comment by welkeyever** [comment]
since the main.go is quite simple, you may paste it fully.

**Comment by zj-kenzhou** [comment]
![image](https://user-images.githubusercontent.com/37363187/196915479-a2f7b585-0462-4c6d-9449-ee0aa430155c.png)

**Comment by zj-kenzhou** [comment]
![image](https://user-images.githubusercontent.com/37363187/196915565-6f783152-9540-4941-8d9b-9f4e34fef198.png)

**Comment by zj-kenzhou** [comment]
thank you!
