### ISSUE TITLE
✨ support cache extension

### ISSUE THREAD

**Issue by BaiZe1998** [cloudwego/hertz#319]
## Is your feature request related to a problem? Please describe.

- Elegantly support cache

## Additional context

refer to:

- https://github.com/gin-contrib/cache
- https://github.com/gofiber/fiber/tree/master/middleware/cache

**Comment by BaiZe1998** [comment]
please assign me, :)

**Comment by li-jin-gou** [comment]
> please assign me, :)

thanks
