### ISSUE TITLE
no use for FsHandler

### ISSUE THREAD

**Issue by byene0923** [cloudwego/hertz#32]
route has the [statisFS](https://github.com/cloudwego/hertz/blob/9ced80f0fdfca80d478af48635921ff52fb30bd2/pkg/route/routergroup.go#L74) interface. and [FsHandler](https://github.com/cloudwego/hertz/blob/9ced80f0fdfca80d478af48635921ff52fb30bd2/pkg/app/fs.go#L1237) is not use any more, I think this can be deleted

**Comment by welkeyever** [comment]
Thanks for your report! 

`FsHandler` is indeed not used anymore. Would you like to submit a pr to fix it?

**Comment by byene0923** [comment]
sure

**Comment by Duslia** [comment]
It has been merged.
