### ISSUE TITLE
got status code warning BUT dunno where the status code is set in the program.

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#323]
```
2022/10/25 08:20:41.653075 header.go:459: [Warn] Invalid StatusCode code 0, status code should not be under 100 or over 599
```
ok so i got this code but now i dunno where to find where the code comes from. can pls have something to trace where the calling of header.go originates? thx

**Comment by li-jin-gou** [comment]
When we use `ctx.Json` or `ctx.Html`  to set an illegal http status code, if  http status code > 10000 or code < 100, it will print warning log.

such as:
```go
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		ctx.JSON(100000, utils.H{"ping": "pong"}) // will print warn log
	})
```
