### ISSUE TITLE
feat: chunk-extension support 

### ISSUE THREAD

**Issue by byene0923** [cloudwego/hertz#334]
**Is your feature request related to a problem? Please describe.**

will hertz support support chunk-extension? [chunk-extension rfc](https://www.rfc-editor.org/rfc/rfc9112#name-chunk-extensions)

**Additional context**

now hertz  [parseChunkSize](https://github.com/cloudwego/hertz/blob/develop/pkg/common/utils/chunk.go#L45) skip the whitespace and check the '\r',

**Comment by welkeyever** [comment]
@byene0923 Should we close this issue? Since the related PR has been closed.

Any update is welocome🙏
