### ISSUE TITLE
High CPU usage in idle and random CPU spikes

### ISSUE THREAD

**Issue by jnelle** [cloudwego/hertz#336]
**Describe the bug**

I moved yesterday my backend (written in fiber) to hertz. Afterwards I deployed it at Digitalocean on the [app platform](https://www.digitalocean.com/products/app-platform) as a Docker container. After the deployment I noticed a high CPU usage and random CPU spikes, which was obviously weird, because I haven't sent any request to the deployed service

**To Reproduce**

1. Go to [Digitalocean](https://www.digitalocean.com/)
2. Create an account
3. Create an app on the app platform
4. Deploy your hertz app
5. Check then the resource usage in insights tab

**Expected behavior**

You should see a an app platform instance which has a high CPU usage in idle and random CPU spikes.

**Screenshots**

![Screenshot 2022-10-29 130714](https://user-images.githubusercontent.com/36324542/198828004-6cd81c2f-5741-481f-b90d-0e4b36a310fb.png)

**Hertz version:**

0.4.0

**Environment:**

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1812955878=/tmp/go-build -gno-record-gcc-switches"

```
**Additional context**

Used third party dependencies:

```
	firebase.google.com/go v3.13.0+incompatible
	github.com/JeremyLoy/config v1.5.0
	github.com/hertz-contrib/cors v0.0.0-20220601061225-50f4e582beaf
	github.com/joho/godotenv v1.4.0
	github.com/mitchellh/mapstructure v1.5.0
	go.mongodb.org/mongo-driver v1.10.3
	google.golang.org/api v0.101.0

```

**Comment by li-jin-gou** [comment]
Thank you for trust and i think this phenomenon is strange and it happens randomly. If we could have pprof sampling of the cpu, I believe the problem would be very well investigated. but the normal pprof does not work so much that we can use [holmes](https://github.com/mosn/holmes) to do pprof of the cpu and It supports triggered acquisition.

**Comment by jnelle** [comment]
Hi, gonna do it this weekend!

**Comment by li-jin-gou** [comment]
> I got the same problem on the digital ocean app platform.

 we can use [holmes](https://github.com/mosn/holmes) to do pprof of the cpu and It supports triggered acquisition and analyse the causes in this way.

**Comment by Dorbmon** [comment]
> > I got the same problem on the digital ocean app platform.
> 
> we can use [holmes](https://github.com/mosn/holmes) to do pprof of the cpu and It supports triggered acquisition and analyse the causes in this way.

I failed to run holmes as it doesn't output any log file. However, I used go pprof. It sampled for 30 seconds. Here is the result:
`
-----------+-------------------------------------------------------
    25.18s   runtime/internal/syscall.Syscall6
             syscall.RawSyscall6
             syscall.RawSyscall
             github.com/cloudwego/netpoll.readv
             github.com/cloudwego/netpoll.(*defaultPoll).handler
             github.com/cloudwego/netpoll.(*defaultPoll).Wait
-----------+-------------------------------------------------------
     4.31s   runtime/internal/syscall.Syscall6
             syscall.RawSyscall6
             github.com/cloudwego/netpoll.EpollWait
             github.com/cloudwego/netpoll.(*defaultPoll).Wait
-----------+-------------------------------------------------------
     120ms   runtime.futex
             runtime.futexsleep
             runtime.notesleep
             runtime.mPark (inline)
             runtime.stopm
             runtime.findRunnable
             runtime.schedule
             runtime.park_m
             runtime.mcall
-----------+-------------------------------------------------------
     230ms   runtime.epollwait
             runtime.netpoll
             runtime.findRunnable
             runtime.schedule
             runtime.park_m
             runtime.mcall
-----------+-------------------------------------------------------
      20ms   runtime.futex
             runtime.futexsleep
             runtime.notesleep
             runtime.mPark (inline)
             runtime.stopm
             runtime.findRunnable
             runtime.schedule
             runtime.goexit0
             runtime.mcall

`
I don't think this causes the high cpu usage.

**Comment by Dorbmon** [comment]
This is my cpu usage curve.
![image](https://user-images.githubusercontent.com/17807931/210702725-27ad42af-50b1-4e01-8e8e-c77be06e06ca.png)
It keeps high.

**Comment by Dorbmon** [comment]
I think it is a bug of netpoll. As I switched to standard.NewTransporter, the cpu usage gets down.
