### ISSUE TITLE
Modify interface check way.

### ISSUE THREAD

**Issue by L2ncE** [cloudwego/hertz#346]
**Is your feature request related to a problem? Please describe.**

I see that the interface checking in Hertz is the following way.

eg:
```go
var _ registry.Registry = &MockRegistry{}
```

However, in general `&SomeType{}` will allocate and initialise a new value (unless the compiler detects and optimises it out) where-as `(*SomeType)(nil)` will never do any allocation. I think there's no need to initialise a new value to validate interfaces.

Interface checks: [go.dev/doc/effective_go#blank_implements](https://go.dev/doc/effective_go#blank_implements).

**Describe the solution you'd like**

Modify the interface checking method in Hertz to the following.

eg:
```go
var _ registry.Registry = (*MockRegistry)(nil)
```

**Comment by li-jin-gou** [comment]
I think it is OK and welcome PR.
