### ISSUE TITLE
请求错误

### ISSUE THREAD

**Issue by Nyx2022** [cloudwego/hertz#349]
**Describe the bug**

请求之后返回错误：
the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection

**To Reproduce**

某些网站会出现这种问题

**Comment by li-jin-gou** [comment]
There is not enough information to help us answer this question. I don't even know how the code is written and whether you are using a client or a server. 😩

**Comment by Duslia** [comment]
It's because the server closes the connection unexpectedly. You can check whether your request is a valid request.
