### ISSUE TITLE
http 框架不支持服务发现吗

### ISSUE THREAD

**Issue by JellyTony** [cloudwego/hertz#35]
自身没有注册服务发现，不能网关通过服务发现代理该服务或者通过服务发现调用该服务

**Comment by welkeyever** [comment]
hertz 的 server 和 client都支持中间件，这部分需求可以直接通过中间件的方式按需扩展（同时也是内部实现的方式）；这部分通用的能力暂时还在梳理当中，着急的话可以按照上述思路搞一版，有任何问题都欢迎在这个issue下讨论~
