### ISSUE TITLE
HostClient.Do Content-Type defaults to application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by kyoukaya** [cloudwego/hertz#359]
**Describe the bug**

In the absence of a specified Content-Type, the Content-Type as sent by `HostClient.Do` defaults to `application/x-www-form-urlencoded` in [RequestHeader.AppendBytes](https://github.com/cloudwego/hertz/blob/8864a2a92b338be9ed9405aab0099293390b8cbf/pkg/protocol/header.go#L372:L374):
```go
	if len(contentType) == 0 && !h.IgnoreBody() {
		contentType = bytestr.StrPostArgsContentType
	}
```

**To Reproduce**

```go
package protocol_test

import (
	"fmt"
	"net/http"
	"testing"

	"github.com/cloudwego/hertz/pkg/protocol"
)

func TestIssue(t *testing.T) {
	var h protocol.RequestHeader
	var buf []byte
	h.SetMethod(http.MethodPost)
	buf = h.AppendBytes(buf)
	fmt.Println(string(buf))
	// POST / HTTP/1.1
	// Content-Type: application/x-www-form-urlencoded
}
```

**Expected behavior**

The expected behaviour would be to **not** send the Content-Type header if it is unknown by the sender, as specified in [RFC9110](https://www.rfc-editor.org/rfc/rfc9110#section-8.3-5).
> A sender that generates a message containing content SHOULD generate a Content-Type header field in that message unless the intended media type of the enclosed representation is unknown to the sender. If a Content-Type header field is not present, the recipient MAY either assume a media type of "application/octet-stream" ([[RFC2046](https://www.rfc-editor.org/rfc/rfc9110#RFC2046)], [Section 4.5.1](https://www.rfc-editor.org/rfc/rfc2046#section-4.5.1)) or examine the data to determine its type.

**Hertz version:**

v0.4.0

**Comment by li-jin-gou** [comment]
I've also seen this rfc, but it doesn't explicitly say not to set the content-type.

**Comment by kyoukaya** [comment]
If the intention is to offer curl-like capabilities, can there be an option to omit it similarly then?
```bash
$ curl -XPOST http://httpbin.org/post -H 'Content-Type: ' -d '{}'
{
  "args": {},
  "data": "{}",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Content-Length": "2",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.84.0",
    "X-Amzn-Trace-Id": "Root=1-636c98b5-40e8878f12b29af35a95d2d8"
  },
  "json": {},
  "origin": "119.75.39.242",
  "url": "http://httpbin.org/post"
}
```

**Comment by li-jin-gou** [comment]
> If the intention is to offer curl-like capabilities, can there be an option to omit it similarly then?
> 
> ```shell
> $ curl -XPOST http://httpbin.org/post -H 'Content-Type: ' -d '{}'
> {
>   "args": {},
>   "data": "{}",
>   "files": {},
>   "form": {},
>   "headers": {
>     "Accept": "*/*",
>     "Content-Length": "2",
>     "Host": "httpbin.org",
>     "User-Agent": "curl/7.84.0",
>     "X-Amzn-Trace-Id": "Root=1-636c98b5-40e8878f12b29af35a95d2d8"
>   },
>   "json": {},
>   "origin": "119.75.39.242",
>   "url": "http://httpbin.org/post"
> }
> ```

This is just an example I gave because I don't think this is a bug.

**Comment by kyoukaya** [comment]
> 

Agreed, I will reopen this as a feature request then.
