### ISSUE TITLE
Request help: Improve documentation of `writeTimeout`

### ISSUE THREAD

**Issue by Duslia** [cloudwego/hertz#377]
> We hope more developers join CloudWeGo. This is a task issue that needs your help.

In https://github.com/cloudwego/hertz/pull/344, we support writeTimeout in client and server. It not only support client and server level configuration but also support request level configuration. Could you please help me improve the doc?

cloudwego link: https://www.cloudwego.io/zh/docs/hertz/reference/config/
en: https://github.com/cloudwego/cloudwego.github.io/blob/main/content/en/docs/hertz/reference/config.md
zh: https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/reference/config.md

You can first complete the Chinese doc and create PR to review. And then translate to English

**Comment by li-jin-gou** [comment]
thanks @wang-tsh
