### ISSUE TITLE
[问题] 请教下如何给分组路由添加 CORS

### ISSUE THREAD

**Issue by biuaxia** [cloudwego/hertz#379]
如题，我想给不同的分组添加 CORS 策略。

比如：

```
v1 := h.Group("/v1")
{
  // loginEndpoint is a handler func
  v1.POST("/login", loginEndpoint)
  v1.POST("/submit", submitEndpoint)
  v1.POST("/streaming_read", readEndpoint)
}

// Simple group: v2
v2 := h.Group("/v2")
{
  v2.POST("/login", loginEndpoint)
  v2.POST("/submit", submitEndpoint)
  v2.POST("/streaming_read", readEndpoint)
}
```

我想要将 v2 所有的路由进行 CORS 放行。

我尝试过：

```
// Simple group: v2
v2 := h.Group("/v2", cors.Default())
{
	v2.POST("/login", loginEndpoint)
	v2.POST("/submit", submitEndpoint)
	v2.POST("/streaming_read", readEndpoint)
}
```

通过 postman 查看响应头，并没有预期的 header。

![image](https://user-images.githubusercontent.com/46131142/202367836-d5a8f83a-e29c-4675-b3c1-585f1e985938.png)

**Comment by li-jin-gou** [comment]
refer to  https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/middleware/cors/ && PATL @BaiZe1998

**Comment by li-jin-gou** [comment]
Please make sure your request is a  `CORS request` cc @biuaxia
