### ISSUE TITLE
sry to ask here, regarding shmipc

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#385]
i cant seem to find shmipc as mentioned on open source not on cloudwego or bytedance github repo.
https://www.cloudwego.io/blog/2021/09/13/cloudwego-open-source-announcement/

possible to show where the repo is? thx in advance.

**Comment by hiqsociety** [comment]
ok thx. shld i leave it open until shmIPC is out? :)

**Comment by li-jin-gou** [comment]
> ok thx. shld i leave this issue open until shmIPC is out? :)

I think so.

**Comment by bengol** [comment]
does the design & develop of shmIPC is in plan ?

**Comment by welkeyever** [comment]
shmIPC is implemented under the design of network abstract interface, which is used to communicate with service mesh proxy in Bytedance(not yet open source).
Maybe you can tell us your usage scenario about shmIPC? This part of the input is relatively small.

**Comment by hiqsociety** [comment]
shmIPC for better inter process transfer speed that's all.

**Comment by ultperf** [comment]
@welkeyever how to know when shmipc is opensourced or when will it be opensourced?

sorry just curious

**Comment by kolinfluence** [comment]
@li-jin-gou is shmipc open sourced already? where is the location?

**Comment by GuangmingLuo** [comment]
Just opened to the public. Welcome to take a try and submit your feedbacks. @hiqsociety @kolinfluence 
1. https://github.com/cloudwego/shmipc-spec
2. https://github.com/cloudwego/shmipc-go
