### ISSUE TITLE
feat:support brotli/br

### ISSUE THREAD

**Issue by byene0923** [cloudwego/hertz#39]
**Is your feature request related to a problem? Please describe.**

hertz only support gzip in [fs.go](https://github.com/cloudwego/hertz/blob/develop/pkg/app/fs.go#L273). may support brotli/br?

**Describe the solution you'd like**

I think hertz  can support it like https://github.com/valyala/fasthttp/pull/880

**Describe alternatives you've considered**
 
**Additional context**

**Comment by Duslia** [comment]
I 'd like to know why you want Hertz to support brotli/br? Or could you pls tell me why gzip cannot satisfy your requirements so that we support it with a high priority.

**Comment by li-jin-gou** [comment]
it haven't responded or made progress for a long time, so I choose to close it. When there is a real demand, I will restart it.
