### ISSUE TITLE
fasthttp's		ctx.Request.Header.VisitAllCookie(func(k, v []byte) {} and VisitAllHeader

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#395]
fasthttp's		ctx.Request.Header.VisitAllCookie(func(k, v []byte) {} and VisitAllHeader

possible to include into hertz? i'm missing these features for a complete migration / transition from fasthttp to hertz. thx.

**Comment by Duslia** [comment]
There are these two functions in Hertz: `ctx.Request.Header.VisitAllCookie(), ctx.Request.Header.VisitAll()`
Please read the doc or try by yourself

**Comment by li-jin-gou** [comment]
I've been working on the detailed documentation recently but it's so much that I've been slow in getting it done, so I'll let you know if it's finished.

**Comment by ultperf** [comment]
@Duslia can u point me to the documentation? i dunno why i cant find it. i think i checked in "app" not sure where the functions u meant are. i will download the whole repo and do search within but pls mention which doc i need to reference. thx

**Comment by Duslia** [comment]
@ultperf  
```

package main

import (
	"context"
	
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

func main() {
	h := server.Default()
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		ctx.Request.Header.VisitAllCookie()
		ctx.Request.Header.VisitAll()
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})

	h.Spin()
}

```

**Comment by Duslia** [comment]
@ultperf Here is all the API: https://pkg.go.dev/github.com/cloudwego/hertz. You can refer to this doc

**Comment by Duslia** [comment]
https://pkg.go.dev/github.com/cloudwego/hertz@v0.4.1/pkg/protocol#RequestHeader
