### ISSUE TITLE
a few questions, coming from fasthttp

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#397]
works on fasthttp but not working on hertz
1. cannot use ctx.ClientIP() (value of type string) as type net.IP in argument to

2. cannot use ctx.ClientIP() (value of type string) as type net.IP in argument to

how to resolve or convert or use equivalent?

**Comment by Duslia** [comment]
net.ParseIP(ctx.ClientIP())

**Comment by ultperf** [comment]
ok thx
