### ISSUE TITLE
need help testing http2 but "stuck" at reverse proxy handling

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#398]
by the way, so far http2 seems ok. i'm trying to test more use case now for reverse proxy.
sorry i'm too new with hertz and too used to fasthttp so mind is stuck at fasthttp understanding

same question asked in https://github.com/hertz-contrib/reverseproxy/issues/9
this repo 
https://github.com/Duslia/hertz
does not have "issue" section option on the github repo to ask, so asking here

this is how fasthttp is done
```
    if err := proxyClientX.Do(&ctx.Request, &ctx.Response); err != nil {
      log.Printf("WebAxx err=%s\n", err)
      ctx.Response.Header.SetStatusCode(503)
      ctx.Response.Header.SetContentType("text/html")
      ctx.Response.SetBody([]byte("err"))
    }

```
**how to do the same for below. Also, how to update for hertz http2 instead of the net standard?**
```
	rp, _ := reverseproxy.NewSingleHostReverseProxy("https://localhost:8082/test",client.WithDialer(standard.NewDialer()))
	h.GET("/ping", rp.ServeHTTP) // <- should be here right?
```

**Comment by Duslia** [comment]
The essence of a reverseProxy is client and reverseProxy provide a api to setClient. You can init a  HTTP2 Client and set it to reverseProxy.

**Comment by li-jin-gou** [comment]
refer to https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/proxy/#reverse-proxy

**Comment by li-jin-gou** [comment]
It looks like we need to add the H2 documentation to the official documentation as well. cc @Duslia

**Comment by ultperf** [comment]
@Duslia it all seemed and sounded very easy to you without example written. 
i seem to get what u mean but actually i not too sure how to provide a http2 client and set it to reverseproxy that is. :I maybe there shld be a default method for this i guess.
 
possible to provide a quick example or some guidance?

**Comment by li-jin-gou** [comment]
refer to https://github.com/cloudwego/hertz-examples/blob/main/reverseproxy/discovery/discovery/main.go#L41

refer to https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/proxy/#reverse-proxy

**Comment by li-jin-gou** [comment]
First you need to know how to initialise a Hertz Client, and ReverseProxy provides SetClient .

**Comment by Duslia** [comment]
Please refer line 37 - 40 to init a HTTP2 client: https://github.com/hertz-contrib/http2/blob/030e2b6768b99393d9b22c78f58824cdf9e85286/examples/h2/main.go#L37

<img width="700" alt="image" src="https://user-images.githubusercontent.com/37136584/202888744-00ebb693-bae7-4efa-8a7e-ae7b515109c6.png">

**Comment by li-jin-gou** [comment]
Please refer line 37 - 40 to init a HTTP2 client: https://github.com/hertz-contrib/http2/blob/030e2b6768b99393d9b22c78f58824cdf9e85286/examples/h2/main.go#L37
```
h2client, _ := client.NewClient()
	c.SetClientFactory(factory.NewClientFactory(
		config.WithDialer(standard.NewDialer()),
		config.WithTLSConfig(&tls.Config{InsecureSkipVerify: true})))

proxy, err := reverseproxy.NewSingleHostReverseProxy("http://127.0.0.1:8000/proxy")
    if err != nil {
        panic(err)
    }

proxy.SetClient(h2client)
```
