### ISSUE TITLE
stuck at "Cookie" at conversion from hertz to fasthttp and vice versa.

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#399]
1st try temp conversion of hertz to fasthttp req and vice versa for resp.

stuck at "Cookie"

possible to suggest what else i'm missing?

```
func ProxyHandlerTemp(c context.Context, ctx *app.RequestContext) {

	var ctxTemp fasthttp.RequestCtx

	ctx.Request.Header.VisitAllCookie(func(k, v []byte) {
		ctxTemp.Request.Header.SetCookieBytesKV(k, v)
	})

	ctxTemp.Request.Header.SetMethodBytes(ctx.Request.Header.Method())
	ctxTemp.Request.SetHostBytes(ctx.Host())
	ctxTemp.Request.SetRequestURIBytes(ctx.Request.RequestURI())
	ctxTemp.Request.Header.SetUserAgentBytes(ctx.UserAgent())
	ctxTemp.Request.SetBodyRaw(ctx.Request.Body())

	ProxyHandler(&ctxTemp)

	ctxTemp.Response.Header.VisitAllCookie(func(k, v []byte) {
		ctx.Response.Header.SetCookie(string(k), string(v))
	})
	ctx.Response.SetBodyRaw(ctxTemp.Response.Body())
	ctx.Response.SetStatusCode(ctxTemp.Response.StatusCode())
}
```
sorry but a bit new to this... how do i set returned cookies from fasthttp to "Cookie"?

```
too many arguments in call to ctx.Response.Header.SetCookie
        have (string, string)
        want (*protocol.Cookie)
```

**Comment by li-jin-gou** [comment]
Hello @ultperf  Why not just copy the response header? 
refer to https://github.com/cloudwego/hertz/blob/develop/pkg/app/context.go#L1000,It appears to be very well annotated.

**Comment by ultperf** [comment]
can u pls help just provide the code for fasthttp getcookie to setcookie for hertz?
coz i dont really know how to port or migrate to that.
i've seen the link u sent but i seem to need to extract so many things from fasthttp?

**Comment by li-jin-gou** [comment]
Set the header directly

**Comment by ultperf** [comment]
@li-jin-gou i normally dont do that so i dunno how to set the header directly. i always thought u need to do a VisitAllCookies() kind of thing.

can u provide the example for fasthttp to getcookie header to hertz?

if i have to guess.

ctx.Header.Set("Cookie", ctxFasthttpTemp.Header.Peek("Cookie")) <- like this?

**Comment by li-jin-gou** [comment]
use https://github.com/cloudwego/hertz/blob/develop/pkg/protocol/cookie.go#L350 💕

**Comment by li-jin-gou** [comment]
My opinion is to use hertz directly. refer to https://github.com/cloudwego/hertz/issues/386#issuecomment-1320763519

**Comment by ultperf** [comment]
last bit of help pls.

it's not easy to convert everything to hertz immediately. i am testing and trying out http2 for now.
how do i set the cookie from ctxTemp (fasthttp) response to ctx (hertz)?
pls help out this. shld be the last part. sorry i not very well verse with this cookie part.
```
	//ctx.Response.SetCookie(cookie * Cookie)
	cookie := ctxTemp.Response.Header.Peek(fasthttp.HeaderCookie)
	ctx.Response.Header.SetCookie(cookie)
	//ctxTemp.Response.Header.VisitAllCookie(func(k, v []byte) {
	//	ctx.Response.Header.Set(string(k), string(v))
	//})
```

**Comment by ultperf** [comment]
i want to use hertz directly but there is too many things to be converted at the moment. i wish to try out the http2 first. so far all things are ok except the reverse proxy part and cookie.

so pls help out this first and i think the rest i can slowly transition.

**Comment by ultperf** [comment]
possible to provide a conversion solution pls? this is not working. why?
```
	cookie := ctxTemp.Response.Header.Peek(fasthttp.HeaderCookie)

	cookieNew := protocol.AcquireCookie()
	cookieNew.Parse(string(cookie))
	ctx.Response.Header.SetCookie(cookieNew)
```

**Comment by justlorain** [comment]
> possible to provide a conversion solution pls? this is not working. why?
> 
> ```
> 	cookie := ctxTemp.Response.Header.Peek(fasthttp.HeaderCookie)
> 
> 	cookieNew := protocol.AcquireCookie()
> 	cookieNew.Parse(string(cookie))
> 	ctx.Response.Header.SetCookie(cookieNew)
> ```

try this, maybe will work

```go
cookieNew := protocol.AcquireCookie()
cookieNew.Parse(string(cookie))
ctx.Response.Header.SetCookie(cookieNew)
// pls add this
protocol.ReleaseCookie(cookieNew)
```

**Comment by ultperf** [comment]
@justlorain it's not working

**Comment by justlorain** [comment]
> @justlorain it's not working, what is wrong? what is missing i wonder. it ran ok but seems cookie not working that's all. coz cannot login.
> 
> ```
> func ProxyHandlerTemp(c context.Context, ctx *app.RequestContext) {
> 
> 	var ctxTemp fasthttp.RequestCtx
> 
> 	ctx.Request.Header.VisitAllCookie(func(k, v []byte) {
> 		ctxTemp.Request.Header.SetCookieBytesKV(k, v)
> 	})
> 
> 	ctx.Request.Header.VisitAll(func(k, v []byte) {
> 		ctxTemp.Request.Header.SetBytesKV(k, v)
> 	})
> 
> 	ctxTemp.Request.Header.Set("X-Real-IP", ctx.ClientIP())
> 	ctxTemp.Request.SetHostBytes(ctx.Host())
> 	ctxTemp.Request.SetRequestURIBytes(ctx.Request.RequestURI())
> 	ctxTemp.Request.SetBodyRaw(ctx.Request.Body())
> 	FirewallProxyHandler(&ctxTemp)
> 
> 	ctx.Response.SetBodyRaw(ctxTemp.Response.Body())
> 	ctx.Response.SetStatusCode(ctxTemp.Response.StatusCode())
> 
> 
> 	cookie := ctxTemp.Response.Header.Peek(fasthttp.HeaderCookie)
> 
> 	cookieNew := protocol.AcquireCookie()
> 	cookieNew.Parse(string(cookie))
> 	ctx.Response.Header.SetCookie(cookieNew)
> 	// pls add this
> 	protocol.ReleaseCookie(cookieNew)
> 
> 	ctxTemp.Response.Header.VisitAll(func(k, v []byte) {
> 		ctx.Response.Header.Set(string(k), string(v))
> 	})
> }
> ```

This will only set an empty cookie, I think you need to use these [Set functions](https://github.com/cloudwego/hertz/blob/develop/pkg/protocol/cookie.go#L161) to set your cookie manually, here is a [example](https://github.com/cloudwego/hertz-examples/blob/main/parameter/cookie/main.go), hope this will help you.

**Comment by justlorain** [comment]
@ultperf Sorry, it seems that I misunderstand this code. The `Parse` should be called in the `VisitAllCookie` like following:
```go
ctx.Response.Header.VisitAllCookie(func(key, value []byte) {
    p := ctxTemp.Response.Header.Peek(fasthttp.HeaderCookie)
    cookie := protocol.AcquireCookie()
    cookie.ParseBytes(p)
    ctx.Response.Header.SetCookie(cookie)
    protocol.ReleaseCookie(cookieNew)
})
```

**Comment by ultperf** [comment]
> erm... but there's no "key" in your setcookie etc... doesnt seem right.

**Comment by ultperf** [comment]
@li-jin-gou can u see that his FastHttpctx is the one using the visitallcookie but hertzctx does not touch "key" anywhere?

**Comment by li-jin-gou** [comment]
value contains key
