### ISSUE TITLE
[QUESTION] - Static function not working properly

### ISSUE THREAD

**Issue by sujit-baniya** [cloudwego/hertz#400]
I'm trying to serve css/js and other assets using `Static(relativePath, root string)` in html file but it doesn't seem to work properly.

I've this code
```go
package main

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/utils"
)

func main() {
	h := server.Default(server.WithHostPorts("127.0.0.1:8080"))
	h.LoadHTMLGlob("./resources/views/layouts/*")

	h.Static("/file", "./public")

	h.GET("/html", func(c context.Context, ctx *app.RequestContext) {
		ctx.HTML(200, "master.html", utils.H{})
	})
	h.Spin()
}
```

In example directory I've this setup
![image](https://user-images.githubusercontent.com/4959215/202901700-a247ca4f-54ac-4f86-bc4a-12b7efbf8727.png)

Since I used prefix `/file`, I tried to use `<link rel="stylesheet" href="/file/css/style.css">` in master.html as in

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/file/css/style.css">
    <title>{{.title}}</title>
</head>
<body>
Master Layout
</body>
</html>
```

But the css is not loading resulting 404 on browser and following error terminal

```go
2022/11/20 18:05:52.503943 fs.go:858: [Error] HERTZ: Cannot open file="./public/file", error=open ./public/file: no such file or directory
2022/11/20 18:05:59.110850 fs.go:858: [Error] HERTZ: Cannot open file="./public/file/css/style.css", error=open ./public/file/css/style.css: no such file or directory
```
![image](https://user-images.githubusercontent.com/4959215/202901780-9009cd05-f5a8-499b-bb36-48e10e44cd60.png)

Please suggest if I'm doing anything wrong

**Comment by L2ncE** [comment]
You can refer to https://github.com/cloudwego/hertz-examples/tree/main/file/staticFile

**Comment by L2ncE** [comment]
You did not create the `file` folder 
```
Cannot open file="./public/file/css/style.css"
```

**Comment by sujit-baniya** [comment]
@L2ncE I tried to use "/file" as alias for "./public" folder. So, I tried using `h.Static("/file", "./public")`.

Please suggest how can I access the files in such case. I used the example from above link

**Comment by L2ncE** [comment]
> @L2ncE I tried to use "/file" as alias for "./public" folder. So, I tried using `h.Static("/file", "./public")`.
> 
> Please suggest how can I access the files in such case. I used the example from above link

Seeing your error I think you just need this.

![image](https://user-images.githubusercontent.com/92938836/202908141-f87d39f0-d76f-4eac-bb09-7598c287e3c9.png)

Or do you just hope that he can get it through `./public/css/style.css`

**Comment by sujit-baniya** [comment]
@L2ncE Check this video please: https://www.loom.com/share/157df15ebdb0430abb677d2c44da8391

Here, I used the code from the example but still it's not working.

**Comment by sujit-baniya** [comment]
Also I'm little bit confused on use of `relativePath` in

```go
func (group *RouterGroup) Static(relativePath, root string) IRoutes {
	return group.StaticFS(relativePath, &frame.FS{Root: root})
}
```
If I use

```go
h.Static("/file", "./public")
```
Does `/file` represent
- sub directory inside `public` directory i.e. `./public/file`
- alias/route of `./public` directory so that `/file` could be used as handler

**Comment by li-jin-gou** [comment]
> Also I'm little bit confused on use of `relativePath` in
> 
> ```go
> func (group *RouterGroup) Static(relativePath, root string) IRoutes {
> 	return group.StaticFS(relativePath, &frame.FS{Root: root})
> }
> ```
> 
> If I use
> 
> ```go
> h.Static("/file", "./public")
> ```
> 
> Does `/file` represent
> 
> * sub directory inside `public` directory i.e. `./public/file`
> * alias/route of `./public` directory so that `/file` could be used as handler

sub directory inside public directory i.e. ./public/file

**Comment by sujit-baniya** [comment]
Isn't it somewhat wrong? I suppose the relativePath makes more sense to have it as an alias/route prefix, something similar to what gofiber does https://docs.gofiber.io/api/app#static

**Comment by li-jin-gou** [comment]
Let me explain:

- The difference is that the PathRewrite logic of FS is the same.

Fiber 
https://github.com/gofiber/fiber/blob/master/router.go#L340
```
		PathRewrite: func(fctx *fasthttp.RequestCtx) []byte {
			path := fctx.Path()
			if len(path) >= prefixLen {
				if isStar && app.getString(path[0:prefixLen]) == prefix {
					path = append(path[0:0], '/')
				} else {
					path = path[prefixLen:]
					if len(path) == 0 || path[len(path)-1] != '/' {
						path = append(path, '/')
					}
				}
			}
			if len(path) > 0 && path[0] != '/' {
				path = append([]byte("/"), path...)
			}
			return path
		},
		PathNotFound: func(fctx *fasthttp.RequestCtx) {
			fctx.Response.SetStatusCode(StatusNotFound)
		},

```


Hertz:
https://github.com/cloudwego/hertz/blob/develop/pkg/app/fs.go#L803

```
	if h.pathRewrite != nil {
		path = h.pathRewrite(ctx)
	} else {
		path = ctx.Path()
	}
```

If you want to be consistent with the behavior of the fiber, use the same `PathRewrite`.

**Comment by sujit-baniya** [comment]
Ah! got it working with PathRewrite

**Comment by li-jin-gou** [comment]
> Ah! got it working with PathRewrite

Thanks for the good questions.

**Comment by sujit-baniya** [comment]
I made some changes in `Static` function to make it work for me

```go
func (group *RouterGroup) Static(prefix, root string, cfg ...frame.StaticConfig) IRoutes {
	var config frame.StaticConfig
	if len(cfg) > 0 {
		config = cfg[0]
	}
	// For security, we want to restrict to the current work directory.
	if root == "" {
		root = "."
	}
	// Cannot have an empty prefix
	if prefix == "" {
		prefix = "/"
	}
	// Prefix always start with a '/' or '*'
	if prefix[0] != '/' {
		prefix = "/" + prefix
	}

	// Strip trailing slashes from the root path
	if len(root) > 0 && root[len(root)-1] == '/' {
		root = root[:len(root)-1]
	}
	// Is prefix a direct wildcard?
	isStar := prefix == "/*"
	// Is prefix a partial wildcard?
	if strings.Contains(prefix, "*") {
		isStar = true
		prefix = strings.Split(prefix, "*")[0]
		// Fix this later
	}
	prefixLen := len(prefix)
	if prefixLen > 1 && prefix[prefixLen-1:] == "/" {
		// /john/ -> /john
		prefixLen--
		prefix = prefix[:prefixLen]
	}
	if config.PathRewrite == nil {
		config.PathRewrite = func(ctx *frame.Context) []byte {
			path := ctx.Path()
			if len(path) >= prefixLen {
				if isStar && utils.UnsafeString(path[0:prefixLen]) == prefix {
					path = append(path[0:0], '/')
				} else {
					path = path[prefixLen:]
					if len(path) == 0 || path[len(path)-1] != '/' {
						path = append(path, '/')
					}
				}
			}
			if len(path) > 0 && path[0] != '/' {
				path = append([]byte("/"), path...)
			}
			return path
		}
	}
	return group.StaticFS(prefix, &frame.FS{
		Root:                 root,
		IndexNames:           config.IndexNames,
		GenerateIndexPages:   config.GenerateIndexPages,
		Compress:             config.Compress,
		AcceptByteRange:      config.AcceptByteRange,
		PathRewrite:          config.PathRewrite,
		PathNotFound:         config.PathNotFound,
		CacheDuration:        config.CacheDuration,
		CompressedFileSuffix: config.CompressedFileSuffix,
	})
}
```

**Comment by li-jin-gou** [comment]
I think this example https://github.com/cloudwego/hertz-examples/tree/main/file/staticFile is too simple, would you like to add more examples to it?  cc @sujit-baniya

**Comment by li-jin-gou** [comment]
A complete demo containing html and css.

**Comment by sujit-baniya** [comment]
@li-jin-gou Sure let me do it tomorrow morning. Do you think we should add third param in `Static()` as config similar to the way I did?

**Comment by li-jin-gou** [comment]
> @li-jin-gou Sure let me do it tomorrow morning. Do you think we should add third param in `Static()` as config similar to the way I did?

I think we should just add the sample code from example. https://github.com/cloudwego/hertz-examples/tree/main/file/staticFile,  and This example code is now too simple.

`add third param in Static() as config` is break change,So much so that I prefer to refine the example first.

**Comment by sujit-baniya** [comment]
PR created

**Comment by li-jin-gou** [comment]
thanks
