### ISSUE TITLE
question regarding handler + reverse proxy

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#402]
how do i pass ctx request to reverseproxy?
how do i return ctx response of what reverseproxy returns?

i'm not sure how to pass ctx to reverse proxy etc because in fasthttp it's just a simple &ctx or *ctx copy around but how does this work with hertz?

with reference below. sorry, if i can figure out then i guess conversion is easier.

```
package main

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/client"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/network/standard"
	"github.com/hertz-contrib/reverseproxy"
)

func main() {

	h := server.New()
	h.Use("/", ProxyHandlerTemp)
	h.Spin()

}

func ProxyHandlerTemp(c context.Context, ctx *app.RequestContext) {

	ctx.Request.Header.Set("Hello", "123")
	//how do i pass ctx request to reverseproxy?

	h := server.New()
	rp, _ := reverseproxy.NewSingleHostReverseProxy("https://localhost:8082/test", client.WithDialer(standard.NewDialer()))
	h.Any("/", rp.ServeHTTP)
	h.Spin()

	//how do i return ctx response of what reverseproxy returns?
	
	ctx.Response.Header.Set("Goodbye", "321")

}

**Comment by li-jin-gou** [comment]
not support and you can refer to https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/proxy/#reverse-proxy and use `SetDirector` and  `SetModifyResponse`

**Comment by ultperf** [comment]
@li-jin-gou can you provide an example of how to transfer from the reverse proxied results to the current h.Use() handler?
what's the ideal way to get the "fastest" response from the reverse proxy with/without the handler function?

**Comment by li-jin-gou** [comment]
> @li-jin-gou can you provide an example of how to transfer from the reverse proxied results to the current h.Use() handler? what's the ideal way to get the "fastest" response from the reverse proxy with/without the handler function?

cc @Skyenought

**Comment by ultperf** [comment]
i just realised i cannot do/use http2 + reverse proxy together

**Comment by li-jin-gou** [comment]
```
c, _ := client.NewClient()
	c.SetClientFactory(factory.NewClientFactory(
		config.WithDialer(standard.NewDialer()),
		config.WithTLSConfig(&tls.Config{InsecureSkipVerify: true})))

proxy, err := reverseproxy.NewSingleHostReverseProxy("http://127.0.0.1:8000/proxy")
    if err != nil {
        panic(err)
    }

proxy.SetClient(c)
```

**Comment by li-jin-gou** [comment]
same to https://github.com/cloudwego/hertz/issues/407

A slight adjustment to its logic is all that is required. however, I would like to remind you that you need to read the documentation yourself and we will add examples where possible.

**Comment by li-jin-gou** [comment]
> > @li-jin-gou您能否提供一个示例，说明如何从反向代理结果转移到当前的 h.Use() 处理程序？从有/没有处理函数的反向代理获得“最快”响应的理想方法是什么？
> 
> 抄送@Skyenought @L2ncE

I think this example needs to be added.

**Comment by zstone12** [comment]
please assign to me.

**Comment by li-jin-gou** [comment]
> please assign to me.

thanks
