### ISSUE TITLE
missing "http2/config" conf locations, pls chk repo.

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#408]
https://github.com/Duslia/hertz/blob/feat/h2/examples/h2/main.go
        "github.com/cloudwego/hertz/pkg/protocol/http2/config"

https://github.com/hertz-contrib/http2/blob/030e2b6768b99393d9b22c78f58824cdf9e85286/examples/h2/main.go#L37
	"github.com/hertz-contrib/http2/config"

with ref to https://github.com/cloudwego/hertz/issues/402

**Comment by li-jin-gou** [comment]
go get can specify a branch. you should use `feat/http2_support` branch. thanks

**Comment by li-jin-gou** [comment]
We will be merge HTTP2 so that it will be smooth to use. cc @Duslia

**Comment by ultperf** [comment]
@li-jin-gou sorry i dont understand
what feat/http2_support? <- what's the exact url to this?
```
go: finding module for package github.com/cloudwego/hertz/pkg/protocol/http2/config
... imports
...... imports
        github.com/cloudwego/hertz/pkg/protocol/http2/config: module github.com/cloudwego/hertz@latest found (v0.4.1), but does not contain package github.com/cloudwego/hertz/pkg/protocol/http2/config
```

**Comment by li-jin-gou** [comment]
it is https://github.com/hertz-contrib/http2/tree/feat/http2_support

**Comment by li-jin-gou** [comment]
go get github.com/hertz-contrib/http2@feat/http2_support

**Comment by ultperf** [comment]
go get -u github.com/hertz-contrib/http2@feat/http2_support

```
go: github.com/hertz-contrib/http2@feat/http2_support: invalid version: version "feat/http2_support" invalid: disallowed version string

```

**Comment by ultperf** [comment]
i did 
```
go env -w GOPRIVATE="github.com/hertz-contrib/http2"
```
doesnt work too...

**Comment by Duslia** [comment]
Now HTTP2 has been merged to main branch. But it depends on the `feat/http2_adapt` branch in the Hertz repo. If you want to use it, please execute the demand following:
```
go  get github.com/hertz-contrib/http2@main
go get github.com/cloudwego/hertz@feat/http2_adapt
```

**Comment by ultperf** [comment]
@Duslia just got this issue. how to resolve?
go get github.com/cloudwego/hertz@feat/http2_adapt
go: github.com/cloudwego/hertz@feat/http2_adapt: invalid version: version "feat/http2_adapt" invalid: disallowed version string

**Comment by Duslia** [comment]
go get github.com/cloudwego/hertz@2def49cd876c70c39cd198bb59716f568e45d08d

**Comment by Duslia** [comment]
Could we contact by lark or slack? It is more convenient.

**Comment by li-jin-gou** [comment]
> Could we contact by lark or slack? It is more convenient.

+1 ❤️
You are seriously experiencing and using Hertz's HTTP2, we encourage this behaviour and will help you to use it.

**Comment by ultperf** [comment]
ok. i will try to install lark soon coz my mobile space limited. next question will use lark

**Comment by li-jin-gou** [comment]
> ok. i will try to install lark soon coz my mobile space limited. next question will use lark

github's issue also OK❤️

**Comment by ultperf** [comment]
ok i'm having this now 
```
 go get github.com/Duslia/hertz/pkg/protocol/http2/config
go: module github.com/Duslia/hertz@upgrade found (v0.0.1), but does not contain package github.com/Duslia/hertz/pkg/protocol/http2/config
```
        
i joined slack but i will finish this one here coz others can reference here and can complete this.

**Comment by Duslia** [comment]
There is no need to depends on github.com/Duslia/hertz

**Comment by Duslia** [comment]
> i extracted below from one of the examples given somewhere on the github sites. errror here
> 
> ```
> undefined: client.WithALPN
> client.WithHTTP2Option
> undefined: h2config
> ```
> 
> need
> 
> ```
> 	h2config "github.com/Duslia/hertz/pkg/protocol/http2/config"
> ```
> 
> change to github.com/cloudwego/hertz/pkg/protocol/http2/config: cannot find module providing package github.com/cloudwego/hertz/pkg/protocol/http2/config
> 
> doesn't work.
> 
> code
> 
> ```
> 		clientC, _ := reverseproxy.NewSingleHostReverseProxy(......................
> 		h2client, _ := client.NewClient()
> 
> 		h2client.SetClientFactory(factory.NewClientFactory(
> 			client.WithALPN(true),
> 			client.WithDialer(standard.NewDialer()),
> 			client.WithTLSConfig(&tls.Config{InsecureSkipVerify: true}),
> 			client.WithHTTP2Option(
> 				h2config.WithMaxHeaderListSize(1024),
> 				h2config.WithPingTimeout(time.Second*15),
> 			),
> 		))
> 		clientC.SetClient(h2client)
> 		
> ```

please refer to the example : https://github.com/hertz-contrib/http2/blob/main/examples
<img width="738" alt="image" src="https://user-images.githubusercontent.com/37136584/203277582-21beb5db-996e-48a1-8c3a-dd640f3ac885.png">

**Comment by ultperf** [comment]
these two only. how to...?
```
undefined: client.WithALPN
undefined: client.WithHTTP2Option
```

**Comment by Duslia** [comment]
Just use the latest example. Now no `WithALPN` option. Please follow: https://github.com/hertz-contrib/http2/blob/main/examples

**Comment by ultperf** [comment]
cannot use client.WithTLSConfig(&tls.Config{…}) (value of type "github.com/cloudwego/hertz/pkg/common/config".ClientOption) as type "github.com/hertz-contrib/http2/config".ClientOption in argument to factory.NewClientFactory


```

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/client"
	"github.com/cloudwego/hertz/pkg/network/standard"
	"github.com/hertz-contrib/http2/factory"
	"github.com/hertz-contrib/reverseproxy"
	"github.com/pelletier/go-toml/v2"
	"github.com/valyala/fasthttp"

		h2client, _ := client.NewClient()

		h2client.SetClientFactory(factory.NewClientFactory(
			//client.WithALPN(true),
			client.WithDialer(standard.NewDialer()),
			client.WithTLSConfig(&tls.Config{InsecureSkipVerify: true}),

		))


		clientC.SetClient(h2client)

```

**Comment by ultperf** [comment]
carrying on here :
https://github.com/cloudwego/hertz/issues/410
