### ISSUE TITLE
what does this mean?

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#411]
```
2022/11/22 20:06:28.062058 reverse_proxy.go:231: [Error] HERTZ: Client request error: "http2: unsupported scheme
```

using nginx with instructions on setting up https
is it because i need to set up http2 or something? possible to provide link to instructions on how to do http2 for nginx etc?

https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-nginx-in-ubuntu-22-04

**Comment by Duslia** [comment]
You use `http` to make a request. However, HTTP2 only supports `HTTPS`. If you'd like to use HTTP2 without TLS, you can use H2C

**Comment by Duslia** [comment]
Have you solved this question?
