### ISSUE TITLE
[QUESTION] - How can I pass multiple validator functions for struct binding?

### ISSUE THREAD

**Issue by sujit-baniya** [cloudwego/hertz#413]
Can you please suggest on how can I pass multiple validator functions along with their individual validation error message?

For e.g.

```go
type Login struct {
	Username string `form:"username,required"`
	Password string `form:"password,required"`
        RememberMe bool `form:"remember_me"
}
```
Here I wanted to pass more validators for fields

**For username,** 
required with error message "Email is required"
user_check with error message "User doesn't exist" (custom validator)
email with error message "Not an email"

**For password,**
required with error message "Password is required"
min and max characters with error message "Can't be more than 32 characters"

**For remember_me,**
remember_me as bool with error message "Invalid flag" if non-bool passed

**Comment by L2ncE** [comment]
refer to 
https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/binding-and-validate/
https://github.com/cloudwego/hertz-examples/tree/main/binding

**Comment by sujit-baniya** [comment]
I did check them but didn't find clue about multiple validators

**Comment by li-jin-gou** [comment]
hertz use https://github.com/bytedance/go-tagexpr binding and validatte package and you can read it's readme.
if you want to use `hz` and `idl` , you can refer to https://www.cloudwego.io/docs/hertz/tutorials/toolkit/toolkit/#supported-api-annotations-1

**Comment by li-jin-gou** [comment]
> Thank @li-jin-gou will check it out. I prefer get hands dirty without `hz` :)
> 
> Also can you please suggest how can I register custom struct in session?
> 
> In session I tried to save `Login` struct but getting error
> 
> ```go
> "securecookie: error - caused by: securecookie: error - caused by: gob: type not registered for interface: requests.Login"
> ```

This does not look like a Hertz error, which I have not encountered.

**Comment by li-jin-gou** [comment]
yes, refer to https://github.com/gorilla/securecookie#examples 
![image](https://user-images.githubusercontent.com/97824201/203534130-7470dcbb-fe54-4ef9-9b0b-885ab105b699.png)

**Comment by li-jin-gou** [comment]
I reopened it because I wanted to optimize it on the documentation

**Comment by li-jin-gou** [comment]
> I reopened it because I wanted to optimize it on the documentation

PATL @Skyenought
