### ISSUE TITLE
[QUESTION] - How to redirect to different url in middleware?

### ISSUE THREAD

**Issue by sujit-baniya** [cloudwego/hertz#414]
I'm trying to redirect to different internal url in middleware, but I'm not redirected. This is the code I tried.

```go
package main

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

func WebAuth(redirectTo string) app.HandlerFunc {
	if redirectTo == "" {
		redirectTo = "/"
	}
	return func(c context.Context, ctx *app.RequestContext) {
		if _, ok := ctx.Get("user"); !ok {
			ctx.Redirect(consts.StatusFound, []byte(redirectTo))
			// ctx.JSON(200, "Test") Don't work either
			return
		}
		ctx.Next(c)
	}
}

func main() {
	h := server.Default(server.WithHostPorts("127.0.0.1:8080"))
	g1 := h.Group("/")
	g1.Use(WebAuth("/foo"))
	g1.GET("/", func(ctx context.Context, c *app.RequestContext) {
		c.Set("user", 1)
		c.String(consts.StatusOK, "Home")
	})
	h.GET("/foo", func(ctx context.Context, c *app.RequestContext) {
		c.String(consts.StatusOK, "hello, world")
	})

	h.Spin()
}
```

The code enters the middleware and inside the if for redirection when tried to visit `"/"`, but it's not redirecting to `"/foo"` and ends up with `"Home"` response

**Expected Result:**
The page should have redirected to `"/foo"` instead of going inside `"/"`

Please suggest what am I doing wrong

**Comment by li-jin-gou** [comment]
cc @zstone12

**Comment by sujit-baniya** [comment]
@li-jin-gou In middleware whatever I put, `ctx.JSON()`, `ctx.HTML()`, `ctx.Redirect()`, the code is going inside `"/"` which is not expected

**Comment by zstone12** [comment]
![image](https://user-images.githubusercontent.com/28105615/203594968-78e5ebb2-a43c-4835-8e44-8d865ef45722.png)


Should use `ctx.Abort()`.
`Abort()` prevents pending handlers from being called.

**Comment by li-jin-gou** [comment]
refer to https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/middleware/
use `ctx.Abort()`

**Comment by sujit-baniya** [comment]
Ah! got it. So wouldn't it be good if `Abort()` is called inside `Redirect()`. I mean what would be the use of `Redirect()` if `Abort()` is not called?

**Comment by zstone12** [comment]
It about

**Comment by li-jin-gou** [comment]
> Thanks for explanation. I was just wondering any use case where I would only call `Redirect()` and not `Abort()`

![image](https://user-images.githubusercontent.com/97824201/203603186-f348d9e7-99a5-471e-8ed2-eae59f0530d5.png)

here last handler.
