### ISSUE TITLE
docs: add more info for graceful shutdown

### ISSUE THREAD

**Issue by welkeyever** [cloudwego/hertz#415]
**Describe the solution you'd like**

Add more info to https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/graceful-shutdown/ (project [address](https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/basic-feature/graceful-shutdown.md)):

1. Add introduction for `SetCustomSignalWaiter` cc: https://github.com/cloudwego/hertz/blob/develop/pkg/app/server/hertz.go#L90 
2. Add introduction for the default `waitSignal` cc: https://github.com/cloudwego/hertz/blob/develop/pkg/app/server/hertz.go#L97

**Comment by zstone12** [comment]
Please assign to me :D

**Comment by li-jin-gou** [comment]
> Please assign to me :D

thanks
