### ISSUE TITLE
docs: add documentation of csrf middleware

### ISSUE THREAD

**Issue by L2ncE** [cloudwego/hertz#422]
**Describe alternatives you've considered**

We are now missing documentation for the [csrf middleware](https://github.com/hertz-contrib/csrf). Could you please help me add the doc?

**Tips**

You can create a `csrf.md` in [tutorials/basic-feature/middleware](https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials/basic-feature/middleware).

**Note**
You can first complete the Chinese doc and create PR to review. And then translate to English.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by Claude-Zq** [comment]
I want to work on this

**Comment by L2ncE** [comment]
> I want to work on this

thx
