### ISSUE TITLE
embed如何使用?

### ISSUE THREAD

**Issue by ezewu** [cloudwego/hertz#423]
embed如何使用?

**Comment by L2ncE** [comment]
Hi, u can improve the question according to the issue template to provide more information👏.

**Comment by ezewu** [comment]
这个web框架还不支持使用 embed吗

**Comment by li-jin-gou** [comment]
> 这个web框架还不支持使用 embed吗

Yes and same to https://github.com/cloudwego/hertz/issues/324 cc @welkeyever

**Comment by li-jin-gou** [comment]
> Hi, u can improve the question according to the issue template to provide more information👏.

Perhaps we could add a CI to limit the specification of the pull request and issue template.  refer to https://github.com/go-gorm/gorm.

**Comment by li-jin-gou** [comment]
Repeated PR's are temporarily closed.
