### ISSUE TITLE
there is monoio for rust, can there be a thread per core for golang?

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#424]
there is monoio for rust, can there be a thread per core for golang?

thread per core golang is difficult coz of goroutine but go routine can be replaced with customized "goroutine" like gopool etc

possible to make it purely a thread per core version with other plugins / batteries designed for use with this customized thread per core version?

**Comment by li-jin-gou** [comment]
netpoll use gopool refer to https://github.com/cloudwego/netpoll#features
