### ISSUE TITLE
is there a way to keep the state of the hertz http session?

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#426]
how to keep stateOfThis variable for this state or is there a better work around other than using mutex lock etc?
```
var stateOfThis uint8 = 1
      h := server.New(
          server.WithHostPorts(":443"),
          server.WithALPN(true),
          server.WithTLS(&tls.Config{
          GetCertificate: func(hello *tls.ClientHelloInfo) (*tls.Certificate, error) {
      
          ip, _, err := net.SplitHostPort(hello.Conn.RemoteAddr().String())
          if err != nil {
              return nil, err
          }
          if ip == "123.123.123.123" {
               stateOfThis = 0
          }
```
```
    h.Use(func(cc context.Context, ctx *app.RequestContext) {
      if stateOfThis == 0 {
        log.Printf("HELLO!")
        return
      }
    })
```

**Comment by li-jin-gou** [comment]
Why not store this variable in a stateful backend such as redis?

**Comment by li-jin-gou** [comment]
If you use global variables I think you still need to lock them.

**Comment by ultperf** [comment]
need extreme speed, wont use redis (too slow) 
can u provide best example for the atomic operations?

would like to have the most extreme speed in this, highest performance way.

**Comment by li-jin-gou** [comment]
https://pkg.go.dev/sync/atomic

**Comment by ultperf** [comment]
i know how to use atomic operations but for the context of extreme performance and this hertz implementation, i dont see how i can make it super fast.

maybe shld consider using fasthttp way inside a for listening loop. is there an alternative for such hertz implementation as proposal. slowing down this part is not a very performant move.

**Comment by li-jin-gou** [comment]
😂In the example I saw, stateOfThis is a global variable and is not used in conjunction with the context. I think it would be good to use atomic.

**Comment by ultperf** [comment]
of course i know, i'm just giving example.
if have better solution using atomic or otherwise do mention.
i believe fasthttp is the right way to go with the listener in for loop. maybe this can be a feature request to resolve this issue.

**Comment by ultperf** [comment]
how to do this without global variable? without global atomic locks etc?

**Comment by li-jin-gou** [comment]
For something similar to a session, take a look at https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/middleware/session/

**Comment by li-jin-gou** [comment]
You can describe your needs in detail so that I can know how to help you. I have not used it. `fasthttp is the right way to go with the listener in for loop`

**Comment by ultperf** [comment]
pls refer to here : https://github.com/cloudwego/hertz/issues/428
basically, i would like to match against an array of IPs and drop them as soon as possible once detected. going into tls config will be too slow. need fastest way to drop IPs
