### ISSUE TITLE
fastest way to drop bad ips

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#427]
with regards to this issue
https://github.com/cloudwego/hertz/issues/426

how do i drop ips way before intercepted by hertz etc? at the network ip layer. because in the example shown, i still need to use the get certificate function to get the ip. i would like to drop the ip as fast as detected as bad ip in within my array

**Comment by li-jin-gou** [comment]
same to https://github.com/valyala/fasthttp/issues/1424

**Comment by ultperf** [comment]
what i mean is the fastest way to drop bad ip before routing through hertz? at netpoll ip detection layer?

**Comment by li-jin-gou** [comment]
> what i mean is the fastest way to drop bad ip before routing through hertz? at netpoll ip detection layer?

Hertz also support Hijack.

**Comment by li-jin-gou** [comment]
I'm in the process of putting together this section of the document and I expect to finish it today. refer to https://github.com/cloudwego/cloudwego.github.io/pull/450
