### ISSUE TITLE
希望支持websocket

### ISSUE THREAD

**Issue by manchurio** [cloudwego/hertz#43]
**Describe the solution you'd like**

作为网关用， 希望支持websocket

**Comment by bilinxing** [comment]
+1 期待字节放出内部的websocket实现

**Comment by xiaobaiyouxi** [comment]
+1

**Comment by baiyutang** [comment]
please assignee to me. I will try to it.

**Comment by baiyutang** [comment]
Hertz has implemented to support Websocket. This issue will be closed.
