### ISSUE TITLE
no Del and no Write for ctx.Request. Can help? where do i find the details for this again?

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#431]
no Del and no Write. Where can i find equivalent etc?
```
    var ctxTemp *app.RequestContext
    ctxTemp.Request.Header.Del("abcdef") // cannot work, no Del
    
    w := bytebufferpool.Get()
    bwq := bufio.NewWriter(w)
    ctxTemp.Request.Write(bwq) // cannot work, no Write
```

possible to provide the go doc section? sorry i cant seem to find it properly. not sure where to find it.

**Comment by wzekin** [comment]
The first question you can use [DelBytes](https://pkg.go.dev/github.com/cloudwego/hertz@v0.4.1/pkg/protocol#RequestHeader.DelBytes) to delete a header.
The second question hertz does not have a similar api, you can use [VisitAll](https://pkg.go.dev/github.com/cloudwego/hertz@v0.4.1/pkg/protocol#RequestHeader.VisitAll) to get headers and [BodyWriteTo](https://pkg.go.dev/github.com/cloudwego/hertz@v0.4.1/pkg/protocol#Response.BodyWriteTo) to get body.

**Comment by ultperf** [comment]
@wzekin i'm not very sure but does VisitAll include cookies and every possible header information?

so body and visitall is all i need?

**Comment by li-jin-gou** [comment]
@ultperf Hertz not support  `Request.Write` func ,you can use Request's api to set http header、body and  status_code.
