### ISSUE TITLE
[Question] Why we using vendored bytebufferpool instead of valyala/bytebufferpool

### ISSUE THREAD

**Issue by MindMayhem** [cloudwego/hertz#436]
Greetings, i'm using Jade templating compiler, which uses [valyala/bytebufferpool](https://github.com/valyala/bytebufferpool)
Currently, i had to change every generated file from valyala repo to your's https://github.com/cloudwego/hertz/tree/develop/pkg/common/bytebufferpool to escape unneccesary byte buffer allocation and write template directly to `ctx.Response.BodyBuffer()`

I thought that you somehow modified or made changes, but after checking both files (bytebufferpool.go) it turned out that all the code is equivalent and only the CloudWego signature is added

Why not using main repository of bytebuffer instead of storaging a copy in hertz repo?

**Comment by li-jin-gou** [comment]
The question is really the same as how to use https://github.com/Joker/jade in Hertz

**Comment by MindMayhem** [comment]
@li-jin-gou no, question is why we using vendored version of bytebufferpool instead of main repository, nothing more, a lot of templating compilers uses bytebufferpool

also, fasthttp and frameworks based on it uses valyala/bytebufferpool too

**Comment by li-jin-gou** [comment]
> @li-jin-gou no, question is why we using vendored version of bytebufferpool instead of main repository, nothing more, a lot of templating compilers uses bytebufferpool
> 
> also, fasthttp and frameworks based on it uses valyala/bytebufferpool too

Well, I thought you didn't know how to use jade anymore.  cc @Duslia @welkeyever

**Comment by welkeyever** [comment]
Good question.
Initially this part is to ensure that the initial iterations are fast and the code is statically stable, and vendor is the fastest way.

I do think it is better to directly depend on the origin repo if there is no more changes at this time.

Will check this ASAP. Thanks for your report.

**Comment by MindMayhem** [comment]
@welkeyever any news?

**Comment by welkeyever** [comment]
Sorry for the late. Because Hertz is also used internally by Bytedance we need to provide a proper way for the potentially incompatible changes.

I saw your pr, really appreciate that - if there is a definite conclusion I will update it ASAP.

**Comment by li-jin-gou** [comment]
I think bufferpool is a critical package, if there is a problem or some optimization we can quickly solve and release, for the time being do not consider using [valyala/bytebufferpool](https://github.com/valyala/bytebufferpool). Thank you PR.
