### ISSUE TITLE
hertz 添加新生成的模板

### ISSUE THREAD

**Issue by SeigeC** [cloudwego/hertz#439]
**Is your feature request related to a problem? Please describe.**
hertz 生成的模板在调用 c.Json 后还需多写个 return 才能结束函数，会导致因为一些异常情况忘记写 return 导致发生预期之外的情况，所以希望生成的模板能添加 `return  resp, err` 的写法

**Comment by welkeyever** [comment]
There is no mandatory requirement for `return` clause in `HandlerFunc`. You may also see it very clearly from its function signature:
`type HandlerFunc func(c context.Context, ctx *RequestContext)`

The exception you mentioned, which leading to some unexpected situation - you may paste some codes to elaborate it.

**Comment by SeigeC** [comment]
像这样一段代码，这三个 return 要是有一个忘了写都会导致函数继续执行出现预期外的错误
```go
func A(c context.Context, ctx *app.RequestContext) {
	ids, err := models.FindUserIds()
	if err != nil {
		ctx.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"error": err.Error(),
		})
		return
	}
	if len(ids) == 0 {
		ctx.JSON(consts.StatusOK, map[string]interface{}{
			"data": emptyInfos,
		})
		return
	}

	infos, err := models.FindUserInfo(ids)
	if err != nil {
		ctx.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"error": err.Error(),
		})
		return
	}

	ctx.JSON(consts.StatusOK, map[string]interface{}{
		"data": infos,
	})
}
```

**Comment by li-jin-gou** [comment]
我们会提供新的 layout 并且新的 layout 解决了这个问题.
