### ISSUE TITLE
question regarding SetRequestURIBytes, SetHostBytes and SetScheme etc

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#448]
if i have already provided full "http://example.com/hello", do i still need to set sethost or setscheme or anything else?
```
  ctx.Request.SetRequestURIBytes(reqURI)
```
still need to set below or no need?
```	
  ctx.Request.SetHostBytes(reqHost)
  ctx.Request.URI().SetScheme("http")
```
with ref to this https://github.com/cloudwego/hertz/issues/446

**Comment by li-jin-gou** [comment]
No setup required.

**Comment by ultperf** [comment]
ok thx!
