### ISSUE TITLE
possible to include this ctx.Response.Header.SetContentEncodingBytes <- ?

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#449]
just this will do.
```
ctx.Response.Header.SetContentEncodingBytes 
```
the rest can work around. thx

**Comment by ultperf** [comment]
after 2 weeks of workarounds, i'm finally left with this last part. seemed a lot of "missing" compatibility features but can be fixed no issue. great work guys. i think mostly a lot of copying and pasting needed.

pls help with this last section as the rest i've already figured out how to workaround checking the codes. only this last section is not evident. thx!

**Comment by ultperf** [comment]
@li-jin-gou can i buy u a coffee when this and https://github.com/cloudwego/hertz/issues/428 is resolved as token of appreciation?

thx a lot for the help extended so far here, on fasthttp and fiber.

**Comment by li-jin-gou** [comment]
> just this will do.
> 
> ```
> ctx.Response.Header.SetContentEncodingBytes 
> ```
> 
> the rest can work around. thx

Hertz does not currently support this feature, you can use `ctx.Response.Header.Set`.

**Comment by li-jin-gou** [comment]
> @li-jin-gou can i buy u a coffee when this and #428 is resolved as token of appreciation?
> 
> thx a lot for the help extended so far here, on fasthttp and fiber.

This is not necessary, as far as I know, you are the first person to use the Hertz HTTP2 feature in open-souece and we appreciate your trust in Hertz.

**Comment by li-jin-gou** [comment]
Same as https://github.com/valyala/fasthttp/pull/1311  and I think we can also support it.

**Comment by wang-tsh** [comment]
Please assign me.

**Comment by li-jin-gou** [comment]
> Please assign me.

thanks

**Comment by wang-tsh** [comment]
> > Please assign me.
> 
> thanks

my pleasure
