### ISSUE TITLE
clarification on reverseproxy.NewSingleHostReverseProxy()

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#452]
does reverseproxy.NewSingleHostReverseProxy() override setrequesturi() settings?

it seems hostreverseproxy overrides the setrequesturi() ? i have yet to check out this solution,
https://github.com/cloudwego/hertz/issues/446
is the above the way to work around?
@li-jin-gou can u provide an example on how to use the above for what i need? this is more on fasthttp HostClient equivalent feature. this is my final last question. i've tested all and it seems to be working except this part

```
  proxy, err := reverseproxy.NewSingleHostReverseProxy(httpScheme + "://" + host + ":" + port + "/")
  if err != nil {
  panic(err)
  }
  proxy.SetClient(H2client)
  
  proxy.SetErrorHandler(func(ctx *app.RequestContext, err error) {
  ctx503Error(ctx)
  })
  
  proxy.ServeHTTP(cc, ctx)
```
also will wait for the fastest ip drop then all ok.
thx!

**Comment by li-jin-gou** [comment]
refer to https://github.com/hertz-contrib/reverseproxy/blob/master/reverse_proxy.go#L108 and i think you may need to customize the Director.

**Comment by ultperf** [comment]
is this correct?
```
  proxy.SetDirector(func(req *protocol.Request) {
    //req.SetRequestURI(string(reverseproxy.JoinURLPath(req, rp.Target))) //seriously my brain hurts just trying to figure out what rp.Target means by joining req with it. what does this mean. strange.
    req.SetRequestURI(ctx.Request.URI())
    req.Header.SetHostBytes(ctx.Request.URI().Host()) //<-- is this still needed if request.uri() is already set?
    req.Options().Apply([]config.RequestOption{config.WithSD(true)}) //<-- what is this setdefine for? isSD bool...?
  })
```
