### ISSUE TITLE
tried setscheme in proxy.SetDirector... how to?

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#455]
with ref to https://github.com/cloudwego/hertz/issues/453
and https://github.com/cloudwego/hertz/issues/452
req.Header.RequestURI().SetScheme undefined (type []byte has no field or method SetScheme)
```
proxy.SetDirector(func(req *protocol.Request) {
  req.SetRequestURI(B2s(requestURI)) 
  req.Header.SetHostBytes(reqHost)
  req.Header.RequestURI().SetScheme(httpScheme) //<- req.Header.RequestURI().SetScheme undefined (type []byte has no field or method SetScheme)
  
  req.Options().Apply([]config.RequestOption{config.WithSD(true)})
})
```

**Comment by li-jin-gou** [comment]
`ctx.URI().SetScheme()`
refer to https://github.com/cloudwego/cloudwego.github.io/pull/450/files and I am writing this part of the document.

**Comment by hiqsociety** [comment]
ctx.URI().SetScheme()? <- how to use within the context of the proxy.SetDirector?
```
proxy.SetDirector(func(req *protocol.Request) {
  ctx.URI().SetScheme("https") // <- how to use here?
  ```

**Comment by li-jin-gou** [comment]
> ctx.URI().SetScheme()? <- how to use within the context of the proxy.SetDirector?
> 
> ```
> proxy.SetDirector(func(req *protocol.Request) {
>   ctx.URI().SetScheme("https") // <- how to use here?
> ```

req.URI().SetScheme()

**Comment by li-jin-gou** [comment]
https://github.com/cloudwego/hertz/blob/9b9ec92704e19626225f6fc10d69a62f1762dbda/pkg/protocol/uri.go#L265-L270

I think it is ok

**Comment by hiqsociety** [comment]
got it. sorry about the question, my mistake.
