### ISSUE TITLE
feat: add Custom inerface in IRoutes interface

### ISSUE THREAD

**Issue by byene0923** [cloudwego/hertz#46]
**Is your feature request related to a problem? Please describe.**

may hertz suport Custom interface for [IRoutes](https://github.com/cloudwego/hertz/blob/develop/pkg/route/routergroup.go#L61) ?

**Describe the solution you'd like**
`Custom([]string, string, ...app.HandlerFunc) IRoutes`

and the implemention like
```go
func (group *RouterGroup) Custom(httpMethods []string, relativePath string, handlers ...app.HandlerFunc) IRoutes {
	if len(httpMethods) == 0 {
		panic("can't find any http method")
	}
	for _, httpMethod := range httpMethods {
		if matches, err := regexp.MatchString("^[A-Z]+$", httpMethod); !matches || err != nil {
			panic("http method " + httpMethod + " is not valid")
		}
		group.handle(httpMethod, relativePath, handlers)
	}
	return group.returnObj()
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Duslia** [comment]
I think it's just a syntactic sugar and may not lead to real improvement. Why you want to add this interface? If it is reasonable, I can add it.

**Comment by byene0923** [comment]
yeah,  it's just a syntactic sugar, but i see [IRoutes](https://github.com/cloudwego/hertz/blob/develop/pkg/route/routergroup.go#L64) has the Any interface, i think may be it is a syntactic sugar too?. so why not add the Custom interface?

**Comment by Duslia** [comment]
emmm I don't think this reason is sufficient. Maybe you can define it in your project?
