### ISSUE TITLE
docs: add documentation of HTTP2 

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/hertz#465]
**Describe alternatives you've considered**

We are now missing documentation for the [HTTP2](https://github.com/hertz-contrib/http2). Could you please help me add the doc?

**Tips**

You can create a `http2.md` in https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials/basic-feature/protocol

**Note**
You can first complete the Chinese doc and create PR to review. And then translate to English.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by Claude-Zq** [comment]
I'd like to try it.

**Comment by li-jin-gou** [comment]
> I'd like to try it.

thanks
