### ISSUE TITLE
Feature Request: for http3, af_xdp -> quic without going through netpoll with ready made repo for udp processing.

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#476]
for http3, af_xdp -> quic without going through netpoll with ready made repo for udp processing.

using this repo can save a lot of time and should help increase performance by 30% minimally in general.
https://github.com/asavie/xdp

not trying to be funny but just hope for the 30% performance that's all because crypto/tls for golang is really slow

**Comment by Duslia** [comment]
It seems that this repo is no longer maintained

**Comment by ultperf** [comment]
@Duslia i dont think it needs anymore maintenance

**Comment by Duslia** [comment]
This capability depends on the kernel version and functionality and it is not very widely applicable. If you are interested in it, you can do some attempts.

**Comment by ultperf** [comment]
@Duslia ok i can try
but can u gimme a clue where's the code section to modify for the socket connection / change for af_xdp to interface with?

**Comment by Duslia** [comment]
The connection relative code is under the pkg/network
