### ISSUE TITLE
nginx as backend sometimes doesnt display content with multiple new loads / reloads or just new page

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#482]
**Describe the bug**
nginx as backend sometimes doesnt display content with multiple new loads / reloads or just new page

in a separate issue, this error appears too
```
2022/12/21 14:49:47.349734 client.go:1840: [Info] http2: Transport readFrame error on conn 0xc00006cd00: (*errors.errorString) EOF
2022/12/21 14:49:47.988014 client.go:1840: [Info] http2: Transport readFrame error on conn 0xc00006d1e0: (*errors.errorString) EOF
2022/12/21 14:49:47.988062 client.go:1840: [Info] http2: Transport readFrame error on conn 0xc0004b0000: (*errors.errorString) EOF
2022/12/21 14:49:47.992292 client.go:1840: [Info] http2: Transport readFrame error on conn 0xc0004b01a0: (*errors.errorString) EOF
```

**To Reproduce**
use the code here
https://github.com/cloudwego/hertz/issues/481

same as mentioned in issue

**Expected behavior**
nginx not showing error but hertz showing blank

**Screenshots**

![screen50](https://user-images.githubusercontent.com/104323920/208933270-40662d79-aedc-4a09-a09f-b67e9e08a53c.jpg)

**Comment by li-jin-gou** [comment]
cc @Duslia

**Comment by Duslia** [comment]
Does this question come up every time？

**Comment by Duslia** [comment]
I cannot understand `multiple new loads / reloads`.
And hertz showing blank is the expected behavior?
<img width="375" alt="image" src="https://user-images.githubusercontent.com/37136584/209051356-f9313399-6c14-4690-a7b9-c162492a753e.png">

**Comment by ultperf** [comment]
@Duslia , when first time visit the url, hertz showing blank. this is not expected. expected behaviour is showing nginx default html page.

if you reload the browser multiple times, u'll sometimes get a blank screen too as attached in the image above. 
expected behaviour is showing nginx default html page.

**Comment by ultperf** [comment]
@Duslia they are two issues (i think same problems), can you look into it?
1. reverse proxy doesnt work well with nginx backend, shows blank page sometimes (check the video)
2. error message after waiting for some time.

https://github.com/cloudwego/hertz/issues/481
