### ISSUE TITLE
HTTP cache - RFC compliant with many other features

### ISSUE THREAD

**Issue by darkweak** [cloudwego/hertz#483]
**Is your feature request related to a problem? Please describe.**
Hello,

I already wrote an HTTP cache system ([called Souin](https://github.com/darkweak/souin)) used by the caddy cache-handler module and roadrunner, compatible with Træfik, Tyk and many other reverse-proxies/API Gateway. It supports the RFC-7234, can partially cache graphQL request, invalidate using xkeys/ykeys like Varnish. It also implements the Fastly purge using the Surrogate-key header. It can store and invalidate a CDN (cloudflare, fastly, Akamai), and it supports the Cache-Status RFC directive. It implements two in-memory/fs storages (badger & nutsdb) and two distributed storages (olric & etcd) that are fully configurable. The keys can be tweaked (e.g. serve the same cached css for multiple domains) and we can change the Cache-Status name through the configuration and it support the ESI tags processing.

Let me know your preference about that. ✌️

**Comment by li-jin-gou** [comment]
I think it is cool.

**Comment by FGYFFFF** [comment]
Looking forward to your contribution~~~

**Comment by darkweak** [comment]
@FGYFFFF Is there a way to override the default response writer?

**Comment by welkeyever** [comment]
> @FGYFFFF Is there a way to override the default response writer? Especially the `w` property that is a `responseBodyWriter`. Because I have to catch the data returned from the upstream.

@darkweak check this https://www.cloudwego.io/docs/hertz/tutorials/framework-exten/response_writer/

**Comment by darkweak** [comment]
@welkeyever Do you have some free time to spend on the PR review? We could create a repository under the `hertz-contrib` organization once everything is okay.

**Comment by welkeyever** [comment]
> @welkeyever Do you have some free time to spend on the PR review? We could create a repository under the `hertz-contrib` organization once everything is okay.

@darkweak Sure, remind me when you're ready🙏

**Comment by darkweak** [comment]
I am 😄
I linked the PR on the Souin repository above. If the code suits you on the PR, we can create the hertz-contrib repository.

**Comment by li-jin-gou** [comment]
> I am 😄 I linked the PR on the Souin repository above. If the code suits you on the PR, we can create the hertz-contrib repository.

cc https://github.com/hertz-contrib/souin

**Comment by darkweak** [comment]
@li-jin-gou `hertz-contrib/httpcache` would be more relevant for users instead of `hertz-contrib/souin` imho. What do you think?

**Comment by li-jin-gou** [comment]
> @li-jin-gou `hertz-contrib/httpcache` would be more relevant for users instead of `hertz-contrib/souin` imho. What do you think?

True, but there is already a repository at https://github.com/hertz-contrib/cache  and worried that the name might confuse people.

**Comment by li-jin-gou** [comment]
> Yes but the https://github.com/hertz-contrib/cache is not an http cache but a business cache (that's quite different), it doesn't implement the HTTP cache related RFCs. Anyway, we could rename it later if needed.

done

**Comment by darkweak** [comment]
Wow, thank you so much, I didn't expect you change it! 😅🙏

**Comment by darkweak** [comment]
The PR https://github.com/hertz-contrib/httpcache/pull/1 is ready! 🚀
