### ISSUE TITLE
Add a more detailed example for service discovery.

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/hertz#485]
> We hope more developers join CloudWeGo. This is a task issue that needs your help.

**Is your feature request related to a problem? Please describe.**

The current examples of service discovery are too simple and we need some complex examples to help users and we need to 
 improve detailed code examples to the [registry](https://github.com/hertz-contrib/registry/).

**picked**
- [x] zookeeper
- [x] consul
- [x] nacos
- [ ] etcd 
- [ ] polaris
- [x] eureka
- [x] servicecomb

**Additional context**

- https://github.com/hertz-contrib/registry/issues/30
- https://github.com/hertz-contrib/registry/

**Comment by Claude-Zq** [comment]
i want to do `consul`

**Comment by li-jin-gou** [comment]
> i want to do `consul`

thanks

**Comment by qiuyuyin** [comment]
etcd plz

**Comment by li-jin-gou** [comment]
> etcd plz

thanks

**Comment by dengWuuu** [comment]
can i nacos？？？？（first time participating in an open source project （doge））

**Comment by li-jin-gou** [comment]
> can i nacos？？？？（first time participating in an open source project （doge））

thanks

**Comment by dengWuuu** [comment]
> > can i nacos？？？？（first time participating in an open source project （doge））
> 
> thanks
[https://github.com/hertz-contrib/registry/pull/33](url) 
I see this pr, can nacos sample update imitate this pr?

**Comment by L2ncE** [comment]
> [https://github.com/hertz-contrib/registry/pull/33](url) I see this pr, can nacos sample update imitate this pr?

Every framework has its own characteristics, you can imitate but don't completely copy.

**Comment by dengWuuu** [comment]
> Every framework has its own characteristics, you can imitate but don't completely copy.
 thanks

**Comment by dengWuuu** [comment]
nacos is finished

**Comment by chaoranz758** [comment]
I want to do zookeeper

**Comment by L2ncE** [comment]
> I want to do zookeeper

Thx

**Comment by MulL1on** [comment]
i want to do eureka

**Comment by li-jin-gou** [comment]
> i want to do eureka

thanks

**Comment by li-jin-gou** [comment]
@chaoranz758 any progress ?

**Comment by chaoranz758** [comment]
> @chaoranz758 any progress ?

I will submit soon

**Comment by ViolaPioggia** [comment]
I want to do zookeeper
