### ISSUE TITLE
docs: optimize logger doc

### ISSUE THREAD

**Issue by L2ncE** [cloudwego/hertz#488]
**Is your feature request related to a problem? Please describe.**

No.

**Describe alternatives you've considered**

We need to improve documentation for the [logger](https://github.com/hertz-contrib/logger) now. Could you please help us optimize the doc?

**Tips**

1. You can improve doc in [docs/hertz/tutorials/framework-exten/log.md](https://github.com/cloudwego/cloudwego.github.io/blob/main/content/en/docs/hertz/tutorials/framework-exten/log.md).
2. You can refer to these documents and PR for optimization.

- Doc
    - https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/middleware/keyauth/
    - https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/middleware/jwt/
    - https://www.cloudwego.io/zh/docs/hertz/tutorials/service-governance/service_discovery/

- PR
    - https://github.com/cloudwego/cloudwego.github.io/pull/363
    - https://github.com/cloudwego/cloudwego.github.io/pull/369
    - https://github.com/cloudwego/cloudwego.github.io/pull/389

**Note**

You can first complete the Chinese doc and create PR to review. And then translate to English.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by ViolaPioggia** [comment]
Please assign it to me
