### ISSUE TITLE
using nginx as backend with reverse proxy example h2 or otherwise

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#489]
@Duslia video of problem
https://tempclip.com/en/JVJWcrdlTUmKXRM/watch

using nginx as backend with reverse proxy example
100x multiple reloads for 404 pages
https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-nginx-in-ubuntu-22-04
pls try with nginx as port 88 as in the script below

/etc/nginx/sites-enabled/default
```
server {

        listen 88 ssl http2 default_server;
        listen [::]:88 ssl http2 default_server;

        include snippets/self-signed.conf;
        include snippets/ssl-params.conf;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }

}
```

error message will only show up / appear after 1 minute or more.
```
2022/12/21 08:41:26.277858 client.go:1840: [Info] http2: Transport readFrame error on conn 0xc0001eda00: (*errors.errorString) EOF
2022/12/21 08:41:27.151528 client.go:1840: [Info] http2: Transport readFrame error on conn 0xc000310ea0: (*errors.errorString) EOF
2022/12/21 08:41:27.764772 client.go:1840: [Info] http2: Transport readFrame error on conn 0xc0003111e0: (*errors.errorString) EOF
```

main.go
```
package main

import (
        "context"
        "crypto/tls"
        "fmt"
        "log"
        "time"

        "github.com/cloudwego/hertz/pkg/app"
        "github.com/cloudwego/hertz/pkg/app/client"
        "github.com/cloudwego/hertz/pkg/app/server"
        "github.com/cloudwego/hertz/pkg/network/standard"
        "github.com/hertz-contrib/http2/config"
        "github.com/hertz-contrib/http2/factory"

        "github.com/hertz-contrib/reverseproxy"
)

func main() {

        cfg := &tls.Config{
                MinVersion:       tls.VersionTLS12,
                CurvePreferences: []tls.CurveID{tls.X25519, tls.CurveP256},
                CipherSuites: []uint16{
                        tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
                        tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
                        tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
                },
        }

        cert, err := tls.LoadX509KeyPair("server.crt", "server.key")
        if err != nil {
                fmt.Println(err.Error())
        }
        cfg.Certificates = append(cfg.Certificates, cert)
        h := server.New(server.WithHostPorts(":443"), server.WithALPN(true), server.WithTLS(cfg))

        h.AddProtocol("h2", factory.NewServerFactory(
                config.WithReadTimeout(time.Minute),
                config.WithDisableKeepAlive(false)))
        cfg.NextProtos = append(cfg.NextProtos, "h2")

        h.Use(func(cc context.Context, ctx *app.RequestContext) {
                ProxyHandlerHertz(cc, ctx)
        })
        h.Spin()
}

func ProxyHandlerHertz(cc context.Context, ctx *app.RequestContext) {
        rp, _ := reverseproxy.NewSingleHostReverseProxy("https://127.0.0.1:88/")

        h2client, _ := client.NewClient()
        h2client.SetClientFactory(factory.NewClientFactory(
                config.WithDialer(standard.NewDialer()),
                config.WithTLSConfig(&tls.Config{InsecureSkipVerify: true}),
        ))
        rp.SetClient(h2client)
        log.Printf("\nctx = %s",ctx)
        rp.ServeHTTP(cc, ctx)
}

```

**Comment by Duslia** [comment]
Can you click here? 
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/37136584/209433621-e405291c-bae1-423c-87ca-3c311886782b.png">

**Comment by Duslia** [comment]
Besides, you can add two logs like this 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/37136584/209433870-790f796e-a16d-4007-9fef-d13dfa049b2f.png">
And take a look at the log output when blank pages appear

**Comment by ultperf** [comment]
i've decided to not use reverse proxy feature with nginx as backend now coz of this issue.
i'm writing a custom reverse proxy backend not using http. so maybe i wont test this for now.
however, u shld look into this issue with nginx, it will definitely not work.

if the "github-actions" can extend 1 mth, i will test when i have time and report, else pls help make sure this issue can be resolved.

**Comment by li-jin-gou** [comment]
> @Duslia i've decided to not use reverse proxy feature with nginx as backend now coz of this issue. i'm writing a custom reverse proxy backend not using http. so maybe i wont test this for now. however, u shld look into this issue with nginx, it will definitely not work.
> 
> if the "github-actions" can extend 1 mth, i will test when i have time and report, else pls help make sure this issue can be resolved.

Follow the template of the issue and the issue will be normal.💕

**Comment by Duslia** [comment]
> @Duslia i've decided to not use reverse proxy feature with nginx as backend now coz of this issue. i'm writing a custom reverse proxy backend not using http. so maybe i wont test this for now. however, u shld look into this issue with nginx, it will definitely not work.
> 
> if the "github-actions" can extend 1 mth, i will test when i have time and report, else pls help make sure this issue can be resolved.

I remember that you can copy response to server response instead of reusing it. You can copy the reverse proxy code and copy the response to the server, like this: 
<img width="811" alt="image" src="https://user-images.githubusercontent.com/37136584/209467307-239ddfae-e848-452d-84d4-acb8353211de.png">
<img width="881" alt="image" src="https://user-images.githubusercontent.com/37136584/209467321-408663e0-0568-4a75-a16f-f64b635092a6.png">
I think you can solve this bug by doing this.

**Comment by ultperf** [comment]
@Duslia totally clueless about what u mentioned.

can u just help with adding the code inside here?
i'm too used to fasthttp way so no idea what u mean really.

also, i hope not to do anything that may break upgrade changes.
pls provide the code by expanding below.
i'm sure i wont be the one to ask this question when hertz becomes popular in future.

```
package main

import (
        "context"
        "crypto/tls"
        "fmt"
        "log"
        "time"

        "github.com/cloudwego/hertz/pkg/app"
        "github.com/cloudwego/hertz/pkg/app/client"
        "github.com/cloudwego/hertz/pkg/app/server"
        "github.com/cloudwego/hertz/pkg/network/standard"
        "github.com/hertz-contrib/http2/config"
        "github.com/hertz-contrib/http2/factory"

        "github.com/hertz-contrib/reverseproxy"
)

func main() {

        cfg := &tls.Config{
                MinVersion:       tls.VersionTLS12,
                CurvePreferences: []tls.CurveID{tls.X25519, tls.CurveP256},
                CipherSuites: []uint16{
                        tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
                        tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
                        tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
                },
        }

        cert, err := tls.LoadX509KeyPair("server.crt", "server.key")
        if err != nil {
                fmt.Println(err.Error())
        }
        cfg.Certificates = append(cfg.Certificates, cert)
        h := server.New(server.WithHostPorts(":443"), server.WithALPN(true), server.WithTLS(cfg))

        h.AddProtocol("h2", factory.NewServerFactory(
                config.WithReadTimeout(time.Minute),
                config.WithDisableKeepAlive(false)))
        cfg.NextProtos = append(cfg.NextProtos, "h2")

        h.Use(func(cc context.Context, ctx *app.RequestContext) {
                ProxyHandlerHertz(cc, ctx)
        })
        h.Spin()
}

func ProxyHandlerHertz(cc context.Context, ctx *app.RequestContext) {
        rp, _ := reverseproxy.NewSingleHostReverseProxy("https://127.0.0.1:88/")

        h2client, _ := client.NewClient()
        h2client.SetClientFactory(factory.NewClientFactory(
                config.WithDialer(standard.NewDialer()),
                config.WithTLSConfig(&tls.Config{InsecureSkipVerify: true}),
        ))
        rp.SetClient(h2client)
        log.Printf("\nctx = %s",ctx)
        rp.ServeHTTP(cc, ctx)
}
```

**Comment by ultperf** [comment]
@Duslia can u help this out? i'm curious what's the best way to do this... seems there will be memory copying.
pls provide the code just to verify if it will work according to what u mean.

**Comment by Duslia** [comment]
No. I wouldn't help you write the code.
