### ISSUE TITLE
[docs]: translate hertz/tutorials/basic-feature/network-lib

### ISSUE THREAD

**Issue by GuangmingLuo** [cloudwego/hertz#49]
zh web page：https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/network-lib/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/basic-feature/network-lib.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials/basic-feature

Notes: 
1. Do not change the original layout, code style or content sequence.
2. Software Translator is a tool, not god, do not use the result as the final result.
3. Translation principle: faithfulness, expressiveness and elegance.
4. Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by li-jin-gou** [comment]
I'd like to translate it  :smirk: @GuangmingLuo

**Comment by holdonbush** [comment]
Hi, I want to try this, thank you

**Comment by holdonbush** [comment]
@GuangmingLuo @li-jin-gou hello, I have submitted a pull request at [repo](https://github.com/cloudwego/cloudwego.github.io/pull/208), hope you can review the translation, thanks
