### ISSUE TITLE
How to do packet encryption and decryption

### ISSUE THREAD

**Issue by timandy** [cloudwego/hertz#491]
**Describe the Question**

I do the work of requesting packet decryption and responding to packet encryption.
so I need to intercept the packet content of Request and Response, perform decryption or encryption, and replace the original packet with decryption or encryption, so as `not to affect the normal Bind and Render`.

1. Request decryption: I can request decryption through `c.SetBodyStream(WrapRequestReader(io. NopCloser(c.RequestBodyStream())), -1)` replaces the request stream.

2. Response encryption: But I didn't find a way to `replace the response stream`, I need your help.

**Reproducible Code**

Please construct a minimum complete and reproducible example for us to get the same error. And tell us how to reproduce it like how you send a request or send what request.

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your question.

**Hertz version:**

Please provide the version of Hertz you are using.

**Environment:**

The output of `go env`.

**Additional context**

Add any other context about the question here.

**Comment by li-jin-gou** [comment]
- request :  c.RequestBodyStream()
- response:  c.SetBodyStream(reader, size)

**Comment by timandy** [comment]
@li-jin-gou   Maybe I didn't make it clear. Theoretically, the reader cannot intercept the written content and convert it into an encrypted stream, which should be the responsibility of a writer. I wrote an example, the transformation of the request stream has been completed, can you help me implement the transformation of the response stream?
[herz-demo.zip](https://github.com/cloudwego/hertz/files/10305405/herz-demo.zip)

**Comment by li-jin-gou** [comment]
``` go
// SetBodyStream sets response body stream and, optionally body size.
//
// bodyStream.Close() is called after finishing reading all body data
// if it implements io.Closer.
//
// If bodySize is >= 0, then bodySize bytes must be provided by bodyStream
// before returning io.EOF.
//
// If bodySize < 0, then bodyStream is read until io.EOF.
//
// See also SetBodyStreamWriter.
func (ctx *RequestContext) SetBodyStream(bodyStream io.Reader, bodySize int) {
	ctx.Response.SetBodyStream(bodyStream, bodySize)
}
```

SetBodyStream is used to set the stream of the response instead of the request.

**Comment by timandy** [comment]
> c.SetBodyStream is used to set the stream of the response instead of the request.
> 
> c.RequestBodyStream is used to get the steam of the request and will return reader.

@li-jin-gou  I know that. You can download my example. Sorry to bother you.

**Comment by li-jin-gou** [comment]
> > c.SetBodyStream is used to set the stream of the response instead of the request.
> > c.RequestBodyStream is used to get the steam of the request and will return reader.
> 
> @li-jin-gou I know that. You can download my example. Sorry to bother you.

why not use `ctx.SetBodyStream()` to set response stream???

```go
func StreamHandler(c context.Context, ctx *app.RequestContext) {
	requestStream := WrapRequest(ctx.RequestBodyStream())
	ctx.Request.SetBodyStream(requestStream, -1)
	println(string(requestStream.Body()))
	ctx.Next(c)
	//TODO println response content

}
```

**Comment by timandy** [comment]
> why not use ctx.SetBodyStream() to set response stream???

Yes, I want to use ctx.SetBodyStream(), but how to get the original response stream? You know encrypt need `original stream` -> `encrypt` -> `set response stream`.

**Comment by li-jin-gou** [comment]
> > why not use ctx.SetBodyStream() to set response stream???
> 
> Yes, I want to use ctx.SetBodyStream(), but how to get the original response stream? You know encrypt need `original stream` -> `encrypt` -> `set response stream`.

use `ctx.Response.BodyStream`

**Comment by timandy** [comment]
```go
func StreamHandler(c context.Context, ctx *app.RequestContext) {
	requestStream := WrapReader(ctx.RequestBodyStream())
	ctx.Request.SetBodyStream(requestStream, -1)
	println(string(requestStream.Body()))
	ctx.Next(c)
	responseStream := WrapReader(ctx.Response.BodyStream()) //Body stream is nil
	ctx.SetBodyStream(responseStream, -1)
	println(string(responseStream.Body()))
}
```
Can not use use ctx.Response.BodyStream get the response body, it is nil.

**Comment by li-jin-gou** [comment]
When we use streaming we need to set the stream in the business handler now and then we use `ctx.Response.BodyStream()` to get it, otherwise we need to use c.Response.Body() to get the data.

**Comment by li-jin-gou** [comment]
This is actually a similar implementation to the Gzip extension.  https://github.com/hertz-contrib/gzip/blob/main/handler.go#L72

**Comment by timandy** [comment]
If response body is a large file, does c.Response.Body() will alloc large size of memory?

**Comment by li-jin-gou** [comment]
> If response body is a large file, does c.Response.Body() will alloc large size of memory?

No and When we use streaming we need to set the stream in the business handler now and then we use ctx.Response.BodyStream() to get it in middleware.

**Comment by timandy** [comment]
We do not want to change the business code, so set response stream in business code can't meet our requirements.

I test with a large file, c.Response.Body() will alloc about 4*FILE_SIZE memory. Actually what we need is a Writer,  through Write() method, we can cache `part` of response body.

**Comment by li-jin-gou** [comment]
> We do not want to change the business code, so set response stream in business code can't meet our requirements.
> 
> I test with a large file, c.Response.Body() will alloc about 4*FILE_SIZE memory. Actually what we need is a Writer, through Write() method, we can cache `part` of response body.
> 
> We used gin before. We can use wrap c.Writer to implement this logic.

Unfortunately hertz is not the same as gin, and the usage of Hertz streaming responses can be found at https://github.com/cloudwego/hertz-examples/tree/main/streaming.

**Comment by li-jin-gou** [comment]
cc @Duslia @FGYFFFF

**Comment by timandy** [comment]
@li-jin-gou Thanks for your answer. I hope hertz support response writer. thanks again.

**Comment by Duslia** [comment]
The response bodystream is you set in the business handler. Have you set it in the business handler? 
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/37136584/209635084-1fe92b27-086d-4ca2-9ff0-e401f4502802.png">

**Comment by Duslia** [comment]
If you use `ctx.Json` to write response, all data still will be in memory. So I recommend you use `ctx.SetBodyStream` to set response. Besides, if you don't want to change the code, you can wrap response body to a reader like:
```
r := bytes.NewReader(ctx.Response.Body())
ctx.SetBodyStream(r, -1)
```

**Comment by timandy** [comment]
This is the new version demo code.
[herz-demo.zip](https://github.com/cloudwego/hertz/files/10306959/herz-demo.zip)

**Comment by Duslia** [comment]
> We do not want to change the business code, so set response stream in business code can't meet our requirements.
> 
> I test with a large file, c.Response.Body() will alloc about 4*FILE_SIZE memory. Actually what we need is a Writer, through Write() method, we can cache `part` of response body.
> 
> We used gin before. We can use wrap c.Writer to implement this logic.

I recommend you to set file reader to hertz directly. Otherwise, it has OOM risk.

**Comment by Duslia** [comment]
> This is the new version demo code. [herz-demo.zip](https://github.com/cloudwego/hertz/files/10306959/herz-demo.zip)

Sry. I forget that the `ctx.Response.Body()` will be recycled when you set response body stream. If you use this feature, you need to first copy `ctx.Response.Body()`
