### ISSUE TITLE
希望可以支持服务过载检测和限流相关算法

### ISSUE THREAD

**Issue by gdis5251** [cloudwego/hertz#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LhdDream** [comment]
可以提供自适应限流算法，可以对于CPU的负载情况，接口耗时及当前的QPS来进行实现。

**Comment by Duslia** [comment]
Related PR https://github.com/hertz-contrib/limiter/pull/1
