### ISSUE TITLE
[QUESTION] - What is the better way to use gookit/validate with hertz request?

### ISSUE THREAD

**Issue by sujit-baniya** [cloudwego/hertz#503]
**Describe the Question**

I'm trying to use https://github.com/gookit/validate to validate the incoming requests be it form, json or any content type. To create validator object, one approach I found is to use `context.Request.Body()` and use it with function `validate.FromJSONBytes()`

**Reproducible Code**

```go
dataFace, err := validate.FromJSONBytes(ctx.Request.Body())
```

**Expected behavior**

This approach is only valid for json body. I wanted to validate other content-type too like form-data or multi-part.
Please suggest better idea to validate the request.

**Comment by welkeyever** [comment]
validate relevant cc @FGYFFFF

**Comment by FGYFFFF** [comment]
I learned about the use of "https://github.com/gookit/validate", if you want to get a checker by "FromXXX", then you need to pass in the corresponding data sources, which you need to get yourself.
For example
```
	h.POST("/hello", func(c context.Context, ctx *app.RequestContext) {
		h, _  := adaptor.GetCompatRequest(&ctx.Request)
		data, err := validate.FromRequest(h)
		if err != nil {
			panic(err)
		}

		v := data.Create()
		// setting rules
		v.FilterRule("age", "int") // convert value to int

		v.AddRule("name", "required")
		v.AddRule("name", "minLen", 7)
		v.AddRule("age", "max", 99)

		if v.Validate() { // validate ok
			// do something ...
		} else {
			fmt.Println(v.Errors)       // all error messages
			fmt.Println(v.Errors.One()) // returns a random error message text
		}
	})
```
But I would rather recommend you to use the parameter binding and validation method that comes with hertz, it is more convenient and powerful.（https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/binding-and-validate/#supported-tags）
In addition, hertz has recently considered refactoring the parameter binding and validating and will provide a pluggable validator.

**Comment by sujit-baniya** [comment]
Thanks, it works
