### ISSUE TITLE
need ETag / If-None-Match

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#504]
@li-jin-gou @Duslia 

pls help! tested hertz a long time to realise this is missing. need for caching purposes

**Is your feature request related to a problem? Please describe.**
missing ETag / If-None-Match

**Describe the solution you'd like**
 ETag / If-None-Match
 
**Describe alternatives you've considered**

no compromise

**Additional context**

missing ETag / If-None-Match

**Comment by ultperf** [comment]
@li-jin-gou possible to get this done in 30 mins? i can test fully the migration from fasthttp to hertz and give some feedback after running in production

**Comment by li-jin-gou** [comment]
If you need it urgently you can implement an Etag middleware yourself.

**Comment by ultperf** [comment]
gimme a clue where to copy from fasthttp and which file to add in?

**Comment by ultperf** [comment]
@li-jin-gou i checked. do u think etag shld be implemented as middleware?

**Comment by li-jin-gou** [comment]
refer to https://github.com/gofiber/fiber/issues/1284

**Comment by ultperf** [comment]
@li-jin-gou yes u are right, it shld be done as a middleware. my bad. thx

**Comment by li-jin-gou** [comment]
re-open and we will plan later to add etag's middleware.
