### ISSUE TITLE
shldnt if-none-match be a standard header in ./pkg/protocol/consts/headers.go?

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#505]
shldnt if-none-match be a standard header in 
./pkg/protocol/consts/headers.go

in fasthttp
```
./headers.go:33:	HeaderIfNoneMatch       = "If-None-Match"
```

**Comment by Duslia** [comment]
Please explain the necessity of it.

**Comment by ultperf** [comment]
@Duslia, i missed something that didnt show "if none match". it's showing now. thx
