### ISSUE TITLE
basic auth middleware example in cloudwego.io is not working

### ISSUE THREAD

**Issue by lgbgbl** [cloudwego/hertz#51]
**Describe the bug**

basic-auth middleware [example](https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/middleware/basic-auth/) in cloudwego.io is not working.

When I tried to build for it, an error occured.
```
main.go:7:2: no required module provides package github.com/cloudwego/hertz/pkg/app/middlewares/basic_auth; to add it:
        go get github.com/cloudwego/hertz/pkg/app/middlewares/basic_auth
```

Then I found that required module should be `github.com/cloudwego/hertz/pkg/app/middlewares/server/basic_auth` instead of `github.com/cloudwego/hertz/pkg/app/middlewares/basic_auth`.

However, compile failed again when I solved the problem above.
```
# command-line-arguments
./main.go:29:23: undefined: basic_auth.AuthUserKey
```

`AuthUserKey` is not defined in package `github.com/cloudwego/hertz/pkg/app/middlewares/server/basic_auth`.

**Comment by Duslia** [comment]
Ok, I will fix it. You can refer to hertz-examples: https://github.com/cloudwego/hertz-examples/blob/main/middleware/basicauth/main.go
