### ISSUE TITLE
2023/01/07 16:53:23.298957 engine.go:451: [Error] HERTZ: Error=tls: client offered only unsupported versions: [], 

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#519]
**Describe the bug**

how to mute this bug or a way to handle it "properly"?

```
2023/01/07 16:53:23.298957 engine.go:451: [Error] HERTZ: Error=tls: client offered only unsupported versions: [], remoteAddr=162.243.136.24:37490
```

**Comment by li-jin-gou** [comment]
can you provide a demo code to show it?

**Comment by ultperf** [comment]
@li-jin-gou using the h2

```
			h := server.New(
				server.WithHostPorts(":443"),
				server.WithALPN(true),
				server.WithTLS(tlsCfg),
				server.WithListenConfig(&net.ListenConfig{
					Control: func(network, address string, c syscall.RawConn) error {
						return c.Control(func(fd uintptr) {
							syscall.SetsockoptInt(int(fd), syscall.SOL_SOCKET, unix.SO_REUSEPORT, 1)
						})
					},
				}),
			)

			h.AddProtocol("h2", factory.NewServerFactory(
				config.WithReadTimeout(45*time.Second),
				config.WithDisableKeepAlive(false)))

			tlsCfg.NextProtos = append(tlsCfg.NextProtos, "h2")

			h.Use(func(cc context.Context, ctx *app.RequestContext) {
				ProxyHandlerHertz(cc, ctx)
			})

			h.Spin()
```
2023/01/08 08:19:29.234654 server.go:1546: [Error] HERTZ: HTTP2 received GOAWAY [FrameHeader GOAWAY len=8], starting graceful shutdown
2023/01/08 09:04:40.919965 engine.go:451: [Error] HERTZ: Error=tls: client offered only unsupported versions: [], remoteAddr=184.105.247.252:52588
2023/01/08 09:05:48.603734 engine.go:451: [Error] HERTZ: Error=tls: no cipher suite supported by both client and server, remoteAddr=184.105.247.252:40950
2023/01/08 09:08:43.619383 engine.go:451: [Error] HERTZ: Error=tls: client requested unsupported application protocols ([http/0.9 http/1.0 spdy/1 spdy/2 spdy/3 h2c hq]), remoteAddr=184.105.247.252:64412
2023/01/08 09:08:43.751116 engine.go:451: [Error] HERTZ: Error=tls: client requested unsupported application protocols ([hq h2c spdy/3 spdy/2 spdy/1 http/1.0 http/0.9]), remoteAddr=184.105.247.252:64420
2023/01/08 09:08:43.883860 engine.go:451: [Error] HERTZ: Error=tls: client offered only unsupported versions: [302 301], remoteAddr=184.105.247.252:43152
2023/01/08 09:08:44.085894 engine.go:451: [Error] HERTZ: Error=read tcp 15.235.41.171:443->184.105.247.252:43168: read: connection reset by peer, remoteAddr=184.105.247.252:43168
```

**Comment by ultperf** [comment]
@li-jin-gou @Duslia the error messages are annoying and should be "ctx.Hijack" for more user control.

being ran in production services now but with these errors it's easy to DDoS and slow down the system considerably with 
log printouts. pls look into this together with fastest way to drop ip as previously mentioned.
https://github.com/cloudwego/hertz/pull/514
thx

**Comment by Duslia** [comment]
This is you because you didn't configure tls.Config correctly. Please search in google.
