### ISSUE TITLE
ctx.Response.Header.Set("Content-Encoding","gzip") not showing in browser?

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#526]
**Describe the bug**
ctx.Response.Header.Set("Content-Encoding","gzip") not showing in browser?

i shld not need to specifically use h.SetContentEncodingBytes(value) right?

basically i am saying the line below doesnt work.
./pkg/protocol/request_test.go:304:	r.Header.Set("Content-Encoding", "gzip")

**To Reproduce**
```
  reqHeaders = append(reqHeaders, "Content-Encoding")
  reqHeaders = append(reqHeaders, "gzip") //try br too?

  for i := 0; i < len(reqHeaders); i = i + 2 {
    ctx.Response.Header.Set(reqHeaders[i], reqHeaders[i+1])
    log.Printf("Appears Content-Encoding not set?! = %s = %s", reqHeaders[i], reqHeaders[i+1]) 
    //set above but not appear in browser?! for "Content-Encoding"
  }
```

**Expected behavior**

shld be shown in browser

Content-Encoding: gzip 

**Hertz version:**
0.5.0

**Comment by wang-tsh** [comment]
maybe you can use
`	rh := ResponseHeader{}
	rh.SetContentEncoding("gzip")
	assert.DeepEqual(t, rh.contentEncoding, []byte("gzip"))
`

**Comment by ultperf** [comment]
@li-jin-gou i'm using h2 so means i can use brotli also. 
i got my responsed from "client" results with fasthttp.

[user] -> [hertz (using h2)] -> [fasthttp] -> [actual server]

from fasthttp, i used the values below to do response.header.set
```
  for i := 0; i < len(reqHeaders); i = i + 2 {
    ctx.Response.Header.Set(reqHeaders[i], reqHeaders[i+1])
  }
  ctx.Response.Header.SetContentEncoding("gzip")
```

no matter what i do, it's not showing "Content-Encoding" in browser

@Duslia how do i "reset" my hertz repo? already did go clean -modcache

can u help verify why Content-Encoding is never showing up? i've done both set and setcontentencoding 

```
2023/01/10 08:50:31 respheaderfirst pass SERV = Content-Type = text/html; charset=UTF-8
2023/01/10 08:50:31 respheaderfirst pass SERV = Content-Encoding = gzip
2023/01/10 08:50:31 respheaderfirst pass SERV = Server = nginx
2023/01/10 08:50:31 respheaderfirst pass SERV = Date = Tue, 10 Jan 2023 08:50:31 GMT
2023/01/10 08:50:31 respheaderfirst pass SERV = Transfer-Encoding = chunked
2023/01/10 08:50:31 respheaderfirst pass SERV = Connection = keep-alive
2023/01/10 08:50:31 respheaderfirst pass SERV = Link = <https://example.com/wp-json/>; rel="https://api.w.org/"
2023/01/10 08:50:31 respheaderfirst pass SERV = Link = <https://example.com/wp-json/wp/v2/pages/5>; rel="alternate"; type="application/json"
2023/01/10 08:50:31 respheaderfirst pass SERV = Link = <https://example.com/>; rel=shortlink
2023/01/10 08:50:31 respheaderfirst pass SERV = Vary = Accept-Encoding
2023/01/10 08:50:31 respheaderfirst pass SERV = X-Content-Type-Options = nosniff
2023/01/10 08:50:31 respheaderfirst pass SERV = X-Xss-Protection = 1; mode=block
```

**Comment by li-jin-gou** [comment]
> @li-jin-gou i'm using h2 so means i can use brotli also but this is not related to br or h2 i think. because i specified gzip ... not sure if it's related to h2 i got my response from "client" results with fasthttp.
> 
> [user] -> [hertz (using h2)] -> [fasthttp] -> [actual server]
> 
> from fasthttp, i used the values below to do response.header.set
> 
> ```
>   for i := 0; i < len(reqHeaders); i = i + 2 {
>     ctx.Response.Header.Set(reqHeaders[i], reqHeaders[i+1])
>   }
>   ctx.Response.Header.SetContentEncoding("gzip")
> ```
> 
> no matter what i do, it's not showing "Content-Encoding" in browser
> 
> @Duslia how do i "reset" my hertz repo? already did go clean -modcache
> 
> can u help verify why Content-Encoding is never showing up? i've done both set and setcontentencoding
> 
> ```
> 2023/01/10 08:50:31 respheaderfirst pass SERV = Content-Type = text/html; charset=UTF-8
> 2023/01/10 08:50:31 respheaderfirst pass SERV = Content-Encoding = gzip
> 2023/01/10 08:50:31 respheaderfirst pass SERV = Server = nginx
> 2023/01/10 08:50:31 respheaderfirst pass SERV = Date = Tue, 10 Jan 2023 08:50:31 GMT
> 2023/01/10 08:50:31 respheaderfirst pass SERV = Transfer-Encoding = chunked
> 2023/01/10 08:50:31 respheaderfirst pass SERV = Connection = keep-alive
> 2023/01/10 08:50:31 respheaderfirst pass SERV = Link = <https://example.com/wp-json/>; rel="https://api.w.org/"
> 2023/01/10 08:50:31 respheaderfirst pass SERV = Link = <https://example.com/wp-json/wp/v2/pages/5>; rel="alternate"; type="application/json"
> 2023/01/10 08:50:31 respheaderfirst pass SERV = Link = <https://example.com/>; rel=shortlink
> 2023/01/10 08:50:31 respheaderfirst pass SERV = Vary = Accept-Encoding
> 2023/01/10 08:50:31 respheaderfirst pass SERV = X-Content-Type-Options = nosniff
> 2023/01/10 08:50:31 respheaderfirst pass SERV = X-Xss-Protection = 1; mode=block
> ```

Sorry, I don't know much about H2 and my code is for H1。

**Comment by li-jin-gou** [comment]
cc @Duslia

**Comment by li-jin-gou** [comment]
cc @Duslia

**Comment by ultperf** [comment]
@li-jin-gou @Duslia closing this and taking the issue with updated detailed information.

pls help coz this is a serious issue which made me use fasthttp as intermediary instead of hertz.
i did it this way
[user] -> [hertz (using h2)] -> [fasthttp] -> [actual server]

coz i thought was my problem but now i found out it's h2 hertz issue
