### ISSUE TITLE
unable to delete "server" response header

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#528]
unable to delete "server" response header
these two not working. maybe i tested too many different repo etc BUT i've already removed go.mod and go.sum and did "go mod tidy" still i cant seem to setcontentencoding and also cant delete server header. why?

or because it's the latest 0.5.0? can help verify? thx in advance.

for the chrome browser output i get

server

```
   ctx.Response.Header.Del("Server")
   ctx.Response.Header.SetContentEncodingBytes([]byte("gzip"))

```

**Comment by li-jin-gou** [comment]
it's ok  but  why not use valid formats and provide a base code...
![image](https://user-images.githubusercontent.com/97824201/211455940-3e22e712-ca5e-4888-acbb-20559f081eb1.png)
