### ISSUE TITLE
hz 命令接口的讨论

### ISSUE THREAD

**Issue by errocks** [cloudwego/hertz#529]
**Describe the Question**

主要是一个demo代码里, 直接make了一下, 导致当前的代码, go.mod出现了奇怪的修改, 感觉到对普通用户应该是一个不太友好的体验
所以想提个issue讨论一下

**Reproducible Code**
```
Makefile

init_api:
	hz new -I idl -idl idl/user/user.proto -module github.com/cloudwego/hertz-examples/bizdemo/hertz_gorm_gen
update_api:
	hz update -I idl -idl idl/user/user.proto
```
在已生成的代码里 直接make一下

**Expected behavior**
这里想讨论一下目前hz命令的语义
```
NAME:
   hz - A idl parser and code generator for Hertz projects

USAGE:
   hz [global options] command [command options] [arguments...]

VERSION:
   v0.5.0
COMMANDS:
   new      Generate a new Hertz project
   update   Update an existing Hertz project
   model    Generate model code only
   client   Generate hertz client based on IDL
   help, h  Shows a list of commands or help for one command
```
1. 个人认为new如果是代表创建的意思, 那创建结束了, 不是太应该允许运行重复执行new, 只能update
2. new project 跟 new project code 觉得也分开一下比较合理 
``` 
     hz api all
     hz api model
     hz api middleware
     hz api route
     hz project new
     hz project update
```
我的guan观点是: 像官网demo的Makefile, 都是init_api ==> hz new 这说明其实hz接口定义比较容易造成混淆

**Screenshots**
<img width="880" alt="image" src="https://user-images.githubusercontent.com/18068311/211592300-2fab79be-adfe-4241-94ea-e9e8ece5d9d6.png">

<img width="627" alt="image" src="https://user-images.githubusercontent.com/18068311/211592242-ff9086b6-8d5d-464f-8e46-1db016bc5385.png">

<img width="970" alt="image" src="https://user-images.githubusercontent.com/18068311/211591736-b160dcfe-c7bf-4c83-a269-260112a84702.png">

**Hertz version:**

Please provide the version of Hertz you are using.

**Environment:**

**Additional context**

**Comment by li-jin-gou** [comment]
@L2ncE  Is there have time to  support for refining the `makefile` for hertz's biz-demo?❤️

**Comment by li-jin-gou** [comment]
- Regarding the optimization of the New command, we should add a prompt to indicate if we need to override and improve the documentation as well as the command prompt.
- I don't know the difference between project and project code, so I'm not sure what the advantages of separating it are. and i  think providing too many commands can lead to a burden for users to use, and there will always be people saying "there are so many commands provided, it's so complicated".

Can you explain the difference between project and project code? @errocks

**Comment by errocks** [comment]
项目模板个人觉得应该是模块的划分比如service, model, 目录结构等, 项目代码的话, 应该是对外api接口决定, hz model比较接近吧但是又只是生成model目录的代码而已, 少了service跟route的处理
一般人会跟那个demo一样, 把初始化项目跟初始化code等同了. init api跟new project 怎么看都不能等价吧
项目应该跟type struct 定义一样, 项目代码应该只是把 这个struct初始化了, 

或者建议new project 的时候可以有默认的project.protobuf的定义暴露出来, 这样用户去new完一个project也不用自己再去官网copy api.protobuf过来, 然后自己创建一个user.protubuf, 这样可能大家不会联想到代码还需要初始化. 然后 hz update一下把整个project的该生成的代码生成一下, 不过目前测试 new 或者update 都是只支持指定idl
```
	hz new -I idl -idl idl/user/user.proto -module github.com/cloudwego/hertz-examples/bizdemo/hertz_gorm_gen
// 这参数也不少了
```
约定优于配置, 我觉得一个默认的project.protobuf也是可以的, 以后我们就直接hz update 就可以了, 把idl目录下 ,需要处理的*.protobuf 都处理一下

尽量不要增加用户思考的设计, 使用体验会更好

尽可能少点命令是对的, 但是清晰才是目的

个人还是觉得new 跟update做的事情太多了, `少即是多`的原则, 这里的`少`不是数量少, 是尽可能简洁

**Comment by errocks** [comment]
而且demo的代码已经证明是有部分用户会混淆了

**Comment by errocks** [comment]
另外个人觉得Makefile应该是框架应该做的事情, 不应该是demo去做

**Comment by li-jin-gou** [comment]
> 项目模板个人觉得应该是模块的划分比如service, model, 目录结构等, 项目代码的话, 应该是对外api接口决定, hz model比较接近吧但是又只是生成model目录的代码而已, 少了service跟route的处理 一般人会跟那个demo一样, 把初始化项目跟初始化code等同了. init api跟new project 怎么看都不能等价吧 项目应该跟type struct 定义一样, 项目代码应该只是把 这个struct初始化了,
> 
> 或者建议new project 的时候可以有默认的project.protobuf的定义暴露出来, 这样用户去new完一个project也不用自己再去官网copy api.protobuf过来, 然后自己创建一个user.protubuf, 这样可能大家不会联想到代码还需要初始化. 然后 hz update一下把整个project的该生成的代码生成一下, 不过目前测试 new 或者update 都是只支持指定idl
> 
> ```
> 	hz new -I idl -idl idl/user/user.proto -module github.com/cloudwego/hertz-examples/bizdemo/hertz_gorm_gen
> // 这参数也不少了
> ```
> 
> 约定优于配置, 我觉得一个默认的project.protobuf也是可以的, 以后我们就直接hz update 就可以了, 把idl目录下 ,需要处理的*.protobuf 都处理一下
> 
> 尽量不要增加用户思考的设计, 使用体验会更好
> 
> 尽可能少点命令是对的, 但是清晰才是目的
> 
> 个人还是觉得new 跟update做的事情太多了, `少即是多`的原则, 这里的`少`不是数量少, 是尽可能简洁

cc @FGYFFFF

**Comment by FGYFFFF** [comment]
> 或者建议new project 的时候可以有默认的project.protobuf的定义暴露出来, 这样用户去new完一个project也不用自己再去官网copy api.protobuf过来, 然后自己创建一个user.protubuf, 这样可能大家不会联想到代码还需要初始化. 然后 hz update一下把整个project的该生成的代码生成一下, 不过目前测试 new 或者update 都是只支持指定idl
> 
> ```
> 	hz new -I idl -idl idl/user/user.proto -module github.com/cloudwego/hertz-examples/bizdemo/hertz_gorm_gen
> // 这参数也不少了
> ```
> 
> 约定优于配置, 我觉得一个默认的project.protobuf也是可以的, 以后我们就直接hz update 就可以了, 把idl目录下 ,需要处理的*.protobuf 都处理一下
> 
> 尽量不要增加用户思考的设计, 使用体验会更好
> 
> 尽可能少点命令是对的, 但是清晰才是目的
> 
> 个人还是觉得new 跟update做的事情太多了, `少即是多`

我感觉这个想法不错，可以把生成的代码都拆开，然后按照用户的想法来拼接，这个我来尝试分解一下~~~

**Comment by tzq0301** [comment]
借楼提个问，其实第一次用 hz 的时候就很好奇，如果在一个运行过 hz new 的项目下再运行一次的话，hz 内部会进行什么判断吗，还是直接重新运行一次 hz new 的逻辑呢

I would like to ask a question, in fact, the first time I used hz, I was curious, if you run it again under a project that has run hz new, what judgment will hz make internally, or will it just run the logic of hz new again?

**Comment by StellarisW** [comment]
> 借楼提个问，其实第一次用 hz 的时候就很好奇，如果在一个运行过 hz new 的项目下再运行一次的话，hz 内部会进行什么判断吗，还是直接重新运行一次 hz new 的逻辑呢
> 
> I would like to ask a question, in fact, the first time I used hz, I was curious, if you run it again under a project that has run hz new, what judgment will hz make internally, or will it just run the logic of hz new again?
源码见 [app.go](https://github.com/cloudwego/hertz/blob/develop/cmd/hz/app/app.go)

再次运行`new`命令的话会覆盖原有文件，
如果想要智能一点的命令的话，推荐使用 [cwgo](https://github.com/cloudwego/cwgo)，cwgo可以自动判断执行 `new`/`update`命令，不过 **cwgo** 最近才开始开发，还有许多优化的点存在，目前还在慢慢打磨
