### ISSUE TITLE
hertz v0.5.0 Windows support is broken

### ISSUE THREAD

**Issue by CAMB-dev** [cloudwego/hertz#532]
**Describe the bug**

**To Reproduce**

go install github.com/cloudwego/hertz/cmd/hz@latest
hz new -module test
go mod tidy
go run .

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/64261617/211741520-3dfa3b58-64c3-40bd-9493-0b29de6e9c71.png)

**Hertz version:**

Hertz v0.5.0

**Environment:**

C:\Users\CAMB>go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\CAMB\AppData\Local\go-build
set GOENV=C:\Users\CAMB\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\CAMB\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\CAMB\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\CAMB\AppData\Local\Temp\go-build1535105355=/tmp/go-build -gno-record-gcc-switches

**Additional context**

I will make a PR later

**Comment by ExerciseBook** [comment]
你不是已经知道为啥了吗？怎么不写原因。

**Comment by CAMB-dev** [comment]
> 

那我改下（

**Comment by nicognaW** [comment]
This issue is related to #412, where the new error conversion logic didn't consider a non-Unix environment.

**Comment by li-jin-gou** [comment]
我们修复一下，感谢反馈。

**Comment by lianhongrui** [comment]
@li-jin-gou 我和 @welkeyever 发私聊了，回头由 @CAMB-dev 发起 PR
https://github.com/cloudwego/hertz/blob/df408af00bfd86db6f967a0c776237d7a3648175/pkg/network/standard/connection.go#L29

**Comment by ExerciseBook** [comment]
@li-jin-gou 我和 @welkeyever 发私聊了，回头由 @CAMB-dev 发起 PR
https://github.com/cloudwego/hertz/blob/df408af00bfd86db6f967a0c776237d7a3648175/pkg/network/standard/connection.go#L29

**Comment by li-jin-gou** [comment]
OK
