### ISSUE TITLE
How to determine whether "bool" is defined ?

### ISSUE THREAD

**Issue by xiaogu-space** [cloudwego/hertz#537]
**Describe the Question**

I want to determine whether "bool" is defined.

**Reproducible Code**
```
IsVisible bool    `json:"isVisible" vd:"$!nil"`
```
**Expected behavior**

But I get the error "validating"

**Hertz version:**

v0.4.2

**Environment:**

go 1.19

**Comment by FGYFFFF** [comment]
Can you describe your problem specifically?

**Comment by xiaogu-space** [comment]
> Can you describe your problem specifically?

the struct like this
```
type columnOrderVisible struct {
	ColumnId  string  `json:"columnId" vd:"$!nil"`
	Order     float64 `json:"order" vd:"$!nil"`
	IsVisible bool    `json:"isVisible"`
}
```
if the json
```
        {
            "order": 5,
            "columnId": "37ce69d4-9608-4ad0-8ee2-1b269107f2c2"
        }
```
the "isVisible" must be defined.how to set vd if the type is bool.

**Comment by li-jin-gou** [comment]
use ` $!= nil ` ?

**Comment by xiaogu-space** [comment]
> use `$!= nil` ?

but have no effect

**Comment by FGYFFFF** [comment]
```
type columnOrderVisible struct {
	ColumnId  *string  `json:"columnId" vd:"$!=nil"`
	Order     *float64 `json:"order" vd:"$!=nil"`
	IsVisible *bool    `json:"isVisible"`
}
```
The type of the field of the struct needs to be a pointer，you can try it like above

**Comment by xiaogu-space** [comment]
> vd:"$!=nil"

That's very good

**Comment by xiaogu-space** [comment]
> ```
> type columnOrderVisible struct {
> 	ColumnId  *string  `json:"columnId" vd:"$!=nil"`
> 	Order     *float64 `json:"order" vd:"$!=nil"`
> 	IsVisible *bool    `json:"isVisible"`
> }
> ```
> 
> The type of the field of the struct needs to be a pointer，you can try it like above

That's very good
