### ISSUE TITLE
Proposal(hz): Add configuration for modifying the layout structure provided by `hz` by default

### ISSUE THREAD

**Issue by Skyenought** [cloudwego/hertz#540]
**Is your feature request related to a problem? Please describe.**

zh: **hz** 默认提供的 layout 过于固定,不便于实际的运用:
例如默认的 layout 无法通过 internal 目录使 biz 目录不对外暴露

en: The default layout provided by **hz** is too fixed for practical use:
For example, the default layout cannot keep the biz directory from being exposed through the `internal` directory

**Describe the solution you'd like**

zh: 在 hz 自定义模板中的 json 配置文件中添加字段用于修改默认layout
en:  Add fields to the json in the hz custom template to modify the default layout

**Describe alternatives you've considered**

```json
{
  "*": {
    "GoModule": "github.com/hertz/hello",
    "ServiceName": "hello",
    "UseApacheThrift": true
  },
  "main.go": {
    "MainData": "this is customized render data"
  },
  "biz": {
    // 一个建议, 可以通过 Alias 将目录或文件改名
    "Alias": "business", 
    // 用于替换默认的路径
    "CustomPath": "internal/business"
  }
}

```

**Comment by li-jin-gou** [comment]
> 直接中文了

这个提议是为了要解决 Biz 目录固定的问题还是什么问题？layout 目前的确只能固定就是这个 `biz` 了，我们有计划想改变这个情况。cc @FGYFFFF

**Comment by Skyenought** [comment]
我的意思是可以通过配置来修改生成文件的位置

**Comment by FGYFFFF** [comment]
hz 生成的代码只有 "biz/router" 是固定的，这个因为是存储状态的，在 update 场景需要固定。我们最近在考虑加入存储生成代码meta的设计

**Comment by li-jin-gou** [comment]
> 我的意思是可以通过配置来修改生成文件的位置

如果是这个意思的话模版目前是支持配置文件路径的吧，cwgo 的layout也是这样指定生成代码的位置，但是 biz/route 这个是固定的

**Comment by Skyenought** [comment]
Can a command line argument be provided to choose between generating biz or internal/biz?

是否可以提供一个命令行参数，以选择生成 biz 还是 internal/biz？

**Comment by FGYFFFF** [comment]
下个版本会增加一个 "router_dir"，使用如下：
`hz new --handler_dir=cmd/api/handler --router_dir=cmd/api/router --model_dir=cmd/api/mdoel --idl=/Users/bytedance/go/src/idl_demo/thrift/psm.thrift`
会生成如下内容:
```
.
├── build.sh
├── cmd
│   └── api
│       ├── handler
│       │   ├── ping.go
│       │   └── toutiao
│       │       └── middleware
│       │           └── hertz
│       │               └── hertz.go
│       ├── mdoel
│       │   └── toutiao
│       │       └── middleware
│       │           └── hertz
│       │               └── psm.go
│       └── router
│           ├── register.go
│           └── toutiao
│               └── middleware
│                   └── hertz
│                       ├── middleware.go
│                       └── psm.go
├── go.mod
├── main.go
├── router.go
├── router_gen.go
└── script
    └── bootstrap.sh
```
其中，除"handler"、"router"、"model" 外的其他代码可自由移动，这就不用管"biz"还是"internal"了

**Comment by Skyenought** [comment]
ok, thank you for your answer!
