### ISSUE TITLE
How to graceful restart Hertz

### ISSUE THREAD

**Issue by Jun-F** [cloudwego/hertz#543]
**Describe the Question**
How to graceful restart in hertz, or how to use [[#fvbock/endless](https://github.com/fvbock/endless)]  or [[#cloudflare/tableflip](https://github.com/cloudflare/tableflip)] in Hertz

**Hertz version:**
0.5.0

**Environment:**
go 1.19

**Comment by FlameMida** [comment]
Is this what you're talking about? [graceful-shutdown](https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/graceful-shutdown/)

**Comment by Jun-F** [comment]
If there is only one hertz service, how to update and restart the service without losing the user's request.
I try to use [[#fvbock/endless](https://github.com/fvbock/endless)] or [[#cloudflare/tableflip](https://github.com/cloudflare/tableflip)] in hertz, but it doesn't work

**Comment by ExerciseBook** [comment]
猜你想找：服务托管

`kubectl rollout restart`

**Comment by ExerciseBook** [comment]
我提供一个最低配的方案。

你写一个 Hertz 服务，我们设为 A，他是你的业务服务，也是你需要用来重启的服务。

我们还需要一个监控服务 B，用来解决你的这个问题。



假设在最开始的时候只有 A 服务，并且只运行了一份，我们设其为实例 a

此时，服务器的网络环境为通过 iptable 将 10.11.45.14:8080 这个 ip 转发到了 a:8080

Nginx 对外接收 某个域名:80 并转发到了 10.11.45.14:8080 这个端口

在这个情况下，用户可以正常通过 某个域名:80 访问到了 a:8080 

没有问题



我们需要给 A 增加一个 api 叫做 `\check_health` 之类的，反正能接受一个请求返回 200 就成


那么重启 A 的流程就是

我们再开一份 A，设其为实例 b。当 b 开始启动时，监控服务 B 不断向 b 发起一个 http 请求，直到 B 发现 b 的这个 check health 接口能访问了，并且返回了 200 那么进入下一步。

将 iptable 中的 10.11.45.14:8080 指向 b:8080

然后等待一段时间后，再将 a 给 kill 9 掉


大概就是这么个流程

**Comment by Jun-F** [comment]
thx

**Comment by xujunhai** [comment]
我还是觉得真graceful 才有用 类似ngxin 平滑重启 启动新的进程 旧的结束后 都走新的
