### ISSUE TITLE
Sorry I cant verify and i cant test but because i've been working with content-encoding issue, i think there's a problem with brotli

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#546]
Sorry I cant verify and i cant test but because i've been working with content-encoding issue, i think there's a problem with brotli generated content-encoding using h2 when http1.1 client is used.

maybe can close this issue but if someone figured out what's happening or having same issue, can mention here too.

the generated brotli or "deflate" is messed up

[client] -> [hertz] -> [fasthttp] -> [hertz]
client received messed up encoding.

i disabled brotli and deflate for the moment for it to work. not sure if it's error on my side but i switched fasthttp in the middle coz of the previous content-encoding issue ( i thought was my problem ).

because of time contraint, i'm using what works and using http1.1 from fasthttp is "ok" because the front facing needs http2 from hertz will do. that's all fine. 

@Duslia @li-jin-gou

**Comment by Duslia** [comment]
You did not commit reproducible code. So I don't know what's the bug is. Please create issue according to template !!!
