### ISSUE TITLE
how to specify execution of command upon graceful  server shutdown by CTRL+C?

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#547]
how to specify execution of command upon graceful server shutdown by CTRL+C?

i would like to execute some clean up linux operations by deleting some files from server.

how do i do this?

**Comment by Duslia** [comment]
```
h := server.Default()
h.OnShutdown = []route.CtxCallback{
func(ctx context.Context) {
	// execute some cleanup work	
},
}
// ...
// h.Spin
```
