### ISSUE TITLE
server.WithOnAccept passing instance calling variable to h.Use()

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#549]
**Describe the Question**

@Duslia pls help

```
var skipIPCheck int = 0 //<--- declared early

...

server.WithOnAccept(func(conn net.Conn) context.Context {
	ip, _, err := net.SplitHostPort(conn.RemoteAddr().String())
	if err != nil {
		log.Printf("could not parse local addr: %s\n", err)
		conn.Close()
		return context.Background()
	}
	if isBadIP(ip) == 1 {
	        skipIPCheck = 1 //ok it's bad ip
		conn.Close()
		return context.Background()
	}
	return context.Background()
}),

h.Use(func(cc context.Context, ctx *app.RequestContext) {
     ProxyHandlerHertz(cc, ctx, skipIPCheck) //would like to pass skipIPCheck = 1 here, how? need to be local variable for this calling instance. pls help
})
```
**Reproducible Code**

as mentioned above

**Expected behavior**

able to pass isBadIP results variable to h.Use()

**Hertz version:**

0.5

**Environment:**

linux go 1.19

**Additional context**

none

**Comment by Duslia** [comment]
If it is badIP and close conn, then it won't enter middleware. If you want to do some logic, you can only do it in server.WithOnAccept.

**Comment by ultperf** [comment]
@Duslia can u gimme an idea on how to use server.WithOnAccept() that passes information to h.Use() ?

basically i need to "skip" h.Use and do ProxyHandlerHertz(cc, ctx, skipIPCheck) inside server.WithOnAccept()
```
h.Use(func(cc context.Context, ctx *app.RequestContext) {
     ProxyHandlerHertz(cc, ctx, skipIPCheck)
}
```

can u provide a quick example pls running  ProxyHandlerHertz(cc,ctx,skipIPCheck) inside WithOnAccept and not go through h.Use

**Comment by ultperf** [comment]
@Duslia , @li-jin-gou 
pls help this, this is my last area of question. i can help answer issues and contrib code if u need me to.
some of the questions i can actually help revert but seriously need to finish this up first. last section. please. thx.

i shld be able to help contribute some code back within 2 weeks after this area.

**Comment by Duslia** [comment]
If it is badIP and close conn, then it **won't** enter middleware. If you want to do some logic, you can **only** do it in server.WithOnAccept.

**Comment by Duslia** [comment]
Middleware will be executed after parsing the whole data.

**Comment by hiqsociety** [comment]
@Duslia i know about the badip part. pls disregard close conn part. i'm talking about the part where i need to pass the parse information (skipIPCheck) to h.Use... 
```
h.Use(func(cc context.Context, ctx *app.RequestContext) {
     ProxyHandlerHertz(cc, ctx, skipIPCheck)
}
```
or how do i skip h.Use and just do h.Use inside the WithOnAccept? means i need to be able to touch ctx inside the WithOnAccept?

i'm trying to skip some code section that has already been done inside WithOnAccept for h.Use so needing to pass skipIPCheck if already checked before inside WithOnAccept.

pls read original code i've amended on this issue to understand better on my question.
pls pls pls help. thx.

**Comment by li-jin-gou** [comment]
Not supported

**Comment by hiqsociety** [comment]
@li-jin-gou pls support it? this is crucial. what's a good way to work around?

**Comment by li-jin-gou** [comment]
> @li-jin-gou pls support it? this is crucial. what's a good way to work around?

cc @Duslia

**Comment by ultperf** [comment]
@li-jin-gou @Duslia 
pls pls pls help this last bit.
thx!

**Comment by Duslia** [comment]
```
func main() {
	h := server.Default(server.WithOnAccept(func(conn net.Conn) context.Context {
		c := context.Background()
		return context.WithValue(c, "aaa", "bbb")
	}))

	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		fmt.Println(c.Value("aaa"))
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})


	h.Spin()
}
```

**Comment by li-jin-gou** [comment]
> 使用标准上下文传递值。
> 
> ```
> func main() {
> 	h := server.Default(server.WithOnAccept(func(conn net.Conn) context.Context {
> 		c := context.Background()
> 		return context.WithValue(c, "aaa", "bbb")
> 	}))
> 
> 	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
> 		fmt.Println(c.Value("aaa"))
> 		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
> 	})
> 
> 
> 	h.Spin()
> }
> ```

thanks

**Comment by ultperf** [comment]
@Duslia @li-jin-gou 
wow. if it works will be my last area. i will start contributing code and help with issues soon. need to tidy my code first and do more production test run. 

thx! u guys are the best!
