### ISSUE TITLE
how to intercept error from > [Error] HERTZ: Error=

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#551]
**Describe the Question**

how to intercept error from
> [Error] HERTZ: Error=

and do something about it? i want to drop them after many failed attempts. i have the function but dunno how to get the error as variable passing. 

some of the IPs are bad bots

final final final area. hopefully no more issues. these are actual small "production" results returned.

**Reproducible Code**

running production hertz gives plenty of errors as below

**Expected behavior**

hope to get some ways to get the hertz error which is not so evident 
err := h.Error? i dunno how to get the errors of each connection instance

**Screenshots**

2023/01/18 01:05:19.407138 engine.go:462: [Error] HERTZ: Error=tls: first record does not look like a TLS handshake, remoteAddr=3.91.71.115:52120
2023/01/18 01:05:19.407287 engine.go:462: [Error] HERTZ: Error=tls: first record does not look like a TLS handshake, remoteAddr=3.91.71.115:52186
2023/01/18 01:05:19.407431 engine.go:462: [Error] HERTZ: Error=tls: first record does not look like a TLS handshake, remoteAddr=3.91.71.115:52122
2023/01/18 01:05:19.407581 engine.go:462: [Error] HERTZ: Error=tls: first record does not look like a TLS handshake, remoteAddr=3.91.71.115:52170
2023/01/18 01:12:15.022890 engine.go:462: [Error] HERTZ: Error=tls: first record does not look like a TLS handshake, remoteAddr=109.237.98.226:52168
2023/01/18 01:23:04.126672 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.105:60162
2023/01/18 01:24:11.011194 engine.go:462: [Error] HERTZ: Error=tls: client offered only unsupported versions: [301], remoteAddr=23.101.59.181:64880
2023/01/18 01:29:55.089796 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.108:51646
2023/01/18 02:01:56.637350 engine.go:462: [Error] HERTZ: Error=error when reading request headers: too long int. Buffer size=192, contents: "SSTP_DUPLEX_POST /sr"..."t: 123.123.123.123\r\n\r\n", remoteAddr=157.245.176.143:33442
2023/01/18 02:07:39.378044 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->167.248.133.60:55204: read: connection reset by peer, remoteAddr=167.248.133.60:55204
2023/01/18 02:08:15.374388 engine.go:462: [Error] HERTZ: Error=tls: client offered only unsupported versions: [301], remoteAddr=84.47.147.86:62155
2023/01/18 02:15:48.749880 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->162.142.125.219:45102: read: connection reset by peer, remoteAddr=162.142.125.219:45102
2023/01/18 02:15:49.256078 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->167.248.133.62:48086: read: connection reset by peer, remoteAddr=167.248.133.62:48086
2023/01/18 02:15:49.563843 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->167.94.138.44:52474: read: connection reset by peer, remoteAddr=167.94.138.44:52474
2023/01/18 02:16:45.869844 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->162.142.125.219:35766: read: connection reset by peer, remoteAddr=162.142.125.219:35766
2023/01/18 02:16:45.900358 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->162.142.125.222:47574: read: connection reset by peer, remoteAddr=162.142.125.222:47574
2023/01/18 02:16:46.258487 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->167.94.138.44:49752: read: connection reset by peer, remoteAddr=167.94.138.44:49752
2023/01/18 02:16:46.681072 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->162.142.125.9:49138: read: connection reset by peer, remoteAddr=162.142.125.9:49138
2023/01/18 02:16:47.205629 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->162.142.125.222:38438: read: connection reset by peer, remoteAddr=162.142.125.222:38438
2023/01/18 02:16:47.265344 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->162.142.125.212:38156: read: connection reset by peer, remoteAddr=162.142.125.212:38156
2023/01/18 02:16:47.484978 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->167.94.138.44:38174: read: connection reset by peer, remoteAddr=167.94.138.44:38174
2023/01/18 02:16:47.628648 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->167.248.133.61:38110: read: connection reset by peer, remoteAddr=167.248.133.61:38110
2023/01/18 02:16:48.635713 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->162.142.125.212:49050: read: connection reset by peer, remoteAddr=162.142.125.212:49050
2023/01/18 02:16:48.840249 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->167.248.133.44:37308: read: connection reset by peer, remoteAddr=167.248.133.44:37308
2023/01/18 02:23:17.206187 engine.go:462: [Error] HERTZ: Error=tls: first record does not look like a TLS handshake, remoteAddr=45.227.254.54:64886
2023/01/18 02:32:42.163859 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.107:44466
2023/01/18 02:47:23.567338 engine.go:462: [Error] HERTZ: Error=tls: client offered only unsupported versions: [301], remoteAddr=85.54.122.7:62891
2023/01/18 02:58:32.212579 engine.go:462: [Error] HERTZ: Error=remote error: tls: unknown certificate, remoteAddr=154.202.114.240:25083
root@vps-8695400b:/home/ubuntu# 2023/01/18 03:02:20.199062 engine.go:462: [Error] HERTZ: Error=remote error: tls: unknown certificate authority, remoteAddr=121.37.247.231:63310
2023/01/18 03:02:21.450722 engine.go:462: [Error] HERTZ: Error=tls: first record does not look like a TLS handshake, remoteAddr=121.37.247.231:63496
2023/01/18 03:05:37.207415 engine.go:462: [Error] HERTZ: Error=tls: first record does not look like a TLS handshake, remoteAddr=45.11.57.48:44220
2023/01/18 03:05:37.949400 engine.go:462: [Error] HERTZ: Error=tls: first record does not look like a TLS handshake, remoteAddr=45.11.57.48:44230
2023/01/18 03:15:53.291561 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.99:49056
2023/01/18 03:20:28.739744 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.108:43506
2023/01/18 03:21:37.141639 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.108:43566
2023/01/18 03:25:25.029209 engine.go:462: [Error] HERTZ: Error=tls: client requested unsupported application protocols ([http/0.9 http/1.0 spdy/1 spdy/2 spdy/3 h2c hq]), remoteAddr=104.131.181.99:60558
2023/01/18 03:25:25.049142 engine.go:462: [Error] HERTZ: Error=tls: client requested unsupported application protocols ([hq h2c spdy/3 spdy/2 spdy/1 http/1.0 http/0.9]), remoteAddr=104.131.181.99:60604
2023/01/18 03:25:25.068348 engine.go:462: [Error] HERTZ: Error=tls: client offered only unsupported versions: [302 301], remoteAddr=104.131.181.99:60672
2023/01/18 03:25:25.106111 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->104.131.181.99:60738: read: connection reset by peer, remoteAddr=104.131.181.99:60738
2023/01/18 03:25:26.200039 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->104.131.181.99:35556: read: connection reset by peer, remoteAddr=104.131.181.99:35556
2023/01/18 03:40:48.696674 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.99:48662
2023/01/18 03:41:05.769079 engine.go:462: [Error] HERTZ: Error=tls: client offered only unsupported versions: [301], remoteAddr=51.104.43.205:1984
2023/01/18 03:50:23.729521 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.96:39320
2023/01/18 03:52:27.139846 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.105:56184
2023/01/18 04:13:57.968761 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.99:51458
2023/01/18 04:17:46.831883 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.98:36158
2023/01/18 04:24:39.900449 engine.go:462: [Error] HERTZ: Error=remote error: tls: unknown certificate authority, remoteAddr=20.214.138.166:59481
2023/01/18 04:34:18.195573 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.108:48132
2023/01/18 04:38:15.994385 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.105:47006
2023/01/18 04:49:54.395465 engine.go:462: [Error] HERTZ: Error=tls: client offered only unsupported versions: [302 301], remoteAddr=205.210.31.40:55336
2023/01/18 05:34:12.358211 engine.go:462: [Error] HERTZ: Error=tls: client offered only unsupported versions: [301], remoteAddr=23.101.59.181:63727
2023/01/18 05:47:01.294469 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.109:51020
2023/01/18 05:56:09.581399 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.108:60514
2023/01/18 05:58:56.077802 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->162.142.125.8:36592: read: connection reset by peer, remoteAddr=162.142.125.8:36592
2023/01/18 05:59:37.943659 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.105:49494
2023/01/18 06:02:55.064688 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.105:34080
2023/01/18 06:33:31.248798 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.105:39548
2023/01/18 06:42:38.167951 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->66.249.64.5:51562: read: connection reset by peer, remoteAddr=66.249.64.5:51562
2023/01/18 07:06:34.492010 engine.go:462: [Error] HERTZ: Error=tls: first record does not look like a TLS handshake, remoteAddr=107.170.192.8:50212

**Hertz version:**

0.5

**Environment:**

ubuntu 22.04

**Additional context**

none

**Comment by li-jin-gou** [comment]
refer to https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/error-handle/

**Comment by welkeyever** [comment]
By inject a system logger impl (do whatever interception in it).
cc https://github.com/cloudwego/hertz/blob/develop/pkg/common/hlog/hlog.go#L74

**Comment by li-jin-gou** [comment]
> By injecting a system logger impl (do whatever interception in it). cc https://github.com/cloudwego/hertz/blob/develop/pkg/common/hlog/hlog.go#L74

good idea

**Comment by ultperf** [comment]
> refer to https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/error-handle/
@li-jin-gou 
can u pls provide a code example on usage? is it inside h.Server or default or something?

with ref to and checked some ip here already
https://github.com/cloudwego/hertz/issues/549

how to use withonaccept or something?

can u see the bot errors? hope to get a way to drop ip asap upon hertz error and detect bad ip

**Comment by li-jin-gou** [comment]
Why not use context.Context

**Comment by li-jin-gou** [comment]
func main() {
	h := server.Default(server.WithOnAccept(func(conn net.Conn) context.Context {
		c := context.Background()
		return context.WithValue(c, "aaa", "bbb")
	}))

	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		fmt.Println(c.Value("aaa"))
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})


	h.Spin()
}

**Comment by ultperf** [comment]
@li-jin-gou 
 [Error] HERTZ: Error= <-- this error how to get?

**Comment by ultperf** [comment]
@li-jin-gou @Duslia 

can u pls provide an example code on how to use this?
https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/error-handle/

**Comment by ultperf** [comment]
@li-jin-gou hope to have an example on how to get the Error message. any example? i'm not sure how to use the link. possible to update with proper example for the documentation?

**Comment by li-jin-gou** [comment]
hello @ultperf  you can contact @GuangmingLuo  to provide free corporate support  and 
The current idea is still mainly to refer to
![image](https://user-images.githubusercontent.com/97824201/213651710-50fc00b1-7bcd-4ff5-bf26-3454cbfb713c.png)

**Comment by ultperf** [comment]
@welkeyever @li-jin-gou it's quite strange not having a mechanism to handle errors from these etc.

any ways to support this in the near future? it's easy to ddos and bring down with all the hertz error.
previously i have badip() to check but now without a way to have the errors from ip, it's quite meaningless.

only hlog.go? i dont even know how to use it. any example of hlog.go#L74 usage?

```
2023/01/18 05:56:09.581399 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.108:60514
2023/01/18 05:58:56.077802 engine.go:462: [Error] HERTZ: Error=read tcp 123.123.123.123:443->162.142.125.8:36592: read: connection reset by peer, remoteAddr=162.142.125.8:36592
2023/01/18 05:59:37.943659 engine.go:462: [Error] HERTZ: Error=remote error: tls: bad certificate, remoteAddr=185.119.81.105:49494
```

**Comment by ultperf** [comment]
@li-jin-gou possible to give an idea how to access all these "HERTZ: Error=" returned variables?

it's really annoying and hope to solve it. 

also, how do i disable these messages from appearing?

**Comment by li-jin-gou** [comment]
I'll open it first, and for logging we can adjust the log level to fix it. https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/log/#set-the-loglevel

**Comment by ultperf** [comment]
@li-jin-gou how to pipe to a function to process the output instead of opening a file?
i would like to pipe to a function / variable to process the log data immediately.
```
    f, err := os.OpenFile("./output.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
    if err != nil {
            panic(err)
    }
    defer f.Close()
    hlog.SetOutput(f)
```

**Comment by li-jin-gou** [comment]
use hlog.SetOutput and it need a writer.



---Original---
From: ***@***.***&gt;
Date: Sun, Jan 22, 2023 20:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cloudwego/hertz] how to intercept error from &gt; [Error] HERTZ:Error= (Issue #551)




 
@li-jin-gou how to pipe to a function to process the output instead of opening a file?
 i would like to pipe to a function / variable to process the log data immediately.
     f, err := os.OpenFile("./output.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)     if err != nil {             panic(err)     }     defer f.Close()     hlog.SetOutput(f)

**Comment by ultperf** [comment]
@Duslia @li-jin-gou  these are the failed "request" of http2 / https
possible for a way to intercept before hitting ctx?

basically i hope i can not use additional hlog module if not needed. it adds an extra layer of complexity to the whole program.

i would like to be able to register the ip of the [Error] HERTZ and i will implement a counter to detect the frequency of failed https / ssl request. e.g.
//this part already done.
if badIP(ip) { 
   drop 
} 
//now needs this part for the https / ssl / connection error which has the IP but i cant capture it for error handling.
//if i can, how? actually how to use hlog is what i mean. hlog supposed to be inside (ctx) calls?
//pls help

if (num of failed request of https / ssl error / connection error) > 100 {
     addIPtoBadList(ip)
}

```
2023/01/24 19:51:08.340557 server.go:1162: [Error] HERTZ: HTTP2 server: connection error from 162.158.86.146:13660: connection error: PROTOCOL_ERROR
2023/01/24 19:51:08.343594 server.go:1162: [Error] HERTZ: HTTP2 server: connection error from 162.158.86.146:13660: connection error: PROTOCOL_ERROR
2023/01/24 20:13:39.678930 engine.go:462: [Error] HERTZ: Error=remote error: tls: unknown certificate authority, remoteAddr=13.38.55.238:64943
2023/01/24 20:18:19.309740 engine.go:462: [Error] HERTZ: Error=tls: first record does not look like a TLS handshake, remoteAddr=169.60.40.139:47440
2023/01/24 20:50:04.676860 engine.go:462: [Error] HERTZ: Error=tls: client requested unsupported application protocols ([http/0.9 http/1.0 spdy/1 spdy/2 spdy/3 h2c hq]), remoteAddr=152.32.129.53:32288
2023/01/24 20:50:05.111250 engine.go:462: [Error] HERTZ: Error=tls: client requested unsupported application protocols ([hq h2c spdy/3 spdy/2 spdy/1 http/1.0 http/0.9]), remoteAddr=152.32.129.53:32584
2023/01/24 20:50:05.543277 engine.go:462: [Error] HERTZ: Error=tls: client offered only unsupported versions: [302 301], remoteAddr=152.32.129.53:32842
```

**Comment by ultperf** [comment]
@Duslia @li-jin-gou 
sample code for reference. pls inform how to capture [Error] HERTZ: ip address inside

thx
```
package main

import (
        "context"
        "crypto/tls"
        "net"
        "syscall"
        "golang.org/x/sys/unix"
        "bytes"
        //"fmt"
        "log"
        "time"

        "github.com/cloudwego/hertz/pkg/app"
        "github.com/cloudwego/hertz/pkg/app/client"
        "golang.org/x/crypto/acme"
        "golang.org/x/crypto/acme/autocert"
        "compress/gzip"
        "github.com/cloudwego/hertz/pkg/app/server"
        "github.com/cloudwego/hertz/pkg/network/standard"
        "github.com/hertz-contrib/http2/config"
        "github.com/hertz-contrib/http2/factory"

        "github.com/hertz-contrib/reverseproxy"
)

func main() {


        certManager := &autocert.Manager{
                Prompt: autocert.AcceptTOS,
                Cache:  autocert.DirCache("./certs"),
                //              HostPolicy: autocert.HostWhitelist("example.com"), // TODO: replace with your domain.
        }
        letsencryptCfg := &tls.Config{
                GetCertificate: certManager.GetCertificate,
                NextProtos: []string{
                        "h2", "http/1.1", acme.ALPNProto,
                },
        }

        tlsCfg := &tls.Config{
                MinVersion: tls.VersionTLS12,
                GetCertificate: func(hello *tls.ClientHelloInfo) (*tls.Certificate, error) {
                        return letsencryptCfg.GetCertificate(hello)
                },
        }

        h := server.New(
                server.WithHostPorts(":443"),
                server.WithALPN(true),
                server.WithTLS(tlsCfg),
                server.WithListenConfig(&net.ListenConfig{
                        Control: func(network, address string, c syscall.RawConn) error {
                                return c.Control(func(fd uintptr) {
                                        syscall.SetsockoptInt(int(fd), syscall.SOL_SOCKET, unix.SO_REUSEPORT, 1)
                                })
                        },
                }),
                server.WithOnAccept(func(conn net.Conn) context.Context {
                        c := context.Background()
                        return context.WithValue(c, "a", "bbb")
                }),
        )

        h.AddProtocol("h2", factory.NewServerFactory(
                config.WithReadTimeout(time.Minute),
                config.WithDisableKeepAlive(false)),
        )

        tlsCfg.NextProtos = append(tlsCfg.NextProtos, "h2")
        h.Use(func(cc context.Context, ctx *app.RequestContext) {

                log.Printf("c = %v = %s",cc, cc.Value("a")) //NOT SHOWING "bbb"?!?!

                var body []byte
                body = []byte("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")

                var b bytes.Buffer
                w := gzip.NewWriter(&b)
                w.Write(body)
                w.Close()
                body = b.Bytes()

                ctx.Response.Header.SetContentEncoding("gzip")
                ctx.Response.Header.SetStatusCode(200)
                ctx.Response.Header.Set("Content-Type", "text/html; charset=UTF-8")
                ctx.Response.Header.Set("Date", "Tue, 10 Jan 2023 23:13:43 GMT")
                ctx.Response.Header.Set("Connection", "keep-alive")

                ctx.Response.Header.Set("Cache-Control", "max-age=31536000")
                ctx.Response.Header.Set("Connection", "keep-alive")
                ctx.Response.SetBody(body)

        })
        h.Spin()
}

```

**Comment by li-jin-gou** [comment]
> @Duslia @li-jin-gou sample code for reference. pls inform how to capture [Error] HERTZ: ip address inside
> 
> thx
> 
> ```
> package main
> 
> import (
>         "context"
>         "crypto/tls"
>         "net"
>         "syscall"
>         "golang.org/x/sys/unix"
>         "bytes"
>         //"fmt"
>         "log"
>         "time"
> 
>         "github.com/cloudwego/hertz/pkg/app"
>         "github.com/cloudwego/hertz/pkg/app/client"
>         "golang.org/x/crypto/acme"
>         "golang.org/x/crypto/acme/autocert"
>         "compress/gzip"
>         "github.com/cloudwego/hertz/pkg/app/server"
>         "github.com/cloudwego/hertz/pkg/network/standard"
>         "github.com/hertz-contrib/http2/config"
>         "github.com/hertz-contrib/http2/factory"
> 
>         "github.com/hertz-contrib/reverseproxy"
> )
> 
> func main() {
> 
> 
>         certManager := &autocert.Manager{
>                 Prompt: autocert.AcceptTOS,
>                 Cache:  autocert.DirCache("./certs"),
>                 //              HostPolicy: autocert.HostWhitelist("example.com"), // TODO: replace with your domain.
>         }
>         letsencryptCfg := &tls.Config{
>                 GetCertificate: certManager.GetCertificate,
>                 NextProtos: []string{
>                         "h2", "http/1.1", acme.ALPNProto,
>                 },
>         }
> 
>         tlsCfg := &tls.Config{
>                 MinVersion: tls.VersionTLS12,
>                 GetCertificate: func(hello *tls.ClientHelloInfo) (*tls.Certificate, error) {
>                         return letsencryptCfg.GetCertificate(hello)
>                 },
>         }
> 
>         h := server.New(
>                 server.WithHostPorts(":443"),
>                 server.WithALPN(true),
>                 server.WithTLS(tlsCfg),
>                 server.WithListenConfig(&net.ListenConfig{
>                         Control: func(network, address string, c syscall.RawConn) error {
>                                 return c.Control(func(fd uintptr) {
>                                         syscall.SetsockoptInt(int(fd), syscall.SOL_SOCKET, unix.SO_REUSEPORT, 1)
>                                 })
>                         },
>                 }),
>                 server.WithOnAccept(func(conn net.Conn) context.Context {
>                         c := context.Background()
>                         return context.WithValue(c, "a", "bbb")
>                 }),
>         )
> 
>         h.AddProtocol("h2", factory.NewServerFactory(
>                 config.WithReadTimeout(time.Minute),
>                 config.WithDisableKeepAlive(false)),
>         )
> 
>         tlsCfg.NextProtos = append(tlsCfg.NextProtos, "h2")
>         h.Use(func(cc context.Context, ctx *app.RequestContext) {
> 
>                 log.Printf("c = %v = %s",cc, cc.Value("a")) //NOT SHOWING "bbb"?!?!
> 
>                 var body []byte
>                 body = []byte("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
> 
>                 var b bytes.Buffer
>                 w := gzip.NewWriter(&b)
>                 w.Write(body)
>                 w.Close()
>                 body = b.Bytes()
> 
>                 ctx.Response.Header.SetContentEncoding("gzip")
>                 ctx.Response.Header.SetStatusCode(200)
>                 ctx.Response.Header.Set("Content-Type", "text/html; charset=UTF-8")
>                 ctx.Response.Header.Set("Date", "Tue, 10 Jan 2023 23:13:43 GMT")
>                 ctx.Response.Header.Set("Connection", "keep-alive")
> 
>                 ctx.Response.Header.Set("Cache-Control", "max-age=31536000")
>                 ctx.Response.Header.Set("Connection", "keep-alive")
>                 ctx.Response.SetBody(body)
> 
>         })
>         h.Spin()
> }
> ```

No time to support this for now,  welcome to submit a PR or  use custom hlog.

**Comment by ultperf** [comment]
@li-jin-gou possible to help answer this last final question i have?
sorry it's my first time using bytes.Buffer this way, not sure if there's a better way to do this...

1. how do i get the updated value of bufferWriter?
2. how do i reset the bufferWriter after every read of the updated value?

```
buffer := bytes.NewBuffer(nil) 
bufferWriter := bufio.NewWriter(buffer)

//var buf bytes.Buffer
/*
f, err := os.OpenFile("./output.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
if err != nil {
	panic(err)
}
defer f.Close()
*/
hlog.SetOutput(bufferWriter)

log.Printf("bufstr = %s", buffer.String())

buffer.Reset()
```
