### ISSUE TITLE
静态文件目录如何自动追加斜杠

### ISSUE THREAD

**Issue by quarkcms** [cloudwego/hertz#553]
例如：http://localhost:3000/admin，如何重定向为http://localhost:3000/admin/

**Comment by Duslia** [comment]
There is an option that you can config. And it is open default

**Comment by li-jin-gou** [comment]
refer to https://www.cloudwego.io/zh/docs/hertz/reference/config/ and you need to according to pull request template

**Comment by quarkcms** [comment]
未找到相关配置

**Comment by Duslia** [comment]
<img width="1619" alt="image" src="https://user-images.githubusercontent.com/37136584/213120889-196c9015-2869-4f81-859a-c9c245357174.png">

**Comment by li-jin-gou** [comment]
Careful review and reading of the documentation is required.
![image](https://user-images.githubusercontent.com/97824201/213120982-9cfa4041-8a70-45a8-9b6b-d17b3ed174b8.png)

**Comment by quarkcms** [comment]
配置不生效，因为路径是文件目录

**Comment by quarkcms** [comment]
麻烦给个实例代码吧

**Comment by li-jin-gou** [comment]
```
package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()
	h.StaticFile("/ping/", "examples/standard/main.go")
	h.Spin()
}

```
It is ok

**Comment by quarkcms** [comment]
还是不行

**Comment by quarkcms** [comment]
可以了
