### ISSUE TITLE
how to properly delete cc.Value("s")?  cc.Value("s") = nil ?

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#560]
**Describe the Question**

would like to clear all cc context.Contxt values. how to do so?
cc.Value("s") = nil?

or is there a better way or recommended way?

tried below and not working. i would like to clear all cc.Value inside. make cc into nil if possible. no idea why it's not working.

```
func FWProxyHandlerHertz(cc context.Context, ctx *app.RequestContext) {
   cc = context.WithValue(context.Background(), "s", nil) // not working with subsequent request. value still around. using http2
		
```

**Comment by ultperf** [comment]
Delete or Clear()

**Comment by ultperf** [comment]
@Duslia how to property update the values of context? sorry i cant seem to get it to work as expected using http2

**Comment by ultperf** [comment]
@Duslia pass by reference or value etc not working. no matter what i do, it's not clearing
@li-jin-gou 
how to resolve this?
my final final final area need resolve for production testing. pls help. thx
```
func FWProxyHandlerHertz(cc *context.Context, ctx *app.RequestContext) {
 //*cc = nil
		(*cc) = context.WithValue(context.Background(), "s", nil)
		
```

**Comment by li-jin-gou** [comment]
i think firstly you can use stackoverflow or google search，it is a golang question.
