### ISSUE TITLE
The hertz(v 0.5.1) project cannot be build on Windows 32

### ISSUE THREAD

**Issue by Hang-che** [cloudwego/hertz#561]
**Describe the bug**
The hertz project cannot be created on Windows, but the documentation explains that windows is supported

**To Reproduce**
1. open cmd
2. cd workspace
3. hz new
4. failed create project
5. error: generating layout failed: lint file 'router_gen.go' failed, err: 7:21: unknown escape sequence

**Expected behavior**

Successfully create a hertz project

**Screenshots**
![image](https://user-images.githubusercontent.com/92908464/213906573-9329314e-0563-4cb1-8118-24ee8407c707.png)

**Hertz version:**

hz version v0.5.1

**Environment:**

The output of `go env`.
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Usrs\~\AppData\Local\go-build
set GOENV=C:\Users\~\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\code\Coding\gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\code\Coding\gopath
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\code\environment\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\code\environment\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\code\Coding\gopath\src\github.com\ch\test_hertz\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\·\AppData\Local\Temp\go-build4266385993=/tmp/go-build -gno-record-gcc-switches
**Additional context**

**Comment by justlorain** [comment]
I just tried it and it works, maybe you can try creating the project directly under `gopath/src`.
![image](https://user-images.githubusercontent.com/87760338/213907399-117473b1-0016-422b-bf1c-934af9474718.png)

**Comment by Skyenought** [comment]
me too

**Comment by Hang-che** [comment]
thank you! I successfully created the project .`hz new` creates the project only in `gopath/src` directory. Other directories even subdirectories of `gopath/src` need to use `-mod` argument

> I just tried it and it works, maybe you can try creating the project directly under `gopath/src`, or use the `-mod` argument refer to https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/toolkit/. ![image](https://user-images.githubusercontent.com/87760338/213907399-117473b1-0016-422b-bf1c-934af9474718.png)

**Comment by lizhe-0423** [comment]
归根到底我认为 他的文档有问题！

**Comment by lizhe-0423** [comment]
我有试着尝试 hz new 但会产生报错信息 
![image](https://user-images.githubusercontent.com/109721930/215046601-45fdafef-ca7e-40be-906f-c2be3748d6f6.png)

**Comment by Skyenought** [comment]
> 我有试着尝试 hz new 但会产生报错信息 ![image](https://user-images.githubusercontent.com/109721930/215046601-45fdafef-ca7e-40be-906f-c2be3748d6f6.png)

您执行这一步没有呢
![image](https://user-images.githubusercontent.com/70408571/215047754-799570ba-0749-4e7c-b534-8ba3464b25d6.png)

**Comment by lizhe-0423** [comment]
> > 我有试着尝试 hz new 但会产生报错信息![图像](https://user-images.githubusercontent.com/109721930/215046601-45fdafef-ca7e-40be-906f-c2be3748d6f6.png)
> 
> 您执行这一步没有呢 ![图像](https://user-images.githubusercontent.com/70408571/215047754-799570ba-0749-4e7c-b534-8ba3464b25d6.png)

当然 像这样 但并没有起到作用
![image](https://user-images.githubusercontent.com/109721930/215048868-8c2b58cf-46b1-4fae-9a8f-d40805cd0f59.png)

**Comment by L2ncE** [comment]
> 当然 像这样 但并没有起到作用

设置中有打开 Go 模块集成 / Go Modules 吗

**Comment by lizhe-0423** [comment]
> > 当然 像这样 但并没有起到作用
> 
> 设置中有打开 Go 模块集成 / Go Modules 吗

谢谢 解决了 但是再运行的时候又产生了新的问题！

报错信息：

# github.com/henrylee2cn/ameda
..\..\..\pkg\mod\github.com\henrylee2cn\ameda@v1.4.10\int.go:13:9: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in return statement (overflows)
..\..\..\pkg\mod\github.com\henrylee2cn\ameda@v1.4.10\uint.go:13:9: cannot use math.MaxUint64 (untyped int constant 18446744073709551615) as uint value in return statement (overflows)

# github.com/henrylee2cn/ameda
..\..\..\pkg\mod\github.com\henrylee2cn\ameda@v1.4.10\int.go:13:9: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in return statement (overflows)
..\..\..\pkg\mod\github.com\henrylee2cn\ameda@v1.4.10\uint.go:13:9: cannot use math.MaxUint64 (untyped int constant 18446744073709551615) as uint value in return statement (overflows)

**Comment by lizhe-0423** [comment]
> > 当然 像这样 但并没有起到作用
> 
> 设置中有打开 Go 模块集成 / Go Modules 吗

谢谢 解决了 但是有新的问题 就是无法成功运行

报错信息：

# github.com/henrylee2cn/ameda
..\..\..\pkg\mod\github.com\henrylee2cn\ameda@v1.4.10\int.go:13:9: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in return statement (overflows)
..\..\..\pkg\mod\github.com\henrylee2cn\ameda@v1.4.10\uint.go:13:9: cannot use math.MaxUint64 (untyped int constant 18446744073709551615) as uint value in return statement (overflows)

![image](https://user-images.githubusercontent.com/109721930/215052746-06702270-889e-458e-8b91-b46df9177c8c.png)

**Comment by li-jin-gou** [comment]
> > > 当然 像这样 但并没有起到作用
> > 
> > 
> > 设置中有打开 Go 模块集成 / Go Modules 吗
> 
> 谢谢 解决了 但是有新的问题 就是无法成功运行
> 
> 报错信息：
> 
> # github.com/henrylee2cn/ameda
> ......\pkg\mod\github.com\henrylee2cn\ameda@v1.4.10\int.go:13:9: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in return statement (overflows) ......\pkg\mod\github.com\henrylee2cn\ameda@v1.4.10\uint.go:13:9: cannot use math.MaxUint64 (untyped int constant 18446744073709551615) as uint value in return statement (overflows)
> 
> ![image](https://user-images.githubusercontent.com/109721930/215052746-06702270-889e-458e-8b91-b46df9177c8c.png)

你是 32 位的机器嘛，同学

**Comment by li-jin-gou** [comment]
目测应该是这个问题 https://github.com/andeya/ameda/commit/8c8adc946c697ff3e78aaa6219550b7b099c2abb

这个是 hertz 间接依赖了一个 common 库导致的问题，你可以使用 

```
go get github.com/andeya/ameda@v1.5.1
```
应该就可以了

**Comment by li-jin-gou** [comment]
> 归根到底我认为 他的文档有问题！

文档问题欢迎详细反馈 issue & pr

**Comment by lizhe-0423** [comment]
> > > > 当然 像这样 但并没有起到作用
> > > 
> > > 
> > > 设置中有打开 Go 模块集成 / Go Modules 吗
> > 
> > 
> > 谢谢 解决了 但是有新的问题 就是无法成功运行
> > 报错信息：
> > # github.com/henrylee2cn/ameda
> > ......\pkg\mod\github.com\henrylee2cn\ameda@v1.4.10\int.go:13:9: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in return statement (overflows) ......\pkg\mod\github.com\henrylee2cn\ameda@v1.4.10\uint.go:13:9: cannot use math.MaxUint64 (untyped int constant 18446744073709551615) as uint value in return statement (overflows)
> > ![image](https://user-images.githubusercontent.com/109721930/215052746-06702270-889e-458e-8b91-b46df9177c8c.png)
> 
> 你是 32 位的机器嘛，同学

但我是64位的

**Comment by li-jin-gou** [comment]
> > > > > 当然 像这样 但并没有起到作用
> > > > 
> > > > 
> > > > 设置中有打开 Go 模块集成 / Go Modules 吗
> > > 
> > > 
> > > 谢谢 解决了 但是有新的问题 就是无法成功运行
> > > 报错信息：
> > > # github.com/henrylee2cn/ameda
> > > ......\pkg\mod\github.com\henrylee2cn\ameda@v1.4.10\int.go:13:9: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in return statement (overflows) ......\pkg\mod\github.com\henrylee2cn\ameda@v1.4.10\uint.go:13:9: cannot use math.MaxUint64 (untyped int constant 18446744073709551615) as uint value in return statement (overflows)
> > > ![image](https://user-images.githubusercontent.com/109721930/215052746-06702270-889e-458e-8b91-b46df9177c8c.png)
> > 
> > 
> > 你是 32 位的机器嘛，同学
> 
> 但我是64位的

先更新一下试下

**Comment by lizhe-0423** [comment]
> 

为什么我无法进行更新？

信息：
go: github.com/andeya/ameda@v1.5.1: parsing go.mod:
        module declares its path as: github.com/henrylee2cn/ameda
                but was required as: github.com/andeya/ameda


![image](https://user-images.githubusercontent.com/109721930/215109333-4e06ba65-f61c-4592-b83c-f7934b033555.png)

**Comment by li-jin-gou** [comment]
按照报错换成 github.com/andeya/ameda 试试呢

&nbsp;另外方便可以发下你的 go env 嘛



---Original---
From: ***@***.***&gt;
Date: Fri, Jan 27, 2023 22:27 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [cloudwego/hertz] The hertz(v 0.5.1) project cannot be created onWindows (Issue #561)




       
当然 像这样 但并没有起到作用
  
设置中有打开 Go 模块集成 / Go Modules 吗
  
谢谢 解决了 但是有新的问题 就是无法成功运行
 报错信息：
 
github.com/henrylee2cn/ameda
 
......***@***.***\int.go:13:9: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in return statement (overflows) ......***@***.***\uint.go:13:9: cannot use math.MaxUint64 (untyped int constant 18446744073709551615) as uint value in return statement (overflows)
 
  
你是 32 位的机器嘛，同学
  
但我是64位的
  
先更新一下试下，目前报错是指向这个问题,
 go get ***@***.***   
无法进行更新
 
信息：
 
go: ***@***.***: parsing go.mod:
 module declares its path as: github.com/henrylee2cn/ameda
 but was required as: github.com/andeya/ameda

**Comment by lizhe-0423** [comment]
> github.com/andeya/ameda

是这样嘛？ 命令执行成功了 但还是无法运行 错误信息 就是上面写到的
![image](https://user-images.githubusercontent.com/109721930/215112193-5a3c03ed-a8cd-46a4-8af9-cf54d448f3d6.png)
运行：
![image](https://user-images.githubusercontent.com/109721930/215112258-fe37d952-0883-4531-a864-58f16b5a1876.png)
环境：
![image](https://user-images.githubusercontent.com/109721930/215112475-6d31de6a-f9a8-4758-9d11-8f18902a25a9.png)

**Comment by li-jin-gou** [comment]
参考：
GOARCH 中 386 与 amd64 的区别
386 代表 32 位系统，也称为 i386。名字源于 Intel 80386 指令集。
amd64 代表 64 位系统。名字源于 64 位指令集最早由 AMD 公司发布。



同学你的go env 看起来是32位的，现在想办法更新一下那个 ameda 的包就可以，或者你如果你装一个 amd64的 go试试



---Original---
From: ***@***.***&gt;
Date: Fri, Jan 27, 2023 22:37 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [cloudwego/hertz] The hertz(v 0.5.1) project cannot be created onWindows (Issue #561)




  
github.com/andeya/ameda
  
是这样嘛？ 命令执行成功了 但还是无法运行 错误信息 就是上面写到的
 
 运行：
 
 环境：

**Comment by lizhe-0423** [comment]
> 参考： GOARCH 中 386 与 amd64 的区别 386 代表 32 位系统，也称为 i386。名字源于 Intel 80386 指令集。 amd64 代表 64 位系统。名字源于 64 位指令集最早由 AMD 公司发布。 同学你的go env 看起来是32位的，现在想办法更新一下那个 ameda 的包就可以，或者你如果你装一个 amd64的 go试试
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Jan 27, 2023 22:37 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;;"State ***@***.***&gt;; Subject: Re: [cloudwego/hertz] The hertz(v 0.5.1) project cannot be created onWindows (Issue #561) github.com/andeya/ameda 是这样嘛？ 命令执行成功了 但还是无法运行 错误信息 就是上面写到的 运行： 环境： — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

感谢 解决了！ 非常感谢。
