### ISSUE TITLE
[Question] hertz在生成代码时，生成的位置和import路径不一致

### ISSUE THREAD

**Issue by hts0000** [cloudwego/hertz#563]
**Describe the Question**
我准备使用`hertz + kitex`来完成我的项目。这是我的目录结构。  
其中`gateway`服务使用`hertz`，`auth`服务使用`kitex`。他们共同处于一个`go mod`创建的项目`demo`下。
```
demo
├── auth
├── gateway
├── go.mod
└── idl
    ├── api.proto
    └── gateway
        └── gateway.proto
```
我期望根据`demo/idl/gateway/gateway.proto`为`gateway`服务生成基础的框架。以下是我的`gateway.proto`文件。
```
syntax = "proto3";

package gateway;

option go_package="demo/gateway";

import "api.proto";

message RegisterRequest {
    string username = 1;  // 注册用户名，最长32个字符
    string password = 2;  // 密码，最长32个字符
}

message RegisterResponse {
    int32 status_code = 1; // 状态码，0: 成功，其他值: 失败
    string status_msg = 2; // 返回状态描述
    int64 user_id = 3;     // 用户id
    string token = 4;      // 用户鉴权token
}

service ApiService {
    rpc Register (RegisterRequest) returns (RegisterResponse) {
        option (api.post) = "/user/register";
    }
}
```
我参照了[文档](https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/toolkit/#%E5%9F%BA%E4%BA%8E-protobuf-idl-%E5%88%9B%E5%BB%BA%E9%A1%B9%E7%9B%AE)，在`demo/gateway`目录执行如下命令生成代码。
```
hz new -mod demo -I ../idl -idl ../idl/gateway/gateway.proto
```
代码成功生成在`demo/gateway`目录，但是里面生成的代码的import路径不对。不止这一个文件如此。
![image](https://user-images.githubusercontent.com/52144113/214070919-bf54f124-155e-4406-88bf-36b09e773db4.png)

我应该怎么做才能生成正确的代码？以及我这样组织项目，目录结构对于`hertz + kitex`来说是否合理？

**Reproducible Code**
1. 创建项目
```
mkdir demo && cd demo
go mod init demo
mkdir -p idl/gateway auth gateway
```
2. 写入`demo/idl/gateway.proto`和`demo/idl/api.proto`文件
3. 生成代码
```
cd gateway
hz new -mod demo -I ../idl -idl ../idl/gateway/gateway.proto
```

**Expected behavior**

期望能生成正确的代码

**Hertz version:**
`hertz v0.5.1`
`hz version v0.5.1`

**Environment:**

The output of `go env`.
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/hts0000/.cache/go-build"
GOENV="/home/hts0000/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/hts0000/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/hts0000/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2298392976=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by li-jin-gou** [comment]
import-path-mistake refer to  https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/toolkit/#%E4%BD%BF%E7%94%A8-protobuf-idl-%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9


layout refer to https://github.com/cloudwego/biz-demo/tree/main/easy_note

**Comment by hts0000** [comment]
use the -mod option like this, can work! thank.
`-mod demo/gateway`
