### ISSUE TITLE
hertz-jwt , how to get token from request body? 

### ISSUE THREAD

**Issue by annie-jpg** [cloudwego/hertz#564]
**Is your feature request related to a problem? Please describe.**
Yes, if the front-end uses the multipart/form-data method to send the token, I cannot use the four methods of hertz-jwt to obtain the token. Should we add the method to obtain the token from the request body?

When i want to get token from request body...

**Describe the solution you'd like**
Add the method to obtain the token, except  header, query, cookie and param. 

**Describe alternatives you've considered**
none.

**Additional context**
none.

**Comment by li-jin-gou** [comment]
refer to https://github.com/hertz-contrib/jwt/pull/14
