### ISSUE TITLE
（Hertz v0.5.1）基于 thrift 生成代码，import 路径生成错误

### ISSUE THREAD

**Issue by zztaki** [cloudwego/hertz#565]
**Describe the bug**

基于 thrift，使用 Hertz v0.5.1 生成代码，import 路径生成错误。

**To Reproduce**

1. 在当前目录创建 hertz_example 目录；
2. 编写 hello.thrift；
3. hz new -idl idl/hello.thrift -module hello 生成代码，并使用 go mod tidy 更新依赖；
4. ./biz/handler/hello/example 文件夹下，example 的引用路径生成错误
![image](https://user-images.githubusercontent.com/50295684/215317944-7285bdc2-0086-41df-9439-a18672d74560.png)
5. 直接 go build 有如下提示
![image](https://user-images.githubusercontent.com/50295684/215317997-e2de6e96-a14f-41f1-9352-0ba5a57ccda4.png)

**Expected behavior**

期望的引用路径应该如下
![image](https://user-images.githubusercontent.com/50295684/215318044-fb8df935-00ed-4255-8d51-5357034d205e.png)

**Screenshots**

**Hertz version:**

v 0.5.1

**Environment:**

![image](https://user-images.githubusercontent.com/50295684/215318072-35659e07-f8ca-4bea-9b39-0ed12e3a9c37.png)

**Additional context**

**Comment by zztaki** [comment]
hello.thrift 文件如下所示：
namespace go hello.example

struct HelloReq {
    1: string Name (api.query="name"); // 添加 api 注解为方便进行参数绑定
}

struct HelloResp {
    1: string RespBody;
}


service HelloService {
    HelloResp HelloMethod(1: HelloReq request) (api.get="/hello");
}

service NewService {
    HelloResp NewMethod(1: HelloReq request) (api.get="/new");
}

**Comment by L2ncE** [comment]
use -module

**Comment by zztaki** [comment]
> Not using -module correctly https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/toolkit/#new

感谢，我发现似乎是 hello 这个 mod 名过于特殊，和 hello 服务同名。当我使用 test 作为 mod 名时，生成的路径名就没有问题了。

**Comment by FGYFFFF** [comment]
> d

这里应该算是一个边缘case，我修一下。建议先取别的 module 名，例如"github.com/cloudwego/test" 等

**Comment by FGYFFFF** [comment]
> > Not using -module correctly https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/toolkit/#new
> 
> 感谢，我发现似乎是 hello 这个 mod 名过于特殊，和 hello 服务同名。当我使用 test 作为 mod 名时，生成的路径名就没有问题了。

查到问题原因了，这里出现的问题原因是你的GoMod("hello")和你的namespace(hello.example)的前缀相同，导致了引用的时候误以为这是一个正确的 import 路径。这是之前针对 protobuf 情况下的一个适配，属于很边缘的case，建议修改一些 go mod的声明~~~

**Comment by zztaki** [comment]
> 

感谢😊

**Comment by zztaki** [comment]
> > > Not using -module correctly https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/toolkit/#new
> > 
> > 
> > 感谢，我发现似乎是 hello 这个 mod 名过于特殊，和 hello 服务同名。当我使用 test 作为 mod 名时，生成的路径名就没有问题了。
> 
> 查到问题原因了，这里出现的问题原因是你的GoMod("hello")和你的namespace(hello.example)的前缀相同，导致了引用的时候误以为这是一个正确的 import 路径。这是之前针对 protobuf 情况下的一个适配，属于很边缘的case，建议修改一些 go mod的声明~~~

感谢😊
