### ISSUE TITLE
handler context parameter design

### ISSUE THREAD

**Issue by warthecatalyst** [cloudwego/hertz#566]
想知道为什么Hertz在HandlerFunc中有一个context.Context接口类型变量

**Comment by li-jin-gou** [comment]
refer to https://www.cloudwego.io/zh/blog/2022/06/21/%E5%AD%97%E8%8A%82%E8%B7%B3%E5%8A%A8%E5%BC%80%E6%BA%90-go-http-%E6%A1%86%E6%9E%B6-hertz-%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%B7%B5/#%E5%BA%94%E7%94%A8%E5%B1%82

**Comment by li-jin-gou** [comment]
We would like to follow the template to make a issue. cc @warthecatalyst
