### ISSUE TITLE
[Question] Something about use HZ toolkit to create a project based on thrift IDL

### ISSUE THREAD

**Issue by linzijie1998** [cloudwego/hertz#570]
Hello, I'm a beginner to the Hertz framework. When I use HZ toolkit (base on thrift IDL) to build my project, I FOUND SOME PROBLEMS
I refer [this example](https://www.cloudwego.io/docs/hertz/tutorials/toolkit/toolkit/#create-a-project-based-on-thrift-idl) to code my thrift IDL:
```thrift
// user.thrift
struct UserRegisterResp {
    1: required i32 StatusCode;
    2: optional string StatusMsg;
    3: required i64 UserID;
    4: required string Token;
}
```
use this command to generate
```shell
hz new -idl user.thrift
```
The generated Golang structure's JSON tag is  `json:"XxxXxx"`, but I want `json:"xxx_xxx"`

I try to use `api.json="xxx_xxx"` fix it (like `api.query="xxx_xxx"`), but it can't solve. I only can replace `Pascal (XxxXxx)` to `UnderScoreCase (xxx_xxx)` in IDL files.
```thrift
// user.thrift
struct UserRegisterResp {
    1: required i32 status_code;
    2: optional string status_msg;
    3: required i64 user_id;
    4: required string token;
}
```

Is there a better way to solve this problem?

**Comment by justlorain** [comment]
Use the `--snake` tag argument for hz new, you can type `hz new -h` for more supported arguments.
