### ISSUE TITLE
Hertz Error: no such file or directory

### ISSUE THREAD

**Issue by feige84** [cloudwego/hertz#573]
Hertz 运行的时候，输出下面的错误：

 2023/01/31 06:11:39 NETPOLL: closeCallback detach operator failed: no such file or directory

 2023/01/31 07:49:47 NETPOLL: poller detach operator failed: no such file or directory

 2023/01/31 08:26:38 NETPOLL: poller detach operator failed: no such file or directory

 2023/01/31 09:48:10 NETPOLL: closeCallback detach operator failed: no such file or directory

 2023/02/01 02:01:57 NETPOLL: closeCallback detach operator failed: no such file or directory

**Comment by Duslia** [comment]
Please provide more information according to the template.

**Comment by Jun-F** [comment]
I had the same problem because I executed `go get -u` and the version of `github.com/cloudwego/netpoll` in `go.mod` was wrong, it became `0.3.2`, it should be `0.3.1`

**Comment by Duslia** [comment]
> Please provide more information according to the template.

Please provide more information according to the template. I don't know how to reproduce it.

**Comment by Jun-F** [comment]
hertz
```
hz new -module demo
go mod tidy
go.mod 的 github.com/cloudwego/netpoll v0.3.1 改为 v0.3.2
go mod tidy
```
ping.go
```
func Ping(ctx context.Context, c *app.RequestContext) {
	time.Sleep(300 * time.Millisecond)
	c.JSON(200, utils.H{
		"message": "pong",
	})
}
```
go run .


nginx conf
```
server
{
        listen    80;

        server_name  demo.com;

        location / {
                proxy_pass http://127.0.0.1:8888/;
                proxy_set_header Host "$http_host";
        }
}
```

ab -c 1000 -n 100000 http://demo.com/ping

![1675404765093](https://user-images.githubusercontent.com/18306375/216525967-9143c1d1-3d3d-41e5-bdd4-32fa4b6ff7e2.jpg)

直接使用ip:端口不会触发，通过nginx转发就会，netpoll使用0.3.1也不会触发

**Comment by joway** [comment]
@Jun-F  应该是只有日志，但是压测本身还是成功的是吧？

**Comment by joway** [comment]
0.3.2 对一些系统调度失败添加了日志，目的是为了在线上异常环境下更加容易排查。本质上功能还是没有变化。

<img width="1706" alt="image" src="https://user-images.githubusercontent.com/8353464/216534598-7a993772-cdc0-45e0-9c50-23f279042552.png">

**Comment by Jun-F** [comment]
压测没有失败请求
