### ISSUE TITLE
go 1.20 sonic 编译报错

### ISSUE THREAD

**Issue by ocean919** [cloudwego/hertz#579]
# github.com/bytedance/sonic/internal/loader
../../pkg/mod/github.com/bytedance/sonic@v1.5.0/internal/loader/funcdata.go:27:22: undefined: _ModuleData
../../pkg/mod/github.com/bytedance/sonic@v1.5.0/internal/loader/funcdata.go:30:27: undefined: _ModuleData
../../pkg/mod/github.com/bytedance/sonic@v1.5.0/internal/loader/funcdata.go:41:6: undefined: _Func
../../pkg/mod/github.com/bytedance/sonic@v1.5.0/internal/loader/funcdata.go:42:12: undefined: _ModuleData
../../pkg/mod/github.com/bytedance/sonic@v1.5.0/internal/loader/funcdata.go:53:16: undefined: _ModuleData
../../pkg/mod/github.com/bytedance/sonic@v1.5.0/internal/loader/funcdata.go:79:26: undefined: _ModuleData
../../pkg/mod/github.com/bytedance/sonic@v1.5.0/internal/loader/funcdata_invalid.go:23:6: panic("Unsupported Go version. Supported versions are: 1.15, 1.16, 1.17, 1.18, 1.19") (no value) used as value
../../pkg/mod/github.com/bytedance/sonic@v1.5.0/internal/loader/loader.go:47:50: too many arguments in call to registerFunction
	have (string, uintptr, uintptr, int, int, uintptr, uintptr, uintptr)
	want (string, uintptr, int, int, uintptr)

**Comment by li-jin-gou** [comment]
refer to https://github.com/bytedance/sonic/issues/355 and https://github.com/cloudwego/hertz/pull/278

**Comment by welkeyever** [comment]
> refer to [bytedance/sonic#355](https://github.com/bytedance/sonic/issues/355) and use #278 to solve it

Requirement: update hertz to v0.5.2

**Comment by waghanza** [comment]
@Duslia @welkeyever I still have compilation issue, even with this version
https://github.com/the-benchmarker/web-frameworks/actions/runs/4072426242/jobs/7015182899#step:6:77

**Comment by li-jin-gou** [comment]
> @Duslia @welkeyever I still have compilation issue, even with this version https://github.com/the-benchmarker/web-frameworks/actions/runs/4072426242/jobs/7015182899#step:6:77

need to use stdjson tag to build

**Comment by waghanza** [comment]
not sure I know what to do @li-jin-gou, could you please open a PR on https://github.com/the-benchmarker/web-frameworks ?

**Comment by li-jin-gou** [comment]
> not sure I know what to do @li-jin-gou, could you please open a PR on https://github.com/the-benchmarker/web-frameworks ?

Let me look at it first, I'm not sure if CI can specify the build tag @waghanza

**Comment by waghanza** [comment]
I have done this in https://github.com/the-benchmarker/web-frameworks/actions/runs/4091123344/jobs/7055006320#step:6:68 @li-jin-gou. Thanks for the tip
