### ISSUE TITLE
Failed to format: 4:15: illegal character U+005C '\' (and 3 more errors)

### ISSUE THREAD

**Issue by ATXTKS** [cloudwego/hertz#588]
**Describe the Question**

安装了Hz和thriftgo之后，试着编译cloudwego教程中的hello.thrift，可是他生成了代码之后，却提示格式化错误。
D:\dox\hertz_demo>hz new -idl idl/hello.thrift -module hzdemo
[WARN] Failed to format D:\dox\hertz_demo\biz\model\hello\example\hello.go: 4:15: illegal character U+005C '\' (and 3 more errors)

并且在goland打开后，他也提示我，在model文件夹中的hello.go文件的格式不正确。

**Expected behavior**

想要不报错。

**Screenshots**

![image](https://user-images.githubusercontent.com/87157185/216495830-831e9977-e62a-41c2-8124-ecdf9867c180.png)

**Hertz version:**

Hz version is v0.5.1

**Environment:**

The output of `go env`.
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ATXTKS\AppData\Local\go-build
set GOENV=C:\Users\ATXTKS\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\GOPATH\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\GOPATH
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\dox\hertz_demo\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\ATXTKS\AppData\Local\Temp\go-build1591107489=/tmp/go-build -gno-record-gcc-switches

**Comment by welkeyever** [comment]
收到反馈~
![image](https://user-images.githubusercontent.com/9826697/216505305-5af842f1-8935-4989-b8ff-c75db0819e6c.png)
这行代码具体内容可以贴一下吗

**Comment by ATXTKS** [comment]
这是报错的那一行代码：
`package hzdemo\biz\model\hello\example`

**Comment by ATXTKS** [comment]
好的，贴上去了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cloudwego/hertz"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月3日(星期五) 中午11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cloudwego/hertz] Failed to format: 4:15: illegal character U+005C '\' (and 3 more errors) (Issue #588)





 
收到反馈~
 
 这行代码具体内容可以贴一下吗

**Comment by FGYFFFF** [comment]
The latest version of thriftgo has problems under windows, use this version first.：
`go install github.com/cloudwego/thriftgo@v0.2.4`
After that we fix it.

**Comment by ATXTKS** [comment]
OK, the problem has been solved. Thanks.

**Comment by FGYFFFF** [comment]
@ATXTKS The problem has been fixed~ You can try thriftgo for latest version:
`go install github.com/cloudwego/thriftgo@v0.2.7`
