### ISSUE TITLE
hz工具的一个bug：当thrift文件出错时，biz目录下没有文件，导致route_gen.go下的代码出错

### ISSUE THREAD

**Issue by xuanweiace** [cloudwego/hertz#591]
**Describe the bug**

使用hz工具生成代码，当所使用的的thrift文件出错时，biz目录下没有文件，导致没有router这个package，导致route_gen.go下的代码出错
**To Reproduce**

**Comment by li-jin-gou** [comment]
目前这是符合预期的，因为 IDL 相关的代码 和 无关代码是分开生成的.

**Comment by xuanweiace** [comment]
> 目前这是符合预期的，因为 IDL 相关的代码 和 无关代码是分开生成的.
> 
> IDL 相关的代码是使用 thrfitgo 或 protoc-gen 生成的，无关代码是工具生成的

那是不是可以考虑，如果报错了，直接也不让工具生成代码了呢？

**Comment by li-jin-gou** [comment]
> > 目前这是符合预期的，因为 IDL 相关的代码 和 无关代码是分开生成的.
> > 
> > IDL 相关的代码是使用 thrfitgo 或 protoc-gen 生成的，无关代码是工具生成的
> 
> 那是不是可以考虑，如果报错了，直接也不让工具生成代码了呢？

的确可以，但是需要评估一下，cc@FGYFFFF

**Comment by FGYFFFF** [comment]
可以优化下~ 感谢反馈
