### ISSUE TITLE
docs: add documentation of etag middleware

### ISSUE THREAD

**Issue by justlorain** [cloudwego/hertz#592]
**Describe the solution you'd like**

We currently lack the documentation of [etag middleware](https://github.com/hertz-contrib/etag), could you please help us supplement this part of the documentation?

**Tips**

- You can refer to other documentation for this, such as [requestid](https://github.com/cloudwego/cloudwego.github.io/blob/main/content/en/docs/hertz/tutorials/basic-feature/middleware/requestid.md).
- You can first complete the Chinese doc and create PR to review. And then translate to English.
- Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by Claude-Zq** [comment]
i want to try😋

**Comment by justlorain** [comment]
> i want to try😋

Thanks!
