### ISSUE TITLE
hertz 如何生成 multipart/form-data 类型的数据结构？

### ISSUE THREAD

**Issue by RexYPX** [cloudwego/hertz#601]
**问题描述**

本人在参加 “第五届字节跳动青训营” 的时候，在完成大作业 “简易抖音开发” 里面需要实现视频上传的功能，客户端（APP）在实现该功能的时候将请求参数 data、token、title 放在了请求体里面。请求体类型需要绑定为 multipart/form-data 类型。

我查看了 hertz 的手册，手册上写了 hertz 可以通过 form 这个 tag 将请求体的内容类型绑定为 multipart/form-data （链接：https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/binding-and-validate/ ）。

但是我在我的 thrift 文件里面指定了api.form之后，使用 hz 命令行工具自动生成框架，在传入 multipart/form-data 类型的请求后却无法无法通过 hertz 的绑定与验证函数(BindAndValidate)，所以提一个 issue 问一下 hertz 如何生成 multipart/form-data 类型的数据结构？

**idl**：
``` 
// publish.thrift
struct PublishActionRequest {
    1: string token (api.form="token")
    2: binary data (api.form="data")
    3: string title (api.form="title")
}

struct PublishActionResponse {
    1: i32 status_code
    2: string status_msg
}

service PublishService {
    PublishActionResponse PublishAction(1: PublishActionRequest req) (api.post="/douyin/publish/action/")
}
```

**Command**：
```
hz new -idl publish.thrift
```

**Screenshots**：

![1253c2474ec2a57038723c65f563ed2](https://user-images.githubusercontent.com/42105043/217201003-4a080e7b-e881-47a7-9296-ee35b1559ce1.png)

下图为手机抓包软件抓到的APP发送的包和响应的包。
#286为发送的 multipart/form-data 类型的请求，#285为上一次发送的 multipart/form-data 类型请求的响应（因为请求过长所以这样截图，#285是对与 #286相同请求的响应）
![12f3af56952e466d02dea49bc189f67](https://user-images.githubusercontent.com/42105043/217202710-03614d2d-93fc-455d-a32c-a754e7db97ee.jpg)

**Comment by li-jin-gou** [comment]
文件内容不支持生成，用 `ctx.FormFile()` 获取 & 可以按照 issue 模版填写 issue 否则会导致 issue.

**Comment by StellarisW** [comment]
> 文件内容暂时不支持生成，用 `ctx.FormFile()` 获取 & 可以按照 issue 模版填写 issue 否则会导致 issue.

后续是否可以支持此类操作

比如
```idl
// publish.thrift
struct PublishActionRequest {
    1: string token (api.form="token")
    2: binary data (api.form="data")
    3: string title (api.form="title")
}
```

生成
```go
type PublishActionRequest struct {
	Token   string `thrift:"token,1" form:"token" json:"token"`
        Data *os.File `thrift:"data,1" form:"data" json:"data"`
        Title string `thrift:"title,1" form:"title" json:"title"`
}
```

**Comment by li-jin-gou** [comment]
cc @FGYFFFF

**Comment by FGYFFFF** [comment]
目前 idl 暂时无 "multipart.File" 对应的类型。可以使用 binary 定义文件，并通过 FromFile 获取文件头，并手动赋值给结构体对应的 field。
后续等待hertz 参数绑定重构后，这部分内容也会有预期的优化

**Comment by Duslia** [comment]
It seems that there is no process recently, so I close this issue.

**Comment by miraclejzd** [comment]
> 目前 idl 暂时无 "multipart.File" 对应的类型。可以使用 binary 定义文件，并通过 FromFile 获取文件头，并手动赋值给结构体对应的 field。 后续等待hertz 参数绑定重构后，这部分内容也会有预期的优化

现在 hertz 对于 IDL 定义的接口依旧不支持文件绑定，后续会有计划支持吗。

**Comment by GuangmingLuo** [comment]
@miraclejzd 不要在 close 的issue下面提问，新开一个 Issue
