### ISSUE TITLE
应用启动监听后一直打印日志

### ISSUE THREAD

**Issue by Hsirehc** [cloudwego/hertz#602]
engine.go:434: [Error] HERTZ: Error=read tcp 127.0.0.1:9957->127.0.0.1:38922: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr=127.0.0.1:38922
engine.go:434: [Error] HERTZ: Error=read tcp 127.0.0.1:9957->127.0.0.1:51260: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr=127.0.0.1:51260

**Comment by L2ncE** [comment]
Please follow the issue template.

**Comment by li-jin-gou** [comment]
> Please follow the issue template to give more info.

+1

**Comment by li-jin-gou** [comment]
The information is so small and not filled out as required by the template that there is no way to troubleshoot the problem
