### ISSUE TITLE
Hijack not dropping connection immediately but returns 404

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#606]
**Describe the bug**

Hijack not dropping connection immediately but returns 404

**To Reproduce**
```
HijackHandlerHertz = func(c network.Conn) {
  c.Close()
  return
}
ctx.Hijack(HijackHandlerHertz) // returns 404 instead of dropping conneciton and not returning anything.
```

**Expected behavior**

drop connection immediately without further processing, without returning anything.

**Screenshots**

returns 404 not found

**Hertz version:**

0.5.1

**Environment:**

go 1.20

**Comment by Duslia** [comment]
HijackHandler is not used for close conn. It is used for websocket.

**Comment by Duslia** [comment]
You can read the comment. 
<img width="908" alt="image" src="https://user-images.githubusercontent.com/37136584/218290397-476f0ecd-1434-4091-8345-5431be53c91b.png">

**Comment by ultperf** [comment]
how do i drop connection immediately?
if badIP(ip) {
    how to drop connection here?
}

**Comment by wzekin** [comment]
you can use `WithOnAccept` when you init your server like this:

``` go
h := server.New(server.WithOnAccept(func(conn net.Conn) context.Context {
	// do something
}))
```

**Comment by ultperf** [comment]
@Duslia @wzekin i have drop bad ips inside withonaccept already but there's internal mechanism to detect queries, and in my logic if there's multiple bad queries made, the ip will be made bad and then drop inside and AFTER withonaccept.
for this query, how do i drop as fast as possible?

also, withonaccept only works if server is directly facing the client.
in my server, it's mostly fronted by cloudflare or other proxies. so still need to use x-forwarded-for ip to DROP connection as fast as possible. how do i this drop?

**Comment by li-jin-gou** [comment]
Not supported, establishing a connection is a Tcp level job, but x-forwarded-for is an HTTP header field and the protocol is not a hierarchy. You can read the data from the connection yourself to determine this, but hertz will not support it.

**Comment by ultperf** [comment]
@li-jin-gou i already did the data reading from the connection. i have the ip.

now i want to drop the connection. how do i drop the connection asap? (i already detected as badip)
the problem is, i did hijack 
```
HijackHandlerHertz = func(c network.Conn) {
  c.Close()
  return
}
ctx.Hijack(HijackHandlerHertz) // returns 404 instead of dropping conneciton and not returning anything.
```
this way but it returns 404 instead of not returning anything.

how to not return anything?
