### ISSUE TITLE
how to fastest drop a ctx without returning any values? just drop ctx or ctx without returning values

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#609]
**Describe the Question**

how to fastest drop a ctx without returning any values? just drop ctx or ctx without returning values

**Reproducible Code**
```
package main

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/network"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

func main() {
	h := server.Default(server.WithOnAccept(func(conn network.Conn) context.Context {
		addr := conn.LocalAddr().String()
		hlog.Info(addr)
		return context.Background()
	}))
	h.GET("/fastdrop", func(c context.Context, ctx *app.RequestContext) {
		_, cancel := context.WithCancel(c)
		cancel()
		
		//this returns 404, which is wrong. should return nothing
	        //how to drop ctx? hijack or something?
	        //dont return anything? no status code, no html, nothing. how?
	})
	h.Spin()
}
```
**Expected behavior**

nothing returned

**Hertz version:**
0.5.1

**Environment:**
go 1.20
**Additional context**
currently returns something to client. i want nothing returned and fastest drop of ctx asap, better still close the connection or something

**Comment by ultperf** [comment]
@li-jin-gou @Duslia @welkeyever 
is there a way to not return anything? "cancel" the ctx. what's the command for cancelling ctx?

this is my last area.

**Comment by ultperf** [comment]
hertz is used behind reverse proxy so needing only to drop the ctx (or conn of this particular ctx), whichever way to drop fastest without returning anything

**Comment by ultperf** [comment]
currently doing this
```
		_, cancel := context.WithCancel(*cc)
		cancel()
		ctx.Response.Header.Reset()
		ctx.Response.Header.SetStatusCode(429)
		ctx.SetBodyString("")
```

possible to NOT return? means dropped or dont return anything.

**Comment by Duslia** [comment]
You can try `ctx.GetConn().Close()`

**Comment by ultperf** [comment]
@Duslia 
ctx.GetConn().Close() seems to return header status 429
possible to not return anything at all?

**Comment by Duslia** [comment]
Please debug by yourself. Hertz won'd return this status code.
