### ISSUE TITLE
文件上传

### ISSUE THREAD

**Issue by whzhades** [cloudwego/hertz#614]
**Describe the Question**

我现在需求是接受把form表单多个 file 然后存到第三方云上 我这边想的是 获取到file后直接把tmpfile存到第三方上 从官方damo里
看到 SaveUploadedFile 这个函数 但是我理解的是这个函数是把form表单的文件保存到本地是 然后我想的是 form表单接受过来的临时文件直接上传到第三方云里 但是发现好像这个tmpfile不能外部调用 

**Reproducible Code**

		form, _ := c.MultipartForm()
		files := form.File["file"]

		for _, file := range files {
			fmt.Println(file.Filename)

			// Upload the file to specific dst.
			c.SaveUploadedFile(file, fmt.Sprintf("./file/upload/%s", file.Filename))
		}

                type FileHeader struct {
	                Filename string
	                Header   textproto.MIMEHeader
	                Size     int64
                
	                content []byte
	                tmpfile string
                }

**Screenshots**

<img width="526" alt="image" src="https://user-images.githubusercontent.com/26140445/218971920-69e37751-226e-48ff-805c-05203adef0d4.png">

![image](https://user-images.githubusercontent.com/26140445/218971966-646c234a-9e5b-44ef-9685-0099a2f2b97b.png)

If applicable, add screenshots to help explain your question.

**Comment by welkeyever** [comment]
```
form, _ := c.MultipartForm()
files := form.File["file"]
```

As you pasted above `FileHeader` is a standard API from Golang. It provide many APIs  that you need in file process Scene.
Such `openedFile := files.Open()` that to get a `Reader` from it. Read it and save it to anywhere you want.

Actually, it's not really a hertz-related issue.

**Comment by whzhades** [comment]
> 

我想要那个临时文件的路径，有办法获取到吗

**Comment by li-jin-gou** [comment]
> ```
> form, _ := c.MultipartForm()
> files := form.File["file"]
> ```
> 
> As you pasted above `FileHeader` is a standard API from Golang. It provides many APIs that you need in file process Scene. Such as `openedFile := files.Open()` that to get a `Reader` from it. Read it and save it to anywhere you want.
> 
> Actually, it's not really a hertz-related issue.

Please follow the above reply and check the GO API documentation.
