### ISSUE TITLE
hz update error

### ISSUE THREAD

**Issue by jjeejj** [cloudwego/hertz#615]
**Describe the Question**
更新 proto 文件后执行 hz updae 报错
![96aa2313-2184-41d3-95b3-0f7ea746cf92](https://user-images.githubusercontent.com/15176971/218980145-727d36e8-be4e-4010-a34f-52109b0b6fff.png)

**Hertz version:**
hz version v0.5.2

**Environment:**
GO111MODULE="on"
GOARCH="arm64"
GOBIN="/Users/golang/bin"
GOCACHE="/Users/Library/Caches/go-build"
GOENV="/Users/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/golang/pkg/mod"
GOOS="darwin"
GOPATH="/Users/golang"
GOPROXY="https://goproxy.cn,,direct"
GOROOT="/Users/golang/go1.19.2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/golang/go1.19.2/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/work/yw/jhim/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9m/9dhxsp597l71c4q0f2pvln440000gn/T/go-build1590182225=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by FGYFFFF** [comment]
please show your "api.proto"

**Comment by jjeejj** [comment]
> 

syntax = "proto3";

package api;

option go_package = "server/cmd/api";

import "hz.proto";

message LoginRequest {
  string code = 1;
}

message LoginResponse {
  string token = 1;
  int64 expired_at = 2[(api.body) = "expired_at"];
}

service apiService {
  rpc Login (LoginRequest) returns (LoginResponse) {option (api.post) = "/auth/login";}
}

**Comment by FGYFFFF** [comment]
I haven't reproduced the problem, can you post your full idl (including hz.proto) and the commands used?

**Comment by jjeejj** [comment]
> I haven't reproduced the problem, can you post your full idl (including hz.proto) and the commands used?

api.proto
```proto
syntax = "proto3";

package api;

option go_package = "server/cmd/api";

import "hz.proto";

message LoginRequest {
string code = 1;
}

message LoginResponse {
string token = 1;
int64 expired_at = 2[(api.body) = "expired_at"];
}

service apiService {
rpc Login (LoginRequest) returns (LoginResponse) {option (api.post) = "/auth/login";}
}
```

hz.proto
```proto
syntax = "proto2";

package api;

import "google/protobuf/descriptor.proto";

option go_package = "/api";

extend google.protobuf.FieldOptions {
  optional string raw_body = 50101;
  optional string query = 50102;
  optional string header = 50103;
  optional string cookie = 50104;
  optional string body = 50105;
  optional string path = 50106;
  optional string vd = 50107;
  optional string form = 50108;
  optional string go_tag = 51001;
  optional string js_conv = 50109;
}

extend google.protobuf.MethodOptions {
  optional string get = 50201;
  optional string post = 50202;
  optional string put = 50203;
  optional string delete = 50204;
  optional string patch = 50205;
  optional string options = 50206;
  optional string head = 50207;
  optional string any = 50208;
  optional string gen_path = 50301;
  optional string api_version = 50302;
  optional string tag = 50303;
  optional string name = 50304;
  optional string api_level = 50305;
  optional string serializer = 50306;
  optional string param = 50307;
  optional string baseurl = 50308;
}

extend google.protobuf.EnumValueOptions {
  optional int32 http_code = 50401;
}
```
执行命令
<img width="887" alt="image" src="https://user-images.githubusercontent.com/15176971/219254680-51b4d653-1cee-463f-97bc-1acded36ba92.png">

**Comment by FGYFFFF** [comment]
Panic reason: delete the generated "go.mod" under non-gopath, and miss this logic when updating, causing the module variable to become a null pointer
Optimized：https://github.com/cloudwego/hertz/pull/616
