### ISSUE TITLE
[Question]: How could i add a basepath for the root group

### ISSUE THREAD

**Issue by rogerogers** [cloudwego/hertz#620]
**Describe the Question**
- How could I add a basepath for the root group when using hz tool auto-generate router
- Seems the package name of the routers is UpperCamelCase, is that how it's defined?
A clear and concise description of what the question is.

**Reproducible Code**

Please construct a minimum complete and reproducible example for us to get the same error. And tell us how to reproduce it like how you send a request or send what request.

**Expected behavior**
The root group with a basepath like `/api`, `/v1`...

**Screenshots**
![image](https://user-images.githubusercontent.com/40619032/219935134-49ef8dfc-e02c-4027-8548-7042576aa9d0.png)

If applicable, add screenshots to help explain your question.

**Hertz version:**

Please provide the version of Hertz you are using.

**Environment:**

The output of `go env`.

**Additional context**

Add any other context about the question here.

**Comment by FGYFFFF** [comment]
1.  root group "/" is generated by default
2.  "UpperCamelCase" has optimized in https://github.com/cloudwego/hertz/pull/611
