### ISSUE TITLE
 Hertz 基于 IDL 的代码生成能力，类 RPC 调用的 HTTP 请求方式

### ISSUE THREAD

**Issue by wenlong139** [cloudwego/hertz#624]
**Describe the Question**

之前用是 feign 作为RPC框架 Http 作为通信协议 进行 Java微服务的调用,目前部分服务迁移go  存在通过http协议 java使用 feign作为rpc框架, go 使用hertz/Kitex 进行 java-go互相调用的情况
想问一下 hertz/Kitex 如何进行类 RPC 调用的 HTTP 请求方式?

**Reproducible Code**

Please construct a minimum complete and reproducible example for us to get the same error. And tell us how to reproduce it like how you send a request or send what request.

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your question.

**Hertz version:**

Please provide the version of Hertz you are using.

**Environment:**

The output of `go env`.

**Additional context**

Add any other context about the question here.

**Comment by li-jin-gou** [comment]
可以看下这个 https://github.com/cloudwego/cloudwego.github.io/pull/521/files#diff-50833553ce8c4afda33e6d198b9ec69d4f305770885b3ef920eabff96168158f 目前文档还有一些 style 需要调整。

**Comment by wenlong139** [comment]
这个好像没有解决  java go互调的问题

**Comment by li-jin-gou** [comment]
hertz 支持服务注册与发现，可以看下相关的文档。



---Original---
From: "Old ***@***.***&gt;
Sent at: 2023年2月21日(Tue) AM9:42
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cloudwego/hertz]  Hertz 基于 IDL 的代码生成能力，类 RPC 调用的 HTTP 请求方式 (Issue #624)




 
这个好像没有解决  java go互调的问题

**Comment by xuyang404** [comment]
> https://www.cloudwego.io/docs/hertz/tutorials/toolkit/client/

404
