### ISSUE TITLE
Can the hertz file download directly use the file byte stream？

### ISSUE THREAD

**Issue by chenghonour** [cloudwego/hertz#636]
**Is your feature request related to a problem? Please describe.**

May I ask if the hertz file download can directly use the file byte stream? so that there is no need to save the file to the disk first.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by li-jin-gou** [comment]
```
c.Response.Header.Set("content-disposition", fmt.Sprintf("attachment; filename=\"%s\"", filename))
c.SetBodyStream(reader, size) 
```

**Comment by li-jin-gou** [comment]
File downloads can use chunked encoding
