### ISSUE TITLE
pls chk this repo "gain" for faster tcp stack

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/hertz#639]
**Is your feature request related to a problem? Please describe.**
too slow.

**Describe the solution you'd like**
use this for speed up
https://github.com/pawelgaczynski/gain

**Describe alternatives you've considered**
bytedance/monoio (rust)

**Additional context**

pls consider the repo suggested
https://github.com/pawelgaczynski/gain
thx

**Comment by li-jin-gou** [comment]
hello @ultperf  hertz support custom network layer， you can do it refer to documation.

**Comment by li-jin-gou** [comment]
https://www.cloudwego.io/docs/hertz/tutorials/framework-exten/advanced-exten/

**Comment by welkeyever** [comment]
Thanks for your report! We will look into it later.
And if you are interested, PR is welcome.

**Comment by gityh2021** [comment]
May I try this?

**Comment by welkeyever** [comment]
> May I try this?

Assigned @gityh2021

**Comment by gityh2021** [comment]
> @gityh2021 how's progress?

I discuss with @li-jin-gou, it seems that this issue is not so meaningful to hertz.

**Comment by li-jin-gou** [comment]
welcome to make a pull request @kolinfluence

**Comment by li-jin-gou** [comment]
same to https://github.com/cloudwego/netpoll/issues/77 and I found the issue to be repetitive, so much so that I closed the current issue.
