### ISSUE TITLE
hz(v0.6.0) failed to execute under windows

### ISSUE THREAD

**Issue by Nihilism0** [cloudwego/hertz#642]
**Describe the bug**

使用hz工具 hz new命令出现问题

**To Reproduce**

![image](https://user-images.githubusercontent.com/114405451/221545715-83bfd7e8-641c-4930-8388-c6a84b176002.png)
在此目录下创建文件,终端输入了hz new -module Hertz_demo命令,生成以下代码和报错
![image](https://user-images.githubusercontent.com/114405451/221546287-5a2f04b3-e721-49ee-b6dc-478cdda92775.png)
![image](https://user-images.githubusercontent.com/114405451/221546369-611940f7-25ca-4f27-84f9-7297c587f43b.png)

**Expected behavior**

生成正确代码

**Hertz version:**
hz version v0.6.0

**Environment:**

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Ambrose\AppData\Local\go-build
set GOENV=C:\Users\Ambrose\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Ambrose\sdk\go1.19.1\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Ambrose\sdk\go1.19.1;C:\Users\Ambrose\sdk\go1.19.1\bin
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=C:\Users\Ambrose\sdk\go1.19.2
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\Ambrose\sdk\go1.19.2\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\Ambrose\GolandProjects\Hertz_demo\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\Ambrose\AppData\Local\Temp\go-build1374903441=/tmp/go-build -gno-record-gcc-switches

**Additional context**

**Comment by FGYFFFF** [comment]
本地试了下，没啥问题。你试试换一个module名呢？这或许是windows 下的问题

**Comment by Nihilism0** [comment]
![image](https://user-images.githubusercontent.com/114405451/221555358-fb419afe-1214-4f17-9eec-b357e5831e1f.png)
一样的情况

**Comment by FGYFFFF** [comment]
emmm. 有可能是 windows 下的问题，一会我试试

**Comment by FGYFFFF** [comment]
https://github.com/cloudwego/hertz/issues/642 fix the problem.

you can try it :
`
go install github.com/cloudwego/hertz/cmd/hz@fix/pkg_error_windows
`
or
`
go install github.com/cloudwego/hertz/cmd/hz@ab0f85e0cf16fa377f4258a999fa38643dba2d25
`
