### ISSUE TITLE
hertz代码生成工具bug

### ISSUE THREAD

**Issue by quarkcms** [cloudwego/hertz#650]
当根目录存在go.mod的情况下；在子目录里执行代码生成命令，子目录里也会生成go.mod文件；
在kitex工具里就不会出现这个问题
![image](https://user-images.githubusercontent.com/60868863/222662792-f07eafc8-2eb9-4981-a500-4a7ea0908ddb.png)

**Comment by FGYFFFF** [comment]
最新版本(v0.6.1)，添加了这个 Feature。

**Comment by FGYFFFF** [comment]
有个最佳实践：https://github.com/cloudwego/biz-demo/pull/26

**Comment by quarkcms** [comment]
不起作用
![image](https://user-images.githubusercontent.com/60868863/222678746-b67db1f3-5430-4435-9c6a-7752e642b736.png)

**Comment by FGYFFFF** [comment]
- 如果想复用上层的 go.mod，那么不需要指定"-mod"，否则就会使用指定的 module，他的优先级较高
- kitex 如果你指定 "-mod" 应该也不会去复用上层的 go.mod

可以看下我上面发的那个最佳实践，代码结构和你目前的是一样的
