### ISSUE TITLE
istio部署的服务，注册中心为consul，但是api服务call rpc服务时报错err:remote or network error: invalid payload

### ISSUE THREAD

**Issue by booldesign** [cloudwego/hertz#651]
**istio部署的服务，注册中心为consul，但是api服务掉rpc服务时报错**

err:remote or network error: invalid payload (first4Bytes=0x48545450, second4Bytes=0x2f312e31)

**Reproducible Code**
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cloud
spec:
  hosts:
    - "*"
  gateways:
    - test-gateway 
  http:
    - match:
        - headers:
            branch:
              exact: feature_0227_test
      route:
        - destination:
            host: usercenter-api
            subset: v1
            port:
              number: 8100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: usercenter-app
spec:
  hosts:
    - usercenter-app
  tcp:
    - match:
        - port: 8100
      route:
        - destination:
            host: usercenter-app
            subset: v1

**Comment by li-jin-gou** [comment]
这似乎是一个 Kitex 的问题而不是 Hertz ，另外 issue 格式不符合会被机器人自动关掉。

**Comment by li-jin-gou** [comment]
same to https://github.com/cloudwego/kitex/issues/674
