### ISSUE TITLE
不支持32位系统使用？

### ISSUE THREAD

**Issue by junbin-yang** [cloudwego/hertz#654]
尝试在armv7l架构的系统上使用报错：
`package main

import (
    "context"

    "github.com/cloudwego/hertz/pkg/app"
    "github.com/cloudwego/hertz/pkg/app/server"
    "github.com/cloudwego/hertz/pkg/common/utils"
    "github.com/cloudwego/hertz/pkg/protocol/consts"
)

func main() {
    h := server.Default(server.WithTransport(standard.NewTransporter))

    h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
            ctx.JSON(consts.StatusOK, utils.H{"message": "pong"})
    })

    h.Spin()
}`

`root@raspberrypi:/data/go/src/hertz_demo# go build
# github.com/cloudwego/netpoll
../../pkg/mod/github.com/cloudwego/netpoll@v0.3.1/sys_sendmsg_linux.go:41:11: cannot use uint64(iovLen) (value of type uint64) as type uint32 in struct literal
../../pkg/mod/github.com/cloudwego/netpoll@v0.3.1/sys_zerocopy_linux.go:33:9: cannot use sec (variable of type int64) as type int32 in struct literal
../../pkg/mod/github.com/cloudwego/netpoll@v0.3.1/sys_zerocopy_linux.go:34:9: cannot use usec (variable of type int64) as type int32 in struct literal
# github.com/henrylee2cn/ameda
../../pkg/mod/github.com/henrylee2cn/ameda@v1.4.10/int.go:13:9: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in return statement (overflows)
../../pkg/mod/github.com/henrylee2cn/ameda@v1.4.10/uint.go:13:9: cannot use math.MaxUint64 (untyped int constant 18446744073709551615) as uint value in return statement (overflows)`

**Comment by li-jin-gou** [comment]
请按照 issue 模版填写 @junbin-yang 参考 https://github.com/cloudwego/hertz/issues/561
