### ISSUE TITLE
不支持32位系统使用？

### ISSUE THREAD

**Issue by junbin-yang** [cloudwego/hertz#655]
**Describe the Question**

无法在32位系统上使用hertz

**Reproducible Code**

package main

import (
    "context"

    "github.com/cloudwego/hertz/pkg/app"
    "github.com/cloudwego/hertz/pkg/app/server"
    "github.com/cloudwego/hertz/pkg/common/utils"
    "github.com/cloudwego/hertz/pkg/protocol/consts"
)

func main() {
    h := server.Default(server.WithTransport(standard.NewTransporter))

    h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
            ctx.JSON(consts.StatusOK, utils.H{"message": "pong"})
    })

    h.Spin()
}

**Expected behavior**

支持armv7l等架构系统

**Screenshots**

If applicable, add screenshots to help explain your question.

**Hertz version:**

hertz@v0.6.0

**Environment:**

GO111MODULE="on"
GOARCH="arm"
GOBIN="/data/go/bin"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/data/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/data/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOARM="6"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/go/src/hertz_demo/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2907447826=/tmp/go-build -gno-record-gcc-switches"

**Additional context**

`root@raspberrypi:/data/go/src/hertz_demo# go build

github.com/cloudwego/netpoll
../../pkg/mod/github.com/cloudwego/netpoll@v0.3.1/sys_sendmsg_linux.go:41:11: cannot use uint64(iovLen) (value of type uint64) as type uint32 in struct literal
../../pkg/mod/github.com/cloudwego/netpoll@v0.3.1/sys_zerocopy_linux.go:33:9: cannot use sec (variable of type int64) as type int32 in struct literal
../../pkg/mod/github.com/cloudwego/netpoll@v0.3.1/sys_zerocopy_linux.go:34:9: cannot use usec (variable of type int64) as type int32 in struct literal

github.com/henrylee2cn/ameda
../../pkg/mod/github.com/henrylee2cn/ameda@v1.4.10/int.go:13:9: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in return statement (overflows)
../../pkg/mod/github.com/henrylee2cn/ameda@v1.4.10/uint.go:13:9: cannot use math.MaxUint64 (untyped int constant 18446744073709551615) as uint value in return statement (overflows)`

**Comment by li-jin-gou** [comment]
cc @joway netpoll 32位的报错

**Comment by li-jin-gou** [comment]
netpoll 不支持 @junbin-yang
