### ISSUE TITLE
Request for help: adding docs for response writer hijack feature

### ISSUE THREAD

**Issue by welkeyever** [cloudwego/hertz#656]
**Is your feature request related to a problem? Please describe.**

In v0.6.0, we have released a feature that allow users to hijack the writer of the response - which provides another way for response writing process.

Based on the feature, we also embed a custom writer which allow users to flush chunk immediately during the handler process.

Docs for both of above are unfinished.

**Describe the solution you'd like**

Adding docs under [here](https://www.cloudwego.io/docs/hertz/tutorials/framework-exten/), and the repo is [this](https://github.com/cloudwego/cloudwego.github.io).
Partly done is Ok:
- [ ] English Version
- [ ] Chinese Version

**Additional context**

Design info: https://github.com/cloudwego/hertz/pull/610.
Example for how to use the embed chunk writer is [here](https://github.com/cloudwego/hertz/pull/610/commits/9c739b225c260142afda86872145763df266855b).

**Comment by a631807682** [comment]
Can i try it?

**Comment by welkeyever** [comment]
Thanks a lot~@a631807682
