### ISSUE TITLE
关于`-handler_dir` 参数的疑惑？

### ISSUE THREAD

**Issue by ryan961** [cloudwego/hertz#657]
https://github.com/cloudwego/hertz/blob/990b814ec9b3159e9e2390591a9a1eb74729cc03/cmd/hz/generator/handler.go#L62

此处的 m.OutputDir 的是否设置可以为空？
我已经通过 `-handler_dir test` 指定了 `*_service.go` 文件的生成路径，但是生成出来中间却默认嵌套了一层。我也尝试了通过 `-handler_by_method` 参数来生成，虽然符合需求，但当 method 多了以后文件就多了。这个设计是有什么特殊用意吗？（文档中有提到 `api.gen_path` 相关的我没看懂，源代码我看已经变成了 api.handler_path）

**Comment by FGYFFFF** [comment]
之所以添加一层的原因是为了做多 idl 的 namespace 分离。
例如，增加了一个 idl 文件后，如果都统一生成到 "biz/handler" 下的话，可能会产生预期之外的命名冲突。
-------------------
"api.handler_path" 配合 "-handler_by_method" 使用，我想这种方式可能更适合你。
```
service Hertz {
    Resp Method1(1: MultiTypeReq request) (api.get="/company/department/group/user:id/name", api.handler_path="v1");
    Resp Method2(1: MultiTagReq request) (api.post="/company/department/group/user:id/sex", api.handler_path="v1");
    Resp Method3(1: BaseType request) (api.put="/company/department/group/user:id/number", api.handler_path="v1");
    Resp Method4(1: data.DataType request) (api.delete="/company/department/group/user:id/age", api.handler_path="v1");
}
```
-------------------
另外 "gen_path" 这块是在文档哪里看到的，我去修改下~

**Comment by li-jin-gou** [comment]
issue 不按照模版添加会被自动关闭 cc @ryan961

**Comment by FGYFFFF** [comment]
@ryan961 可以把你想生成的结构简单列出来吗？
