### ISSUE TITLE
hertz 默认使用 json 反序列化的请求体， 有没有方法 自定义反序列化方法

### ISSUE THREAD

**Issue by jjeejj** [cloudwego/hertz#661]
![56c8293e-3832-44fb-b570-94df9f1a8fa5](https://user-images.githubusercontent.com/15176971/224303695-a0a558fe-0e7a-435a-83fa-6583bc84cb3e.png)

看到 默认使用 json 反序列化的请求体，能不能自定义反序列化的防范？

**Comment by li-jin-gou** [comment]
接受的是一个函数，你自己写一个函数就可以了 @jjeejj 
issue 按照模版写，否则会被 ci close

**Comment by jjeejj** [comment]
> 

具体是哪个方法呢？
