### ISSUE TITLE
a bit unrelated but can someone provide creative solution to this?

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#662]
i'm trying to break down the header and body and method from
ctx *app.RequestContext
so that i can transfer by other protocol instead of http which is a bit more heavy than... redis or grpc etc.

does anyone know how i can distill down the ctx of method, header and body and transfer over the wire with grpc BUT not the whole http header stuff?

e.g. "Content-Method" : GET <- this i would like to transfer as GET in int16 (2 bytes)
is there a way to make all these information reduced and NOT be in http header etc? coz http header overhead is high.

anyone has any creative solution? to transfer http header through grpc or redis pub/sub

is this all or is there more?
https://www.aisangam.com/blog/wp-content/uploads/2019/10/HTTPRequestMessageFormat.png

**Comment by li-jin-gou** [comment]
you can use break point to debug and read some document about hertz
，i  think use break point to debug is a good idea.
