### ISSUE TITLE
[QUESTION] - Is it possible to define optional route parameter?

### ISSUE THREAD

**Issue by sujit-baniya** [cloudwego/hertz#663]
**Describe the Question**
Sometime it's necessary to use optional route parameter while defining routes. For instance, for defining i18n, I would need to define endpoints as:

```go
router.GET("/:lang/terms", hertz.HandlerFunc)
```

Here I explicitly need to define the lang while using route. 

```go
/en/terms
/es/terms
```

**Expected behavior**

If I could define the route as similar

```go
router.GET("/:lang?/terms", hertz.HandlerFunc)
```

I could define the default lang as required when I try to access `/terms`. And any time I can pass param to override default `/es/terms`

**Comment by welkeyever** [comment]
Already supported：https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/route/

**Comment by sujit-baniya** [comment]
@welkeyever I'm sorry but I didn't find any example associated with optional param

**Comment by li-jin-gou** [comment]
![image](https://user-images.githubusercontent.com/97824201/224666755-d481d033-b26c-44da-b7fc-fb09ecca8f29.png)

**Comment by sujit-baniya** [comment]
I'm afraid it's not optional, or is it?

```go
router.GET("/:lang/terms", hertz.HandlerFunc)
```

Can I call above route using `/terms` and not `/en/terms`?

**Comment by li-jin-gou** [comment]
not support

**Comment by sujit-baniya** [comment]
I think it's a good feature to add to library.

**Comment by FGYFFFF** [comment]
> I think it's a good feature to add to library.
Feel free to contribute your thoughts if you can~

**Comment by welkeyever** [comment]
This may break the current way of constructing the trie - /terms and /en/terms belong to two different nodes.

**Comment by Skyenought** [comment]
In fact, all the frameworks I know that support optional param route , only support trailing use, for example `/hello/:world?`,           ` /:world?/hello` is not supported, it's too complex, in fact I think we should avoid using routes this way

**Comment by welkeyever** [comment]
This issue will be closed due to inactivity. Please feel free to reopen it if there is anything new.
