### ISSUE TITLE
[docs]: Update the translation of hertz Getting Started

### ISSUE THREAD

**Issue by Duslia** [cloudwego/hertz#67]
zh web page：https://www.cloudwego.io/zh/docs/hertz/getting-started/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/getting-started/_index.md
en folder：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/en/docs/hertz/getting-started/_index.md

Notes:

- Do not change the original layout, code style or content sequence.
- Software Translator is a tool, not god, do not use the result as the final result.
- Translation principle: faithfulness, expressiveness and elegance.
- Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by liweitingwt** [comment]
Hello， I want to try this, thank you.
