### ISSUE TITLE
how to use goroutine to promote perfermance  in registered router function database operation

### ISSUE THREAD

**Issue by zanlichard** [cloudwego/hertz#673]
h.GET("/flush/chunk", func(c context.Context, ctx *app.RequestContext) {
		// Hijack the writer of response
		ctx.Response.HijackWriter(resp.NewChunkedBodyWriter(&ctx.Response, ctx.GetWriter()))

		for i := 0; i < 10; i++ {
			ctx.Write([]byte(fmt.Sprintf("chunk %d: %s", i, strings.Repeat("hi~", i)))) // nolint: errcheck
			ctx.Flush()                                                                 // nolint: errcheck
			time.Sleep(200 * time.Millisecond)
		}
	})

in this function,/flush/chunk if need to access mysql or redis

**Comment by FGYFFFF** [comment]
Please describe the usage scenario specifically

**Comment by li-jin-gou** [comment]
refer to example https://github.com/cloudwego/hertz-examples/tree/main/streaming and use chunked codes wisely.
