### ISSUE TITLE
whether the number of goroutines the gopool.CtxGo owning can configure?

### ISSUE THREAD

**Issue by zanlichard** [cloudwego/hertz#675]
**Describe the Question**

whether the number of goroutines the gopool.CtxGo owning can configure?

**Reproducible Code**

var runTask = gopool.CtxGo
runTask(c.ctx, task)

**Expected behavior**

configure goroutines amount

**Screenshots**

If applicable, add screenshots to help explain your question.

**Hertz version:**

  v0.5.2

**Environment:**

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3852811340=/tmp/go-build -gno-record-gcc-switches"

**Additional context**

Add any other context about the question here.

**Comment by FGYFFFF** [comment]
What are your requirements?  Maybe you can set it by `gopool.SetCap()`
