### ISSUE TITLE
how to use goroutine to promote perfermance in registered router function database operation

### ISSUE THREAD

**Issue by zanlichard** [cloudwego/hertz#676]
**Describe the Question**
how to use goroutine to promote perfermance in registered router function database operation
**Reproducible Code**

      h.GET("/flush/chunk", func(c context.Context, ctx *app.RequestContext) {
                 //here access database such as redis or mysql
                //how to create goroutine to access
	})

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your question.

**Hertz version:**

0.5.2

**Environment:**

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3852811340=/tmp/go-build -gno-record-gcc-switches"

**Additional context**

Add any other context about the question here.

**Comment by welkeyever** [comment]
Not sure understand your question.
[Writer hijack](https://www.cloudwego.io/blog/2023/03/02/hertz-release-v0.6.0/#http11-supports-for-response-writer-hijacking) provide another way of writing response.
If your response data is related to a outcome from a time consuming operation, there is nothing to promote by using goroutine.

**Comment by welkeyever** [comment]
Is this issue solved? If not, some more context can be added.
