### ISSUE TITLE
Proposal: add Protocol method Or Field in ResponseHeader

### ISSUE THREAD

**Issue by lgbgbl** [cloudwego/hertz#679]
**Is your feature request related to a problem? Please describe.**
hertz doesn't have an effective way to acquire http protocol version in response header.

**Describe the solution you'd like**
add `Protocol` method Or Field in ResponseHeader

**Comment by li-jin-gou** [comment]
HTTP response does not have protocol and method fields and refer to https://developer.mozilla.org/en-US/docs/Glossary/Response_header

**Comment by li-jin-gou** [comment]
![image](https://user-images.githubusercontent.com/97824201/226237349-18a699f4-8961-471f-860d-f7db81cd7b30.png)

**Comment by lgbgbl** [comment]
Sorry, it may not exist in http Response Header. I just wonder how to get http protocol version from status-line in http response in hertz quickly. https://www.rfc-editor.org/rfc/rfc2616#section-6.1
