### ISSUE TITLE
再次调用h.SetHTMLTemplate(tmpl2),并未改变*app.RequestContext的HTMLRender的指针地址

### ISSUE THREAD

**Issue by springrain** [cloudwego/hertz#683]
**Describe the bug**

再次调用h.SetHTMLTemplate(tmpl),并未改变*app.RequestContext的HTMLRender的指针地址

模板更新之后,重复注册会有异常,所以声明了新的Template对象,并调用 h.SetHTMLTemplate(tmpl2)

**To Reproduce**

1. h.SetHTMLTemplate(tmpl)
2. h.SetHTMLTemplate(tmpl2)
3. 路由中*app.RequestContext的HTMLRender一直是第一次设置的tmpl指针地址

**Expected behavior**

希望设置 h.SetHTMLTemplate(tmpl2)之后,关联对象都变更为最新的

**Hertz version:**

v0.6.0

**Environment:**

```
set GOVERSION=go1.20.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\SPRING~1\AppData\Local\Temp\go-build1711418186=/tmp/go-build -gno-record-gcc-switches
````

**Comment by FGYFFFF** [comment]
Maybe you can try "auto-reloading", more information can be found at https://github.com/cloudwego/hertz/pull/207

**Comment by springrain** [comment]
我的场景是必须使用SetHTMLTemplate方法的,这个方法调用的是HTMLProduction,不是HTMLDebug
我目前是未改变指针地址实现的
```go
*tmpl = *loadTmpl
```

**Comment by FGYFFFF** [comment]
@springrain 能在详细描述下使用场景，或者给出一个简单的demo吗？我现在无法确定你的问题？
你是指在多次调用"SetHTMLTemplate"后，实际上 html render 的模板还是无法改变吗？这个配置应该在 server 启动前配置，你是在server 启动后配置了吗？

**Comment by springrain** [comment]
> @springrain 能在详细描述下使用场景，或者给出一个简单的demo吗？我现在无法确定你的问题？ 你是指在多次调用"SetHTMLTemplate"后，实际上 html render 的模板还是无法改变吗？这个配置应该在 server 启动前配置，你是在server 启动后配置了吗？

gpress是类似wordpress的开源项目,要读取自定义的主题,gpress并不知道主题的目录结构和模板文件,所以读取了所有的模板文件,然后[loadTmpl.New(relativePath)](https://gitee.com/gpress/gpress/blob/master/utilHertz.go#L72),主题是可以在线编辑的,所以需要重新加载模板文件,是在server启动前调用 [h.SetHTMLTemplate(tmpl)](https://gitee.com/gpress/gpress/blob/master/utilHertz.go#L28) ,用户修改模板后,reload,再次调用[h.SetHTMLTemplate(tmpl)](https://gitee.com/gpress/gpress/blob/master/utilHertz.go#L89),问题就是再次调用之后,路由里还是获取的老的模板内容,*app.RequestContext的HTMLRender的指针地址一直都是第一次初始化的tmpl对象的

**Comment by FGYFFFF** [comment]
你不用必须使用"LoadHTMLGlob"，你可以像 "auto-reload" 示例一样:
```
h := server.Default(server.WithAutoReloadRender(true, 0))
h.LoadHTMLGlob("./examples/html_rendering/*")
```
这里会自动加载你更新后的内容。你不需要关心他的实现~

**Comment by springrain** [comment]
> 你不用必须使用"LoadHTMLGlob"，你可以像 "auto-reload" 示例一样:
> 
> ```
> h := server.Default(server.WithAutoReloadRender(true, 0))
> h.LoadHTMLGlob("./examples/html_rendering/*")
> ```
> 
> 这里会自动加载你更新后的内容。你不需要关心他的实现~

gpress并不知道主题的目录结构,这是由周边生态自定义的,如果使用LoadHTMLGlob函数,就需要明确知道目录层级

**Comment by FGYFFFF** [comment]
"h.LoadHTMLGlob"是通配匹配的，但是没有办自动重加载。可以根据你的需求来使用

**Comment by shengjian-tech** [comment]
> "h.LoadHTMLGlob"是通配匹配的，但是没有办自动重加载。可以根据你的需求来使用

LoadHTMLGlob 的统配只到指定目录 比如 ./template/* 并不能加载 ./template/test/a.html,只能加载  ./template/a.html

**Comment by springrain** [comment]
> "h.LoadHTMLGlob"是通配匹配的，但是没有办自动重加载。可以根据你的需求来使用

LoadHTMLGlob 的统配只到指定目录 比如 ./template/* 并不能加载 ./template/test/a.html,只能加载 ./template/a.html

**Comment by FGYFFFF** [comment]
> > "h.LoadHTMLGlob"是通配匹配的，但是没有办自动重加载。可以根据你的需求来使用
> 
> LoadHTMLGlob 的统配只到指定目录 比如 ./template/* 并不能加载 ./template/test/a.html,只能加载 ./template/a.html

刚刚查了下"Glob" 的用法，其实可以写复杂些的通配表示，或者自己来做一个 file 的搜索。总体上 hertz 和 gin 的 setHtmlTemplate 是一致的。也可以去参考下 gin 的用法

**Comment by cuteLittleDevil** [comment]
`
package main

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"html/template"
)

func main() {
	h := server.Default()
	tmpl := template.New("hertz").
		Delims("", "").
		Funcs(template.FuncMap{})
	tmpl.Parse(`1, {{.Name}}!`)
	h.GET("/template1", func(ctx context.Context, c *app.RequestContext) {
		c.HTML(200, "", map[string]string{"Name": "Hertz"})
	})
	h.GET("/template2", func(ctx context.Context, c *app.RequestContext) {
		tmpl2 := template.New("hertz").
			Delims("", "").
			Funcs(template.FuncMap{})
		tmpl2.Parse(`2, {{.Name}}!`)
		//*tmpl = *tmpl2
		h.SetHTMLTemplate(tmpl2)
		c.HTML(200, "", map[string]string{"Name": "Hertz"})
	})
	h.SetHTMLTemplate(tmpl)
	h.Spin()
}

`
	github.com/cloudwego/hertz v0.9.2
![image](https://github.com/user-attachments/assets/e53c187d-d8e9-4d82-824f-33b484ab5a9b)
预期是显示2, Hertz的 		h.SetHTMLTemplate(tmpl2) 这个设置无效了
