### ISSUE TITLE
Proposal: add sse extension

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/hertz#688]
**Is your feature request related to a problem? Please describe.**

Currently Hertz does not support sse extension

**Describe the solution you'd like**

Add a sse extension or add a sse example

**Additional context**

- https://github.com/manucorporat/sse
- https://github.com/gofiber/recipes/tree/master/sse

**Comment by Haswf** [comment]
I would like to work on this.

**Comment by li-jin-gou** [comment]
> I would like to work on this.

thanks @Haswf ❤️

**Comment by jibenliu** [comment]
I'm working on it for one day

**Comment by jibenliu** [comment]
server demo
```
import 	"github.com/manucorporat/sse"

func demo(ctx context.Context, c *app.RequestContext) {
	bt, _ := c.Body()
	fmt.Println(bt)
	c.Response.Header.Set("Content-Type", "text/event-stream")
	c.Response.Header.Set("Cache-Control", "no-cache")
	c.Response.Header.Set("Connection", "keep-alive")
	c.Response.Header.Set("Transfer-Encoding", "chunked")

	for i := 0; i < 10; i++ {
		time.Sleep(2 * time.Second)
		sse.Encode(c.Response.BodyWriter(), sse.Event{
			Id:    "124",
			Event: "message",
			Data: map[string]interface{}{
				"user":    "manu",
				"date":    time.Now().Unix(),
				"content": "hi!",
			},
		})
		c.Flush()
	}
	fmt.Fprintf(c.Response.BodyWriter(), "event: close\ndata: close\n\n") // 一定要带上data，否则无效
}
```

client demo
```
        ctx := context.Background()
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, "http://localhost:8888/sse?appId=1&page=1&pageSize=10", io.NopCloser(strings.NewReader("send message")))
	if err != nil {
		panic(err)
	}
	conn := sse.NewConnection(req)

	_ = conn.SubscribeToAll(func(event sse.Event) {
		fmt.Println(event.String())
		fmt.Println(event.LastEventID)
		fmt.Println(event.Name)
	})
	err = conn.Connect()
	if err != nil {
		panic(err)
	}
```

**Comment by Haswf** [comment]
For anyone who are concerd, [haswf/sse](https://github.com/Haswf/sse/tree/feat_sse) contains sse implementation for Hertz. 

A few things to do:
1. add README
2. add a real-world example e.g. https://github.com/gin-gonic/examples/tree/master/server-sent-event

**Comment by Haswf** [comment]
I ran into a problem that event.Render (which internally calls resp.AppendBody to write event) doesn't trigger a flush, which is required for server-sent event to work. For example, the following code only send response back to client after 10 seconds has elapled and the 2nd event has been rendered. The expected behaviour is http header is immediately returned with 1st event, then the 2nd event is sent after 10 seconds. Can someone know how Hertz response buffer work helps me out?
```
package main

import (
	"context"
	"time"

	"github.com/Haswf/sse"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func main() {
	h := server.Default()

	h.GET("/sse", func(ctx context.Context, c *app.RequestContext) {
		// client can tell server last event it received with Last-Event-ID header
		lastEventID := sse.GetLastEventID(c)
		hlog.CtxInfof(ctx, "last event ID: %s", lastEventID)
		// you can call Render multiple times to send events to client
		c.Render(200, sse.Event{
			Event: "message",
			Data: map[string]string{
				"content": "hello world",
			},
		})
		c.Flush()
		time.Sleep(10 * time.Second)
		c.Render(200, sse.Event{
			Event: "timestamp",
			Data:  time.Now().Format(time.RFC3339),
		})
	})

	h.Spin()
}
```

**Comment by Haswf** [comment]
Postman privodes a reference server-sent event api, which returns immediately then event follows. 
``` bash
curl --location -N 'postman-echo.com/server-events/100'
```

![image](https://user-images.githubusercontent.com/34025121/230779750-2d612097-8152-43b8-87e2-9cf8e104fee9.png)

**Comment by li-jin-gou** [comment]
refer to https://www.cloudwego.io/docs/hertz/tutorials/framework-exten/response_writer/

**Comment by Haswf** [comment]
> refer to https://www.cloudwego.io/docs/hertz/tutorials/framework-exten/response_writer/

Thank you. This problem has been resolved by implementing a StreamBodyWriter according the document you referenced.
