### ISSUE TITLE
[docs]: translate hertz/tutorials/basic-feature/stream

### ISSUE THREAD

**Issue by Duslia** [cloudwego/hertz#69]
zh web page：https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/stream/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/basic-feature/stream.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials

Notes:

- Do not change the original layout, code style or content sequence.
- Software Translator is a tool, not god, do not use the result as the final result.
- Translation principle: faithfulness, expressiveness and elegance.
- Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by Skyenought** [comment]
I want to try this.

**Comment by Duslia** [comment]
Well done!
