### ISSUE TITLE
use proto to generate swager

### ISSUE THREAD

**Issue by yanrongliang** [cloudwego/hertz#692]
hz 的命令可以通过 proto 生成 swagger 吗？类似 grpc-gateway？

**Comment by FGYFFFF** [comment]
Another plugin is needed to generate swagger(https://github.com/google/gnostic/tree/main/cmd/protoc-gen-openapi):
- You can use the 'hz plugin extension' to integrate the plugin. (https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/plugin/#%E7%A4%BA%E4%BE%8B-1)
- Or you can use the protoc command directly to generate.

Make sure your go_package is defined as follows:
`option go_package="{$MODULE_NAME}/{$MODEL_DIR}/xxx"`
