### ISSUE TITLE
long running process crashed here

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/hertz#693]
**Describe the bug**

long running process crashed

**To Reproduce**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb80ca2]

goroutine 359534 [running]:
github.com/cloudwego/hertz/pkg/network/standard.(*Conn).Len(...)
        /root/go/pkg/mod/github.com/cloudwego/hertz@v0.6.0/pkg/network/standard/connection.go:438
github.com/cloudwego/hertz/pkg/network/standard.(*Conn).Read(0x44a693?, {0xc000edce78?, 0x1?, 0x0?})
        /root/go/pkg/mod/github.com/cloudwego/hertz@v0.6.0/pkg/network/standard/connection.go:82 +0x22
io.ReadAtLeast({0x7fcbc1083e90, 0xc000e95780}, {0xc000edce78, 0x9, 0x9}, 0x9)
        /usr/local/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
        /usr/local/go/src/io/io.go:351
github.com/hertz-contrib/http2.readFrameHeader({0xc000edce78?, 0x9?, 0xc00174a880?}, {0x7fcbc1083e90?, 0xc000e95780?})
        /root/go/pkg/mod/github.com/hertz-contrib/http2@v0.1.5/frame.go:253 +0x6e
github.com/hertz-contrib/http2.(*Framer).ReadFrame(0xc000edce40)
        /root/go/pkg/mod/github.com/hertz-contrib/http2@v0.1.5/frame.go:503 +0x95
github.com/hertz-contrib/http2.(*serverConn).readFrames(0xc000ba1500)
        /root/go/pkg/mod/github.com/hertz-contrib/http2@v0.1.5/server.go:526 +0x91
created by github.com/hertz-contrib/http2.(*serverConn).serve
        /root/go/pkg/mod/github.com/hertz-contrib/http2@v0.1.5/server.go:625 +0x4d2
child 1 exited with error: exit status 2

```

**Expected behavior**

pls check the code

**Hertz version:**

0.6.0

**Comment by li-jin-gou** [comment]
I suspect that the use of conn after the request has ended is causing this problem.

**Comment by li-jin-gou** [comment]
If you have time, please take a look. cc @Duslia  @wzekin

**Comment by Duslia** [comment]
What is the HTTP2 version or commit?

**Comment by kolinfluence** [comment]
@Duslia 

        github.com/hertz-contrib/http2 v0.1.5

**Comment by li-jin-gou** [comment]
cc @Duslia

**Comment by Duslia** [comment]
It's hard to debug if it cannot reproduce. You can first update http2 to the latest commit and watch it for a while. If it produce again, you can construct a minimal reproduced demo based on your biz logic. Usually it's with high concurrency or some handler or connection error.

**Comment by Duslia** [comment]
Do you use `ctx.GetConn().Close()` to close connection?

**Comment by wzekin** [comment]
Hello, this issue was caused by coroutine calling the write interface after the connection was closed. Today, we reviewed the exposed interfaces and found that the problem may be caused by your call to `ctx.GetConn().Close()` which closes the connection. Therefore, we have implemented [a fallback version](https://github.com/cloudwego/hertz/pull/698) that can completely solve this issue. Currently, this branch can be used for urgent repairs, but if you are not in a hurry, you can wait for us to verify and release a new version before using it.

**Comment by kolinfluence** [comment]
@wzekin ok i can wait. pls update it.
@Duslia 
yes i used ctx.GetConn().Close() a lot of places. almost everywhere.

pls do mention when the update will happen. coz it's being used in production now.

**Comment by Duslia** [comment]
Hello. If you are using it in production environment, could you pls register [here](https://github.com/cloudwego/hertz/issues/73)?

**Comment by kolinfluence** [comment]
@Duslia i will after this issue is fixed because now it's crashable.

**Comment by kolinfluence** [comment]
when is this fix? it's kind of a serious bug actually.

**Comment by Duslia** [comment]
@kolinfluence  Could you register now? We can set up a Lark group to support.

**Comment by welkeyever** [comment]
> @kolinfluence Could you register now? We can set up a Lark group to support.

@kolinfluence Hi~ Please let me know if you have hertz in your production environment🤗
