### ISSUE TITLE
hz new import path is wrong

### ISSUE THREAD

**Issue by Rainshaw** [cloudwego/hertz#700]
**Describe the bug**
`arg.Cwd` should replace with `arg.OutDir`?

https://github.com/cloudwego/hertz/blob/bec7f37a9ca37e725ba29927fa6b66773ee5bf23/cmd/hz/config/argument.go#L227

**To Reproduce**

1. Run `mkdir test && cd test && go mod init test && hz new -out_dir cmd/api
2. Open 'test/cmd/api/router_gen.go'
4. See import paths:
```
import (
	"github.com/cloudwego/hertz/pkg/app/server"
	router "test/biz/router"
)
```

**Expected behavior**

```
import (
	"github.com/cloudwego/hertz/pkg/app/server"
	router "test/cmd/api/biz/router"
)
```

**Screenshots**

**Hertz version:**

0.6.1

**Environment:**

The output of `go env`.

**Additional context**

**Comment by Rainshaw** [comment]
why this issue closed? I think it is not resolved @FGYFFFF

**Comment by FGYFFFF** [comment]
@Rainshaw The solution is given above and will be optimized subsequently
