### ISSUE TITLE
perf tool show application based on hertz cpu cost too high

### ISSUE THREAD

**Issue by zanlichard** [cloudwego/hertz#701]
**Describe the Question**

A clear and concise description of what the question is.

**Reproducible Code**

Please construct a minimum complete and reproducible example for us to get the same error. And tell us how to reproduce it like how you send a request or send what request.

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your question.

**Hertz version:**

0.5.2

**Environment:**

go 1.19.3

**Additional context**

![61aa9888-e974-4f7f-be47-949f77382836](https://user-images.githubusercontent.com/8087210/229406454-407b892e-9423-42df-ac8a-3f9645419517.jpeg)

**Comment by li-jin-gou** [comment]
use
```
go nev 
```
![image](https://user-images.githubusercontent.com/97824201/229416306-af7295c8-0125-4e4a-b0e9-ddc73d63a1ec.png)

 to copy Environment:

Are you using netpoll or the standard library and Is it possible to provide a code that can be reproduced?

**Comment by zanlichard** [comment]
already compile go code to binary
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/lichard/go-workspace/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lichard/go-workspace"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/lichard/userstate/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1784992758=/tmp/go-build -gno-record-gcc-switches"

**Comment by li-jin-gou** [comment]
We can use https://github.com/hertz-contrib/pprof for CPU sampling.

**Comment by zanlichard** [comment]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/8087210/229424613-dbecece0-3ed5-4260-ac9b-66c7c3f8a5e1.png">

**Comment by zanlichard** [comment]
Use dlv to attach fb_uss process,fb_uss looks like processing no request any more

**Comment by zanlichard** [comment]
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/8087210/229425464-1f9e5232-32ed-4738-85a1-389571a8c498.png">

**Comment by zanlichard** [comment]
Using dlv attach the process fb_uss, but can't find the thread id 13299 or 11160 found by cmd ''top -d 1  -p 11160 -H''

**Comment by li-jin-gou** [comment]
The current clues do not lead to a specific problem, we need more detailed sampling information to locate the problem e.g. using https://github.com/hertz-contrib/pprof and it would be good if a reproducible demo could be provided.

**Comment by zanlichard** [comment]
<img width="833" alt="image" src="https://user-images.githubusercontent.com/8087210/229432799-3176c566-e18b-4f25-9a66-8d513c609fd6.png">

From the picture,we can see that the cpu load dispatchs no balance to every cpu cores

**Comment by li-jin-gou** [comment]
In my personal opinion, this is inefficient and we need more detailed sampling information or a code that can be returned.

**Comment by li-jin-gou** [comment]
> ok,I will offer pprof sample information later

👍🏻
