### ISSUE TITLE
network request transfer delay during  from transport layer to bussiness hander layer over 3 seconds

### ISSUE THREAD

**Issue by zanlichard** [cloudwego/hertz#703]
**Describe the Question**

network request transfer delay during  from transport layer to bussiness hander layer over 3 seconds

**Reproducible Code**
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/8087210/229480771-e89d85b3-07e5-4678-a689-561180c91396.png">

**Expected behavior**
   the http request process less then  1 seconds

**Screenshots**

If applicable, add screenshots to help explain your question.

**Hertz version:**

0.5.2

**Environment:**

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/lichard/go-workspace/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lichard/go-workspace"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1209987262=/tmp/go-build -gno-record-gcc-switches"

**Additional context**

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/8087210/229479683-50da403a-a1b6-41c1-b789-73b739fb7f3e.png">
 
use tcpdump to pick data from network 

![FNJrSsU9jp](https://user-images.githubusercontent.com/8087210/229479793-a131b25a-524f-4904-ba13-f5453465c33e.jpg)

this is bussiness time cost info

http api interface implements below:
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/8087210/229480332-8c82db56-4cbe-4da4-b221-800b2ee2f2cf.png">

**Comment by welkeyever** [comment]
Non-stream mode will wait for all of the body bytes to come before trigger the business handler.
If you wanna process the request as soon as header parsed, try stream read body mode: https://github.com/cloudwego/hertz-examples/blob/main/streaming/streaming_read/main.go

**Comment by zanlichard** [comment]
the timestamp of client sending http request is 16:58:45.314746 record by tcpdump packed file,
the timestamp of http request arriving application's bussiness layer is 16:58:59.198 record by application's tracing log,
even if the application does not use stream read byte mode,the delay from transport layer to business layer should not so big such as 3 seconds

**Comment by welkeyever** [comment]
See if you can construct a minimum recurrence set. If it happens occasionally, it is most likely caused by the network.
