### ISSUE TITLE
google.protobuf.Any hertz bind可以怎样被解析？proto如何支持二维数组？

### ISSUE THREAD

**Issue by laixiaohuai** [cloudwego/hertz#705]
**Describe the Question**

1. hertz bind 不能解析 proto google.protobuf.Any  字段类型
2. proto如何支持二维数组

proto: 
message PostUserReq {
  string Password = 2[(api.query)="password",(api.body)="password,required"];
  string Username = 3[(api.query)="username",(api.body)="username,required"];
  string Nickname = 4[(api.query)="nickname",(api.body)="nickname,required"];
  string Avatar = 5[(api.query)="avatar",(api.body)="avatar"];
  string UserType = 6[(api.query)="user_type",(api.body)="user_type"];
  string Phone = 7[(api.query)="phone",(api.body)="phone"];
  string Email = 8[(api.query)="email",(api.body)="email"];
  string Userid = 9[(api.query)="userid",(api.body)="userid"];
//  bytes Path = 11[(gogoproto.customtype) = "InterfaceType"];
  google.protobuf.Any Path = 11[(api.query)="path,omitempty",(api.body)="path,omitempty"];
//  google.protobuf.Any Path = 11[(api.query)="path,omitempty",(api.body)="path,omitempty"];
  repeated int64 RoleIds = 10[(api.query)="role_ids,omitempty",(api.body)="role_ids,omitempty",(api.go_tag)="gorm:\"-\" ignore:\"yes\""];
//  repeated Role Roles = 20[(api.query)="roles",(api.body)="roles"];
}

**Comment by li-jin-gou** [comment]
@laixiaohuai   这样可以嘛？？
```
message InternalArray {
    repeated int internal_array = 1;
}
repeated InternalArray array = 1;
```

另外我还想到了一个解决方案是你可以自定义 handler ,而不是使用 IDL 定义。
https://github.com/cloudwego/hertz-examples/blob/main/hz/thrift/router.go#L13

hertz 其实并一定需要 IDL 才能初始化。例如 https://github.com/cloudwego/hertz-examples/blob/main/hello/main.go

**Comment by laixiaohuai** [comment]
> @laixiaohuai 这样可以嘛？？
> 
> ```
> message InternalArray {
>     repeated int internal_array = 1;
> }
> repeated InternalArray array = 1;
> ```
> 
> 另外我还想到了一个解决方案是你可以自定义 handler ,而不是使用 IDL 定义。 https://github.com/cloudwego/hertz-examples/blob/main/hz/thrift/router.go#L13
> 
> hertz 其实并一定需要 IDL 才能初始化。例如 https://github.com/cloudwego/hertz-examples/blob/main/hello/main.go

1. 二维数组这么写得到的是{
  "array": [{
    "internalArray": [1, 2]
  }, {
    "internalArray": [3, 4]
  }]
}这么一个数据结构，而我想要的是[[1,2],[3,4]]这种类似数据结构；
2. 用IDL就是想一套代码既支持http，也支持gRPC，省得反复写一个接口；

**Comment by Nihilism0** [comment]
@laixiaohuai 试试这样呢？

message MyMessage {
  repeated int32 rows = 1;
  repeated int32 cols = 2;
  repeated repeated int32 data = 3;
}
data是一个嵌套的重复字段，可以作为一个二维数组

**Comment by laixiaohuai** [comment]
> @laixiaohuai 试试这样呢？
> 
> message MyMessage { repeated int32 rows = 1; repeated int32 cols = 2; repeated repeated int32 data = 3; } data是一个嵌套的重复字段，可以作为一个二维数组

proto不支持这么写

**Comment by li-jin-gou** [comment]
cc @FGYFFFF

**Comment by FGYFFFF** [comment]
1. "proto google.protobuf.Any"：其生成的内容不属于 go 的基本类型，所以需要你对齐自定义一个[参数绑定函数](https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/binding-and-validate/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B1%BB%E5%9E%8B%E8%A7%A3%E6%9E%90)
2.  protobuf 应该没有默认支持多维数组，因此可以像上述回答一样来定义，可参考https://protobuf.dev/programming-guides/proto3/
