### ISSUE TITLE
怎么更新已经注册的路由?

### ISSUE THREAD

**Issue by springrain** [cloudwego/hertz#707]
**Describe the Question**

已经注册的路由,怎么更新HandlerFunc?

**Reproducible Code**

已经注册的路由,怎么更新处理的函数HandlerFunc?
```go
//会报错路由重复注册
h.Handle("GET", "/", nil)
```

**Comment by welkeyever** [comment]
handler 动态生成的需求？注册一个function generator:
```
func generator() app.HandlerFunc {
	switch xxx {
	case 1:
		return func(a context.Context, ctx *app.RequestContext) {
			xxx
		}
	case 2:
		return func(a context.Context, ctx *app.RequestContext) {
			xxx
		}
	}
	return func(c context.Context, ctx *app.RequestContext) {
		xxx	
	}
}

func main() {
	h := server.Default()
	h.Handle("GET", "/", generator())

        xxx
}
```

**Comment by springrain** [comment]
> handler 动态生成的需求？注册一个function generator:
> 
> ```
> func generator() app.HandlerFunc {
> 	switch xxx {
> 	case 1:
> 		return func(a context.Context, ctx *app.RequestContext) {
> 			xxx
> 		}
> 	case 2:
> 		return func(a context.Context, ctx *app.RequestContext) {
> 			xxx
> 		}
> 	}
> 	return func(c context.Context, ctx *app.RequestContext) {
> 		xxx	
> 	}
> }
> 
> func main() {
> 	h := server.Default()
> 	h.Handle("GET", "/", generator())
> 
>         xxx
> }
> ```

这样只是注册时动态选择了一个,注册成功之后 ,也是无法修改的吧

**Comment by li-jin-gou** [comment]
same to https://github.com/cloudwego/hertz/issues/621

**Comment by springrain** [comment]
我目前是使用套壳的hander变相实现了动态替换路由
```go
handler := appFS.NewRequestHandler()
	_, ok := realHandlerFuncMap.Load(relativePath)

	//无论是否已经存在,都先更新到map里
	realHandlerFuncMap.Store(relativePath, handler)

	if ok { //已经存在这个路由注册,只替换值,不添加路由
		return
	}
	// 未添加的路由,添加到路由表里
	urlPattern := path.Join(relativePath, "/*filepath")

	//套壳实现动态替换路由,实际就是记录路径和hander的对应关系,然后通过套壳hander调用实际的hander
	handlerFunc := func(c context.Context, ctx *app.RequestContext) {
		realHandlerFunc, ok := realHandlerFuncMap.Load(relativePath)
		if !ok || realHandlerFunc == nil {
			return
		}
		realHandlerFunc.(app.HandlerFunc)(c, ctx)
	}
	h.GET(urlPattern, handlerFunc)
	h.HEAD(urlPattern, handlerFunc)
```
