### ISSUE TITLE
hertz-curl: an adaption of http2curl for Hertz request

### ISSUE THREAD

**Issue by Haswf** [cloudwego/hertz#709]
**Is your feature request related to a problem? Please describe.**

[http2curl](https://github.com/moul/http2curl) is a handy tool to convert http.Request to curl command, which is compact and supported by many API tools.
I used to convert protocol.Request to http.Request, then use http2curl to generate curl command, but this conversion is tedious and turns out to be expensive.

``` go
// convert hertz request to *http.Request
r, err := adaptor.GetCompatRequest(&c.Request)
if err != nil {
   return nil, fmt.Errorf("get compat request error: %w", err)
}
// log curl command
curl, err := http2curl.GetCurlCommand(r)
if err != nil {
   return nil, fmt.Errorf("get curl command error: %w", err)
}
fmt.Println(curl.String)
```

**Describe the solution you'd like**

In [hertz-curl](https://github.com/Haswf/hertz-curl), adaption has been made for Hertz's request for two purposes:
1. simplify usage by removing never-returned error from return value.
2. improve performance by avoiding unnecessary copying.  See [Benchmark](https://github.com/Haswf/hertz-curl#benchmark) for comparsion.

``` go
cmd := curl.GetCurlCommand(&c.Request)
hlog.Info(cmd.String())
// 2023/04/06 22:33:00.044947 main.go:15: [Info] curl -X 'GET' -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate, br' -H 'Connection: keep-alive' -H 'Host: localhost:8888' -H 'Postman-Token: bc98e52c-e9fd-4c71-895b-9a27d940f151' -H 'User-Agent: PostmanRuntime/7.29.2' 'http://localhost:8888/curl'
c.JSON(consts.StatusOK, utils.H{"curl": cmd.String()})
```

**Describe alternatives you've considered**

This packages uses "curl" as its package name, which might conflict if users wish to use curl as a variable name.
We could use `hcurl` instead, but what the package does become less obvious. 
 
**Additional context**

None

**Comment by li-jin-gou** [comment]
same to https://github.com/li-jin-gou/http2curl/

**Comment by Haswf** [comment]
> same to https://github.com/li-jin-gou/http2curl/

Sign. I don't think this is mentioned anywhere in the document. We should move at least one of the projects to hertz-contribute and add documentation and/or example for it. So people won't create a new fork in the future.

**Comment by Haswf** [comment]
I don't think `req.URI() == nil` check is going to work for Hertz without a tweak because req.URI() always return a non-nil pointer regardless whether SetRequestURI is called. 

```go 
// GetCurlCommand returns a CurlCommand corresponding to an http.Request
func GetCurlCommand(req *http.Request) (*CurlCommand, error) {
	if req.URL == nil {
		return nil, ErrorURINull
	}
}

``` 

The following change solves this problem.
``` go

func GetCurlCommand(req *protocol.Request) (*Command, error) {
	if req.URI().String() == "http:///" {
		return nil, ErrRequestURINotSet
	}
}

```

**Comment by li-jin-gou** [comment]
won't be considered for now
