### ISSUE TITLE
[docs]: translate hertz/tutorials/basic-feature/protocol, log, err handle

### ISSUE THREAD

**Issue by Duslia** [cloudwego/hertz#71]
protocol: 
zh web page：https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/protocol/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/basic-feature/protocol.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials

log:
zh web page：https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/log
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/basic-feature/log.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials

error handle:
zh web page：https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/error-handle/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/basic-feature/error-handle.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials

Notes:

Do not change the original layout, code style or content sequence.
Software Translator is a tool, not god, do not use the result as the final result.
Translation principle: faithfulness, expressiveness and elegance.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by Jacob953** [comment]
Hi, @Duslia! Plz assign this to me.
