### ISSUE TITLE
how do i show how much byte allocate / heap escape per request made through the golang app using hertz?

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/hertz#711]
how do i show how much byte allocate / heap escape per request made through the golang app using hertz?

is there a way to show heap escape analysis or garbage generated per request with log.Printf output or something?

**Comment by li-jin-gou** [comment]
This has nothing to do with hertz, it relies on go's pprof and label, https://pkg.go.dev/runtime/pprof.
