### ISSUE TITLE
How to ensure concurrent safety of protocol.Response?

### ISSUE THREAD

**Issue by justlorain** [cloudwego/hertz#719]
**Describe the Question**

How to ensure concurrent safety of `protocol.Response` in concurrent cases?

**Expected behavior**

Multiple gorountine sets the response at the same time without concurrency issues.

**Hertz version:**

v0.6.2

**Environment:**

go 1.18

**Comment by li-jin-gou** [comment]
Concurrent responses are not supported and you will need to secure them yourself.
