### ISSUE TITLE
[docs]: translate hertz/tutorials/basic-feature/graceful-shutdown, forward-proxy, unit-test

### ISSUE THREAD

**Issue by Duslia** [cloudwego/hertz#72]
graceful-shutdown:
zh web page：https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/graceful-shutdown/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/basic-feature/graceful-shutdown.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials

forward-proxy:
zh web page：https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/forward-proxy/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/basic-feature/forward-proxy.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials

unit-test:
zh web page：https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/unit-test/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/basic-feature/unit-test.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials

Notes:

Do not change the original layout, code style or content sequence.
Software Translator is a tool, not god, do not use the result as the final result.
Translation principle: faithfulness, expressiveness and elegance.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by stephenzhang0713** [comment]
Hi, I can help with these translations

**Comment by stephenzhang0713** [comment]
#71
