### ISSUE TITLE
Use vd for parameter verification set $>=0  when eq 0  not effective

### ISSUE THREAD

**Issue by dingbb** [cloudwego/hertz#723]
**Describe the Question**
Use vd for parameter verification set $>=0  when eq 0  not effective

A clear and concise description of what the question is.

**Reproducible Code**

Please construct a minimum complete and reproducible example for us to get the same error. And tell us how to reproduce it like how you send a request or send what request.

**Expected behavior**
i want values from 0 to 100

**Screenshots**
![image](https://user-images.githubusercontent.com/29624378/231930921-ca314bf7-f8f7-49f0-9a78-a0e42283f874.png)
![image](https://user-images.githubusercontent.com/29624378/231931061-d3470c54-47ce-4c2c-80be-e68d61c14b73.png)

**Hertz version:**
hz version v0.3.0
cwgo version v0.0.1
thrift v0.13.0
hertz v0.6.0

**Environment:**
go1.20.2 arm64

**Additional context**
Use parameter verification 
i64 Weight (api.body="weight",api.vd="$>=0 && $=<100; msg:'weight must not in 0 -> 100'")

weight = 0 is error

**Comment by welkeyever** [comment]
Unlikely, you can paste all the tag information of the generated struct.

**Comment by rogerogers** [comment]
`$=<100` maybe `$<=100`?

**Comment by rogerogers** [comment]
`weight must not in 0 -> 100` -> `weight must in 0 -> 100` ?

**Comment by li-jin-gou** [comment]
> `$=<100` -> `$<=100`?

cool @rogerogers 👍🏻

**Comment by dingbb** [comment]
thanks, It has been resolved. 


> `$=<100` -> `$<=100`?
