### ISSUE TITLE
[FEATURE REQUEST] - Allow graceful restart

### ISSUE THREAD

**Issue by sujit-baniya** [cloudwego/hertz#725]
**Is your feature request related to a problem? Please describe.**

Sometime after the configuration is changed or server gets irresponsive, it requires server restart instead of shutdown. So restart function will help restart the application

**Describe the solution you'd like**

Similar to shutdown, it triggers all Restart hooks and the server gets restarted again programmatically

**Comment by li-jin-gou** [comment]
cc @welkeyever

**Comment by welkeyever** [comment]
@sujit-baniya Never seen this scene in a production environment, can you explain it in detail?
Since hertz already support graceful shutdown, theoretically, it can be realized by yourself?

**Comment by sujit-baniya** [comment]
@welkeyever I've been working on a project that requires to build Routes and Handlers based on JSON config. For the purpose, I've forked this package and added some changes

For the restart functionalities, I've used tableflip and now it's working as intended as per my use-case.
