### ISSUE TITLE
Client disconnect but ctx‘Done didn't change

### ISSUE THREAD

**Issue by liumuqi** [cloudwego/hertz#729]
**Describe the bug**

**To Reproduce**

hertz function like this
func Test(ctx context.Context, c *app.RequestContext) {
	// This prints to STDOUT to show that processing has started
	fmt.Fprint(os.Stdout, "processing request\n")
	// We use `select` to execute a piece of code depending on which
	// channel receives a message first
	select {
	case <-time.After(2 * time.Second):
		// If we receive a message after 2 seconds
		// that means the request has been processed
		// We then write this as the response
		c.Response.BodyWriter().Write([]byte("request processed"))
	case <-ctx.Done():
		// If the request gets cancelled, log it
		// to STDERR
		fmt.Fprint(os.Stderr, "request cancelled\n")
	}
	fmt.Fprint(os.Stdout, "...............................\n")
}

**Expected behavior**
when i close client's request in 2 second, it should print "request cancelled" ...but nothing.   hertz should fix this problem 

**Hertz version: 0.6.2

Please provide the version of Hertz you are using.

**Environment:**

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jarvis/Library/Caches/go-build"
GOENV="/Users/jarvis/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jarvis/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jarvis/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/Users/jarvis/Documents/code/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rd/gxmrg4vs4cb2h_jmb7sddwlm0000gn/T/go-build4164724797=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Additional context**

**Comment by li-jin-gou** [comment]
It's not a bug, it's designed to be so because creating a new channel for every request is just too expensive, so the channel returned by context.Done() is only closed when the server is shutting down.

**Comment by liumuqi** [comment]
> It's not a bug, it's designed to be so ,because creating a new channel for every request is just too expensive, so the channel returned by context.Done() is only closed when the server is shutting down.

So for long task client terminals, isn't the server still running. Isn't this even worse....

**Comment by li-jin-gou** [comment]
If idempotency is not guaranteed, we recommend using net/http , which is not currently in our plans.

**Comment by li-jin-gou** [comment]
If you are using it in-house, you can request technical support from cloudwego for this feature.
