### ISSUE TITLE
ctx. cc "not working" 

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/hertz#730]
can you provide an example where cc context.Background() is used?

it doesnt seemed to be registered on consecutive http call even when I've done *cc = context.WithValue(*cc, "key2", "value2")

on consecutive runs, key2 is not registered

using latest hertz version

seems to be related to this too
https://github.com/cloudwego/hertz/issues/729

**Comment by li-jin-gou** [comment]
The code can be seen in how the middleware is written and passed.

**Comment by kolinfluence** [comment]
@li-jin-gou ok my bad, it's my code issue. thx
