### ISSUE TITLE
当 proto 文件删除了，对应的接口要如何删除呢？

### ISSUE THREAD

**Issue by maojinhua** [cloudwego/hertz#736]
比如说我一开始写了一个
hello.proto这个接口描述的 idl ，后续我把这个 hello.proto 文件删除了，对应的里面的接口要怎么删除呢？只能手动去删除 router 文件吗？ 还是 hz 有什么选项可以自动删除 router 里对应的代码呢

**Comment by maojinhua** [comment]
你好，可能我没描述明白
hz update -I idl -idl idl/hello/hello.proto   这个命令 会按照 hello.proto 的内容去生成 router 和 handler 相关代码
如果我把 hello.proto 删除了，再次执行 上述命令会报错 .proto: No such file or directory
当我执行 hz update -I idl -idl idl/ 这样子的命令也会报错 idl path idl/ is not a valid file
![image](https://user-images.githubusercontent.com/13777695/233011459-6cb920e8-e6a7-43b5-bac8-0dccee812185.png)
所以不是很明白所谓的覆盖更新的命令是什么呢？

**Comment by Duslia** [comment]
没删干净或者目录里面没有 idl 文件了吧

**Comment by welkeyever** [comment]
手动删就行，工具原则上不做用户代码的删除：这个往往存在一定的安全风险。
确认不再需要直接删除就行了（idl + 生成的代码）。

**Comment by FGYFFFF** [comment]
> 

如果不需要需要删除掉某一个接口定义，直接删除掉对应的"biz/router/{namespace}/"下的路由和中间件文件就好了。另外需要把 register.go 中对应的路由注册函数删掉。
不过一般也不会删除 proto 文件。你是啥需求啊

**Comment by maojinhua** [comment]
> 手动删就行，工具原则上不做用户代码的删除：这个往往存在一定的安全风险。 确认不再需要直接删除就行了（idl + 生成的代码）。

嗯好的谢谢
