### ISSUE TITLE
Is cache deletion correct with gopool entry as example attached in code?

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/hertz#737]
**Describe the Question**
@li-jin-gou pls help me out this last section, only u can and understand what i'm doing
given the code below, is using the gopool the right way to clean up any cache information from the c (context.Done()) value for the whole "runtime" of disconnected http calls?

**Reproducible Code**

```
package main

import (
	"context"
	"log"
	"net"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/bytedance/gopkg/util/gopool"
)

func main() {
	var i uint8 = 0
	h := server.New(
		server.WithOnAccept(func(conn net.Conn) context.Context {
			c := context.Background()
			if i == 0 { 
				i++
				return context.WithValue(c, "aaa", "bbb")
			}
			gopool.Go(func() {
                            select {
                            case <-c.Done():
                            cacheDelete("2") //**to remove cache data after completion of context? will this work?**
                          }

			return context.Background()
		}),
	)
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		ctx.JSON(consts.StatusOK, utils.H{"message": "pong"})
		log.Printf("value1 = %v", c.Value("aaa"))
                cacheSet("2", []byte("something")) //add cache data
		
	})

	h.Spin()
}
```

**Expected behavior**

"2" in cache will be removed after completion / disconnection of http client

@li-jin-gou please help this out. final question. i need 1 week testing before i can post production information on the page u previously mentioned.
thanks a lot!

**Comment by welkeyever** [comment]
If you are an enterprise user using hertz, please register through our issue(the status does not need to be fully online, testing is also possible), and we will spend extra time to provide high-quality support for related needs - in addition to replying to github issues, hertz is currently responsible for tens of thousands of oncalls from internal services - we are very welcome, if you would you like to help us optimize the framework❤️

**Comment by li-jin-gou** [comment]
![image](https://user-images.githubusercontent.com/97824201/234803118-27198f89-489e-46f8-8248-aa8b00afe6da.png)
 @kolinfluence  Because HTTP 1.1 uses keep-alive, the connection and ctx will be reused, but you can turn off the keep-alive feature to solve this problem, otherwise there is no way to solve your problem at present.

- doc:  https://www.cloudwego.io/docs/hertz/reference/config/
