### ISSUE TITLE
BindAndValidate int64 pass string will error

### ISSUE THREAD

**Issue by Hanson** [cloudwego/hertz#738]
**Describe the Question**

When we using proto, gen int64/uint64 to ts, it'll be parse to string because javascript max int is 2^53-1。when JavaScript post string as uint64，BindAndValidate will show error about Mismatch type uint64 with value string

how to fix this problem?

**Reproducible Code**

**Expected behavior**

BindAndValidate pass string as uint64/int64 should not error

**Screenshots**

**Hertz version:**

0.3.0

**Environment:**

**Additional context**

**Comment by FGYFFFF** [comment]
Please give me a replay of the scenario：

-  the generated struct for "int64/uint64"
-  the request that you send

**Comment by Hanson** [comment]
@FGYFFFF for example

```
// proto

message SendReq {
	uint64 id = 1;
}

message SendResp {

}

service XxService {
	rpc Send(SendReq) returns(SendResp) {
		option (api.post) = "/send";
	}
}
```

```
request

post {"id":"1"}
```

**Comment by FGYFFFF** [comment]
This is an expected error, json unamrshal will strictly type match。

Maybe you can add 'string' option to json, like blow
```
message SendReq {
	uint64 id = 1[(api.body)="body,string"];
}
```
