### ISSUE TITLE
 A required privilege is not held by the client.

### ISSUE THREAD

**Issue by s5364733** [cloudwego/hertz#739]
现在执行hz  生成 代码报错如下: <br/>
```java 
build plugin command failed: symlink "D:\\goproject\\bin\\protoc-gen-hertz.exe": symlink D:\goproject\bin\hz.exe D:\goproject\bin\protoc-gen-hertz.exe: A required privilege is not held by the client.
```
涉及到的版本:<br/>
**0.6.2   0.6.3**

>已开启管理员模式

**Comment by li-jin-gou** [comment]
refer to https://answers.microsoft.com/en-us/windows/forum/all/how-to-fix-problem-a-required-privilege-is-not/d206b4b3-b6c2-4b0b-8629-5d4dfcb8f8d0 and It's a permissions issue with windows.

**Comment by li-jin-gou** [comment]
If you can find the reason, you can contribute to hertz's documentation, thank you very much.

**Comment by s5364733** [comment]
> refer to https://answers.microsoft.com/en-us/windows/forum/all/how-to-fix-problem-a-required-privilege-is-not/d206b4b3-b6c2-4b0b-8629-5d4dfcb8f8d0 and It's a permissions issue with windows.

能不能给一个具体的方案，这里好像没有明显的解决方案，你意思是系统的问题吗，和框架没有关系吗

**Comment by s5364733** [comment]
> > refer to https://answers.microsoft.com/en-us/windows/forum/all/how-to-fix-problem-a-required-privilege-is-not/d206b4b3-b6c2-4b0b-8629-5d4dfcb8f8d0 and It's a permissions issue with windows.
> 
> 能不能给一个具体的方案，这里好像没有明显的解决方案，你意思是系统的问题吗，和框架没有关系吗

按照这个流程走完之后执行报:<br/>

build plugin command failed: symlink "D:\\goproject\\bin\\thrift-gen-hertz.exe": symlink D:\goproject\bin\hz.exe D:\goproject\bin\thrift-gen-hertz.exe: Cannot create a file when that file already exists.

麻烦处理下 我们好多同事都是这个问题，window10 系统

**Comment by li-jin-gou** [comment]
> > refer to https://answers.microsoft.com/en-us/windows/forum/all/how-to-fix-problem-a-required-privilege-is-not/d206b4b3-b6c2-4b0b-8629-5d4dfcb8f8d0 and It's a permissions issue with windows.
> 
> 能不能给一个具体的方案，这里好像没有明显的解决方案，你意思是系统的问题吗，和框架没有关系吗

是的，和框架没什么关系

**Comment by FGYFFFF** [comment]
you can try it.
```
go install github.com/cloudwego/hertz/cmd/hz@1a97d556c28020a8643d729bb6242c38a984728a
```

**Comment by s5364733** [comment]
> you can try it.
> 
> ```
> go install github.com/cloudwego/hertz/cmd/hz@1a97d556c28020a8643d729bb6242c38a984728a
> ```

**Comment by s5364733** [comment]
> you can try it.
> 
> ```
> go install github.com/cloudwego/hertz/cmd/hz@1a97d556c28020a8643d729bb6242c38a984728a
> ```
ok
