### ISSUE TITLE
upload files EOF err when file size less than 512 bytes

### ISSUE THREAD

**Issue by PerfectZQ** [cloudwego/hertz#746]
**Describe the bug**

upload files EOF err when file size less than 512 bytes

**To Reproduce**

1. Go to pkg/protocol/multipart.go 139L 
2. It will return EOF err when file size less than 512B

**Expected behavior**

EOF should be ignored

**Screenshots**
![76a41b39-588f-41c9-b597-083e6112fe7a](https://user-images.githubusercontent.com/11895903/233923635-fa1b013c-ec22-4457-b1c6-c9b724e64178.jpeg)

**Hertz version:**

v0.5.0

**Environment:**

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/byteide/.cache/go-build"
GOENV="/home/byteide/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/byteide/go/pkg/mod"
GONOPROXY="*.xxx.org,*.everphoto.cn,git.smartisan.com"
GONOSUMDB="*.xxx.org,*.everphoto.cn,git.smartisan.com"
GOOS="linux"
GOPATH="/home/byteide/go"
GOPRIVATE="*.byted.org,*.everphoto.cn,git.smartisan.com"
GOPROXY="https://go-mod-proxy.xxxx.org|https://goproxy.cn|https://proxy.golang.org|direct"
GOROOT="/home/byteide/go/go1.18.10"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/home/byteide/go/go1.18.10/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.10"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/byteide/workspace/xxx/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1286874491=/tmp/go-build -gno-record-gcc-switches"

**Additional context**

**Comment by welkeyever** [comment]
Thanks for your report! We will take a look at it soon. cc @wzekin

**Comment by wzekin** [comment]
How is your Reader implemented @PerfectZQ

**Comment by PerfectZQ** [comment]
> How is your Reader implemented @PerfectZQ

it's a normal hdfs file reader of ufs agent
