### ISSUE TITLE
请问 为什么handler 中触发了 panic 却没有异常堆栈信息

### ISSUE THREAD

**Issue by maojinhua** [cloudwego/hertz#749]
如下图所示，我在handler 里之间 panic 了，然后用 postman 访问是 500 错误，但是控制台没有输出异常堆栈信息，请问要怎么让他输出呢
![image](https://user-images.githubusercontent.com/13777695/234214395-f12ed462-34b2-45f3-9c1c-64b1ebc918f7.png)

![image](https://user-images.githubusercontent.com/13777695/234214306-8cf812fa-fed2-4130-9819-42d71c0607cd.png)

服务器启动代码如下：
```go
func serverInit() {
	h := server.Default(
		server.WithHostPorts(viper.Conf.App.HostPort),
		server.WithExitWaitTime(60),
	)
	//h.Use(middleware.GlobalErrorHandler)
	register(h)
	h.Spin()
}
```

**Comment by a631807682** [comment]
disabledLogger was returned due to zerolog's lack of call [WithContext](https://github.com/rs/zerolog/blob/master/ctx.go#L34) 

https://github.com/hertz-contrib/logger/blob/main/zerolog/logger.go#L138

**Comment by maojinhua** [comment]
这是我 main.go 的代码
```go
// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzZerolog "github.com/hertz-contrib/logger/zerolog"
	"os"
	"task-schedule/dal"
	"task-schedule/pkg/viper"
)

func main() {
	viper.InitViper()

	hlog.SetLogger(hertzZerolog.New(
		hertzZerolog.WithOutput(os.Stdout),     // allows to specify output
		hertzZerolog.WithLevel(hlog.LevelInfo), // option with log level
		hertzZerolog.WithTimestamp(),           // option with timestamp
		hertzZerolog.WithCaller()))             // option with caller

	err := dal.Init()
	if err != nil {
		return
	}
	serverInit()
}

func serverInit() {
	h := server.Default(
		server.WithHostPorts(viper.Conf.App.HostPort),
		server.WithExitWaitTime(60),
	)
	//h.Use(middleware.GlobalErrorHandler)
	register(h)
	h.Spin()
}

```

**Comment by li-jin-gou** [comment]
Hello @sillen102  I found that using zerolog's Ctx*** method calls zerolog.Ctx, which returns a new logger in most scenarios, causing some problems with printing because the user's configuration is missing.

![image](https://user-images.githubusercontent.com/97824201/234241819-780283ec-9dd6-4c8d-a4be-3558a6b91bc0.png)

**Comment by sillen102** [comment]
> Hello @sillen102 I found that using zerolog's Ctx*** method calls zerolog.Ctx, which returns a new logger in most scenarios, causing some problems with printing because the user's configuration is missing.
> 
> ![image](https://user-images.githubusercontent.com/97824201/234241819-780283ec-9dd6-4c8d-a4be-3558a6b91bc0.png)

It's been a long time since I looked at this code but in what circumstances does it cause problems? According to the documentation from zerolog a logger should be attached to the context before calling this function. If there is no logger attached then it will use the DefaultContextLogger.

So it depends on what is the intent and what is expected. Is the expectation to associate a logger with a context that has no logger associated to it and then use it, or is the intent to use a logger already associated with the context?

I think that depending on the intent it could be as is or if it needs to be updated it could be fixed by using the other context function from zerolog like so:
```go
// CtxLogf associate logger with context and log.
func (l *Logger) CtxLogf(level hlog.Level, ctx context.Context, format string, kvs ...interface{}) {
	logger := l.Unwrap()
	logger.WithContext(ctx)
	switch level {
	case hlog.LevelTrace, hlog.LevelDebug:
		logger.Debug().Msg(fmt.Sprintf(format, kvs...))
	case hlog.LevelInfo:
		logger.Info().Msg(fmt.Sprintf(format, kvs...))
	case hlog.LevelNotice, hlog.LevelWarn:
		logger.Warn().Msg(fmt.Sprintf(format, kvs...))
	case hlog.LevelError:
		logger.Error().Msg(fmt.Sprintf(format, kvs...))
	case hlog.LevelFatal:
		logger.Fatal().Msg(fmt.Sprintf(format, kvs...))
	default:
		logger.Warn().Msg(fmt.Sprintf(format, kvs...))
	}
}
```

For reference: this is the code used from zerolog:
```go
type ctxKey struct{}

// WithContext returns a copy of ctx with l associated. If an instance of Logger
// is already in the context, the context is not updated.
//
// For instance, to add a field to an existing logger in the context, use this
// notation:
//
//     ctx := r.Context()
//     l := zerolog.Ctx(ctx)
//     l.UpdateContext(func(c Context) Context {
//         return c.Str("bar", "baz")
//     })
func (l Logger) WithContext(ctx context.Context) context.Context {
	if lp, ok := ctx.Value(ctxKey{}).(*Logger); ok {
		if lp == &l {
			// Do not store same logger.
			return ctx
		}
	} else if l.level == Disabled {
		// Do not store disabled logger.
		return ctx
	}
	return context.WithValue(ctx, ctxKey{}, &l)
}

// Ctx returns the Logger associated with the ctx. If no logger
// is associated, DefaultContextLogger is returned, unless DefaultContextLogger
// is nil, in which case a disabled logger is returned.
func Ctx(ctx context.Context) *Logger {
	if l, ok := ctx.Value(ctxKey{}).(*Logger); ok {
		return l
	} else if l = DefaultContextLogger; l != nil {
		return l
	}
	return disabledLogger
}
```

**Comment by maojinhua** [comment]
> 这不应该，因为我看到了恢复的默认现实，我本地测试一下https://github.com/cloudwego/hertz/blob/develop/pkg/app/middlewares/server/recovery/option.go#L37
> 
> ![图像](https://user-images.githubusercontent.com/97824201/234234822-a94530d4-e4e3-47a2-82c6-d5e006063c5d.png)

你好 请问我现在应该怎么做 可以正常打印 panic 异常堆栈信息呢？ 
还有一个问题就是要怎么打印接口请求信息？比如一个接口的响应时间之类的，状态码之类的日志呢？

**Comment by li-jin-gou** [comment]
> > 这不应该，因为我看到了恢复的默认现实，我本地测试一下https://github.com/cloudwego/hertz/blob/develop/pkg/app/middlewares/server/recovery/option.go#L37
> > ![图像](https://user-images.githubusercontent.com/97824201/234234822-a94530d4-e4e3-47a2-82c6-d5e006063c5d.png)
> 
> 你好 请问我现在应该怎么做 可以正常打印 panic 异常堆栈信息呢？ 还有一个问题就是要怎么打印接口请求信息？比如一个接口的响应时间之类的，状态码之类的日志呢？
@maojinhua 
- hlog 的 zero-log 实现在 Ctx*** 有一些问题可以看上文
- 第二个看下 hertz access_log  中间件的使用 https://github.com/hertz-contrib/logger/tree/main/accesslog

**Comment by maojinhua** [comment]
> > > 这不应该，因为我看到了恢复的默认现实，我本地测试一下https://github.com/cloudwego/hertz/blob/develop/pkg/app/middlewares/server/recovery/option.go#L37
> > > ![图像](https://user-images.githubusercontent.com/97824201/234234822-a94530d4-e4e3-47a2-82c6-d5e006063c5d.png)
> > 
> > 
> > 你好 请问我现在应该怎么做 可以正常打印 panic 异常堆栈信息呢？ 还有一个问题就是要怎么打印接口请求信息？比如一个接口的响应时间之类的，状态码之类的日志呢？
> > @maojinhua
> 
> * hlog 的 zero-log 实现在 Ctx*** 有一些问题可以看上文  cc @welkeyever ,这块看了一下直接用用户的logger打印日志是不是就可以，但是问题是 ctx 用不到了，zap 也有类似的 ctx 用不到的问题，目前解决方案是在扩展里加了 hook 函数来搞的 https://github.com/hertz-contrib/logger/pull/25/files
> * 第二个看下 hertz access_log  中间件的使用 https://github.com/hertz-contrib/logger/tree/main/accesslog

嗯好的 谢谢，我试试哈

**Comment by welkeyever** [comment]
@li-jin-gou https://github.com/hertz-contrib/logger/pull/25/files 这个的思路是对的，`CtxLogger`这个接口的设计初衷就是给用户提供一个透传上下文的可能；具体如何处理ctx中的value也好，ctx的终结也好(ctx.Done)这个根据对应的logger实现来就行。
如果没有额外针对上述ctx的相关处理，原则上等价于`Logger`接口的具体实现。

**Comment by li-jin-gou** [comment]
@maojinhua  更新一下 github.com/hertz-contrib/logger/zerolog
