### ISSUE TITLE
how to get GoModule or ProjPackage for generator.CustomizedFileForMethod?

### ISSUE THREAD

**Issue by Rainshaw** [cloudwego/hertz#753]
**Describe the Question**

I write a tpl to generate files, but I can not find a variable for gomodule or projpackage like other tpl.

**Reproducible Code**

```yaml
layouts:
   - path:     path: "biz/service/{{.HandlerGenPath}}/{{ToSnakeCase .MethodName}}.go"
    loop_method: true
    update_behavior:
      type: "skip"
    body: |-
      package {{.FilePackage}}
      import (
          "context"
          "github.com/cloudwego/hertz/pkg/app"
      {{- range $k, $v := .Models}}
          {{$k}} "{{$v.Package}}"
      {{- end}}
          "{{.GoModule}}/pkg/errno" or "{{$.ProjPackage}}/pkg/errno"
      )
      type {{.Name}}Service struct {
          RequestContext  *app.RequestContext
          Context         context.Context
      }
      
      func New{{.Name}}Service(ctx context.Context, RequestContext *app.RequestContext) *{{.Name}}Service {
          return &{{.Name}}Service{RequestContext: RequestContext, Context: ctx}
      }
      
      func (h *{{.Name}}Service) Run(req *{{.RequestTypeName}}, resp *{{.ReturnTypeName}}) (err *errno.Err) {
          //defer func() {
          // hlog.CtxInfof(h.Context, "req = %+v", req)
          // hlog.CtxInfof(h.Context, "resp = %+v", resp)
          //}()
          // todo edit your code
          return
      }
```

**Expected behavior**

neithor of these variable work, please help

**Screenshots**

If applicable, add screenshots to help explain your question.

**Hertz version:**

0.5.2

**Environment:**

The output of `go env`.

**Additional context**

Add any other context about the question here.

**Comment by li-jin-gou** [comment]
I will solve it

**Comment by FGYFFFF** [comment]
The design did not take into account the need to refer to other meta information when looping "method". I will add this information.
But you can set the go module to a fixed value first.
```yaml
layouts:
   - path:     path: "biz/service/{{.HandlerGenPath}}/{{ToSnakeCase .MethodName}}.go"
    loop_method: true
    update_behavior:
      type: "skip"
    body: |-
      package {{.FilePackage}}
      import (
          "context"
          "github.com/cloudwego/hertz/pkg/app"
      {{- range $k, $v := .Models}}
          {{$k}} "{{$v.Package}}"
      {{- end}}
          "github.com/Rainshaw/hz/pkg/errno"
      )
      type {{.Name}}Service struct {
          RequestContext  *app.RequestContext
          Context         context.Context
      }
      
      func New{{.Name}}Service(ctx context.Context, RequestContext *app.RequestContext) *{{.Name}}Service {
          return &{{.Name}}Service{RequestContext: RequestContext, Context: ctx}
      }
      
      func (h *{{.Name}}Service) Run(req *{{.RequestTypeName}}, resp *{{.ReturnTypeName}}) (err *errno.Err) {
          //defer func() {
          // hlog.CtxInfof(h.Context, "req = %+v", req)
          // hlog.CtxInfof(h.Context, "resp = %+v", resp)
          //}()
          // todo edit your code
          return
      }
```

**Comment by Rainshaw** [comment]
> The design did not take into account the need to refer to other meta information when looping "method". I will add this information. But you can set the go module to a fixed value first.
> 
> ```yaml
> layouts:
>    - path:     path: "biz/service/{{.HandlerGenPath}}/{{ToSnakeCase .MethodName}}.go"
>     loop_method: true
>     update_behavior:
>       type: "skip"
>     body: |-
>       package {{.FilePackage}}
>       import (
>           "context"
>           "github.com/cloudwego/hertz/pkg/app"
>       {{- range $k, $v := .Models}}
>           {{$k}} "{{$v.Package}}"
>       {{- end}}
>           "github.com/Rainshaw/hz/pkg/errno"
>       )
>       type {{.Name}}Service struct {
>           RequestContext  *app.RequestContext
>           Context         context.Context
>       }
>       
>       func New{{.Name}}Service(ctx context.Context, RequestContext *app.RequestContext) *{{.Name}}Service {
>           return &{{.Name}}Service{RequestContext: RequestContext, Context: ctx}
>       }
>       
>       func (h *{{.Name}}Service) Run(req *{{.RequestTypeName}}, resp *{{.ReturnTypeName}}) (err *errno.Err) {
>           //defer func() {
>           // hlog.CtxInfof(h.Context, "req = %+v", req)
>           // hlog.CtxInfof(h.Context, "resp = %+v", resp)
>           //}()
>           // todo edit your code
>           return
>       }
> ```

yep, I am doing this way 🌝
