### ISSUE TITLE
Introduce constants for commonly used MIME types

### ISSUE THREAD

**Issue by x80486** [cloudwego/hertz#754]
## Is your feature request related to a problem? Please describe.

Not a problem, but an inconvenient. I see there are constants available for HTTP methods, HTTP status codes, and so on. I think it would be great if `Hertz` can expand on that and introduce constants for commonly used MIME types as well — probably within `consts`.

## Describe the solution you'd like

To be able to refer to commonly used MIME types using predefined values, such as `MIMETextPlain`, `MIMETextPlainCharsetUTF8`, etc.

## Describe alternatives you've considered

Importing the relevant packages from `Fiber` or any other library that include these.

## Additional context

I usually have something like this in almost all handlers:

```go
func RootHandler(ctx context.Context, req *app.RequestContext) {
  switch header := http.DetectContentType(req.GetHeader(consts.HeaderAccept)); header {
  case "text/plain", "text/plain; charset=utf-8": // Errrr...not great
    {
      req.Header(consts.HeaderContentType, header)
      req.String(consts.StatusOK, "Go Hertz!")
    }
  ...
  default:
    {
      req.Header(consts.HeaderContentType, "text/plain")
      req.String(consts.StatusNotAcceptable, "Not Acceptable")
    }
  }
}
```

**Comment by welkeyever** [comment]
Good idea! May just add a file for this sort of consts under `pkg/protocol/consts`.

**Comment by cqqqq777** [comment]
let me try

**Comment by li-jin-gou** [comment]
> let me try

thanks @cqqqq777
