### ISSUE TITLE
how to exit immediately?

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/hertz#755]
WithExitWaitTime(0)?
it's currently waiting 5s to exit

**Comment by li-jin-gou** [comment]
refer to https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/graceful-shutdown/ or use engine.Run instead of engine.Spin

**Comment by hiqsociety** [comment]
it's not easy to find example of engine.Run in hertz.

when i terminate the process, it needs to wait 5 seconds.

how to do engine.Run? possible to provide an example? thx

**Comment by li-jin-gou** [comment]
![image](https://user-images.githubusercontent.com/97824201/236184129-2d0809c9-7fbb-45fe-ac2b-7e382bdf3048.png)

**Comment by li-jin-gou** [comment]
> it's not easy to find example of engine.Run in hertz.
> 
> when i terminate the process, it needs to wait 5 seconds.
> 
> how to do engine.Run? possible to provide an example? thx

I don't think this needs an example because it's a simple method substitution, but some students did write this document.
