### ISSUE TITLE
自定义模版的使用data.json失败

### ISSUE THREAD

**Issue by cuteLittleDevil** [cloudwego/hertz#756]
**Describe the Question**

A clear and concise description of what the question is.

**Reproducible Code**
以下命令生成成功
hz new -module collect --idl=../shared/idl/http/notice.thrift \
	--customize_layout=../shared/template/layout.yaml\
	--customize_package=../shared/template/package.yaml
以下命令增加了template/data.json失败
hz new -module collect --idl=../shared/idl/http/notice.thrift \
	--customize_layout=../shared/template/layout.yaml:template/data.json \
	--customize_package=../shared/template/package.yaml

**Expected behavior**

根据本地模版生成成功

If applicable, add screenshots to help explain your question.

**Hertz version:**
0.6.2
Please provide the version of Hertz you are using.
<img width="850" alt="image" src="https://user-images.githubusercontent.com/38343763/236136110-338b49c0-1f9a-4e03-8b17-961cf3e3f2b0.png">
main.go 11行的位置为        "{{.GoModule}}/initialize"

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/38343763/236135963-11eb3747-0bc0-48cb-b3ad-aa89d2ebe8ee.png">

The output of `go env`.

<img width="1682" alt="image" src="https://user-images.githubusercontent.com/38343763/236135406-b09df057-e7ae-4d08-ac72-809aa35accdc.png">

Add any other context about the question here.
目录结构
test
 -collect
   --template
   ---data.json
 -shared
 --idl
 ---notice.thrift
 --template
 ---layout.yaml
 ---package.yaml

**Comment by cuteLittleDevil** [comment]
https://github.com/cloudwego/hertz-examples
希望这个项目增加使用data.json的例子
目前文档上写着data.json的生成命令 但是hertz-examples并没有相关的例子

**Comment by cuteLittleDevil** [comment]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/38343763/236137732-07e9c525-c6e5-409d-9bfc-46d2baa43d93.png">

**Comment by li-jin-gou** [comment]
这个 data.json 的作用主要是传递一些命令行参数，如果不传递 data.json 的话参数会从命令行中获取，目前看这个报错的话看起来是 GoMoudle 这个参数没有传递。

![image](https://user-images.githubusercontent.com/97824201/236138083-865f54cf-b7b3-4984-b173-7595355761d9.png)

我稍后补充一个示例。

**Comment by cuteLittleDevil** [comment]
> 这个data.json的作用主要是传一些命令行参数，如果不传data.json的参数会从命令行中获取，目前看这个报错的话看起来自 main.go 的 GoMoudle 这个参数没有传来。
> 
> ![图像](https://user-images.githubusercontent.com/97824201/236138083-865f54cf-b7b3-4984-b173-7595355761d9.png)
> 
> 我在补完一个例子。
<img width="594" alt="image" src="https://user-images.githubusercontent.com/38343763/236140607-fb1b7be2-14d7-4522-9990-316b7594e281.png">
希望示例还有自定义添加的参数 比如TestParam

**Comment by li-jin-gou** [comment]
我将会添加 example

**Comment by cuteLittleDevil** [comment]
请问一下 命令现在需要做什么样的改变才可以把data.json传递过去
目前命令是这样的
	hz new -module collect --idl=../shared/idl/http/notice.thrift \
	--customize_layout=../shared/template/layout.yaml:template/data.json \
	--customize_package=../shared/template/package.yaml:template/data.json

**Comment by cuteLittleDevil** [comment]
> ![image](https://user-images.githubusercontent.com/97824201/236505201-a2d208dd-89dd-4e9d-b68c-f4bfc75f71c4.png) package 模版不支持渲染数据 https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/more-feature/template/#%E6%A8%A1%E6%9D%BF%E6%B8%B2%E6%9F%93%E5%8F%82%E6%95%B0%E6%96%87%E4%BB%B6%E7%9A%84%E5%90%AB%E4%B9%89 && 其它可参考 PR

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/38343763/236608363-3456a902-1657-441e-9668-b34082c802af.png">
添加:template/data.json 提示layout_config_path doesn't exist
template/data.json和../shared/template/layout.yaml路径的文件都存在

**Comment by li-jin-gou** [comment]
你看看 example 是可以的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月6日(周六) 下午2:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cloudwego/hertz] 自定义模版的使用data.json失败 (Issue #756)




  
 package 模版不支持渲染数据 https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/more-feature/template/#%E6%A8%A1%E6%9D%BF%E6%B8%B2%E6%9F%93%E5%8F%82%E6%95%B0%E6%96%87%E4%BB%B6%E7%9A%84%E5%90%AB%E4%B9%89 &amp;&amp; 其它可参考 PR
  

 添加:template/data.json 提示layout_config_path doesn't exist template/data.json和../shared/template/layout.yaml路径的文件都存在

**Comment by cuteLittleDevil** [comment]
> 你看看 example 是可以的
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年5月6日(周六) 下午2:56 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [cloudwego/hertz] 自定义模版的使用data.json失败 (Issue #756) package 模版不支持渲染数据 https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/more-feature/template/#%E6%A8%A1%E6%9D%BF%E6%B8%B2%E6%9F%93%E5%8F%82%E6%95%B0%E6%96%87%E4%BB%B6%E7%9A%84%E5%90%AB%E4%B9%89 &amp;&amp; 其它可参考 PR 添加:template/data.json 提示layout_config_path doesn't exist template/data.json和../shared/template/layout.yaml路径的文件都存在 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.Message ID: ***@***.***&gt;

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/38343763/236615041-bf9f0767-2623-4ccf-90f9-17ec7d171c2b.png">
如图所示 layout.yaml和data.json同目录可以 跨目录就失败了

**Comment by FGYFFFF** [comment]
看一下你的 "hz  --version" 的版本可以吗？
在 "hz v0.5.0" 之后，layout 模板的渲染数据需要通过 "--customize_layout_data_path" 选项来传递，避免单一选项带来的干扰~

**Comment by cuteLittleDevil** [comment]
> --customize_layout_data_path
目前使用"--customize_layout_data_path" 可以了
v0.6.2 希望在这个页面补充"--customize_layout_data_path" 选项 提示在某一个版本修改为这样https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/usage/command/#new

**Comment by cuteLittleDevil** [comment]
> 看一下你的 "hz --version" 的版本可以吗？ 在 "hz v0.5.0" 之后，layout 模板的渲染数据需要通过 "--customize_layout_data_path" 选项来传递，避免单一选项带来的干扰~


目前使用"--customize_layout_data_path" 可以了
v0.6.2 希望在这个页面补充"--customize_layout_data_path" 选项 提示在某一个版本修改为这样https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/usage/command/#new

**Comment by li-jin-gou** [comment]
> > 看一下你的 "hz --version" 的版本可以吗？ 在 "hz v0.5.0" 之后，layout 模板的渲染数据需要通过 "--customize_layout_data_path" 选项来传递，避免单一选项带来的干扰~
> 
> 目前使用"--customize_layout_data_path" 可以了 v0.6.2 希望在这个页面补充"--customize_layout_data_path" 选项 提示在某一个版本修改为这样https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/usage/command/#new

后续加一下。
