### ISSUE TITLE
cookie session defaultkey不能更改，cookie过期时间没有自动刷新功能

### ISSUE THREAD

**Issue by laixiaohuai** [cloudwego/hertz#757]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/14883388/236253997-4f4da6b3-c0aa-4133-ae29-67d2597053d5.png">

1. cookie session defaultkey不能更改
2. cookie过期时间没有自动刷新功能

**Comment by laixiaohuai** [comment]
3. 不能指定sessionId写入session内容

**Comment by laixiaohuai** [comment]
> @laixiaohuai 建议按照模版填写 issue 否则会被机器人自动关闭，另外则是可以让信息尽可能去全一些，方便其它同学回答。
> 
> * 因为 session/cookie 扩展依赖 https://github.com/gorilla/sessions 实现,所以没办法支持自动刷新，你可以实现一个支持自动刷新的 store 满足你的需求。
> * 1 和 3 目前没看出具体的使用场景是什么&&可以详细描述一下，因为我看了代码注释，这些变量正常都不是需要&&希望用户感知的。

3确实是业务场景需要用到，当前的sessionId 确实要去更改另一个sessionId下的session内容

**Comment by welkeyever** [comment]
> > @laixiaohuai 建议按照模版填写 issue 否则会被机器人自动关闭，另外则是可以让信息尽可能去全一些，方便其它同学回答。
> > 
> > * 因为 session/cookie 扩展依赖 https://github.com/gorilla/sessions 实现,所以没办法支持自动刷新，你可以实现一个支持自动刷新的 store 满足你的需求。
> > * 1 和 3 目前没看出具体的使用场景是什么&&可以详细描述一下，因为我看了代码注释，这些变量正常都不是需要&&希望用户感知的。
> 
> 3确实是业务场景需要用到，当前的sessionId 确实要去更改另一个sessionId下的session内容

fyi：如果是企业用户可以填一下 hertz 的置顶 issue，我们会提供更高优的 oncall 答疑

**Comment by li-jin-gou** [comment]
> > > @laixiaohuai 建议按照模版填写 issue 否则会被机器人自动关闭，另外则是可以让信息尽可能去全一些，方便其它同学回答。
> > > 
> > > * 因为 session/cookie 扩展依赖 https://github.com/gorilla/sessions 实现,所以没办法支持自动刷新，你可以实现一个支持自动刷新的 store 满足你的需求。
> > > * 1 和 3 目前没看出具体的使用场景是什么&&可以详细描述一下，因为我看了代码注释，这些变量正常都不是需要&&希望用户感知的。
> > 
> > 
> > 3确实是业务场景需要用到，当前的sessionId 确实要去更改另一个sessionId下的session内容
> 
> fyi：如果是企业用户可以填一下 hertz 的置顶 issue，我们会提供更高优的 oncall 答疑

注册过了的
