### ISSUE TITLE
webSocket 是否可以完成分布式信息发送呢？

### ISSUE THREAD

**Issue by ysy2001224** [cloudwego/hertz#763]
当多个ws连接建立之后，当某一个连接发生动作，需要通知其他的ws连接，给其他的ws连接发送消息，
目前是否有实现方案呢？或者有什么实现的思路可以提供一下嘛。

**Comment by li-jin-gou** [comment]
目前没有实现方案&& 这和 websocket 关系不大 && 属于业务系统的设计问题。
- 如题：https://stackoverflow.com/questions/3155528/can-i-broadcast-to-all-websocket-clients
