### ISSUE TITLE
thrift生成的Hertz http server 和client，server返回状态码的一个问题

### ISSUE THREAD

**Issue by Li-giegie** [cloudwego/hertz#764]
Describe the Question
thrift 生成 hertz server和client，客户端发起一次调用，当服务端返回的状态码不为200时，客户端返回一个nil，JSON序列化失败的错误，

To Reproduce
1.随便写一个idl
2.生成一个服务端和客户端
3.实现idl中的服务接口，返回状态码400
4.客户端发起调用

Expected behavior
hertz服务端返回值非200，客户端仍然正常解析返回值，返回值可能包含本次错误原因

Hertz version：v0.6.3
OS：Ubuntu 20.04
Golang：1.20

Additional context
使用thrift生成的Hertz http server 和client，事情起源与我使用客户端请求服务端时，服务端返回状态码非200httpstateOK时，客户端的返回值（通常为两个返回值，一个（resp）响应结果，一个err（错误））resp为nil，err为json序列化失败，一开始以为服务端返回的JSON、或者客户端接受的JSON出现了意外情况导致JSON不能被正常序列化，但直到找到了源码并把接受的切片打印出来后我发现客户端正常收到了JSON，经过我多次测试，原因就是因为服务端返回的状态码不是200造成的，希望这一点可以改变，给出的理由是客户端收到了服务端的响应JSON字符串但没有序列化到返回值里面

**Comment by li-jin-gou** [comment]
@Li-giegie 可以按照 issue 模版填写&&提供一下复现代码&&否则会被机器人自动关闭
![image](https://user-images.githubusercontent.com/97824201/236595791-d9fb6c7b-17aa-49e6-93dd-4f88356b99bb.png)

**Comment by li-jin-gou** [comment]
@Li-giegie  我大概看了一下原因，
- https://github.com/cloudwego/hertz-examples/blob/main/hz/hz_client/client/hertz_gen/toutiao/middleware/hzClient/hertz/hertz_client.go#L531
![image](https://user-images.githubusercontent.com/97824201/236596563-b01775bf-c5cc-4d4c-9d00-1284d6a4d16a.png) 这个是默认 client 行为，可以使用 https://github.com/cloudwego/hertz-examples/blob/main/hz/hz_client/client/hertz_gen/toutiao/middleware/hzClient/hertz/hertz_client.go#L101 初始化一个 client 修改。

**Comment by Li-giegie** [comment]
@li-jin-gou 晓得喽
