### ISSUE TITLE
日志如何实现既保存到文件中，有前台输出 

### ISSUE THREAD

**Issue by doing007** [cloudwego/hertz#769]
这是我目前的
只能输出到文件中

`
stdLogger := logrus.StandardLogger()
	logger := hertzlogrus.NewLogger(hertzlogrus.WithLogger(stdLogger))
	// 可定制的输出目录。
	var logFilePath string
	dir := "./hlog"
	logFilePath = dir + "/logs/"
	if err := os.MkdirAll(logFilePath, 0o777); err != nil {
		log.Println(err.Error())
		return
	}

	// 将文件名设置为日期
	logFileName := time.Now().Format("2006-01-02") + ".log"
	fileName := path.Join(logFilePath, logFileName)
	if _, err := os.Stat(fileName); err != nil {
		if _, err := os.Create(fileName); err != nil {
			log.Println(err.Error())
			return
		}
	}

	logger = hertzlogrus.NewLogger()
	// 提供压缩和删除
	lumberjackLogger := &lumberjack.Logger{
		Filename:   fileName,
		MaxSize:    20,   // 一个文件最大可达20M。
		MaxBackups: 5,    // 最多同时保存 5 个文件。
		MaxAge:     10,   // 一个文件最多可以保存 10 天。
		Compress:   true, // 用 gzip 压缩。
	}

	logger.SetOutput(lumberjackLogger)
	logger.SetLevel(hlog.LevelDebug)

	hlog.SetLogger(logger)
`

**Comment by li-jin-gou** [comment]
按照 issue 模板调整一下格式吧，否则会被机器人自动关闭@doing007

**Comment by laixiaohuai** [comment]
> 这是我目前的 只能输出到文件中
> 
> ` stdLogger := logrus.StandardLogger() logger := hertzlogrus.NewLogger(hertzlogrus.WithLogger(stdLogger)) // 可定制的输出目录。 var logFilePath string dir := "./hlog" logFilePath = dir + "/logs/" if err := os.MkdirAll(logFilePath, 0o777); err != nil { log.Println(err.Error()) return }
> 
> ```
> // 将文件名设置为日期
> logFileName := time.Now().Format("2006-01-02") + ".log"
> fileName := path.Join(logFilePath, logFileName)
> if _, err := os.Stat(fileName); err != nil {
> 	if _, err := os.Create(fileName); err != nil {
> 		log.Println(err.Error())
> 		return
> 	}
> }
> 
> logger = hertzlogrus.NewLogger()
> // 提供压缩和删除
> lumberjackLogger := &lumberjack.Logger{
> 	Filename:   fileName,
> 	MaxSize:    20,   // 一个文件最大可达20M。
> 	MaxBackups: 5,    // 最多同时保存 5 个文件。
> 	MaxAge:     10,   // 一个文件最多可以保存 10 天。
> 	Compress:   true, // 用 gzip 压缩。
> }
> 
> logger.SetOutput(lumberjackLogger)
> logger.SetLevel(hlog.LevelDebug)
> 
> hlog.SetLogger(logger)
> ```
> 
> `

// 将文件名设置为日期
logFileName := time.Now().Format("2006-01-02") + ".log"
fileName := path.Join(logFilePath, logFileName)
if _, err := os.Stat(fileName); err != nil {
	if _, err := os.Create(fileName); err != nil {
		log.Println(err.Error())
		return
	}
}

logger = hertzlogrus.NewLogger()
// 提供压缩和删除
lumberjackLogger := &lumberjack.Logger{
	Filename:   fileName,
	MaxSize:    20,   // 一个文件最大可达20M。
	MaxBackups: 5,    // 最多同时保存 5 个文件。
	MaxAge:     10,   // 一个文件最多可以保存 10 天。
	Compress:   true, // 用 gzip 压缩。
}
// 划重点
iw := io.MultiWriter(lumberjackLogger, os.Stdout) 
logger.SetOutput(iw)
logger.SetLevel(hlog.LevelDebug)

hlog.SetLogger(logger)

**Comment by li-jin-gou** [comment]
> > 这是我目前的 只能输出到文件中
> > 
> > ` stdLogger := logrus.StandardLogger() logger := hertzlogrus.NewLogger(hertzlogrus.WithLogger(stdLogger)) // 可定制的输出目录。 var logFilePath string dir := "./hlog" logFilePath = dir + "/logs/" if err := os.MkdirAll(logFilePath, 0o777); err != nil { log.Println(err.Error()) return }
> > 
> > ```
> > // 将文件名设置为日期
> > logFileName := time.Now().Format("2006-01-02") + ".log"
> > fileName := path.Join(logFilePath, logFileName)
> > if _, err := os.Stat(fileName); err != nil {
> > 	if _, err := os.Create(fileName); err != nil {
> > 		log.Println(err.Error())
> > 		return
> > 	}
> > }
> > 
> > logger = hertzlogrus.NewLogger()
> > // 提供压缩和删除
> > lumberjackLogger := &lumberjack.Logger{
> > 	Filename:   fileName,
> > 	MaxSize:    20,   // 一个文件最大可达20M。
> > 	MaxBackups: 5,    // 最多同时保存 5 个文件。
> > 	MaxAge:     10,   // 一个文件最多可以保存 10 天。
> > 	Compress:   true, // 用 gzip 压缩。
> > }
> > 
> > logger.SetOutput(lumberjackLogger)
> > logger.SetLevel(hlog.LevelDebug)
> > 
> > hlog.SetLogger(logger)
> > ```
> > 
> > `
> 
> // 将文件名设置为日期
> logFileName := time.Now().Format("2006-01-02") + ".log"
> fileName := path.Join(logFilePath, logFileName)
> if _, err := os.Stat(fileName); err != nil {
> 	if _, err := os.Create(fileName); err != nil {
> 		log.Println(err.Error())
> 		return
> 	}
> }
> 
> logger = hertzlogrus.NewLogger()
> // 提供压缩和删除
> lumberjackLogger := &lumberjack.Logger{
> 	Filename:   fileName,
> 	MaxSize:    20,   // 一个文件最大可达20M。
> 	MaxBackups: 5,    // 最多同时保存 5 个文件。
> 	MaxAge:     10,   // 一个文件最多可以保存 10 天。
> 	Compress:   true, // 用 gzip 压缩。
> }
> // 划重点
> iw := io.MultiWriter(lumberjackLogger, os.Stdout) 
> logger.SetOutput(iw)
> logger.SetLevel(hlog.LevelDebug)
> 
> hlog.SetLogger(logger)

thanks
