### ISSUE TITLE
参考了自定义Logger，但是无法生成trace_id

### ISSUE THREAD

**Issue by jettjia** [cloudwego/hertz#770]
设置了自定义的logger,内容完全参考的：
https://github.com/cloudwego/hertz-examples/tree/main/hlog/custom

在使用的时候，引入了trace。发现，没有生成 trace_id等信息
func Test_hertz_server_trace(t *testing.T) {
	logger := NewLogger()
	hlog.SetLogger(logger)
	hlog.SetLevel(hlog.LevelDebug)

	serviceName := "demo-hertz-server"
	exportEndpoint := "10.4.7.71:4317"

	p := provider.NewOpenTelemetryProvider(
		provider.WithServiceName(serviceName),
		provider.WithExportEndpoint(exportEndpoint),
		provider.WithInsecure(),
	)
	defer p.Shutdown(context.Background())

	tracer, cfg := hertztracing.NewServerTracer()
	h := server.Default(tracer)
	h.Use(hertztracing.ServerMiddleware(cfg))

	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		resp := "ddddddddddddddddddddddddddddd"
		hlog.CtxInfof(c, "message received successfully: %s", "i am hertz")
		ctx.JSON(consts.StatusOK, resp)
	})

	h.Spin()
}

**Comment by li-jin-gou** [comment]
@jettjia  logger 下的日志没有任何处理，是一个纯logger实现，需要用  https://github.com/hertz-contrib/obs-opentelemetry/tree/main/logging
