### ISSUE TITLE
Is there any way to declare API Annotation for grouping route?

### ISSUE THREAD

**Issue by ansidev** [cloudwego/hertz#775]
**Describe the Question**

I want to generate grouping routes. However, it seems that this feature is not available at this moment.

**Reproducible Code**

https://github.com/cloudwego/hertz-examples/tree/main/hz/protobuf

**Expected behavior**

Something looks like this will be generated:

```go
root := r.Group("/group-name")
```

**Hertz version:**

v0.6.3

**Environment:**

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/x/Library/Caches/go-build"
GOENV="/Users/x/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/x/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/x/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.20.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.20.4/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/Users/x/projects/hertz/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rg
/2ghbpv594593xwc66z446w5w0000gn/T/go-build773401175=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by li-jin-gou** [comment]
Currently not supported @ansidev

**Comment by welkeyever** [comment]
The exist route generated strategy has already been based on the `Group` api.
Does the current implementation not meet your requirement? Maybe provide more info about your usage scenario?

**Comment by ansidev** [comment]
@welkeyever What do you mean by this?

```
The exist route generated strategy has already been based on the Group api.
```

The current version only generates this LOC

```go
root := r.Group("/", rootMw()...)
```

I guess the route group is always `/` and cannot be customized.

**Comment by welkeyever** [comment]
@ansidev No and maybe you should check a more complex demo first, such as: https://github.com/cloudwego/hertz-examples/tree/main/bizdemo.
