### ISSUE TITLE
c.JSON cannot customize the ContentType

### ISSUE THREAD

**Issue by springrain** [cloudwego/hertz#777]
**Is your feature request related to a problem? Please describe.**
When I implement activitypub's webfinger, the ContentType needs to be application/jrd+json, and currently does not support custom JSON format ContentType

https://github.com/cloudwego/hertz/blob/develop/pkg/app/server/render/json.go#L78

**Describe the solution you'd like**
JSONRender add a ContentType member, and the Render function handles custom ContentType 
```go
// JSONRender JSON contains the given interface object.
type JSONRender struct {
	Data interface{}
	ContentType string
}

var jsonContentType = "application/json; charset=utf-8"

// Render (JSON) writes data with custom ContentType.
func (r JSONRender) Render(resp *protocol.Response) error {
	if r.ContentType=="" {
		writeContentType(resp, jsonContentType)
	}else{
		writeContentType(resp, r.ContentType)
	}
	
	jsonBytes, err := jsonMarshalFunc(r.Data)
	if err != nil {
		return err
	}

	resp.AppendBody(jsonBytes)
	return nil
}
```
This requirement is relatively small, and maybe it should not be implemented.

**Comment by li-jin-gou** [comment]
@springrain  previously there were users with similar problems, they want to modify contet-type ,which is a break change, basically custom rendor way to customize some special render logic.

**Comment by springrain** [comment]
> @springrain previously there were users with similar problems, they want to modify contet-type ,which is a break change for framework, basically custom rendor way to customize some special render logic.

The problem with custom jsonreader is that having to specify json's JSONMarshaler loses the automatic matching feature of sonic
