### ISSUE TITLE
i have this issue but i'm not sure how to debug or what it means. how to simulate the issue?

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/hertz#778]
i have this issue but i'm not sure how to debug or what it means. how to simulate the issue / problem / error?
what does it mean?
```
server.go:1894: [Error] HERTZ: HTTP2 write response body error when serving 172.70.174.245:26952: http: request method or response status code does not allow body
```

**Comment by rogerogers** [comment]
The status code is 204 but there is also a body?

**Comment by kolinfluence** [comment]
@rogerogers how to check which status codes have body and which doesnt? i'm writing a customized reverse proxy so anything returned with "body" will be used in setbody

**Comment by rogerogers** [comment]
For this specific problem, you can check out the method https://github.com/hertz-contrib/http2/blob/e0eecbe2edd15b04264f8b7ac345e03b021e5193/http2.go#L309. For further information, you need to Google.


> @rogerogers how to check which status codes have body and which doesnt? i'm writing a customized reverse proxy so anything returned with "body" will be used in setbody
