### ISSUE TITLE
herzt啥时候支持http2？

### ISSUE THREAD

**Issue by xj524598** [cloudwego/hertz#779]
herzt啥时候支持http2？
我看 有代码：  engine.protocolServers[suite.HTTP2].Serve(c, conn)，但是无对应实现。。

**Comment by li-jin-gou** [comment]
很早之前就支持了，看下文档吧

**Comment by GuangmingLuo** [comment]
https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/protocol/http2/
