### ISSUE TITLE
[docs]: translate hertz/tutorials/toolkit/template/

### ISSUE THREAD

**Issue by Duslia** [cloudwego/hertz#78]
template:
zh web page：https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/template/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/toolkit/template.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials

Notes:

Do not change the original layout, code style or content sequence.
Software Translator is a tool, not god, do not use the result as the final result.
Translation principle: faithfulness, expressiveness and elegance.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by stephenzhang0713** [comment]
I can help with this translations

**Comment by stephenzhang0713** [comment]
Hi, I would like to help with translations

**Comment by ylck** [comment]
let me try

**Comment by Duslia** [comment]
well done!
