### ISSUE TITLE
2023/05/19 20:21:07.463055 server.go:1928: [Error] HERTZ: HTTP2: write response body error when serving 123.123.123.123:63047: http: request method or response status code does not allow body

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/hertz#788]
**Describe the bug**

@li-jin-gou @Duslia @rogerogers 
```
2023/05/19 20:21:07.463055 server.go:1928: [Error] HERTZ: HTTP2: write response body error when serving 123.123.123.123:63047: http: request method or response status code does not allow body
```

cannot set "consts.StatusNotModified" because in server.go of github.com/hertz-contrib/http2/server.go
line 1922 gives 1928 error if ctx Status return code is 304 notmodified 

pls fix this github.com/hertz-contrib/http2/server.go
it is writeResponseBody() that is giving the error, see comment after line.

server.go file
```
                rw.WriteHeader(reqCtx.Response.StatusCode())
                err = writeResponseBody(rw, reqCtx) //SET BODY HERE WILL ERROR FOR status 304 etc! 
                //those without bodies! BUT... come to think of it, 
                //it should be OK to have custom body for any status. 
                //so i think should fix the code internal.
```
using h2 and latest hertz.

**To Reproduce**
```
func CtxStatusNotModified(ctx *app.RequestContext) {
	ctx.SetStatusCode(consts.StatusNotModified)
	//with or without below line doesnt work
	//ctx.Response.Header.Set("Cache-Control", "no-transform") 
}
```

closed https://github.com/cloudwego/hertz/issues/786 to re-opened here.
**Expected behavior**

no errors

**Screenshots**

**Hertz version:**
0.6

**Comment by kolinfluence** [comment]
@li-jin-gou just curious why you remove it as bug because it is bug using h2

**Comment by li-jin-gou** [comment]
> @li-jin-gou just curious why you remove it as bug because it is bug using h2

I'm currently working on other high-optimality issues, and I'll look at this issue later.

**Comment by li-jin-gou** [comment]
If you are an enterprise user using hertz, please register through our issue(the status does not need to be fully online, testing is also possible), and we will spend extra time to provide high-quality support for related needs - in addition to replying to github issues, hertz is currently responsible for tens of thousands of oncalls from internal services - we are very welcome, if you would you like to help us optimize the framework❤️

**Comment by kolinfluence** [comment]
@li-jin-gou need to iron out the bugs first. this error i have is "crashing" the site with 304 status not found. it's actually very serious.

**Comment by kolinfluence** [comment]
@li-jin-gou please expedite the pull request. truly appreciate this. it's crashing with status codes without body. this is terrible.

**Comment by kolinfluence** [comment]
@welkeyever @li-jin-gou i may have discovered another bug but i need the confirmation that this is not the one affecting it before i can proceed reporting another serious bug i think is not really relevant to this. i cant and wont confirm yet without conclusive evidence.

please expedite this so i can confirm and report the other more serious bug than this. it has something to do with reverseproxy
