### ISSUE TITLE
想使用字节的开源做serviceMesh

### ISSUE THREAD

**Issue by xj524598** [cloudwego/hertz#789]
如题：
目前serviceMesh支持HTTP、HTTPS、GRPC
未来想支持mysql、redis、kafka、mq等
目前看直接使用herzt是可以支撑当前协议，但是担心是否可以基于当前herzt做其他协议的二开。如果直接使用netpoll的话，还需要把http、https、grpc 都集合下

**Comment by li-jin-gou** [comment]
@xj524598 如果只是 http、https、grpc  的话用 hertz 没什么问题，但是如果将来要是还想支持 mysql、redis、kafka 这些的估计就够呛了。
