### ISSUE TITLE
the hertz process terminated automaticly

### ISSUE THREAD

**Issue by angrysnail** [cloudwego/hertz#801]
2023/06/01 08:59:15.183686 client.go:20: [Info] [Godotenv] Init Env success, RUN_ENV: PROD
2023/06/01 08:59:15.183933 client.go:25: [Info] runEnv: PROD,confPath : /data/clan/package/clan-go/conf
2023/06/01 08:59:15.184040 client.go:29: [Info] filepath.Join(confPath, "prod.config.yaml"): /data/clan/package/clan-go/conf/prod.config.yaml
2023/06/01 08:59:15.184645 client.go:40: [Info] [Viper] Conf.App: &viper.App{HostPorts:"0.0.0.0:38080", MaxRequestBodySize:31457280}
2023/06/01 08:59:15.184752 client.go:41: [Info] [Viper] Conf.Redis: &viper.Redis{Addr:"127.0.0.1:6379", Password:"", Db:0, EncodeLockSecond:10, DecodeLockSecond:10, DriftLockSecond:2, CompressLockSecond:5, DriftLimit:10000}
2023/06/01 08:59:15.184825 client.go:43: [Info] [Viper] Conf.Cronjob: &viper.Cronjob{TempFileMinute:1440, TokenMinute:55}
2023/06/01 08:59:15.184883 client.go:44: [Info] [Viper] Conf.Database: &viper.Database{UserName:"root", Password:"yaogouzhangmysql", Host:"localhost", Port:"3306", Name:"clan", Alias:"default"}
2023/06/01 08:59:15.184938 client.go:45: [Info] [Viper] Conf.Tinify: &viper.Tinify{Host:"https://api.tinify.com", Auth:"Basic XXX"}
2023/06/01 08:59:15.185320 client.go:38: [Info] [Redis] PING: ping: PONG
Client.Name is: mysql2023/06/01 08:59:15.190448 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/ping                     --> handlerName=coding.net/angrysnail/clan/biz/handler.Ping (num=3 handlers)
2023/06/01 08:59:15.190605 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/helps      --> handlerName=coding.net/angrysnail/clan/biz/handler.ListHelp (num=4 handlers)
2023/06/01 08:59:15.190701 engine.go:617: [Debug] HERTZ: Method=POST   absolutePath=/clango/api/v1/help       --> handlerName=coding.net/angrysnail/clan/biz/handler.InsertHelp (num=6 handlers)
2023/06/01 08:59:15.190760 engine.go:617: [Debug] HERTZ: Method=PUT    absolutePath=/clango/api/v1/help       --> handlerName=coding.net/angrysnail/clan/biz/handler.EditHelp (num=6 handlers)
2023/06/01 08:59:15.190819 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/help/:id   --> handlerName=coding.net/angrysnail/clan/biz/handler.DeleteHelp (num=5 handlers)
2023/06/01 08:59:15.190875 engine.go:617: [Debug] HERTZ: Method=POST   absolutePath=/clango/api/v1/education  --> handlerName=coding.net/angrysnail/clan/biz/handler.InsertEducation (num=6 handlers)
2023/06/01 08:59:15.190933 engine.go:617: [Debug] HERTZ: Method=PUT    absolutePath=/clango/api/v1/education  --> handlerName=coding.net/angrysnail/clan/biz/handler.EditEducation (num=6 handlers)
2023/06/01 08:59:15.191017 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/member/:id/educations --> handlerName=coding.net/angrysnail/clan/biz/handler.ListEducation (num=4 handlers)
2023/06/01 08:59:15.191079 engine.go:617: [Debug] HERTZ: Method=POST   absolutePath=/clango/api/v1/article    --> handlerName=coding.net/angrysnail/clan/biz/handler.InsertArticle (num=5 handlers)
2023/06/01 08:59:15.191138 engine.go:617: [Debug] HERTZ: Method=POST   absolutePath=/clango/api/v1/article/:id/media --> handlerName=coding.net/angrysnail/clan/biz/handler.AddArticleMedia (num=5 handlers)
2023/06/01 08:59:15.191193 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/articles/mine --> handlerName=coding.net/angrysnail/clan/biz/handler.ListMyArticles (num=4 handlers)
2023/06/01 08:59:15.191248 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/noauth/articles --> handlerName=coding.net/angrysnail/clan/biz/handler.ListArticles (num=4 handlers)
2023/06/01 08:59:15.191301 engine.go:617: [Debug] HERTZ: Method=PUT    absolutePath=/clango/api/v1/noauth/article/:id/read --> handlerName=coding.net/angrysnail/clan/biz/handler.ReadArticle (num=4 handlers)
2023/06/01 08:59:15.191356 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/noauth/article/:id/medias --> handlerName=coding.net/angrysnail/clan/biz/handler.ListArticleMedias (num=4 handlers)
2023/06/01 08:59:15.191420 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/article/:id --> handlerName=coding.net/angrysnail/clan/biz/handler.GetWebArticle (num=4 handlers)
2023/06/01 08:59:15.191475 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/articles   --> handlerName=coding.net/angrysnail/clan/biz/handler.ListWebArticles (num=4 handlers)
2023/06/01 08:59:15.191529 engine.go:617: [Debug] HERTZ: Method=DELETE absolutePath=/clango/api/v1/article/:ids --> handlerName=coding.net/angrysnail/clan/biz/handler.DeleteWebArticle (num=6 handlers)
2023/06/01 08:59:15.191584 engine.go:617: [Debug] HERTZ: Method=PUT    absolutePath=/clango/api/v1/article    --> handlerName=coding.net/angrysnail/clan/biz/handler.SaveWebArticle (num=6 handlers)
2023/06/01 08:59:15.191637 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/noauth/suggestions --> handlerName=coding.net/angrysnail/clan/biz/handler.ListSuggestions (num=4 handlers)
2023/06/01 08:59:15.191690 engine.go:617: [Debug] HERTZ: Method=POST   absolutePath=/clango/api/v1/suggestion --> handlerName=coding.net/angrysnail/clan/biz/handler.InsertSuggestion (num=4 handlers)
2023/06/01 08:59:15.191743 engine.go:617: [Debug] HERTZ: Method=PUT    absolutePath=/clango/api/v1/suggestion/:id/read --> handlerName=coding.net/angrysnail/clan/biz/handler.ReadSuggestion (num=4 handlers)
2023/06/01 08:59:15.191800 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/noauth/comments --> handlerName=coding.net/angrysnail/clan/biz/handler.ListComments (num=4 handlers)
2023/06/01 08:59:15.191853 engine.go:617: [Debug] HERTZ: Method=POST   absolutePath=/clango/api/v1/comment    --> handlerName=coding.net/angrysnail/clan/biz/handler.InsertComment (num=5 handlers)
2023/06/01 08:59:15.191907 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/noauth/activities --> handlerName=coding.net/angrysnail/clan/biz/handler.ListActivities (num=4 handlers)
2023/06/01 08:59:15.191960 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/activity/:id --> handlerName=coding.net/angrysnail/clan/biz/handler.GetActivity (num=4 handlers)
2023/06/01 08:59:15.192025 engine.go:617: [Debug] HERTZ: Method=POST   absolutePath=/clango/api/v1/activity   --> handlerName=coding.net/angrysnail/clan/biz/handler.SaveWebActivity (num=5 handlers)
2023/06/01 08:59:15.192081 engine.go:617: [Debug] HERTZ: Method=DELETE absolutePath=/clango/api/v1/activity/:ids --> handlerName=coding.net/angrysnail/clan/biz/handler.DeleteWebActivity (num=5 handlers)
2023/06/01 08:59:15.192135 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/activities --> handlerName=coding.net/angrysnail/clan/biz/handler.ListWebActivities (num=4 handlers)
2023/06/01 08:59:15.192195 engine.go:617: [Debug] HERTZ: Method=POST   absolutePath=/clango/api/v1/wxUser     --> handlerName=coding.net/angrysnail/clan/biz/handler.SaveWebWxUser (num=5 handlers)
2023/06/01 08:59:15.192248 engine.go:617: [Debug] HERTZ: Method=DELETE absolutePath=/clango/api/v1/wxUser/:ids --> handlerName=coding.net/angrysnail/clan/biz/handler.DeleteWebWxUser (num=5 handlers)
2023/06/01 08:59:15.192303 engine.go:617: [Debug] HERTZ: Method=PUT    absolutePath=/clango/api/v1/wxUser/:ids/admin/:flag --> handlerName=coding.net/angrysnail/clan/biz/handler.AdminWebWxUser (num=5 handlers)
2023/06/01 08:59:15.192359 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/wxUsers    --> handlerName=coding.net/angrysnail/clan/biz/handler.ListWebWxUsers (num=4 handlers)
2023/06/01 08:59:15.192413 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/wxUser/:id --> handlerName=coding.net/angrysnail/clan/biz/handler.GetWebWxUser (num=4 handlers)
2023/06/01 08:59:15.192478 engine.go:617: [Debug] HERTZ: Method=PUT    absolutePath=/clango/api/v1/admin/:type/:id/disable --> handlerName=coding.net/angrysnail/clan/biz/handler.AdminDisableSome (num=5 handlers)
2023/06/01 08:59:15.192541 engine.go:617: [Debug] HERTZ: Method=PUT    absolutePath=/clango/api/v1/admin/suggestion/:id/answer --> handlerName=coding.net/angrysnail/clan/biz/handler.AdminAnswerSuggestion (num=5 handlers)
2023/06/01 08:59:15.192597 engine.go:617: [Debug] HERTZ: Method=PUT    absolutePath=/clango/api/v1/admin/:type/:id/pin --> handlerName=coding.net/angrysnail/clan/biz/handler.MakePinned (num=5 handlers)
2023/06/01 08:59:15.192657 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/admin/punish/:openId --> handlerName=coding.net/angrysnail/clan/biz/handler.GetPunishWxUser (num=5 handlers)
2023/06/01 08:59:15.192714 engine.go:617: [Debug] HERTZ: Method=PUT    absolutePath=/clango/api/v1/admin/punish/:openId/:punish --> handlerName=coding.net/angrysnail/clan/biz/handler.DoPunishWxUser (num=5 handlers)
2023/06/01 08:59:15.192775 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/common/myLatestCountInfo --> handlerName=coding.net/angrysnail/clan/biz/handler.FetchMyLatestCountInfo (num=4 handlers)
2023/06/01 08:59:15.192829 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/noauth/votes --> handlerName=coding.net/angrysnail/clan/biz/handler.ListVotes (num=4 handlers)
2023/06/01 08:59:15.192888 engine.go:617: [Debug] HERTZ: Method=POST   absolutePath=/clango/api/v1/vote       --> handlerName=coding.net/angrysnail/clan/biz/handler.InsertVote (num=5 handlers)
2023/06/01 08:59:15.192941 engine.go:617: [Debug] HERTZ: Method=PUT    absolutePath=/clango/api/v1/vote/:id   --> handlerName=coding.net/angrysnail/clan/biz/handler.Vote (num=5 handlers)
2023/06/01 08:59:15.193003 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/noauth/cemeteries --> handlerName=coding.net/angrysnail/clan/biz/handler.ListCemeteries (num=4 handlers)
2023/06/01 08:59:15.193057 engine.go:617: [Debug] HERTZ: Method=GET    absolutePath=/clango/api/v1/cemetery/:id --> handlerName=coding.net/angrysnail/clan/biz/handler.GetCemetery (num=4 handlers)
2023/06/01 08:59:15.193111 engine.go:617: [Debug] HERTZ: Method=POST   absolutePath=/clango/api/v1/cemetery   --> handlerName=coding.net/angrysnail/clan/biz/handler.SaveCemetery (num=5 handlers)
2023/06/01 08:59:15.193165 engine.go:617: [Debug] HERTZ: Method=PUT    absolutePath=/clango/api/v1/cemetery   --> handlerName=coding.net/angrysnail/clan/biz/handler.SaveCemetery (num=5 handlers)
2023/06/01 08:59:15.193228 engine.go:389: [Info] HERTZ: Using network library=netpoll
2023/06/01 08:59:15.193411 transport.go:109: [Info] HERTZ: HTTP server listening on address=[::]:38080
Terminated

func main() {
	rand.Seed(time.Now().UnixNano())
	// 默认从.env中读取变量，并将其写入到os中
	godotenv.InitGodotenv()
	viper.InitViper()
	redis.InitRedis()
	cronjob.InitCronjob()
	//tinify.InitTinify()
	minio.InitMinio()
	db.InitDatabase()
	rbac.InitToken()

	serverInit()
}

func serverInit() {
	h := server.Default(
		server.WithHostPorts(viper.Conf.App.HostPorts),
		server.WithMaxRequestBodySize(viper.Conf.App.MaxRequestBodySize),
		server.WithExitWaitTime(60),
	)
	h.Use(filters.TokenFilter)
	//h.Use(csrf.New())

	//enforcer, _ := casbin.Custom.NewEnforcer("config/casbin/model.conf")

	enforcer := clancasbin.CustomEnforcer{}

	Auth, _ = casbin.NewCasbinMiddlewareFromEnforcer(enforcer, getPermissions)

	bindingInit()
	register(h)
	h.Run()
}

why? any suggestion?

**Comment by li-jin-gou** [comment]
This has nothing to do with the framework, the program received an exit signal that caused it to exit automatically.

**Comment by li-jin-gou** [comment]
Please fill in the information according to the issue template to help us respond faster.

**Comment by li-jin-gou** [comment]
If you are using nohup to run the service, you may be able to upgrade hertz to the latest version and use Spin to run the service. refer to https://github.com/cloudwego/hertz/pull/441.
