### ISSUE TITLE
数值精度问题

### ISSUE THREAD

**Issue by doing007** [cloudwego/hertz#805]
我按照FAQ中的文档将 数据 序列化成自定义的结构体 (i64 json string) 但是 返回的数据还是 失去了精准
如果我使用了 hterz 和kitex  并且是用了thrift-go 我该怎么 进行 支持int64 的值呢？

**Comment by li-jin-gou** [comment]
json unmarshal 处不做特殊处理也可能会精度丢失。

**Comment by ice4026** [comment]
如果用 jsoniter 的话可以加上 UseNumber，可以保证精度

**Comment by li-jin-gou** [comment]
> 如果用 jsoniter 的话可以加上 UseNumber，可以保证精度

标准库 json 也支持，看代码应该是第二次 unmarshal 的时候精度丢失了。
