### ISSUE TITLE
How to define a flexible zap field in hlog

### ISSUE THREAD

**Issue by Skyenought** [cloudwego/hertz#809]
**Describe the Question**

在使用 logger/zap 的默认配置时, 以下为默认格式
```shell
{"level":"info","ts":1671805077.290119,"msg":"HERTZ: Using network library=standard"}
```
在官方文档中 zap 自定义 field 中 val 基本是写死的
```go
func AccessLog() app.HandlerFunc {
	return func(c context.Context, ctx *app.RequestContext) {
		start := time.Now()
		ctx.Next(c)
		end := time.Now()
		latency := end.Sub(start).Microseconds
		hlog.CtxTracef(c, "status=%d cost=%d method=%s full_path=%s client_ip=%s host=%s",
			ctx.Response.StatusCode(), latency,
			ctx.Request.Header.Method(), ctx.Request.URI().PathOriginal(), ctx.ClientIP(), ctx.Request.Host())
	}
}
// 我想要的不是这种格式
// {"level":"info","ts":1686289281.2581038,","msg":"Hello, World!200"}

// 这种 val 的值被写死了
l := hertzzap.NewLogger(hertzzap.WithZapOptions(zap.Fields(zap.String("service", "logging"))))


```
如果我想要添加像 status 这种实时灵活的 field, 我该怎么做?
```shell
{"level":"info","ts":1686288747.1588864,"msg":"Success","latency":"3.187µs","status":200,"method":"GET","url":"/"}

```
**Reproducible Code**

Please construct a minimum complete and reproducible example for us to get the same error. And tell us how to reproduce it like how you send a request or send what request.

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your question.

**Hertz version:**

Please provide the version of Hertz you are using.

**Environment:**

The output of `go env`.

**Additional context**

Add any other context about the question here.

**Comment by li-jin-gou** [comment]
same to https://github.com/hertz-contrib/logger/issues/32
