### ISSUE TITLE
[docs]: translate hertz/tutorials/tutorials/framework-exten/monitor & log

### ISSUE THREAD

**Issue by Duslia** [cloudwego/hertz#81]
monitor:
zh web page：https://www.cloudwego.io/zh/docs/hertz/tutorials/framework-exten/monitor/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/framework-exten/monitor.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials

log:
zh web page：https://www.cloudwego.io/zh/docs/hertz/tutorials/framework-exten/log/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/framework-exten/log.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials

Notes:

Do not change the original layout, code style or content sequence.
Software Translator is a tool, not god, do not use the result as the final result.
Translation principle: faithfulness, expressiveness and elegance.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by Hao-Wu** [comment]
@Duslia Please assign this to me

**Comment by Duslia** [comment]
Well done!

**Comment by Hao-Wu** [comment]
They're all merged.
This issue can be closed.
