### ISSUE TITLE
How to check the total size in bytes of the ctx request?

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/hertz#810]
**Describe the Question**

1. would like to check the total size in bytes of the ctx.Request header or body or both.

is it possible to do so without looping through the whole request header or something?
other than header request too i mean. everything ctx.Request

2. is there a cap for the ctx.Request header (or body) set by hertz? e.g. maximum header size or body size? is there a way i can set it manually?

**Comment by li-jin-gou** [comment]
![image](https://github.com/cloudwego/hertz/assets/97824201/8b651241-2d2d-4959-b44f-45c5117e6604)
read hertz doc  in https://www.cloudwego.io/docs/hertz/reference/config/
