### ISSUE TITLE
307 Temporary Redirect

### ISSUE THREAD

**Issue by nanakura** [cloudwego/hertz#818]
**Describe the bug**

The request sent by the front-end was corresponding to 307, but my backend code does not define it that way

**To Reproduce**
I have defined routers like the following
```go
func register(r *route.RouterGroup) {
    bucketService := impl.NewBucketService()

    storeGroup := r.Group("/store", pastoMw)
    {
        bucketSubGroup := storeGroup.Group("/bucket")
        {
            bucketSubGroup.POST("/", bucketService.AddBucket) 
        }
    }
}
```

**Expected behavior**

API should be requested normally

**Screenshots**
The request sent by the front-end has been responded to 307
![image](https://github.com/cloudwego/hertz/assets/69560752/80184f31-e420-4497-b0a0-6d9c1ea024cd)

![image](https://github.com/cloudwego/hertz/assets/69560752/82d3c929-3fc1-410c-847e-be59fbc03257)

**Hertz version:**
0.6.4

**Environment:**

The output of `go env`.

```
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=D:\tmp\go-build
set GOENV=C:\Users\27371\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\workspace\Projects\GolandProjects\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\workspace\Projects\GolandProjects
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\workspace\Projects\GolandProjects\go1.19.5
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\workspace\Projects\GolandProjects\go1.19.5\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=D:\workspace\Projects\GolandProjects\src\qiankun-oss\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=D:\tmp\sys\go-build3649694551=/tmp/go-build -gno-record-gcc-switches  
```

**Comment by li-jin-gou** [comment]
![image](https://github.com/cloudwego/hertz/assets/97824201/da994937-fb9f-4cf7-980c-e7ba340185fb)

**Comment by li-jin-gou** [comment]
If this is missing a / triggers an automatic redirect, then I think we should add it to the routing documentation.

**Comment by nanakura** [comment]
> ![image](https://user-images.githubusercontent.com/97824201/246617979-da994937-fb9f-4cf7-980c-e7ba340185fb.png)

got it

**Comment by li-jin-gou** [comment]
This issue is a newbie task waiting to be claimed by others.

**Comment by cqqqq777** [comment]
I have free time

**Comment by welkeyever** [comment]
Assigned to you @cqqqq777

**Comment by cqqqq777** [comment]
https://github.com/cloudwego/cloudwego.github.io/pull/720
