### ISSUE TITLE
[docs]: translate hertz/tutorials/framework-exten/advanced-exten/network-lib/

### ISSUE THREAD

**Issue by Duslia** [cloudwego/hertz#82]
network-lib:
zh web page：https://www.cloudwego.io/zh/docs/hertz/tutorials/framework-exten/advanced-exten/network-lib/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/tutorials/framework-exten/advanced-exten/network-lib.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/tutorials

Notes:

Do not change the original layout, code style or content sequence.
Software Translator is a tool, not god, do not use the result as the final result.
Translation principle: faithfulness, expressiveness and elegance.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by zhoulilily** [comment]
I want to try it. thank you @Duslia

**Comment by Duslia** [comment]
Well done!
