### ISSUE TITLE
项目迁移到herzt的问题

### ISSUE THREAD

**Issue by xj524598** [cloudwego/hertz#820]
背景：使用了迁移脚本后，迁移工作还是很大
项目技术栈：项目使用了fasthttp和grpc
问题：
如上，我的项目使用了fasthttp和grpc分别处理两种流量，为了兼容两者协议，我的很多方法的参数都是context.Context,而迁移脚本并没有替换这些方法或者接口参数。
此外就是我的方法是为了给两者协议都使用的，因此我需要根据context.Context来判断此时是HTTP还是GRPC,但是我看herzt的context是*app.RequestContext，且我暂时不知道如何根据这个RequestContext来判断协议是HTTP还是HTTP2

**Comment by li-jin-gou** [comment]
- 迁移脚本并不能覆盖所有 case。
-  hertz api 的使用先参考这个 PR 吧，基本把 RequestContext 的方法都列出来了 https://github.com/cloudwego/cloudwego.github.io/pull/619/files#diff-0d61c34528c87e0e7db77cfcebcd98347b7738b2854d168259b13fb919f6db48R526
