### ISSUE TITLE
[Question]:How to get native http.ResponseWriter and http.Request using the app.HandlerFunc?

### ISSUE THREAD

**Issue by springrain** [cloudwego/hertz#826]
**Describe the Question**

How to get native http.ResponseWriter and http.Request using the app.HandlerFunc?

**Hertz version:**
0.6.4

**Comment by li-jin-gou** [comment]
https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/adaptor/

**Comment by springrain** [comment]
```go
req, err := adaptor.GetCompatRequest(&c.Request)
```
If I modify the header using the req object, app.RequestContext change automatically?

**Comment by li-jin-gou** [comment]
> ```go
> req, err := adaptor.GetCompatRequest(&c.Request)
> ```
> 
> If I modify the header using the req object, app.RequestContext change automatically?

No

**Comment by springrain** [comment]
Ok, thank you very much, I modified the third-party components to be compatible with Hertz, no need to adapt
