### ISSUE TITLE
hz new submodule

### ISSUE THREAD

**Issue by comien** [cloudwego/hertz#828]
**Describe the Question**

之前是通过独立仓的方式使用 hz
```
hz new -module demo
```
想请教一下，怎么在大仓模式下创建服务。
例如，我想在 app/ 创建一个 hz 的 api 服务，用根目录的 go.mod。
```sh
├── app
├── go.mod
└── go.sum
```

**Comment by li-jin-gou** [comment]
refer to https://github.com/cloudwego/biz-demo/tree/main/easy_note

**Comment by comien** [comment]
> refer to https://github.com/cloudwego/biz-demo/tree/main/easy_note

解决了谢谢，我的 hz 版本有些低，没有发现新增的一些命令选项
