### ISSUE TITLE
hertz server connection monitoring

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/hertz#831]
**Is your feature request related to a problem? Please describe.**

When there is an abnormal request on the line when the framework does not have connection monitoring, this time it is very difficult to troubleshoot the problem .

**Describe the solution you'd like**

Supports connection monitoring

**Additional context**

This is a real online requirement.

**Comment by welkeyever** [comment]
Waiting for help? Or transfer it to meego task.

**Comment by Haswf** [comment]
Do you have any additional context for the issue? It's not clear to me what we should do.

**Comment by li-jin-gou** [comment]
There are no actual scenarios at the moment, choose to turn it off .
