### ISSUE TITLE
 Unknown flag: --hertz_opt when init project with protobuf

### ISSUE THREAD

**Issue by xinjiyuan97** [cloudwego/hertz#832]
**Describe the Question**
使用文档中的protobuf创建hertz的项目时，提示 Unknown flag: --hertz_opt

**Reproducible Code**

plugin protoc_gen_hertz returns error: exit status 1, cause:
Unknown flag: --hertz_opt

**Expected behavior**
成功初始化项目

**Screenshots**
![image](https://github.com/cloudwego/hertz/assets/12007836/6628cd93-ad6f-40ce-81f8-ae1cd02b17be)
生成后的目录结构
![image](https://github.com/cloudwego/hertz/assets/12007836/2be03ab9-0f26-4cf5-bb57-c8e82c78ad7e)

**Hertz version:**
hz version v0.6.4
ubuntu 20.04
golang 1.20
libprotoc 3.0.0

**Environment:**
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/azureuser/work/bin"
GOCACHE="/home/azureuser/.cache/go-build"
GOENV="/home/azureuser/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/azureuser/work/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/azureuser/work"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/azureuser/work/src/gitee.com/xinjiyuan97/mock_account/go.mod"
GOWORK=""

**Additional context**

Add any other context about the question here.

**Comment by li-jin-gou** [comment]
我试下。

**Comment by FGYFFFF** [comment]
@xinjiyuan97 可以`hz --verbose new -I --idl` 打下详细日志；我猜测 这个问题和 protoc 的版本有关系，目前我的protoc 版本如下
```
$ protoc --version
libprotoc 3.21.12
```
