### ISSUE TITLE
hertztools

### ISSUE THREAD

**Issue by xiaolibuzai-ovo** [cloudwego/hertz#837]
**能否支持指定生成的model名称呢？以及package名称**
**model生成似乎存在些问题，并非预期结果**

这是我使用的命令  hz model --idl "xxx" 

他总会在biz/model目录下，生成一个以idl文件命名的目录，并且idl文件名称以thrift idl 的namespace层级命名，是否可以修改呢？
<img width="177" alt="image" src="https://github.com/cloudwego/hertz/assets/96616876/fb012107-7b62-488c-bfee-e1fe435b7eed">

**Comment by xiaolibuzai-ovo** [comment]
并且似乎生成的文件有些问题，预期应该只有model，但文件中实际生成了很多thrift相关的rpc包

**Comment by welkeyever** [comment]
支持修改的。
P.S issue填写的时候勿删模板本身的项，没有置空就行了，否则会被ci识别为无效issue

**Comment by li-jin-gou** [comment]
要是还有问题，内部同学直接在内部提 oncall 吧 @xiaolibuzai-ovo
