### ISSUE TITLE
:memo: [docs]: translate hertz/faq/

### ISSUE THREAD

**Issue by Duslia** [cloudwego/hertz#84]
faq:
zh web page：https://www.cloudwego.io/zh/docs/hertz/faq/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/faq/_index.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/faq

Notes:

Do not change the original layout, code style or content sequence.
Software Translator is a tool, not god, do not use the result as the final result.
Translation principle: faithfulness, expressiveness and elegance.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by daydaygo** [comment]
https://github.com/cloudwego/cloudwego.github.io/pull/214

**Comment by Duslia** [comment]
Hi~ There are some comments on this PR https://github.com/cloudwego/cloudwego.github.io/pull/214. Could you pls fix it?

**Comment by GuangmingLuo** [comment]
The assignee of this issue has been reset.

**Comment by Haswf** [comment]
I would like to work on this.

**Comment by li-jin-gou** [comment]
The assignee of this issue has been reset.

**Comment by KevinChens** [comment]
I am willing to work for this :)

**Comment by li-jin-gou** [comment]
> I am willing to work for this :)

thanks @KevinChens
