### ISSUE TITLE
how to show memory allocation / cpu runtime of processes in production environment?

### ISSUE THREAD

**Issue by kolinfluence** [cloudwego/hertz#840]
having a lot of garbage generated and not sure where the code is.
possible to give an idea?

i suspect it's many tls termination memory alloc issue etc

**Comment by li-jin-gou** [comment]
use pprof and refer to https://www.freecodecamp.org/news/how-i-investigated-memory-leaks-in-go-using-pprof-on-a-large-codebase-4bec4325e192/
