### ISSUE TITLE
[docs]: translate hertz/reference/config/

### ISSUE THREAD

**Issue by Duslia** [cloudwego/hertz#85]
config:
zh web page：https://www.cloudwego.io/zh/docs/hertz/reference/config/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/reference/config.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/reference

Notes:

Do not change the original layout, code style or content sequence.
Software Translator is a tool, not god, do not use the result as the final result.
Translation principle: faithfulness, expressiveness and elegance.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by liweitingwt** [comment]
hello, I want to try this issue, thank you.

**Comment by Duslia** [comment]
Well done!
