### ISSUE TITLE
【Question】.proto file service group

### ISSUE THREAD

**Issue by orange-juzipi** [cloudwego/hertz#853]
**Describe the Question**

proto文件中 `service` 如何设置路由的前缀，实现 restfull 风格?

**Comment by justlorain** [comment]
可以试试这样，参考[hz 使用 (protobuf)](https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/usage/usage-protobuf/)

```protobuf
service HelloService {
  rpc HelloGET(HelloReq) returns(HelloResp) {
    option (api.get) = "/hello";
  }
  rpc HelloPOST(HelloReq) returns(HelloResp) {
    option (api.post) = "/hello";
  }
}
```

**Comment by orange-juzipi** [comment]
> 可以这样尝试，参考[hz 使用 (protobuf)](https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/usage/usage-protobuf/)
> 
> ```proto
> service HelloService {
>   rpc HelloGET(HelloReq) returns(HelloResp) {
>     option (api.get) = "/hello";
>   }
>   rpc HelloPOST(HelloReq2) returns(HelloResp2) {
>     option (api.post) = "/hello";
>   }
> }
> ```

嗯嗯，目前用的是这种，就是生成之后看到有分组的代码，以为可以设置在分组之上。

**Comment by justlorain** [comment]
> > 可以这样尝试，参考[hz 使用 (protobuf)](https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/usage/usage-protobuf/)
> > ```proto
> > service HelloService {
> >   rpc HelloGET(HelloReq) returns(HelloResp) {
> >     option (api.get) = "/hello";
> >   }
> >   rpc HelloPOST(HelloReq2) returns(HelloResp2) {
> >     option (api.post) = "/hello";
> >   }
> > }
> > ```
> 
> 嗯嗯，目前用的是这种，就是生成之后看到有分组的代码，以为可以设置在分组之上。

有公共前缀的话 hz 会自动分组的
