### ISSUE TITLE
如何感知请求已结束？

### ISSUE THREAD

**Issue by peng19940915** [cloudwego/hertz#855]
比如请求中间突然断开了，而此时有一个任务正在执行（如在远程pod上执行一段命令），希望感知到这次断开，并做出对应的清理工作，我看了gin框架使用的net/http是支持该特性的：ctx.Done(), 给每个请求都创建了一个channel
但翻了下hertz以前的issue，发现你们觉得该特性会带来很大性能开销，类似场景hertz有无更好的解决思路？

**Comment by welkeyever** [comment]
本质上其实是想要一个链接断开的时候被cancel的ctx？

**Comment by peng19940915** [comment]
> 本质上其实是想要一个链接断开的时候被cancel的ctx？

嗯嗯，只要能感知到链接断开就行

**Comment by welkeyever** [comment]
翻了一下标准库的实现，你只的是https://github.com/golang/go/blob/master/src/net/http/server.go#L2011 这个地方的cancel吗，这个cancel比较粗暴，handler执行完毕就cancel了，而非链接关闭才执行；

目前 netpoll 网络库应该能做到真正链接断开的时候cancel上下文，不过这部分最好能够和标准网络库实现对齐。

**Comment by xiaotushaoxia** [comment]
你的需求是。“当一个请求过来的时候你阻塞地调用一个函数（函数第一个参数是ctx），你希望客户端断开tcp连接的时候可以让ctx Done” 吗。

**Comment by peng19940915** [comment]
> 你的需求是。“当一个请求过来的时候你阻塞地调用一个函数（函数第一个参数是ctx），你希望客户端断开tcp连接的时候可以让ctx Done” 吗。 @peng19940915



> 翻了一下标准库的实现，你指的是https://github.com/golang/go/blob/master/src/net/http/server.go#L2011 这个地方的cancel吗，这个cancel比较粗暴，handler执行完毕就cancel了，而非链接关闭才执行；
> 
> 目前 netpoll 网络库应该能做到真正链接断开的时候cancel上下文，不过这部分最好能够和标准网络库实现对齐。

**Comment by peng19940915** [comment]
> 你的需求是。“当一个请求过来的时候你阻塞地调用一个函数（函数第一个参数是ctx），你希望客户端断开tcp连接的时候可以让ctx Done” 吗。 @peng19940915

差不多吧，核心需求是希望因为网络中断等原因导致客户端与hertz断开了，hertz要能感知到，感知到后才能做出相应的资源回收动作

**Comment by peng19940915** [comment]
> xiaotushaoxia

抱歉这么晚才回复，hertz有办法能实现嘛？目前业务上有类似场景，用户发起了一个请求，服务端调用了一个第三方程序，但有时候用户主动断开请求后，第三方程序还是在跑

**Comment by xiaotushaoxia** [comment]
> > xiaotushaoxia
> 
> 抱歉这么晚才回复，hertz有办法能实现嘛？目前业务上有类似场景，用户发起了一个请求，服务端调用了一个第三方程序，但有时候用户主动断开请求后，第三方程序还是在跑

我也没找到，可能要换上websocket吧 这样可以知道连接有没有断开

**Comment by li-jin-gou** [comment]
> > xiaotushaoxia
> 
> 抱歉这么晚才回复，hertz有办法能实现嘛？目前业务上有类似场景，用户发起了一个请求，服务端调用了一个第三方程序，但有时候用户主动断开请求后，第三方程序还是在跑

hi，@xiaotushaoxia @peng19940915  可以飞书联系聊下，如果在生产环境下使用 hertz 并且的确是真实需求的话我们可以支持一下

**Comment by chaoranz758** [comment]
plz assign to me

**Comment by liqiaoyang-pm** [comment]
你好，这个问题最后解决了吗，我最近也有一个这个需求，在gin中可以感知到，但是hertz就是不行

**Comment by li-jin-gou** [comment]
> 你好，这个问题最后解决了吗，我最近也有一个这个需求，在gin中可以感知到，但是hertz就是不行

在这个 PR 跟进，没赶上 0.9.0 ，下周争取合入 https://github.com/cloudwego/hertz/pull/1054

**Comment by jjeejj** [comment]
这个需求很常见：比如发生消息的时候 客户端断开链接，消息到了服务端 但是还没有发出去， 这个时候  可能有的需求就会取消这次的消息的发送

**Comment by welkeyever** [comment]
> 这个需求很常见：比如发生消息的时候 客户端断开链接，消息到了服务端 但是还没有发出去， 这个时候 可能有的需求就会取消这次的消息的发送

@jjeejj 已经合入 & 发版了，参见上面那个 pr 哈。
具体用法加个这个配置：https://github.com/cloudwego/hertz/pull/1054/files#diff-520119af3b6cf25ece68ba17379009fdc1839d18db0c0e997758e49ea8d45f4aR408
