### ISSUE TITLE
hz: The term 'hz' is not recognized

### ISSUE THREAD

**Issue by hduyyg** [cloudwego/hertz#856]
windows安装hertz之后，hz命令无法识别
PS D:\work\go-work\src\userdemo> go install github.com/cloudwego/hertz/cmd/hz@latest
PS D:\work\go-work\src\userdemo> hz -v
hz: The term 'hz' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by li-jin-gou** [comment]
https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/usage/cautions/#%E4%BD%BF%E7%94%A8-windows-%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%E6%97%B6%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
