### ISSUE TITLE
hertz 服务注册染色概念

### ISSUE THREAD

**Issue by laixiaohuai** [cloudwego/hertz#858]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

可以支持染色概念吗？就是同一套环境，加了请求标识（可以是请求头，可以是其他模式），可以访问到特定实例，当染色的实例不存在，请求将到没染色标识的实例上来兜底

**Describe alternatives you've considered**

**Additional context**

**Comment by li-jin-gou** [comment]
可以看下 istio

**Comment by GuangmingLuo** [comment]
Kitex 支持 xDS 协议和 Proxyless 架构，可以结合 Istio 在框架侧实现泳道和自定义路由，详见 https://github.com/kitex-contrib/xds 和相关公众号文章；Hertz 暂未支持 xDS 协议，需要结合开源的服务网格数据面+控制面来实现染色和泳道。
