### ISSUE TITLE
[docs]: translate hertz/reference/version & json

### ISSUE THREAD

**Issue by Duslia** [cloudwego/hertz#86]
version:
zh web page：https://www.cloudwego.io/zh/docs/hertz/reference/version/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/reference/version.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/reference

json:
zh web page：https://www.cloudwego.io/zh/docs/hertz/reference/json/
zh doc：https://github.com/cloudwego/cloudwego.github.io/blob/main/content/zh/docs/hertz/reference/json.md
en folder：https://github.com/cloudwego/cloudwego.github.io/tree/main/content/en/docs/hertz/reference

Notes:

Do not change the original layout, code style or content sequence.
Software Translator is a tool, not god, do not use the result as the final result.
Translation principle: faithfulness, expressiveness and elegance.
Submit your PR here in this [repo](https://github.com/cloudwego/cloudwego.github.io).

**Comment by Duslia** [comment]
Well done!

**Comment by Duslia** [comment]
This PR has been merged. However, the hierarchy of the document is incorrect.

**Comment by stephenzhang0713** [comment]
> This PR has been merged. However, the hierarchy of the document is incorrect. We fix it.

Hi, I have fixed the layout of document in my PR: https://github.com/cloudwego/cloudwego.github.io/pull/240 , plz review this PR
