### ISSUE TITLE
什么情况下 server 会主动 fin 客户端连接（非idle timeout）

### ISSUE THREAD

**Issue by coder-user** [cloudwego/hertz#861]
herzt server 监听的端口为 9946，使用netpoll的transport

并发性能测试时候，发现服务端请求完成后，主动 fin（非idle timeout） 的情况，在客户端连接池复用的情况下，可能会导致部分失败

请问一下，在什么情况下，服务端会主动 fin 客户端的连接???

![image](https://github.com/cloudwego/hertz/assets/35922343/fd27343d-fc06-46dc-b240-f48c5ed7f221)

当前考虑尝试设置一下 gopool.SetCap()

**Comment by welkeyever** [comment]
应该只有短连接场景可能有存在显示的连接关闭，看看对应的请求是否带有 `Connection: Close` 这个 header

**Comment by rogerogers** [comment]
HTTP版本是1.0，就带着Connection: Close貌似。

**Comment by welkeyever** [comment]
嗯，HTTP/1.0 除非显示设置 Connection 为非 Close，才是长链接，默认情况都是短连接。 @coder-user

**Comment by li-jin-gou** [comment]
> HTTP版本是1.0，就带着Connection: Close貌似。

@rogerogers 一针见血👍🏻

**Comment by coder-user** [comment]
谢谢各位  @welkeyever @rogerogers
