### ISSUE TITLE
I've come across async cache and mcache but any lru cache suitable to use with hertz?

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#865]
**Describe the Question**

I've come across async cache and mcache but any lru cache suitable to use with hertz?

developed by you guys or whatever. looking for a minimal byte alloc solution preferably zero alloc.

curious what do you guys use for lru cache that's all.

**Comment by li-jin-gou** [comment]
No but welcome to make a pull request.

**Comment by HzTTT** [comment]
I want to try it

**Comment by li-jin-gou** [comment]
@HzTTT  Thanks a lot, I wasn't sure about the difficulty, it might not be very easy to implement and there's no real user scenario where you have to use it.

**Comment by li-jin-gou** [comment]
Sorry, that should have been a question.
