### ISSUE TITLE
hert的请求响应流程文档，源码分析，有吗

### ISSUE THREAD

**Issue by Webster-Yang** [cloudwego/hertz#870]
hert的请求响应流程文档，源码分析，有吗

**Comment by li-jin-gou** [comment]
没有，但是 goland 可以在handler里断点，左下角会把函数的堆栈信息打印出来，这样一下就能看出执行流程

**Comment by li-jin-gou** [comment]
> 纯粹好奇 你们这内部部门有多少团队在使用?

用 Go 写 HTTP 服务的团队都在用 hertz 👀 @cccvip

**Comment by li-jin-gou** [comment]
https://juejin.cn/post/7271518821818335287 from @Skyenought

**Comment by AllianceTing** [comment]
Apply to claim this issue

**Comment by Skyenought** [comment]
https://juejin.cn/post/7239910240359694396

**Comment by AllianceTing** [comment]
[Hertz](https://bytedance.feishu.cn/docx/SIzodJrxXoQPvrxQTdccBGyjncd)

**Comment by AllianceTing** [comment]
https://juejin.cn/post/7291134345926344704
