### ISSUE TITLE
当路径中本身有冒号时，会和命名参数路由冲突，该怎么解决？

### ISSUE THREAD

**Issue by clumsy456** [cloudwego/hertz#872]
**Describe the Question**

https://ga4gh.github.io/task-execution-schemas/docs/#operation/CancelTask
![image](https://github.com/cloudwego/hertz/assets/19684295/04fe2b08-1db4-4394-9fa6-f647947f82b6)
要实现这样的路由，当path写作`/:id:cancel`的时候，会报错 "only one wildcard per path segment is allowed"

**Reproducible Code**

**Expected behavior**

能够正确处理路径中原有的冒号

**Screenshots**

**Hertz version:**

v0.6.6

**Comment by li-jin-gou** [comment]
cc @welkeyever 这个有推荐解决方案不

**Comment by welkeyever** [comment]
':' 应该是属于url中的特殊字符：分割host和port，如果作为普通字符存在于url中需要对其转义的。确认一下是否是需要定义一个':'在url里吧，这个应该是不符合rfc规范的。

fyi：https://datatracker.ietf.org/doc/html/rfc3986#section-2.2

**Comment by rogerogers** [comment]
python有这种写法貌似，这里如果要兼容可以用一个通配路由，比如 `tasks/:idAction` 然后在方法里区分具体操作

**Comment by clumsy456** [comment]
> python有这种写法貌似，这里如果要兼容可以用一个通配路由，比如 `tasks/:idAction` 然后在方法里区分具体操作

我目前也只能这样处理了

**Comment by clumsy456** [comment]
> ':' 应该是属于url中的特殊字符：分割host和port，如果作为普通字符存在于url中需要对其转义的。确认一下是否是需要定义一个':'在url里吧，这个应该是不符合rfc规范的。
> 
> fyi：https://datatracker.ietf.org/doc/html/rfc3986#section-2.2

明白你说的这个不符合规范。不过，我引用的这个https://ga4gh.github.io/task-execution-schemas/docs/#operation/CancelTask是一个开源的API规范，说明实际还是有这种用法的。我不确定这种用法是不是有一定的广泛程度。

**Comment by Duslia** [comment]
用一个参数路由匹配 {id}:cancel，然后自己解一下

**Comment by welkeyever** [comment]
> > ':' 应该是属于url中的特殊字符：分割host和port，如果作为普通字符存在于url中需要对其转义的。确认一下是否是需要定义一个':'在url里吧，这个应该是不符合rfc规范的。
> > fyi：https://datatracker.ietf.org/doc/html/rfc3986#section-2.2
> 
> 明白你说的这个不符合规范。不过，我引用的这个https://ga4gh.github.io/task-execution-schemas/docs/#operation/CancelTask 是一个开源的API规范，说明实际还是有这种用法的。我不确定这种用法是不是有一定的广泛程度。

应该不会，hertz目前线上几万个服务，你说的这种url用法还是第一次听说。
