### ISSUE TITLE
命令是 hz update -idl idl/api.thrift 报错

### ISSUE THREAD

**Issue by wilac-pv** [cloudwego/hertz#873]
使用https://github.com/cloudwego/hertz-examples/blob/main/bizdemo/hertz_gorm/idl/api.thrift 
命令是 hz update -idl idl/api.thrift 
生成出来的model下的api.go 报错、原因是少参数context

**Comment by li-jin-gou** [comment]
refer to https://github.com/cloudwego/kitex/issues/479
