### ISSUE TITLE
IDL don't generate vd tag

### ISSUE THREAD

**Issue by towelong** [cloudwego/hertz#88]
![image](https://user-images.githubusercontent.com/41502558/174834255-b1cb9a60-a4e5-4788-9756-9b1d46e00794.png)
![image](https://user-images.githubusercontent.com/41502558/174834362-f34c0e19-6fd7-4526-873c-6ed587437f77.png)

**Comment by Duslia** [comment]
You need to define vd tag on HelloReq struct, not HelloService. Please refer to https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/toolkit/#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95.
<img width="690" alt="image" src="https://user-images.githubusercontent.com/37136584/174920045-5a83aaff-5414-404e-944a-ebcec0291914.png">

**Comment by towelong** [comment]
> You need to define vd tag on HelloReq struct, not HelloService. Please refer to https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/toolkit/#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95. <img alt="image" width="690" src="https://user-images.githubusercontent.com/37136584/174920045-5a83aaff-5414-404e-944a-ebcec0291914.png">

thinks, I had been resolved this issue.
