### ISSUE TITLE
How does standard.transport switch netpoll.transporter

### ISSUE THREAD

**Issue by Webster-Yang** [cloudwego/hertz#880]
How does standard.transport switch netpoll.transporter

**Comment by li-jin-gou** [comment]
https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/network-lib/

**Comment by GuangmingLuo** [comment]
现在从文档里面找资料有遇到什么困难吗？如果没有困难，建议优先去官网文档浏览或者检索你想要的信息~

**Comment by li-jin-gou** [comment]
> 现在从文档里面找资料有遇到什么困难吗？如果没有困难，建议优先去官网文档浏览或者检索你想要的信息~

后面目录打平一些应该一眼就能看到了～

**Comment by li-jin-gou** [comment]
条件编译 windows 会自动切换 net
