### ISSUE TITLE
对于 Server 来说，默认使用netpoll还是standard

### ISSUE THREAD

**Issue by Webster-Yang** [cloudwego/hertz#881]
https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/network-lib/

对于 Server 来说，默认使用 netpoll

<img width="824" alt="企业微信截图_16909504718064" src="https://github.com/cloudwego/hertz/assets/5946139/3520626e-bda9-48a5-9515-4b28d813ed0d">

从代码上看，默认是standard

**Comment by li-jin-gou** [comment]
https://github.com/cloudwego/hertz/issues/880#issuecomment-1661470795

条件编译，不同操作系统行为不一样
