### ISSUE TITLE
压测对比，结果符合预期吗

### ISSUE THREAD

**Issue by Webster-Yang** [cloudwego/hertz#883]
### 代码
```
package main

import (
	"context"
	"errors"
	"fmt"
	"io/ioutil"
	"net/http"
	_ "net/http/pprof"
	"strconv"
	"strings"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/network/netpoll"
	"github.com/cloudwego/hertz/pkg/network/standard"
	"github.com/valyala/fasthttp"
)

func startNetpollHertzServer() {
	h := server.New(server.WithHostPorts("0.0.0.0:8881"), server.WithTransport(netpoll.NewTransporter))

	h.POST("/echo", func(ctx context.Context, c *app.RequestContext) {
		body, _ := c.Body()
		c.Bind(body)
		c.Write(body)
	})

	h.Spin()
}

func startStandardHertzServer() {
	h := server.New(server.WithHostPorts("0.0.0.0:8882"), server.WithTransport(standard.NewTransporter))

	h.POST("/echo", func(ctx context.Context, c *app.RequestContext) {
		body, _ := c.Body()
		c.Bind(body)
		c.Write(body)
	})

	h.Spin()
}

// 启动调试服务器
func startNetHttpServer() {
	http.HandleFunc("/echo", func(w http.ResponseWriter, r *http.Request) {
		body, _ := ioutil.ReadAll(r.Body)
		w.Write(body)
	})
	e := http.ListenAndServe("0.0.0.0:8883", nil)
	if e != nil {
		for {
			e = http.ListenAndServe("0.0.0.0:8883", nil)
			if e == nil {
				return
			}
			time.Sleep(time.Minute)
		}
	}
}

func main() {
	go func() {
		startNetpollHertzServer()
	}()

	go func() {
		startStandardHertzServer()
	}()

	go func() {
		startNetHttpServer()
	}()

	requestHandler := func(ctx *fasthttp.RequestCtx) {
		defer func() {
			if r := recover(); r != nil {
				//check exactly what the panic was and create error.
				var err error
				switch x := r.(type) {
				case string:
					err = errors.New(x)
				case error:
					err = x
				default:
					err = errors.New("unknow panic")
				}
				fmt.Println(err.Error())
			}

		}()

		path := string(ctx.Path())
		if strings.HasPrefix(path, "/echo") {
			IResponse(ctx, 200, ctx.Request.Body())
		}

	}

	if err := fasthttp.ListenAndServe(":8884", requestHandler); err != nil {
		fmt.Println(err.Error())
	}
}

func IResponse(ctx *fasthttp.RequestCtx, code int, responseBody []byte) {
	ctx.Response.SetStatusCode(code)
	ctx.Response.Header.ResetConnectionClose()
	ctx.Response.Header.Set("Content-Length", strconv.Itoa(len(responseBody)))
	//	ctx.Response.Header.Set("Content-Type", "application/json")
	ctx.Success("application/json", responseBody)
}

```

### 压测服务器

| ip                    | 核 | 内存 | 备注 |
| ----------------------- | ---------------- | ------------ | ----------------------- |
|10.100.217.239 | 4核|4G|| 

### body为51字节

```
 ["service=tcbase.java.dsf.dsf.demo.java.service4"]
```

### 压测echo端口

| 端口                    | 框架  | 备注 |
| ----------------------- | ---------------- | ------------ |
|:8883|net.http||
|:8884|fasthttp||
|:8881 |hertz|netpoll|
|:8882 |hertz|standard|

### fasthttp接口压测
http://10.100.217.239:8884/echo

|| 100 个线程                  |  300 个线程   |  500 个线程   |  700 个线程   | 1000 个线程   |
|----| ----------------------- | ---------------- | ------------ | ----------------------- |----------------------- |
|qps|39337.05|37929.08|101487.36|99591.35|105322.56|
|avg(ms)|0|0|3|5|7|
|失败率(%)|0|0|0|0|0|
|cpu使用率|53%|60%|100%|100%|100%|
|内存使用率|21%|21%|21%|21%|21%|

### net.http接口压测
http://10.100.217.239:8883/echo

|| 100 个线程                  |  300 个线程   |  500 个线程   |  700 个线程   | 1000 个线程   |
|----| ----------------------- | ---------------- | ------------ | ----------------------- |----------------------- |
|qps|36946.96|39792.09|51703.64|54352.19|55335.07|
|avg(ms)|0|0|7|11|17|
|失败率(%)|0|0|0|0|0|
|cpu使用率|75%|81%|98%|100%|100%|
|内存使用率|21%|21%|21%|21%|21%|

### hertz standard 接口压测
http://10.100.217.239:8882/echo

|| 100 个线程                  |  300 个线程   |  500 个线程   |  700 个线程   | 1000 个线程   |
|----| ----------------------- | ---------------- | ------------ | ----------------------- |----------------------- |
|qps|40621.62|37407.93|92102.05|88432.58|55929.24|
|avg(ms)|0|0|4|6|8|
|失败率(%)|0|0|0|0|3.489|
|cpu使用率|54%|56%|100%|100%|100%|
|内存使用率|18%|18%|18%|18%|18%|

### hertz netpoll接口压测
http://10.100.217.239:8881/echo

|| 100 个线程                  |  300 个线程   |  500 个线程   |  700 个线程   | 1000 个线程   |
|----| ----------------------- | ---------------- | ------------ | ----------------------- |----------------------- |
|qps|39666.38|38812.93|85481.04|87767.05|93564.48|
|avg(ms)|0|0|3|6|9|
|失败率(%)|0|0|0|0|0|
|cpu使用率|53%|58%|95%|99%|98%|
|内存使用率|16%|17%|18%|18%|18.5%|

**Comment by Webster-Yang** [comment]
hertz standard
hertz netpoll
fasthttp
三者的性能差不多啊

**Comment by li-jin-gou** [comment]
参考 https://www.cloudwego.io/zh/blog/2023/02/24/http-%E6%A1%86%E6%9E%B6-hertz-%E5%AE%9E%E8%B7%B5%E5%85%A5%E9%97%A8%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95%E6%8C%87%E5%8D%97/
