### ISSUE TITLE
希望cloudwego文档加入夜间模式

### ISSUE THREAD

**Issue by cold-runner** [cloudwego/hertz#885]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

希望前端能在cloudwego文档中增加夜间主题，晚上阅读时保护视力

**Comment by li-jin-gou** [comment]
点赞，可以按照模板改下 issue ，否则会被自动关闭哈

**Comment by welkeyever** [comment]
文档的优化在这里追踪吧：https://github.com/cloudwego/cloudwego.github.io
Hertz 仓库更多关注的是框架范畴内的事情

**Comment by cold-runner** [comment]
> 文档的优化在这里追踪吧：https://github.com/cloudwego/cloudwego.github.io Hertz 仓库更多关注的是框架范畴内的事情

好的
