### ISSUE TITLE
about Tracer add more simple demo or example

### ISSUE THREAD

**Issue by GreenAppleOne** [cloudwego/hertz#89]
Link tracing is a fundamental piece of information needed in every environment in the project, can it be started by default at the log or database level? In addition, can you give an example that is more friendly to newbies and can be used out of the box, although there is an example in the hertz example, it does not meet the basic needs.

**Comment by Duslia** [comment]
Yes. Batteries included is our long-term goal. In  the future, we will provide more example and more out-of-box ability to help user to construct Hertz project. If you'd like to cooperate with us or have some idea, you can join our user group. We can discuss deeply.

**Comment by Duslia** [comment]
We support obs-opentelementry these days.
repo: https://github.com/hertz-contrib/obs-opentelemetry
example: https://github.com/cloudwego/hertz-examples/tree/main/opentelemetry
If you have any other questions, please join Lark group or report a github issue
