### ISSUE TITLE
hertz创建的http接口，能否生成trace id？

### ISSUE THREAD

**Issue by 929421803** [cloudwego/hertz#892]

**Comment by li-jin-gou** [comment]
参考 https://github.com/cloudwego/biz-demo/pull/18/files 基于 https://github.com/hertz-contrib/obs-opentelemetry/blob/main/README_CN.md 实现了你说的功能

**Comment by li-jin-gou** [comment]
这个问题比较经典，下次可以按照 issue 模版填写否则 issue 会被关闭。

**Comment by justlorain** [comment]
最新的 requestid 中间件可以直接通过配置 `WithGenerator` 返回 traceid 参考[这里](https://github.com/cloudwego/biz-demo/pull/19/files#diff-b6131233ba8311dfdd9358d9316620334d26961cdf616d49c112432327a0169d)
