### ISSUE TITLE
域名如何映射到内部路由地址?

### ISSUE THREAD

**Issue by springrain** [cloudwego/hertz#896]
**Describe the Question**

基于hertz搭建了saas平台,例如a用户的首页地址是 /saas/web/a/index, /saas/web/是固定路径,/a/*代表是a用户所有数据,现在a用户想使用自己的域名解析,比如 aaa.com,希望直接使用域名访问,例如首页就是 aaa.com/index,路径中不再显示 /saas/web/a,这个功能应该如何实现呢?

**Comment by rogerogers** [comment]
感觉这不是应该网关或代理来实现的吗

**Comment by springrain** [comment]
> 感觉这不是应该网关或代理来实现的吗

优先使用hertz自身实现,这样就不依赖外部的nginx了.

**Comment by li-jin-gou** [comment]
反向代理或者 handlContext 了..

**Comment by li-jin-gou** [comment]
如果不需要过中间件的话，直接获取路由信息然后执行 handler 应该也可以。 https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/route/#%E8%8E%B7%E5%8F%96%E8%B7%AF%E7%94%B1%E6%B3%A8%E5%86%8C%E4%BF%A1%E6%81%AF

**Comment by springrain** [comment]
可以根据请求方法和路径,获取这个路由所有的HandlerFunc吗? 主要是为了完成路由匹配的过程.

**Comment by springrain** [comment]
修改```route.Engine```的```ServeHTTP```方法可以实现,需要扩展一个函数,这个需求应该是小众的,不知道是否需要pr?
```go
// ServeHTTP makes the router implement the Handler interface.
func (engine *Engine) ServeHTTP(c context.Context, ctx *app.RequestContext) {
	if engine.PanicHandler != nil {
		defer engine.recv(ctx)
	}

	rPath := ""
	if engine.GetOptions().FuncRewrite != nil {
		rPath, _ = engine.GetOptions().FuncRewrite(c, ctx)
	}
	if rPath == "" {
		rPath = string(ctx.Request.URI().Path())
		if engine.GetOptions().UseRawPath {
			rPath = string(ctx.Request.URI().PathOriginal())
		}
	}
	//rPath := string(ctx.Request.URI().Path())
```

**Comment by li-jin-gou** [comment]
PATL @welkeyever

**Comment by welkeyever** [comment]
这个应该是一个[反向代理](https://github.com/hertz-contrib/reverseproxy/blob/master/reverse_proxy.go#L62)相关的需求，hertz 来实现可能并不合适，建议通过分层来解耦这个场景。或者直接通过 [NoRoute](https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/engine/#noroute) 劫持路由逻辑，自行决定路由匹配规则。

**Comment by springrain** [comment]
好的,非常感谢,我先使用反向代理实现吧
