### ISSUE TITLE
"phonenumbers" using a lot of memory

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#904]
see this, it's using a lot of mem and keeps increasing.
using h2. is there a reason why it is so? pls look into it. thx

![Screenshot from 2023-08-13 03-46-34](https://github.com/cloudwego/hertz/assets/51492452/e3d7d760-684b-4806-9746-bbcd9a63d720)

**Comment by li-jin-gou** [comment]
I don't see any memory consumption about hertz h2, please check the business logic.
