### ISSUE TITLE
长轮询场景无法实现

### ISSUE THREAD

**Issue by mazhan465** [cloudwego/hertz#909]
我们公司由于服务QPS较高，希望使用hertz框架的netpoll网络库来优化自身性能。
http场景和websocekt场景都能适配，但是在适配长轮询业务场景中，似乎无法实现。
尝试使用websocket的upgrade方法中实现逻辑调用hijack，但是在http handler中调用之后，需要将http handler返回，而不能执行阻塞，等待其余业务的返回。
我们尝试将hijack后的阻塞逻辑go出去，但是这样会导致在serve方法中，调用handle之后，直接调用flush返回http header，让客户端认为结束本次请求，但由于在serve方法中，hijack的执行是在handler之后，如果handler方法不结束，却又无法进入hijack中的逻辑，希望可以解决此问题

**Comment by li-jin-gou** [comment]
这个场景支持的，https://www.cloudwego.io/zh/docs/hertz/tutorials/framework-exten/response_writer/

**Comment by li-jin-gou** [comment]
要是打算在内部实际场景落地 hertz 的话可以飞书联系，详细聊聊。
