### ISSUE TITLE
请问 thrif 和 protobuf 有特定的使用场景吗？我该如何抉择？

### ISSUE THREAD

**Issue by Sue211213** [cloudwego/hertz#910]
请问 thrif 和 protobuf 有特定的使用场景吗？我该如何抉择？

**Comment by li-jin-gou** [comment]
对于 hertz 来说没有，就是借住 idl 生成结构体和一些基本的桩代码，但是开源的话 pb 生态丰富，有一些现成的插件 hz 可以直接使用。
