### ISSUE TITLE
hertz框架使用gen导包问题

### ISSUE THREAD

**Issue by Hiromu-amaza** [cloudwego/hertz#912]
**Describe the Question**

如下，generate.go文件中的impoet中的genModel路径（orm_gen），应该是运行generato.go文件后所生成的文件。
为什么现在就可以被引用

**Screenshots**

![7d5d5bc2b9f2f594def9d1760196098](https://github.com/cloudwego/hertz/assets/99572630/e55c6ad5-75f9-4883-b15c-59cb45a08863)
![113fd0e1daac702c42b15501682cbc2](https://github.com/cloudwego/hertz/assets/99572630/f99af5de-1bb1-4a62-901d-f1cee8a0847f)

**Hertz version:**

0.6.3

**Comment by li-jin-gou** [comment]
@Hiromu-amaza 和作者确定了正常应该分成两步的
