### ISSUE TITLE
自定义 package 模板 handler.go：处理函数逻辑 如何获取到对应的 ServiceName

### ISSUE THREAD

**Issue by CoolLiuzw** [cloudwego/hertz#918]
**Describe the Question**

自定义 package 模板 handler.go：处理函数逻辑 如何获取到对应的 ServiceName 

如下配置：
```protobuf
proto
service User {
  rpc Login(xxx) returns(xxx) {
    option(api.get)="xxxx";
  }
}
```

```go
// handler.go
func Login(ctx context.Context, c *app.RequestContext) {
      ...

l := service.NewUserService(ctx, c) // l.service.New{{.ServiceName}}Service, 如这边的 ServiceName 为 User
  ...
}
```

**Hertz version:**
hz version v0.6.6

**Environment:**
set GOVERSION=go1.20.6

**Comment by coder-user** [comment]
![image](https://github.com/cloudwego/hertz/assets/35922343/de65d91b-fb35-4246-a474-be90ff2dba80)

请问可以在`type Handler struct`结构体中添加一个`ServiceName string`字段来满足这个需求吗？

---
如果适合的话，我提交一下代码

**Comment by li-jin-gou** [comment]
PATL @FGYFFFF

**Comment by li-jin-gou** [comment]
能参考一下 cgwo 的 hertz 模版吧 https://github.com/cloudwego/cwgo/tree/main/tpl/hertz/server/standard

**Comment by coder-user** [comment]
> 能参考一下 cgwo 的 hertz 模版吧 https://github.com/cloudwego/cwgo/tree/main/tpl/hertz/server/standard

当前hertz模版 handler.go 部分为：
```go
          resp,err := service.New{{$MethodInfo.Name}}Service(ctx, c).Run(&req)
          if err != nil {
               utils.SendErrResponse(ctx, c, consts.StatusOK, err)
               return
          }
```
模版为，Service 中的每个 Method 独立一个 New{{方法名称}}Service 函数。

---

我期望是基于 Service 的名称，一个 Service 只有一个 `New{{.ServiceName}}Service` 方法，如下

```go
l := service.NewUserService(ctx, c) // l.service.New{{.ServiceName}}Service, 如这边的 ServiceName 为 User
  ...
}
```

当前分析 hz 代码，handler 模版的 data，无 ServiceName 相关信息，期望能补充一下

**Comment by FGYFFFF** [comment]
> > 能参考一下 cgwo 的 hertz 模版吧 https://github.com/cloudwego/cwgo/tree/main/tpl/hertz/server/standard
> 
> 当前hertz模版 handler.go 部分为：
> 
> ```go
>           resp,err := service.New{{$MethodInfo.Name}}Service(ctx, c).Run(&req)
>           if err != nil {
>                utils.SendErrResponse(ctx, c, consts.StatusOK, err)
>                return
>           }
> ```
> 
> 模版为，Service 中的每个 Method 独立一个 New{{方法名称}}Service 函数。
> 
> 我期望是基于 Service 的名称，一个 Service 只有一个 `New{{.ServiceName}}Service` 方法，如下
> 
> ```go
> l := service.NewUserService(ctx, c) // l.service.New{{.ServiceName}}Service, 如这边的 ServiceName 为 User
>   ...
> }
> ```
> 
> 当前分析 hz 代码，handler 模版的 data，无 ServiceName 相关信息，期望能补充一下

有的，https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/more-feature/template/#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%80%E4%B8%AA-package-%E6%A8%A1%E6%9D%BF cc

**Comment by coder-user** [comment]
> > > 能参考一下 cgwo 的 hertz 模版吧 https://github.com/cloudwego/cwgo/tree/main/tpl/hertz/server/standard
> > 
> > 
> > 当前hertz模版 handler.go 部分为：
> > ```go
> >           resp,err := service.New{{$MethodInfo.Name}}Service(ctx, c).Run(&req)
> >           if err != nil {
> >                utils.SendErrResponse(ctx, c, consts.StatusOK, err)
> >                return
> >           }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 模版为，Service 中的每个 Method 独立一个 New{{方法名称}}Service 函数。
> > 我期望是基于 Service 的名称，一个 Service 只有一个 `New{{.ServiceName}}Service` 方法，如下
> > ```go
> > l := service.NewUserService(ctx, c) // l.service.New{{.ServiceName}}Service, 如这边的 ServiceName 为 User
> >   ...
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 当前分析 hz 代码，handler 模版的 data，无 ServiceName 相关信息，期望能补充一下
> 
> 有的，https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/more-feature/template/#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%80%E4%B8%AA-package-%E6%A8%A1%E6%9D%BF cc

麻烦讲讲具体哪里，
我是需要在 handler.go 文件夹模版中获取到 ServiceName

**Comment by FGYFFFF** [comment]
<img width="1271" alt="image" src="https://github.com/cloudwego/hertz/assets/97507466/351ea8af-c0b5-47f8-84c9-5cf6c8ac0b45">
可以看下这里。 如果是想修改默认handler 的话，目前不是感知serviceName的，可以直接重新定义一个 handler 模板

**Comment by MelodyMKII** [comment]
> <img alt="image" width="1271" src="https://private-user-images.githubusercontent.com/97507466/262538021-351ea8af-c0b5-47f8-84c9-5cf6c8ac0b45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEwMTgxODIsIm5iZiI6MTc0MTAxNzg4MiwicGF0aCI6Ii85NzUwNzQ2Ni8yNjI1MzgwMjEtMzUxZWE4YWYtYzBiNS00N2Y4LTg0YzktNWNmNmM4YWMwYjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzAzVDE2MDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYjViMjBiYTU5YTlhNWZiZTM3ZWEzODY2M2U3M2Y5MjllOTgxZjg0ZTNkOWIwMGYwMzc2ZTQ5YWNjNDk4N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.92pChRBhDYFg63t0kkwrpD8dGpNYzPt2BnnDgi8Uinc"> 可以看下这里。 如果是想修改默认handler 的话，目前不是感知serviceName的，可以直接重新定义一个 handler 模板

遇到同样的问题，如果重新定义handler模板，首先没办法禁用掉默认的handler.go模板，
![Image](https://github.com/user-attachments/assets/64ea1225-e2e6-4c22-94bc-b91a7fbbe464)
而且实现时需要考虑out_dir 的相对路径

所以希望还是希望能在handler.go里面提供ServiceName

**Comment by eliohn** [comment]
在Hanler 也取不到包名吗？GenPackage
