### ISSUE TITLE
protoc_gen_hertz returns error: exit status 1

### ISSUE THREAD

**Issue by Sue211213** [cloudwego/hertz#919]
According to `hertz` official example, I imported `google/protobuf/descriptor.proto` in `idl/api.proto` file.

When I execute the generate command, it throws an error `google/protobuf/descriptor.proto: File not found.`.

The same code, in a Linux environment is fine. I don't know if this is a bug or if it's a windows issue.

Official example: https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/usage-protobuf/

**Comment by Sue211213** [comment]
**Describe the Question**

这个问题来自于官方示例：[hz 使用 (protobuf) | CloudWeGo](https://www.cloudwego.io/zh/docs/hertz/tutorials/toolkit/usage-protobuf/)

按照步骤，在完成 idl 的编写后，执行命令 `hz new -I idl -idl idl/hello/hello.proto`，发生错误：

```bash
hz new -I idl -idl idl/hello/hello.proto
#plugin protoc_gen_hertz returns error: exit status 1, cause:
#google/protobuf/descriptor.proto: File not found.
#api.proto:6:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
#api.proto:10:8: "google.protobuf.FieldOptions" is not defined.
#...
```

**Reproducible Code**

我是在 Windows 系统下编写此示例

> 在 Linux 环境下尝试过可以成功。

**Screenshots**

![image-20230818141146483](https://github.com/cloudwego/hertz/assets/96043433/2e0d1d9b-9ec7-4e9b-90a1-7969ea044a21)


**Hertz version:**

```bash
hz --version
#hz version v0.6.6
```

**Environment:**

```bash
go env
#set GO111MODULE=auto
#set GOARCH=amd64
#set GOBIN=
#set GOCACHE=C:\Users\cc\AppData\Local\go-build
#set GOENV=C:\Users\cc\AppData\Roaming\go\env
#set GOEXE=.exe
#set GOEXPERIMENT=
#set GOFLAGS=
#set GOHOSTARCH=amd64
#set GOHOSTOS=windows
#set GOINSECURE=
#set GOMODCACHE=D:\workspace\golang\pkg\mod
#set GONOPROXY=
#set GONOSUMDB=
#set GOOS=windows
#set GOPATH=D:\workspace\golang
#set GOPRIVATE=
#set GOPROXY=https://goproxy.cn,direct
#set GOROOT=D:\Go
#set GOSUMDB=sum.golang.org
#set GOTMPDIR=
#set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
#set GOVCS=
#set GOVERSION=go1.19.4
#set GCCGO=gccgo
#set GOAMD64=v1
#set AR=ar
#set CC=gcc
#set CXX=g++
#set CGO_ENABLED=1
#set GOMOD=D:\workspace\golang\src\proto_demo\go.mod
#set GOWORK=
#set CGO_CFLAGS=-g -O2
#set CGO_CPPFLAGS=
#set CGO_CXXFLAGS=-g -O2
#set CGO_FFLAGS=-g -O2
#set CGO_LDFLAGS=-g -O2
#set PKG_CONFIG=pkg-config
#set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\cc\AppData\Local\Temp\go-build3905511486=/tmp/go-build -gno-record-gcc-switches 
```

**Comment by rogerogers** [comment]
下载protoc的时候里面有个include文件夹，使用的时候可以指定到 `-I` 选项。Linux会从一些默认位置查找这些文件，比如`/usr/local/include` `$HOME/.local/include`等位置，Windows应该也有这种文件夹，不过我不太熟悉，Windows可以手动指定下，或者放到把 `include` 里面的google文件夹放到idl文件夹
