### ISSUE TITLE
hertz 绑定验证参数 如何只输出 错误信息 和支持 中文错误信息

### ISSUE THREAD

**Issue by as882301** [cloudwego/hertz#929]
如下图 错误信息可以支持中文错误信息输出吗？还有可以直接拿到错误信息 cause 吗？
![tt](https://github.com/cloudwego/hertz/assets/8169000/0773840f-9a98-4d26-ae64-f192822a49a7)

**Comment by li-jin-gou** [comment]
支持中文的，目前底层依赖 https://github.com/bytedance/go-tagexpr/blob/8355f4a779516f099096ae65fb70e7cca8bc26ab/binding/error.go#L4 需要断言类型转换一下，就可以获取到字段，不过我们新版的 binding 近期就要合入了，不依赖这个库了。

**Comment by as882301** [comment]
> 支持中文的，目前底层依赖 https://github.com/bytedance/go-tagexpr/blob/8355f4a779516f099096ae65fb70e7cca8bc26ab/binding/error.go#L4 需要断言类型转换一下，就可以获取到字段，不过我们新版的 binding 近期就要合入了，不依赖这个库了。

好的 我之前gin中使用
github.com/go-playground/validator/v10
可以入下图把自带的一些验证方法转成中文的错误信息

![image](https://github.com/cloudwego/hertz/assets/8169000/d69b9d36-9b3c-4ec2-9137-afecba1bd625)

新版本希望的可以直接获取到错误信息 和带上 多语言错误信息

**Comment by li-jin-gou** [comment]
PATL @FGYFFFF

**Comment by rogerogers** [comment]
https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/binding-and-validate/#%E8%87%AA%E5%AE%9A%E4%B9%89-bind-%E5%92%8C-validate-%E7%9A%84-error

应该是这个吧，自定义error handler之后在里面处理

**Comment by as882301** [comment]
> https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/binding-and-validate/#%E8%87%AA%E5%AE%9A%E4%B9%89-bind-%E5%92%8C-validate-%E7%9A%84-error
> 
> 这个应该可以吧，自定义error handler之后在里面处理

已有的验证规则没有支持转成中文信息的

**Comment by FGYFFFF** [comment]
> > 支持中文的，目前底层依赖 https://github.com/bytedance/go-tagexpr/blob/8355f4a779516f099096ae65fb70e7cca8bc26ab/binding/error.go#L4 需要断言类型转换一下，就可以获取到字段，不过我们新版的 binding 近期就要合入了，不依赖这个库了。
> 
> 好的 我之前gin中使用 github.com/go-playground/validator/v10 可以入下图把自带的一些验证方法转成中文的错误信息
> 
> ![image](https://user-images.githubusercontent.com/8169000/263588105-d69b9d36-9b3c-4ec2-9137-afecba1bd625.png)
> 
> 新版本希望的可以直接获取到错误信息 和带上 多语言错误信息

新版本的校验逻辑可以自定义为"github.com/go-playground/validator/v10"，到时候应该可以直接切换过去

**Comment by as882301** [comment]
> > > 支持中文的，目前底层依赖 https://github.com/bytedance/go-tagexpr/blob/8355f4a779516f099096ae65fb70e7cca8bc26ab/binding/error.go#L4 需要断言类型转换一下，就可以获取到字段，不过我们新版的 binding 近期就要合入了，不依赖这个库了。
> > 
> > 
> > 好的 我之前gin中使用 github.com/go-playground/validator/v10 可以入下图把自带的一些验证方法转成中文的错误信息
> > ![image](https://user-images.githubusercontent.com/8169000/263588105-d69b9d36-9b3c-4ec2-9137-afecba1bd625.png)
> > 新版本希望的可以直接获取到错误信息 和带上 多语言错误信息
> 
> 新版本的校验逻辑可以自定义为"github.com/go-playground/validator/v10"，到时候应该可以直接切换过去

好的 期待新版本 ！

**Comment by li-jin-gou** [comment]
❤️

**Comment by liuzhaowei55** [comment]
期待新版验证方案的尽快发布

**Comment by li-jin-gou** [comment]
> 期待新版验证方案的尽快发布

就在今天 @liuzhaowei55

**Comment by tizips** [comment]
请问重构后的校验文档什么时候会更新出来

**Comment by li-jin-gou** [comment]
有进度在这个 issue 更新。 cc @FGYFFFF

**Comment by tizips** [comment]
OK，期待

**Comment by FGYFFFF** [comment]
@tizips https://github.com/hertz-contrib/binding/tree/main/go_playground  可参考这里的 Example，将 Validator 切换到 go-playground/validator。

**Comment by xuyang404** [comment]
更新吗？原本vd校验能否支持转成中文信息呢？
