### ISSUE TITLE
一个报错：the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection

### ISSUE THREAD

**Issue by antyiwei** [cloudwego/hertz#935]
**Describe the Question**

一个报错
the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection

**Reproducible Code**

package request2

import (
"context"
"crypto/tls"
"encoding/json"
"errors"
"fmt"
"time"

"github.com/sirupsen/logrus"

"github.com/cloudwego/hertz/pkg/app/client"
"github.com/cloudwego/hertz/pkg/network/standard"
"github.com/cloudwego/hertz/pkg/protocol"
"github.com/cloudwego/hertz/pkg/protocol/consts"
)

var cli *client. Client
var err error

func init() {
cli, err = client. NewClient(
client.WithDialTimeout(1*time.Second), // 连接建立超时时间，默认 1s
client.WithDialer(standard.NewDialer()),
client.WithKeepAlive(true),
client.WithMaxIdleConnDuration(5*time.Second), // 设置空闲连接超时时间，当超时后会关闭该连接，默认10s
client.WithMaxConnDuration(10*time.Second),    // 设置连接存活的最大时长，超过这个时间的连接在完成当前请求后会被关闭，默认无限长
client.WithMaxConnWaitTimeout(5*time.Second),  // 设置等待空闲连接的最大时间，默认不等待
client.WithTLSConfig(&tls.Config{
InsecureSkipVerify: true,
}),
)
if err != nil {
return
}
}

func Post(url string, header map[string]string, req, resp interface{}) error {

R := &protocol. Request{}
RP := &protocol. Response{}

R.SetMethod(consts.MethodPost)
R.SetRequestURI(url)
R.SetHeader("Content-Type", "application/json;  charset=UTF-8")
R.SetHeaders(header)

defer func() {
logrus.WithFields(logrus.Fields{
"R.Header. Header":  string(R.Header.Header()),
"R.Body":           string(R.Body()),
"RP.Header. Header": string(RP.Header.Header()),
"PR.Body":          string(RP.Body()),
}).Info("请求上游")
}()

reqJson, err := json.Marshal(req)
if err != nil {
return err
}
R.AppendBody(reqJson)

err = cli.DoTimeout(context.Background(), R, RP, 2*time.Second)
if err != nil {
return err
}

switch RP.StatusCode() {
case 200:
goto end
case 400:
return errors. New("400 interfaceError")
case 401:
return errors. New("401 Unauthorized")
case 403:
return errors. New("403 permissionDenied")
case 404:
return errors. New("404 page not found")
case 429:
return errors. New("429 trigger current limiting")
case 503:
return errors. New("503 Service unavailable")
default:
return errors. New("service is gone")
}

end:

//fmt.Printf("----->%v %v %v", string(RP.Body()), json.Valid([]byte(RP.Body())), RP.StatusCode())

if !json.Valid(RP.Body()) {
return fmt. Errorf("%v", string(RP.Body()))
}

err = json.Unmarshal(RP.Body(), &resp)
if err != nil {
return err
}

return nil

}
 

**Hertz version:**

github.com/cloudwego/hertz v0.6.0
github.com/cloudwego/netpoll v0.3.1

**Environment:**

k8s pod

执行的是一个二进制文件

**Comment by welkeyever** [comment]
升级到最新 hertz再试试，针对这个问题应该有个优化。

**Comment by antyiwei** [comment]
<img width="595" alt="image" src="https://github.com/cloudwego/hertz/assets/26668105/c829411e-f52f-4acb-b32d-5bf6cad60d40">

**Comment by antyiwei** [comment]
go get -u github.com/cloudwego/hertz                          
go: upgraded github.com/cloudwego/hertz v0.6.0 => v0.6.8
go: upgraded github.com/cloudwego/netpoll v0.3.1 => v0.3.2


本地升级了一下，只能明天看看了

**Comment by welkeyever** [comment]
Possibly related to this optimize: #871.

**Comment by antyiwei** [comment]
情况并没有解决，问题依然存在。
<img width="1514" alt="image" src="https://github.com/cloudwego/hertz/assets/26668105/5f2ac45d-f132-47db-860e-ae2f4206d1c2">

**Comment by welkeyever** [comment]
稍等，我试试

**Comment by antyiwei** [comment]
1. 升级版本，昨天没有发布成功。
2. 上游网络出现故障，当前我无法确定升级的效果

**Comment by welkeyever** [comment]
新版本能兜住一部分，这个日志说明池中的连接失效了，进行了一次尝试：
```
[Warn] HERTZ: Client connection attempt times: 1, url: http://localhost:8888/post. This is mainly because the connection in pool is closed by peer in advance. If this number is too high which indicates that long-connection are basically unavailable, try to change the request to short-connection.
```

不过看起来应该没有完全cover住所有的case，这个我再看看，有进展了在这里update。
