### ISSUE TITLE
extremely slow, slower than gnet by 40% benchmark because of syscall6

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/hertz#937]
possible to fix this?

"prefork mode" of hertz for "Hello World!" for techempower benchmark
https://github.com/cloudxaas/gosprapp/blob/main/web/app/app.go

possible to provide guidance on how to speed it up?
gnet ~ 95k req/s
hertz ~ 55k req/s

that's almost 40% slower than gnet

![Screenshot from 2023-09-06 12-32-22](https://github.com/cloudwego/hertz/assets/51492452/6b14e508-4be1-4a39-a8e6-e0ba8f6c6768)

**Comment by li-jin-gou** [comment]
Can you provide detailed code and pressure test environment? I only see hertz's code.

**Comment by hiqsociety** [comment]
@li-jin-gou 
the code is compared with
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Go/gnet/src/main.go

wrk -t 1 -d 10 http://.... :8080 / 8081

pls try it out.
io_uring is the next step. just saying that's all. thx

**Comment by hiqsociety** [comment]
@li-jin-gou trying to use this framework with "prefork mode" to compete in techempower benchmark

do guide on how to make it faster. thx

**Comment by li-jin-gou** [comment]
this is pr in https://github.com/TechEmpower/FrameworkBenchmarks/pull/8483 @hiqsociety  
I don't think it makes much sense to compare gnet and hertz, maybe look at gnet and netpoll.

**Comment by li-jin-gou** [comment]
I think hertz support for prefork could be a higher priority, as it seems like his performance gains are huge. @hiqsociety

**Comment by hiqsociety** [comment]
@li-jin-gou i dunno what this is about but hertz should be compared with gnet / fiber and it's still very slow compared to either.

whatever mode you prefer, just make it faster than what it is currently.

it's really too slow, defeats the purpose of using hertz.

> This is pr in [TechEmpower/FrameworkBenchmarks#8483](https://github.com/TechEmpower/FrameworkBenchmarks/pull/8483) @hiqsociety We found that the code for the benchmark was not the same, which could lead to inaccurate results. I don't think it makes much sense to compare gnet and hertz, maybe look at gnet and netpoll.
> 
> * netpoll-benchmark: https://github.com/cloudwego/netpoll-benchmark

**Comment by hiqsociety** [comment]
@li-jin-gou it's fixed? possible to open this issue as a continual speed improvements update?

**Comment by li-jin-gou** [comment]
> @li-jin-gou it's fixed? possible to open this issue as a continual speed improvements update? i just submitted a pull request to techempower benchmark on the prefork mode.
> 
> is there any guidance on built in prefork mode for hertz or can just use mine?

OK, [#8483](https://github.com/TechEmpower/FrameworkBenchmarks/pull/8483)  already merged and @Skyenought  will explore ways to optimize performance include Prefork etc.

**Comment by hiqsociety** [comment]
this non-preforked results make hertz look so bad.
https://www.techempower.com/benchmarks/#hw=ph&test=plaintext&section=data-r22

my prefork version is accepted into the latest techempower benchmark repo. hope to be included in hertz as default prefork.

**Comment by li-jin-gou** [comment]
> this non-preforked results make hertz look so bad. https://www.techempower.com/benchmarks/#hw=ph&test=plaintext&section=data-r22
> 
> my prefork version is accepted into the latest techempower benchmark repo. hope to be included in hertz as default prefork.

Don't really want to maintain prefork as there is no real user demand for it.  If a user wants to use prefork, I think it would be a good idea to refer them to your code. https://github.com/TechEmpower/FrameworkBenchmarks/pull/8528
