### ISSUE TITLE
在我处理 http 请求业务时，我应该如何判断我的 http client 已经是断开的状态了

### ISSUE THREAD

**Issue by wvculfckln6002** [cloudwego/hertz#939]
**Describe the Question**

在我处理 http 请求业务时，我应该如何判断我的 http client 已经是断开的状态了

标准库的话，可以通过 context.Done， hz 是怎么判断呢？

**Comment by li-jin-gou** [comment]
和这个是不是一样的？https://github.com/cloudwego/hertz/issues/855
