### ISSUE TITLE
想咨询个 批量idl生成代码 的简单问题~

### ISSUE THREAD

**Issue by SIN5t** [cloudwego/hertz#943]
**Describe the Question**
    为多个idl生成代码的时候，且这多个idl中可能有关联性，如何一次性生成呢？

A clear and concise description of what the question is.
    之前尝试一个一个生成，例如 命令：`hz new  -idl idl/user.proto  -module github.com/SIN5t/tiktok_v2 --out_dir cmd/api/`
    生成user的idl之后，如果还想在同一个路径生成其他的idl，会提示覆盖问题，使用-force指令等

   自己尝试一次生成多个：
  ```
 hz new  -idl idl/user.proto idl/video.proto idl/relation.proto idl/message.proto idl/favorite.proto idl/co
mment.proto  -module github.com/SIN5t/tiktok_v2 --out_dir cmd/api/  
```
  
   或者想用通配符：`hz new  -idl idl/*.proto  -module github.com/SIN5t/tiktok_v2 --out_dir cmd/api/`
   结果都不尽人意，自己猜的不行

   看了官方hertz使用的例子，似乎都是一个idl文件的生成实例，试了很久没有解决问题。也看了cloudwego的说明文档，可能自己能力不足，没找到解决方案

相信开发人员还是很轻松能回答我这个问题的，最近一直弄不出来，劳烦回复~

**Comment by li-jin-gou** [comment]
PATL @FGYFFFF

**Comment by SIN5t** [comment]
十分感谢！问题已经解决!!

**Comment by li-jin-gou** [comment]
暂时打开，设置为 first good issue @SIN5t

**Comment by Skyenought** [comment]
assign me
