### ISSUE TITLE
希望websocket支持到go 1.20

### ISSUE THREAD

**Issue by Hiromu-amaza** [cloudwego/hertz#945]
websocket仅支持到go1.19，采用go 1.20作为环境时会报错，请问什么时候可以适配go 1.20
![abb1099b0e5e857567368aec05fa7df](https://github.com/cloudwego/hertz/assets/99572630/113bce25-7236-4b91-968e-b8dc392467ee)

**Comment by li-jin-gou** [comment]
@Hiromu-amaza 更新一下 sonic 版本即可。
