### ISSUE TITLE
中间件中无法获取session

### ISSUE THREAD

**Issue by suosuo6** [cloudwego/hertz#951]
![WX20230921-161848@2x](https://github.com/cloudwego/hertz/assets/42489992/4701236d-d033-4799-9e5c-b9d6f08e0c9f)
**Describe the Question**

A clear and concise description of what the question is.

**Reproducible Code**

Please construct a minimum complete and reproducible example for us to get the same error. And tell us how to reproduce it like how you send a request or send what request.

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your question.

**Hertz version:**

Please provide the version of Hertz you are using.

**Environment:**

The output of `go env`.

**Additional context**

Add any other context about the question here.

**Comment by li-jin-gou** [comment]
参考 https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/middleware/session/

**Comment by li-jin-gou** [comment]
获取 session 需要将执行 session 中间件的逻辑
