### ISSUE TITLE
Request help：add docs for config hook of host client

### ISSUE THREAD

**Issue by welkeyever** [cloudwego/hertz#952]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Add docs for add docs for config hook of host client. Related pr: https://github.com/cloudwego/hertz/pull/938.

**Describe alternatives you've considered**

Add docs under https://github.com/cloudwego/cloudwego.github.io both in EN & CH.

**Additional context**
Related docs page: https://www.cloudwego.io/zh/docs/hertz/reference/config/

**Comment by lim-yoona** [comment]
Can i try this issue?

**Comment by justlorain** [comment]
Thanks!
