### ISSUE TITLE
Feature Request: add api.proto to `hz new`? 

### ISSUE THREAD

**Issue by Skyenought** [cloudwego/hertz#956]
**Is your feature request related to a problem? Please describe.**

在 hz 使用 proto 生成代码时, 每次都要从文档中复制 api.proto, 我觉得可以在 hz new 时生成一个, 不使用可以自行删除

**Describe the solution you'd like**

能否在 `hz new` 时增加 api.proto 

**Describe alternatives you've considered**

**Additional context**

**Comment by li-jin-gou** [comment]
这个不是 Question @Skyenought 另外这个有实际的用户场景&诉求嘛
