### ISSUE TITLE
使用官方文档的获取ClientIP的方法，偶尔会出现获取到内网ip的情况

### ISSUE THREAD

**Issue by dcy** [cloudwego/hertz#958]
使用v0.6.8版本，根据[官方文档](https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/context/request/#setclientipfunc)，获取代码如下：
```golang
func GetIP(c *app.RequestContext) string {
	ip := c.ClientIP()
	opts := app.ClientIPOptions{
		RemoteIPHeaders: []string{"X-Forwarded-For", "X-Real-IP"},
		TrustedProxies:  map[string]bool{ip: true},
	}
	c.SetClientIPFunc(app.ClientIPWithOption(opts))

	return c.ClientIP() 
```
正常的请求，在`X-Forwarded-For`和`X-Real-IP`都是外网ip的情况下，偶尔会获取到client的ip是内网ip

**Comment by li-jin-gou** [comment]
在 https://github.com/cloudwego/hertz/pull/934 已修复，待发版，发版之后关闭这个 PR

**Comment by li-jin-gou** [comment]
这个 issue 的 SetClientIPFunc 文档有问题 @chaoranz758

**Comment by li-jin-gou** [comment]
@dcy 已发版

**Comment by li-jin-gou** [comment]
文档优化 done https://github.com/cloudwego/cloudwego.github.io/pull/796
