### ISSUE TITLE
www.cloudwego.io 打不开了

### ISSUE THREAD

**Issue by flyerxp** [cloudwego/hertz#966]
www.cloudwego.io 打不开了
帮助手册无法查看了。
这个是要放弃了吗？

**Comment by li-jin-gou** [comment]
参考 https://github.com/cloudwego/cloudwego.github.io/issues/803

**Comment by rogerogers** [comment]
可以加下飞书群，有进展会及时公布。

**Comment by flyerxp** [comment]
> 可以加下飞书群，有进展会及时公布。
哪个飞书群？有码码，贴下扫码。

**Comment by rogerogers** [comment]
https://github.com/cloudwego/hertz#community
