### ISSUE TITLE
[QUESTION] - How to set different Read Timeout for http handlers and websocket handler

### ISSUE THREAD

**Issue by sujit-baniya** [cloudwego/hertz#969]
**Describe the Question**

By default hertz has 3 minutes of Read timeout which is fine. But I wanted to disable ReadTimeout for Websocket handler. Currently the websocket connection auto close with error `Error connection read timeout`.

Is it possible to disable or increase the Read Timeout for websocket handler.

**Comment by li-jin-gou** [comment]
https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/protocol/websocket/#setreadtimeoutsetwritetimeout
