### ISSUE TITLE
Request help: add streaming gzip in hertz gzip doc

### ISSUE THREAD

**Issue by chaoranz758** [cloudwego/hertz#973]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Add docs for streaming gzip middleware.  Related pr: https://github.com/hertz-contrib/gzip/pull/11.

**Describe alternatives you've considered**

Add docs under https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/middleware/gzip/ both in EN & CH.

**Additional context**

Related reference:
https://github.com/hertz-contrib/gzip#for-server-stream-compression
https://github.com/hertz-contrib/gzip/tree/main/example/stream

**Comment by Claude-Zq** [comment]
I want to work on this

**Comment by Claude-Zq** [comment]
@chaoranz758 想确认一下GzipStream 是流式压缩流式写 还是 整体压缩后再流式写
https://github.com/cloudwego/cloudwego.github.io/pull/829#discussion_r1365441253
