### ISSUE TITLE
通过thrift生成的resp结构体，默认会在字段后面加上 query, form, thrift等tag，像query这种tag就不必生成了

### ISSUE THREAD

**Issue by guaidashu** [cloudwego/hertz#975]
<img width="997" alt="image" src="https://github.com/cloudwego/hertz/assets/17829682/08266d0f-4c1f-4b99-9898-00b69c82538c">

**Comment by Skyenought** [comment]
这些 go tag 不会影响 json render, 实际上的无感知的, 无须关注
