### ISSUE TITLE
使用文档错误, 服务端没有此配置项(WithDisableHeaderNamesNormalizing), 客户端有

### ISSUE THREAD

**Issue by shixiaofeia** [cloudwego/hertz#976]
WithDisableHeaderNamesNormalizing 这个配置项我需要在服务端使用, 文档上写的也是服务端, 但实际使用服务端没有, 没有客户端有
![image](https://github.com/cloudwego/hertz/assets/63829677/853e9b7d-75a3-43ca-9290-f1e3e0121a0b)

**Comment by li-jin-gou** [comment]
升级到最新&&参考 https://github.com/cloudwego/hertz/releases/tag/v0.7.0

**Comment by shixiaofeia** [comment]
不好意思, 我刚看的这个问题 https://github.com/cloudwego/hertz/issues/442;
感谢回复
