### ISSUE TITLE
关于Spin优雅退出

### ISSUE THREAD

**Issue by guaidashu** [cloudwego/hertz#977]
优雅退出，我觉得除了让已经在执行的请求继续执行完毕再结束整个进程外，还可以自定义要关闭的第三方组件或其他操作，看了下hertz.go文件的，signalWaiter可以自定义，这样雀食可以自己做个。

但其实不如直接让Spin可以接收一个Close方法用于用户自定义 结束后要做的操作，我这种懒人就懒得去自定义个signalWaiter了， 目前没看到这个相关的，也或许是已经有了但我没看完，狗头保命。

**Comment by li-jin-gou** [comment]
参考 http://cloudwego.cn/zh/docs/hertz/tutorials/basic-feature/graceful-shutdown/
