### ISSUE TITLE
How do I delete a registered route?

### ISSUE THREAD

**Issue by springrain** [cloudwego/hertz#979]
**Describe the Question**

How do I delete a registered route?

**Hertz version:**

0.7.1

**Comment by li-jin-gou** [comment]
Deleting routes is not supported cc @Duslia

**Comment by li-jin-gou** [comment]
I've seen gateways that just register the 404 handler route and then do simple route matching and handler reloading themselves.

**Comment by FGYFFFF** [comment]
Is it an idl-generated route?

**Comment by springrain** [comment]
Hertz loads routes provided by external modules (e.g. WASM), external modules update routes, there will be conflicts, hope to delete the old route, register a new route

**Comment by springrain** [comment]
I modified the ```routergroup.go``` and ```tree.go``` implementation and I don't know if I need this pr.
Specific references: https://gitee.com/gpress/hertz/commit/2e614725e31ca7491627270ce8f88b83cde0488b

**Comment by Duslia** [comment]
Hertz was not originally designed to consider dynamic registration and deletion of routes, which requires locking to ensure. If dynamic routing is needed, one can use NoRoute and then implement the route matching method themselves.

**Comment by springrain** [comment]
Ok, thank you very much
